### ISSUE TITLE
Guidance on a dev flow that switches between mocked responses and real ones

### ISSUE THREAD

**Issue by VanTanev** [mswjs/msw#123]
**Is your feature request related to a problem? Please describe.**
In my practice, I often switch my dev setup between hitting the real API (for correctness testing) and using the MockServiceWorker for its faster and easier to control response. 

My current approach in a create-react-app project is this:
```typescript
if (process.env.NODE_ENV === 'development' && process.env.REACT_APP_MOCK_API === 1) {
    require('./__api_mocks__')
}
```

However, switching between mocked and non-mocked responses requires switching the ENV variable and restarting the webpack process.

**Describe the solution you'd like**
Maybe an interface on localStorage could be exposed to control msw behavior. Possibly something like:
```javascript
// disable
localStorage.msw = false

// enable
localStorage.msw = undefined | true

// mock only requests matching urls like "products/list" by providing a regex
localStorage.msw = /products\/list/
```

**Comment by kettanaito** [comment]
Hey, @VanTanev. That's a great dev pattern, thanks for sharing your insights. 

You can enable/disable mocking logic on runtime in a few ways. I'll list them below.

## Transient request handler

If your request handler returns nothing, Mock Service Worker will treat this as "bypass this request", and will perform it as-is, returning the _actual_ response.

```js
// src/__api_mocks__.js
composeMocks(
  rest.get(/products\/list/, (req, res, ctx) => {
    // Comment/uncomment this and save the file.
    // Update will propagate to the Service Worker and should apply immediately.
    // return res(ctx.json([1, 2, 3])
  })
)
```

Alternatively, to disable the entire mocking, try commenting out the `start()` call at the end of your mock definition file:

```js
// src/__api_mocks__.js
composeMocks(...)

// start()
```

## Using `start` and `stop` methods

Calling the `composeMocks()` function returns you a controller over the registered Service Worker. Leverage `start` and `stop` methods to start and stop the mocking, respectively. You can propagate them to the `window` object to call them during your application's runtime, for example.

```js
// src/__api_mocks__.js
import { composeMocks } from 'msw'

const { start, stop } = composeMocks(...yourHandlers)

// Usually, you just start the mocks straight away
start()

// But you can defer the start to runtime, if you wish
window.__mswStart = start

// The same with stopping the mocking whenever you like
// during the development, directly in the browser
window.__mswStop = stop
```

> The way to propagate the `start`/`stop` is up to you, but in case you use my recommendation above, I strongly encourage to mutate the `window` only within your mock definition file. Let's keep that as a part of mocking, so it never touches `window` unintentionally.

---

I hope I understood the question correctly. Please let me know if those tips help.

**Comment by VanTanev** [comment]
Hello @kettanaito, and thank you for the quick response!

Unfortunately, both these approaches are not quite what I'm looking for.

The comment/uncomment approach is ill-suited for something that should be committed to a repo. It means that the mock being enabled or disabled is committed to code as well, which would be bad ergonomics, in my opinion.

The `window.__start` approach doesn't work either - it cannot capture the requests that happen on page reload, which I think in many cases will be exactly the request one wants captured.  For example, when you change code, page auto-reloads after webpack rebuild, and requests should be mocked or not depending on current setting.

I wrote something quite silly, but it works for my purposes:

```typescript
const { start, stop } = composeMocks(...myMocks)
let started = false

setInterval(() => {
    if (started && window.localStorage.msw !== 'true') {
        stop()
        started = false
        console.warn('Stopping MSW')
    }
    if (!started && window.localStorage.msw === 'true') {
        start()
        started = true
        console.warn('Starting MSW')
    }
}, 1000)
```

```javascript
// in browser console
localStorage.msw = true
```

**Comment by kettanaito** [comment]
@VanTanev, absolutely agree on the point that commenting out the `start()` invocation is a rather one-go approach that shouldn't be a general development pattern.

Thank you for the example above, I think I understand the issue now. Calling `start()` or `stop()` is per current session, so once the page is reloaded, it bootstraps anew, starting a worker, while you'd like for it to remain stopped. Is that correct?

**Comment by VanTanev** [comment]
@kettanaito My idea is for start() or stop() to "latch." I need to be able to control it from the browser, and latch it to either state, as the browser will be reloading constantly  (due to webpack hot reload, etc). So, it's necessary to keep the preferred state of started or stopped in localStorage or sessionStorage.

**Comment by kettanaito** [comment]
I can recommend you to create a custom wrapper around the `start()` method. 

```js
// src/__api_mocks__/index.js
import { setupWorker } from 'msw'
import { weakStart } from './weakStart'

const worker = setupWorker(...)

weakStart(worker)
```

```js
// src/__api_mocks__/weakStart.js
const FLAG = 'msw-suppressed'

export function weakStart(worker) {
  const start = (options) => {
    // Check the current mocking state in the localStorage
    const shouldSuppress = localStorage.getItem(FLAG)

    if (shouldSuppress) {
      return Promise.resolve()
    }

    return worker.start(options)
  }

  // Make controller methods globally available to call during runtime.
  // Chain the localStorage update to preserve the state.
  window.mocks = {
    start: start().then(() => localStorage.removeItem(FLAG)),
    stop: worker.stop().then(() => localStorage.setItem(FLAG, 'true'))
  }

  // Enable mocks by default
  start()
}
```

This would be compatible with how `start`/`stop` behave, in terms of returning a Promise you could await before bootstrapping your application, if needed. It would also make your mocking state preserved between reloads, as we chained the writing to the localStorage to each respective method. 

> Notice how we are not calling `stop()` in case `!shouldEnable`. This is because MSW detect page unload and remove the current client from the map of clients that have mocking enabled.

I wouldn't handle this on the library's side, since the conditions for enabling/disabling the runtime mocking can be various. Ideally, such control should be dedicated to something as a in-browser dev tool (#23), so that library doesn't manage this.

Could you please let me know if this solves your current task?

**Comment by VanTanev** [comment]
@kettanaito Using your code as a base, I added only a couple of small fixes (eg, `worker.stop()` doesn't return a promise. Also, I wanted to have a way to specify default options).

Thanks a lot for your assistance! Hopefully, this is useful for other people too.

```typescript
import { setupWorker } from 'msw'
import characterMocks from './character'

const worker = setupWorker(...characterMocks)

// necessary for history-based routing
const options = { serviceWorker: { url: '/mockServiceWorker.js' } }
weakStart(worker, options)

/////////////////////////////////

const FLAG = 'msw-suppressed'
type StartOptions = Parameters<typeof worker.start>[0]

export function weakStart(
    worker: ReturnType<typeof setupWorker>,
    defaultOptions: StartOptions = {},
): ReturnType<typeof worker.start> {
    const start = (options?: StartOptions): ReturnType<typeof worker.start> => {
        // Check the current mocking state in the localStorage
        const shouldSuppress = localStorage.getItem(FLAG)

        if (shouldSuppress) {
            return Promise.resolve(null)
        }

        return worker.start(options ?? defaultOptions)
    }

    // Make controller methods globally available to call during runtime.
    // Chain the localStorage update to preserve the state.
    const mocks = {
        start: (options?: StartOptions) =>
            start(options ?? defaultOptions).then(() =>
                localStorage.removeItem(FLAG),
            ),
        stop: () => {
            worker.stop()
            localStorage.setItem(FLAG, 'true')
        },
    }
    ;(window as any).mocks = mocks

    // Enable mocks by default
    return start(defaultOptions)
}
```

**Comment by kettanaito** [comment]
My pleasure! True, `stop()` at the moment doesn't return a Promise. It used to unregister the worker, but now the worker unregisters itself when the last controlled client is closed. `stop()` now stops the mocking, removing the client's id from the worker's internal list of clients.

Glad it helped!
