### ISSUE TITLE
Forward any body of the request to the mock route handler

### ISSUE THREAD

**Issue by dashed** [mswjs/msw#13]
I ran into a usecase whereby I needed to personalize mock responses based on the request's body for `POST` requests:

```
msw.post(
  "http://localhost:3000/cats",
  (req, res, { status, set, delay, json }) => {

    if(req.body) {
        // do something with body
    }

    return res(status(404), delay(10000), json({ errorMessage: `no cats :(` }));
  }
);
```

------

I can send a quick PR for this if there's interest for this.

**Comment by kettanaito** [comment]
Thank you once more, @dashed, you rock today!

Indeed, it seems that `req.body` is not mapped to the `req` object sent from Service Worker to the MSW. Do you mind creating a pull request for that? I would be very thankful.

**Comment by kettanaito** [comment]
Thank you for contributing! Your support is much appreciated 🙏
