### ISSUE TITLE
Is there a way to submit edits to the website documentation?

### ISSUE THREAD

**Issue by mitchconquer** [mswjs/msw#152]
**Is your feature request related to a problem? Please describe.**
When I load my app at a route other than the root, MSW would fail to load the service worker. For example, if I load my app from this URL `http://localhost:3000/customers/2dd641c3-4069-424e-ad3d-8b2563358dd8`, I get the following error.

```
[MSW] Failed to register Service Worker (./mockServiceWorker.js). DOMException: Failed to register a ServiceWorker for scope ('http://localhost:3000/customers/') with script ('http://localhost:3000/customers/mockServiceWorker.js'): The script has an unsupported MIME type ('text/html').
```

I figured out that this is because it was looking for the service worker relative to the initial URL, so I need to change my start method to be absolute.

```javascript
// old code
return setupWorker(...handlers).start();

// new code
return setupWorker(...handlers).start({
  serviceWorker: {
    url: '/mockServiceWorker.js',
  },
});
```

**Describe the solution you'd like**
I was thinking to update the [custom URL](https://redd.gitbook.io/msw/recipes/custom-service-worker-url) page in the docs to indicate that the default setting is to look for the service mocks at `<HOSTNAME>/mockServiceWorker.js` but actually it looks for it at `<initialURL>/mockServiceWorker.js`.

Perhaps I still don't understand correctly but I believe that is the behavior.

**Describe alternatives you've considered**
An alternative would be to [update the default](https://github.com/mswjs/msw/blob/master/src/setupWorker/start/createStart.ts#L14) to

```javascript
const DEFAULT_START_OPTIONS: DeepRequired<StartOptions> = {
  serviceWorker: {
    url: '/mockServiceWorker.js', // remove the initial "." on this url value
    options: null as any,
  },
  quiet: false,
}
```

**Comment by kettanaito** [comment]
Hey, @mitchconquer. Nice to hear from you again. 

Actually, I think it's a flaw in the library's code. The expected default behavior is that the worker file is loaded at the root of the website. I believe this line is an issue:

https://github.com/mswjs/msw/blob/23569efdaefe24f0a92b94c2ef765505ae1336ea/src/setupWorker/start/createStart.ts#L14

The default value (`./mockServiceWorker.js`) should lose its `.` (dot). That way it'd always request the worker file from the root of the website. With the dot, on the other hand, it attempts to resolve the worker's file path relative to the current _path_.

Please, would you be interested in correcting this in a pull request?

**Comment by kettanaito** [comment]
Regarding the documentation, unfortunately, I haven't found a way to accept edits to a GitBook projects due to their closed source nature. I'm preparing a custom website for the library, which will include a self-hosted documentation, where you'd be able to provide edits in a form of a regular pull request. I'm sorry for the current inconvenience and appreciate your effort. Please stay tunned!

**Comment by mitchconquer** [comment]
Oh I'd like to try yes! I made a PR with the change, do I need some kind of permissions to push it up? What else should I include?

**Comment by kettanaito** [comment]
@mitchconquer, create a pull request from your fork to this repository, and let's review it together. [These instructions](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) can be helpful to create a pull request from your fork. Looking forward to see your pull request :)

**Comment by mitchconquer** [comment]
Awesome thanks for the guidance! Here's [PR #153](https://github.com/mswjs/msw/pull/153).
