### ISSUE TITLE
Error: Service Worker Fails to Register

### ISSUE THREAD

**Issue by sjlutterbie** [mswjs/msw#157]
## Describe the bug
When loading our app, we get the following error:
```
[MSW] Failed to register Service Worker (/mockServiceWorker.js).
message: [Exception: TypeError: Illegal invocation at DOMException.invokeGetter (<anonymous>:1:142)]
```

## Environment

- `msw: 0.15.9`
- `nodejs: 10.15.0`
- `npm: 6.13.16`

Browser: `Chrome v81.0.4044.138 (Official Build) (64-bit)`

## Expected behavior

We've tried a number of fixes, but nothing has prevented the above error.

Any insight is greatly appreciated!

**Comment by kettanaito** [comment]
Hey, @sjlutterbie. Thanks for raising this.

Please, could you share how do you declare your mock definitions using MSW? I'm specifically interested _how_ and _when_ you are calling the `start()` method that registers the worker.

It'd be helpful if you could share a minimum reproduction repo, so I could debug it much faster. As of now there's not enough info/stack trace to draw any conclusion. Thanks!

**Comment by sjlutterbie** [comment]
Hi, @kettanaito, thank you for the quick response. I'll follow up with more information as soon as possible. Creating a reproduction repo might be tricky, but I'll at least try to document how and when it gets called in our app's flow.

Are there any general guidelines on _when_? Key events it should be loaded before/after?

**Comment by kettanaito** [comment]
@sjlutterbie, thanks for the cooperation!

Regarding the recommendation on when to start the worker, in case your pages perform API requests on load, and you'd like to mock those requests, it's necessary to postpone the application's bootstrapping until the service worker is activated. Registering and activating a worker is an asynchronous operation, so when your app has bootstrapped, the worker may still be inactive, thus, unable to process outgoing requests.

To defer the start of the worker, you can use the following pattern:

```js
// src/index.js
async function render() {
  if (process.env.NODE_ENV === 'development') {
    const { worker } = require('./mocks')
    await worker.start()
  }

  ReactDOM.render(<App />, document.getElementById('root'))
}

render()
```

> This creates a wrapper around the bootstrapping code (in this case `React.DOM.render()`) that conditionally awaits until the mocking service worker is active, before rendering the application.

I don't think that the lack of such setup can cause the issue you've described. I understand that it's difficult to share the exact code, but I'd appreciate if you can make a minimal example. Thanks.

**Comment by sjlutterbie** [comment]
Hi @kettanaito, we're still investigating this on our end and, until we can say otherwise, assume it's due to the specifics of our app. Please don't let it be a blocker to #104 or other issues... we'll reach out when we have more information. Thank you :)

**Comment by sjlutterbie** [comment]
We successfully resolved this problem; it was caused by a local SSL configuration issue. Thanks for your help :)

**Comment by kettanaito** [comment]
Glad to hear that! Happy to help.

**Comment by whyDontI** [comment]
Hey @sjlutterbie,
I am also trying to use MSW with local SSL config (`Next js` and `local-ssl-proxy`).
Can you provide any details on how you made it work?
Thanks 😃

**Comment by sjlutterbie** [comment]
Hi Nikhil,

I'm afraid I don't remember the specifics, nor do I have access to the
specific environment, anymore. I can say we were using neither Next.js nor
local-ssl-proxy, however, so I don't know how much our solution would
applied to your situation.

Sorry I can't be of more help!

Simon
