### ISSUE TITLE
"application/json" req.body is not parsed

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#159]
## Describe the bug
When referencing the `req.body` that has been issued via `JSON.stringify({...})`, it's exposed as a stringified JSON.

## Environment

- `msw: 0.15.9`

## Expected behavior

Whenever `req.headers['content-type']` is JSON, MSW should parse the request body into a JavaScript Object. The `Content-Type` header should be a source of truth.

## Roadmap

- [ ] Add an integration test to `test/rest-api/body` asserting multiple body content types (text/xml/json/blob).

**Comment by kettanaito** [comment]
I think the same Content-Type based logic can be used to parse the response body when seeing the matched request log in a browser's console:

https://github.com/mswjs/msw/blob/7f80eb0857bd04dd9fc762207f092352821fcd36/src/utils/logger.ts#L41

**Comment by whyDontI** [comment]
Current solution only works with lower case value eg. `application/json` and doesn't work with `Application/JSON`
https://github.com/mswjs/msw/pull/172#discussion_r786449936
