### ISSUE TITLE
Request JSON body is not parsed in Node

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#171]
## Describe the bug
When mocking a request in NodeJS and performing a request with `Content-Type: application/json`, the `req.body` reference in a request handle is stringified body, instead of a parsed one (see #159).

## Environment

- `msw: 0.16.1`
- `nodejs: v10.18.1`
- `npm: 6.13.4`

## To Reproduce

```js
const server = setupServer(
  rest.post('https://test.msw.io', (req, res, ctx) => {
    return res(
      ctx.status(403),
      ctx.set('x-header', 'yes'),
      ctx.json(req.body as Record<string, any>),
    )
  }),
)

server.listen()

fetch('https://test.msw.io', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    payload: 'info',
  }),
})
```

## Expected behavior
Request's JSON body is always parsed to a JavaScript object, regardless if running in browser or node.

## Screenshots
```diff
+  Expected: {"payload": "info"}
-  Received: "{\"payload\":\"info\"}"
```

**Comment by franco646** [comment]
how can i parse a multipart/form-data fetch ?

**Comment by kettanaito** [comment]
Hi, @franco646. 

The `multipart/form-data` payload will automatically be parsed as a part of making a request. You then can access the parsed data (as a JSON) in `req.body`. Here's [an integration test](https://github.com/mswjs/msw/tree/4a3a3658c51683524a68fd1fd3875a3079b3e738/test/rest-api/request/body) that showcases a `FormData` being constructed, passed to `fetch`, and accessed in the request handler. Take a look there for inspiration.
