### ISSUE TITLE
Empty request JSON body throws exception in a request handler

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#175]
## Describe the bug
When attempting to parse a JSON body, which is empty, an exception seems to happen.

## Environment

- `msw: 0.16.2`

## Expected behavior
Empty body is not attempted to be parsed, even if request has `Content-Type: application/json`.

## Screenshots

- https://github.com/kentcdodds/bookshelf/pull/58#issuecomment-631571131
- https://github.com/kentcdodds/bookshelf/commit/25eddf6ace83671b8fbee2afc4a07dcfed93e666

**Comment by kentcdodds** [comment]
Maybe if the request type is `GET` then don't bother retrieving the `body`?

**Comment by kettanaito** [comment]
Yeah, that's a good call. I'm a little concerned just in case there's a parsing issue, and would like to reproduce this with a `POST` request, when body can be an empty string on purpose. I believe if that would fail also, then a single fix should cover any scenario with an empty body, including GET, that's not expected to have a request body.

> When debugging, I usually spotted GET requests not having the `body` property at all... One of the things to figure out is how it turned to be an empty string when it's not set.

In the current state the request body is parsed only if set:

https://github.com/mswjs/msw/blob/fa6a45ae9bd2ea28fed0d29e730ac2dd9d91f1b5/src/utils/parseRequestBody.ts#L6-L17

If I provide a `req.body: ''` it cannot throw an exception (at least not from a `JSON.parse` call).

**Comment by kettanaito** [comment]
Finding an interesting behavior: when Service Worker gets an intercepted request's body:

https://github.com/mswjs/msw/blob/fa6a45ae9bd2ea28fed0d29e730ac2dd9d91f1b5/src/mockServiceWorker.js#L110-L112

In case body was not set, it still return an empty string when doing `request.text()` instead of `undefined`. This makes it impossible to distinguish between an explicit `""` request body and an empty one. 

> Due to this behavior I've even introduced an explicit skip for empty string values during the stringified captured request parsing on the client side. If I'm not mistaken, this was added to be able to perform response patching. If forwarding the mocked `req` instance with an empty string body to `ctx.fetch()` it throws an exception:
>
> `TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.`

https://github.com/mswjs/msw/blob/fa6a45ae9bd2ea28fed0d29e730ac2dd9d91f1b5/src/utils/handleRequestWith.ts#L34-L38

At the same time, `GET` requests _can_ have a body per spec, it's just [not useful to do that](https://stackoverflow.com/a/983458). So we cannot ignore request body parsing for `GET` requests altogether.

Looks like I'd have to look around in how to make sure that non-existing body is received as `req.body: undefined` on the client side.

> One can argue that a missing body and intentionally blank body are semantically equal, as `""` in JavaScript is a falsy value.

**Comment by kettanaito** [comment]
Since `GET` requests are meant to be idempotent, I see no danger in treating `req.body: ''` as `req.body: undefined`. However, in other methods that may make a difference. I think the best solution here would be to set that `handleRequestWith` parsing logic to:

```js
// Prevent empty fields from presering an empty value. 
// It's invalid to perform a GET request with { body: "" } 
if (this.method === 'GET' && value === '') { 
  return undefined 
}
```
