### ISSUE TITLE
Exposed types are missing

### ISSUE THREAD

**Issue by KnisterPeter** [mswjs/msw#185]
## Describe the bug

All `@types` are missing which are exposed through the api.
Since the types of msw are only `devDependencies` they are not installed on using sides, but since they are exposed through the API and therefore the `.d.ts` files for msw, they should be `dependencies`. Then they are installed as well when installing msw.

`cookie` is an example here:

```sh
[runtime:tsc] ../../node_modules/msw/lib/types/rest.d.ts:142:64 - error TS7016: Could not find a declaration file for module 'cookie'. '.../node_modules/msw/node_modules/cookie/index.js' implicitly has an 'any' type.
[runtime:tsc]   Try `npm install @types/cookie` if it exists or add a new declaration (.d.ts) file containing `declare module 'cookie';`
[runtime:tsc] 
[runtime:tsc] 142         cookie: (name: string, value: string, options?: import("cookie").CookieSerializeOptions | undefined) => import("./response").ResponseTransformer;
[runtime:tsc]                                                                    ~~~~~~~~
[runtime:tsc] 
```

## Environment

- `msw: 0.17.2`
- `nodejs: v13.12.0`
- `yarn: 1.22.4`

**Comment by kettanaito** [comment]
Hey, @KnisterPeter. Thanks for reporting this! You're right, those type dependencies must be listed as regular dependencies in `package.json`. 

Please, would you be interested in sending a pull request? I'd gladly review so we could release it :) Let me know.

**Comment by KnisterPeter** [comment]
Sure, I'll do that tomorrow

**Comment by kettanaito** [comment]
Thank you for these changes! Will be released as the next patch version.
