### ISSUE TITLE
Integration tests fail locally with "function uv_close"

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#188]
This has been happening for a while locally, which makes the publishing pipeline annoying sometimes:

```
Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 176.
error Command failed with signal "SIGABRT".
```

**Comment by kettanaito** [comment]
Haven't experienced that since #197. Can be potentially fixed.

**Comment by kettanaito** [comment]
Run the integration tests multiple times, **the issue is reproducible**.

**Comment by marcosvega91** [comment]
I'm facing the same issue now 🤒 . I can't start regression tests

**Comment by kettanaito** [comment]
@marcosvega91, sorry to hear that. It usually helps to re-run the test(s). I know it's not ideal, but I don't know any technical details about this issue yet to resolve it. Most likely it's related to the test setup (WDS + Puppeteer). I like that setup, but I see some memory implications there.

**Comment by marcosvega91** [comment]
unfortunately to it doesn't work even I rerun 😢  I'll try to find a different way

**Comment by kettanaito** [comment]
Could you please update me with the OS you are using? Maybe that could help us find the root cause of the issue. Also, does this happen when you run all the tests, or even a single test in isolation?

**Comment by marcosvega91** [comment]
I have a mac with macOS Catalina. It is happening if I run a single test or all tests

**Comment by marcosvega91** [comment]
regarding the issue I have read [this](https://github.com/webpack/webpack/issues/10037). I have tried to update watchpack to a different version and now sometimes they work and sometimes not.

**Comment by cowboyd** [comment]
@marcosvega91 the workaround there worked, cheers!

Adding 

```
  "resolutions": {
    "chokidar": "3.3.1"
  }
```

to `package.json` causes warnings on the yarn install, but makes the tests work consistently.

**Comment by kettanaito** [comment]
That's a great find! Please, could you open a pull request with that custom resolution?

**Comment by cowboyd** [comment]
Sure, are you ok with it printing the warnings to the console?

```
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
warning Resolution field "chokidar@3.3.1" is incompatible with requested version "chokidar@^2.1.8"
warning Resolution field "chokidar@3.3.1" is incompatible with requested version "chokidar@^2.1.8"
```

I wonder if there is a way to suppress them per/package

**Comment by kettanaito** [comment]
I'd carefully check if those warnings originate from development dependencies or production dependencies. It wouldn't be nice for anybody installing `msw` to experience those warnings. If they are for dev, then it's completely fine.

**Comment by marcosvega91** [comment]
It's originating from `watchpack` that is a dependency of `webpack` so I think that we can proceed without a problem
