### ISSUE TITLE
Defer actual requests until mocks are ready by default

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#190]
Here'a an example @kentcdodds is using to ensure no requests are performed before the mock service worker is ready:

```js
const originalFetch = window.fetch

window.fetch = async (...args) => {
  await worker.start()
  window.fetch = originalFetch()
  return window.fetch(...args)
}
```

The library may ship this as a default behavior for _client-side_ execution. Most likely, working with `XMLHttpRequest`, since it's often used by `fetch`. This would grant a better user experience than having to ask users to wrap their app mounting logic until the service worker is ready.

## Cons

- Stubbing `XMLHttpRequest`

## Pros

- The stub is transparent, restores to the original implementation once mocks are ready.
- No need to defer app's rendering. App would now know absolutely nothing about mocking.

**Comment by kentcdodds** [comment]
Make sure that it's possible to opt-out of this behavior, but I think it's definitely best if it's the default. Less surprising.

**Comment by kettanaito** [comment]
MSW will defer all network requests on the client's side until the Service Worker instance is ready to intercept them as a default behavior since `0.19.0`. See more information on the API in the release notes.

Thank you, @kentcdodds,  for this suggestion. It'll make the experience with the library smooth and eliminate one of its drawbacks compared to other solutions!

**Comment by kentcdodds** [comment]
Yeah! Terrific news!!
