### ISSUE TITLE
Give access to parsed cookies on the req

### ISSUE THREAD

**Issue by kentcdodds** [mswjs/msw#199]
**Is your feature request related to a problem? Please describe.**

When trying to use msw for an app that uses cookies for things like authentication, I have to manually parse `document.cookie`.

**Describe the solution you'd like**

I'd like to be able to access the (parsed) cookies in my requests via `req.cookies`.

**Describe alternatives you've considered**

I can parse it myself.

**Additional context**

I'm thinking about switching https://github.com/kentcdodds/bootstrap to use cookies instead of localStorage jwt tokens for authentication due to security concerns. I'm not 100% certain that I'll do it (because that opens a whole new can of worms), but in any case I think it would be a hard requirement for people who *are* using cookies for their authentication scheme in their app.

**Comment by kettanaito** [comment]
Hey, @kentcdodds! Thanks for suggesting this. Finally, I'm going to get to implementing the access to request cookies in a request handler. Should be released in the next version. Stay tuned!
