### ISSUE TITLE
define environment

### ISSUE THREAD

**Issue by brunubarbosa** [mswjs/msw#206]
## Describe the bug
I wanna know how to set up a config to just mock at jest tests, I intend to do e2e tests with real data from the server, so, on the test environment, I wanna use msw mock just in one case, I'm using `.env` to set a fake address when I'm on the test environment but I don't know how to define to don't use mock on cypress tests
## Environment

- `msw: 0.19.0`
- `nodejs:12.13.1`
- `npm: 6.14.5`

**Comment by kettanaito** [comment]
Hey, @brunubarbosa. MSW won't perform any implicit mocking. You declare client-side mocking using `setupWorker`, and mocking in Node (i.e. for Jest tests) using `setupServer`. It's up to you whether to use either or both, it's not mandatory in any way.

If you wish to use MSW only for tests running in Jest, follow these steps:

1. [Setup your tests](https://github.com/mswjs/examples/blob/951b148652626772fb0ceb085625414d42ffdd24/examples/rest-react/src/setupTests.js#L6-L25). This illustrates how to do that in Create React App (`src/setupTests.js`), but in a regular app you can create a `jest.setup.js` and reference it in `jest.config.js`:

```js
// jest.setup.js
// The same contents as in the referenced example file above.
```

```js
// jest.config.js
module.exports = {
  setupFiles: ['./jest.setup.js']
}
```

2. Done. Here's an example a [unit test](https://github.com/mswjs/examples/blob/951b148652626772fb0ceb085625414d42ffdd24/examples/rest-react/src/LoginForm.test.js) that uses mocking only for Jest tests, it can be helpful.

Let me know if this helps!
