### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by nvh95** [mswjs/msw#208]
https://redd.gitbook.io/msw/tutorials/usage-in-node
A parenthesis is missing from the above page
```diff
const server = setupServer(
    rest.get('/user', (req, res, ctx) => {
-      return res(ctx.json({ firstName: 'John' })
+      return res(ctx.json({ firstName: 'John' }))
    })
  )
```
I wonder is there any way to report a typo or something missing in the document (instead of creating a new issue)
Thanks

**Comment by kettanaito** [comment]
Hey, @nvh95! Thank you for reporting this. That's indeed a typo and I've merged the fix to the current documentation.

Sorry, there is no easy way to contribute to the docs at the moment, but I'm working hard to publish a new website and revamped docs, which would be much more contributor-friendly.
