### ISSUE TITLE
Handle GraphQL with GET request

### ISSUE THREAD

**Issue by tkamenoko** [mswjs/msw#210]
**Is your feature request related to a problem? Please describe.**
https://graphql.org/learn/serving-over-http/

A GraphQL server often handles both `GET` and `POST` request, but `msw` does not handle GraphQL with `GET` .

**Describe the solution you'd like**

https://github.com/mswjs/msw/blob/32ab4cb008a3baebbfbf3081edd7e0a428efe82c/src/graphql.ts#L96-L100

Currently,  GraphQL handler reads only request body, so it ignores `GET` GraphQL request.
GraphQL handler should parse query string against `GET` request.

**Comment by kettanaito** [comment]
Hey, @tkamenoko. Thanks for suggesting this, it's a great addition to the GraphQL support. 

I'll try to tackle this in the nearest future. Stay tuned.

**Comment by kettanaito** [comment]
The fix should be released in [`0.19.3`](https://github.com/mswjs/msw/releases/tag/v0.19.3). Please update and let me know if GraphQL requests using GET method are intercepted. Thanks.

**Comment by tkamenoko** [comment]
Thanks! It works fine.
