### ISSUE TITLE
Export GraphlRequest Type & Context Types

### ISSUE THREAD

**Issue by toinevk** [mswjs/msw#213]
**Is your feature request related to a problem? Please describe.**
Currently the library doesnt export types for GraphQL Response (i.e. GraphQLMockedRequest<Record<string, any>>) nor types for context (generic, GraphQL or request). These types are useful when composing MSW in typescript. As a result typescript complains. 

**Describe the solution you'd like**
If possible - export types for the above. Happy to submit a PR if you are open to it.

**Describe alternatives you've considered**
Building out the types myself but thats prone to errors as the library evolves :) 

**Additional context**
This specifically has come up for me because I am try to compose a MSW in typescript that uses both graphql and REST end points. In my instance graphql serves my primary data, but auth is handled by a third party REST endpoint. Both need to be mocked to enable proper tests.

**Comment by kettanaito** [comment]
Hey, @toinevk. Thanks for raising this, it's a valid concern.

I agree that the library should export those internal types it uses for annotating GraphQL requests/responses. Do you mind shipping a pull request? I'd be glad to assist you in code review and see these changes in master!
