### ISSUE TITLE
Support for GraphQL Upload/Multipart Spec

### ISSUE THREAD

**Issue by jodelasur** [mswjs/msw#215]
**Is your feature request related to a problem? Please describe.**
Yes. Mocking mutations that send files results to an error.

**Describe the solution you'd like**
Have support for mocking GraphQL uploads. I understand uploads aren't part of the core GraphQL spec, but [having a possibly good chunk of GraphQL users who use the upload spec](https://www.npmtrends.com/graphql-upload-vs-apollo-upload-client-vs-graphql) might be a good reason to implement it.

For our use case, we just need a way to intercept the mutation without errors so we could return a mocked response. This can be expanded to full file mocking if someone else needs it.

**Describe alternatives you've considered**
Our end goal is to be able to test our mutations that upload files. We currently use [MockedProvider](https://www.apollographql.com/docs/react/development-testing/testing/#mockedprovider).

**Additional context**
Looking into the code, I see that msw doesn't have parse logic for multipart requests, so req.body isn't parsed properly.

Multipart request spec - https://github.com/jaydenseric/graphql-multipart-request-spec
Package I use to upload - https://www.npmjs.com/package/apollo-upload-client
Sample repo - https://github.com/jodelasur/msw-graphql-upload-test

Notes on sample repo:
- There are three tests in App.test.js. You should look at the third one ('can upload the file').
- You should run each test individually. Running the whole App describe block results to an error. I'm assuming it's because the Apollo client doesn't reset in-between tests. I don't know how to fix this yet.

**Comment by kettanaito** [comment]
Hey, thanks for raising this and for the detailed example repo!

I'm testing that repository, and observe GraphQL file upload behind handled as the spec says:

1. `SET_BUILD_FILE` mutation is performed.
1. The `req.body` of the mutation is a `FormData`, instead of a string/JSON.
1. The `FormData` body contains three chunks:

```
operations: {"operationName":"SetBuildFile","variables":{"id":1,"file":null},"query":"mutation SetBuildFile($id: ID, $file: Upload) {\n  SetBuildFile(id: $id, file: $file) {\n    build {\n      id\n      fileSet\n      __typename\n    }\n    __typename\n  }\n}\n"}

map: {"1":["variables.file"]}

1: [object File]
```

Do I understand this correctly, that you expect this `FormData` to be read, `operations` string to be parsed for validity, and uploaded files being available in `req.variables` (could you elaborate how exactly those variables should look like)?

I'm not familiar with file upload spec, your knowledge here would be much appreciated!

**Comment by jodelasur** [comment]
I'm also not that familiar with the spec details. 😂 Maybe someone else with more knowledge can chime in and help. 

I think your understanding is correct. Not sure what you mean about "how those variables should look like". I guess the structure should still be the same as the mutation input, and the file fields should be of type [File](https://developer.mozilla.org/en-US/docs/Web/API/File), since that is what we map to the fields.

**Comment by roydendro** [comment]
+1 for this feature from me btw, i'm also using https://www.npmjs.com/package/apollo-upload-client
