### ISSUE TITLE
Docs: Suggested documentation improvements

### ISSUE THREAD

**Issue by AndrewSwerlick** [mswjs/msw#216]
MSW is an excellent tool, but in setting it up I found I had to do a lot of poking around in the code, and research on google for other examples. With this being a newer project under going alot of change it seems like the documentation isn't quite as complete and comprehensive as it could be.

I think the documentation could be improved significantly with the following enhancements.

* Include a link to the Usage in Node section in Getting Started, for those who are primarily interested in using MSW in unit testing scenarios (or just move some of the content)
* Expand the API section to include the API for the worker and server objects created by the setupWorker and setupServer objects
* Link to the Path Matching section in the rest API section
* Expand the Usage in Node section with more details

If there's interest, I'd be willing to take a crack at submitting a pull request for these changes, but I wanted to create the issue first and confirm that you all felt these would be valuable enhancements.

**Comment by kettanaito** [comment]
Hey, @AndrewSwerlick. I agree with you that the current state of the docs is far from ideal.

I'm about to launch a brand new website for MSW, which includes documentation rewritten from scratch. You can [see the website live](https://mswjs.io) already. Could you please let me know if that new documentation covers your suggestions? Thanks.

**Comment by AndrewSwerlick** [comment]
@kettanaito they check pretty much every box!

I did see a couple of typos and minor improvments that I'd be happy to fix via pull request if there's a repo for the site, but in general these are very solid. Only wish I'd had them last week!

**Comment by kettanaito** [comment]
Glad to hear that!
Sure, here’s the repo: https://github.com/mswjs/mswjs.io. Your pull request would be highly appreciated.
