### ISSUE TITLE
Support for binary response types

### ISSUE THREAD

**Issue by chrisguttandin** [mswjs/msw#221]
**Is your feature request related to a problem? Please describe.**
I tried to mock a response which contains a wav file. My initial attempt looked like this:

```js
res(
    ctx.status(200, 'OK'),
    ctx.set('Content-Length', arrayBuffer.byteLength.toString()),
    ctx.set('Content-Type', 'audio/wav'),
    ctx.body(arrayBuffer)
);
```

That didn't work. The response did not contain the contents of the `ArrayBuffer`. It was `[object Object]` instead.

**Describe the solution you'd like**
I wonder if it would be possible to remove the JSON serialization and deserialization. Removing it from [here](https://github.com/mswjs/msw/blob/master/src/utils/createBroadcastChannel.ts#L27) and [here](https://github.com/mswjs/msw/blob/master/src/mockServiceWorker.js#L132) makes the example from above work.

**Describe alternatives you've considered**
I also tried converting the `ArrayBuffer` to a string but that didn't work out and specifying an `ArrayBuffer` directly is of course way more convenient.

**Comment by kettanaito** [comment]
Hey, @chrisguttandin. Support of binary response types is definitely something we should have.

The serialization and deserialization is required to pass the request/response information between the Service Worker and the client. I don't think we should drop serialization, but rather find a suitable way to transfer array buffer between two processes.

## Serialize `ArrayBuffer`

```ts
// src/context/buffer.ts
export function buffer(value: ArrayBuffer): ResponseTransformer {
  return (res) => {
    // We should serialize the buffer before sending it to the worker
    const body = String.fromCharCode.apply(null, new Uint16Array(BUFFER))
    // Also need to set some flag for the worker to know it should convert this body
    // into an ArrayBuffer, once it receives it.
    res.body = body
    return res
  }
}

```

## Deserialize string into `ArrayBuffer`

```ts
// mockServiceWorker.js
function createBufferFromString(str) {
  const buffer = new ArrayBuffer(str.length * 2)
  const bufferView = new Uint16Array(buffer)

  for (let i = 0; i < str.length; i++) {
    bufferView[i] = str.charAtCode(i)
  }

  return buffer
}
```

The question is whether we can use `ArrayBuffer` when constructing a `Response` instance. I don't have much knowledge on this just yet. 

> Alternatively, we can see if there's a native API to transfer buffer data using worker ports.

What do you think about such approach?

**Comment by chrisguttandin** [comment]
Hi @kettanaito, thanks for the quick response.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response/Response) a response can handle a [`BufferSource`](https://developer.mozilla.org/en-US/docs/Web/API/BufferSource) which can also be an `ArrayBuffer`.

I wonder what feature does the serialization currently bring? I'm new to this code base so there is a good chance I'm overlooking something. But since `postMessage()` is used to send the data to the ServiceWorker the data would be cloned anyway.
