### ISSUE TITLE
"SyntaxError: invalid regexp group" for "REST - Params" example in Firefox

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#223]
## Describe the bug

```
SyntaxError: invalid regexp group
```

## Environment

- `msw: 0.19.3`
- `nodejs: irrelevant`
- `npm: irrelevant`

> Firefox 77.0.1 (64-bit) MacOS

## To Reproduce
```bash
$ yarn test:focused test/rest-api/params.mocks.ts
```

1. Open the printed URL in Firefox. 
1. Perform a `fetch('https://api.github.com/users/:username/messages/abc-123')` request from your browser's console.

## Expected behavior
The regular expression pattern string provided to the `pathToRegExp` function is a valid regular expression.

**Comment by kettanaito** [comment]
Discovered when trying to reproduce #220.

**Comment by kettanaito** [comment]
Firefox [states to have named capture groups implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=1362154#c38), and they should be available in Firefox 88, according to the [feature support table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility). However, Firefox 88 is not the latest version distributed yet.

> Named captured groups are not supported in IE and Firefox for Android.

**Comment by LeBenLeBen** [comment]
I ran the test you mentioned in Firefox Developer Edition 78 and it pass 👍

**Comment by kettanaito** [comment]
Thanks for letting me know, @LeBenLeBen! Alternatively, we can wait until Firefox 88 is released, but I'm not aware of the exact time when that's going to happen. Having a broken path parameters in Firefox is not a good thing. However, MSW is rather a dev tool, so browser support isn't an actual priority (just as certain dev tools are available only in certain browsers).

I'll let this issue hang here for some time, if the new version of Firefox gets released, this can be closed. If not, we'll think of a strategy.

**Comment by kettanaito** [comment]
There is no plan to support this at the moment. The recommendation is to wait until the next version of Firefox is released, or use a different browser with a named capture groups in RegExp support.
