### ISSUE TITLE
Redirect response

### ISSUE THREAD

**Issue by mitchconquer** [mswjs/msw#228]
**Is your feature request related to a problem? Please describe.**
Hi, I am creating a little app to handle OAuth and it needs to be able to mock redirect responses. 

**Describe the solution you'd like**
Is it possible implement redirect responses?

**Describe alternatives you've considered**
I tried overwriting the response object to include the Location header but it seems to get erased and I couldn't figure out why.

**Comment by kettanaito** [comment]
Hey, @mitchconquer. Thanks for raising this. Could you please include the request handler code you've used to mock a redirect response?

I think you should be able to redirect by setting a proper response status code, and location header.

```js
rest.get('/auth', (req, res, ctx) => {
  return res(ctx.status(301), ctx.set('Location', 'https://google.com'))
})
```

I don't have any test currently to verify that. Let's use this issue as an opportunity to do that.

**Comment by kettanaito** [comment]
I've added an integration test covering HTTP redirects:

https://github.com/mswjs/msw/blob/ebb85fb9f82c3e1bb0c117ebfc4b77e557d8cc61/test/rest-api/redirect.mocks.ts#L1-L17

Could you please take a look at tell me if that answers your question, @mitchconquer? I believe it behaves as the regular redirect at the moment.
