### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#23]
I propose to develop a browser extension for MSW.

## What the extension would do

1. List all mocking routes defined via MSW.
1. Allow to create, edit and remove mocking routes on runtime. Changes affect the page fetch resources, as they affect MSW.
1. Basically, it's CRUD of mocking routes under a browser extension.
1. Feature: Declared mocking routes can be exported to API Blueprint (or other formats) to be a working version of an API.

**Comment by kettanaito** [comment]
Developing a browser extension is currently out of scope. I find **a browser's DevTools to be the best extension**. While having a dedicated one may be beneficial, there are more important goals at hand, like defining a future-proof API and working on new features.

**Comment by loia5tqd001** [comment]
This is actually great, I'm happy to see this idea to be brought to life, apart from lacking manpower resources, is there any other reason you closed the issue @kettanaito I would love to work on this, even tho I'm still very noob but I'm definitely passionate about this idea and am 100% willing to work on this with maybe some of your guidance from time to time @kettanaito could you share a bit more about your vision
