### ISSUE TITLE
There is no warning when using query params in the handler URL

### ISSUE THREAD

**Issue by rafaelalmeidatk** [mswjs/msw#231]
## Describe the bug
The following mock will never work since the query strings are removed from the original URL but not from the handler URL:

```js
rest.get("/foo?bar=10", (req, res, ctx) => {
  return res(
    ctx.json({
      foo: "bar",
    })
  );
}),
```

## Environment

- `msw: 0.19.0`
- `nodejs: 12.17.0`
- `npm: 6.14.4`

## To Reproduce
1. Add the handler mentioned above
2. In the app, do a request to `/foo?bar=10`
3. Error: the request is not mocked

## Expected behavior
There should be an warning explaining why the mock won't work and how to fix the problem

**Comment by kettanaito** [comment]
Hey, @rafaelalmeidatk! Nice to see you here! Thanks for bringing this in a form of an issue. The usage of query parameters in request handlers URLs should be discouraged and a warning message would help tremendously.

I'll try to plan and do this in the nearest future. Just in case you'd be interested in shipping a pull request with this, I'll always support you in code review to make this change awesome.
