### ISSUE TITLE
Display a meaningful error message when worker module is not found

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#237]
## Current behavior

When you call `worker.start()` and there's no worker module at the given path (or the default path), it will produce a general error.

## Expected behavior

Display an error with the suggestion to double check if you ran `npx msw init <PUBLIC_DIR>`, and link to the documentation page elaborating on that command. 

Example of such error message:

```
[MSW] Failed to find a Service Worker file at "./mockServiceWorker.js". Did you forget to run "npx msw init <PUBLIC_DIR>"?

See more details at: https://mswjs.io/docs/cli/init
```

**Comment by kettanaito** [comment]
@marcosvega91, hey. I wanted to ask if you'd be interested in implementing this improvement? I'd love to include it in the next patch release, and everything else seems to be ready. No pressure, just let me know :) Thanks.

**Comment by marcosvega91** [comment]
Hey @kettanaito yes of course, I'm happy to give an hand :)

**Comment by kettanaito** [comment]
Sounds awesome!

I think this is the place to have that error message in case when the lack of the service worker file is the reason:

https://github.com/mswjs/msw/blob/806ab4495868da6db40df750353d9ddee37e9e33/src/setupWorker/start/utils/getWorkerInstance.ts#L57-L64

We'd have to somehow figure out what caused the error (can be generally any unhandled exception), and in case it was a missing worker file, we can provide some suggestions to the users to double check if they run `npx msw init` command.
