### ISSUE TITLE
Transparent handler ("*") doesn't allow fall-through

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#258]
## Reproduction step 

```js
setupWorker(
  rest.get('*', () => console.log('caught')),
  rest.get('/user', (req, res, ctx) => res(ctx.json({ firstName: 'John' }))
)
```

## Expected behavior

1. Prints out `"caught"` in the console.
1. Returns `{ firstName: "John" }` as the mocked response.

## Current behavior

`GET /user` returns `404` (not handled).

**Comment by marcosvega91** [comment]
this should work only for `'*'` or even for `'/use*'` for example?

**Comment by kettanaito** [comment]
In case of `/user*`, it should match all the following URLs:

- `/user`, `/user/`
- `/user/foo`
- `http://location:XXXX/user` (considering `localhost:XXXX` is the current location)

This would fallthrough only if there is no matching request handler for the current request (just as any other handler behaves). I believe this is the current behavior. 

The issue is about an `*` (asterisk) only, which means "match all". I've had a report from a user that while they had `rest.get('*')` handler, if they returned nothing from the handler, the matching didn't continue to the next handlers, resulting into an unhandled request.

**Comment by marcosvega91** [comment]
ok so if we have 

```javascript
setupWorker(
  rest.get('/use*', () => console.log('caught')),
  rest.get('/user', (req, res, ctx) => res(ctx.json({ firstName: 'John' }))
)
```

should print `caught` in the console and return the json?

**Comment by kettanaito** [comment]
Yes 💯 Because the first `/use*` handler matched, but returned no mocked response. So it falls through to the next handler, and `/user` matches, returning a mocked response. The end result is both `"caught"` printed into the console and the mocked response.

**Comment by marcosvega91** [comment]
just last question, if the order is the opposite as the example below, the behaviour should be the same?

```javascript
setupWorker(
  rest.get('/user', (req, res, ctx) => res(ctx.json({ firstName: 'John' })),
  rest.get('/use*', () => console.log('caught'))
)
```

**Comment by kettanaito** [comment]
No. If the `/user` matches and returns a mocked response, MSW stops iterating down the list of request handlers (current behavior).
