### ISSUE TITLE
Response patching in Node fails

### ISSUE THREAD

**Issue by pmelab** [mswjs/msw#264]
When trying to use response patching as described in the documentation in a node process (`setupServer`), `ctx.fetch` fails with `Window is undefined` because it uses `window.fetch` directly. Am I missing something? Is there any way around that?

**Comment by kettanaito** [comment]
Hey, @pmelab. Thanks for reporting this.

You're right, `ctx.fetch` currently relies on `fetch`, which is not present in a NodeJS environment by default (you still may be able to use that when running in a jsdom environment, for example). 

That brings in a topic of env-specific context utilities. `ctx.fetch()` behaves differently for browser, where `fetch` can be used, and NodeJS, where we should rather do `http.request`. That also affects a call signature of the same utility. I'd need to think about how to approach this. Feel free to suggest your ideas!

**Comment by pmelab** [comment]
Thanks for the quick response @kettanaito !
My first attempt to solve this would be using [cross-fetch](https://github.com/lquixada/cross-fetch) or [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) in `context.fetch`? I would be happy to give it a shot, but currently I can't even run the integration tests due to a `Command failed with signal "SIGSEGV".
`. Is there any documentation on this?

**Edit:** Never mind. Switched to Node 12, tests work now.

**Comment by kettanaito** [comment]
Yeah, `isomorphic-fetch` may be a good idea. I'd definitely like to retain the same API for the end developer, so they don't have to worry wether their mocks are running in a browser or Node. 

> We already have `node-fetch` as a dependency. Perhaps we could be able to utilize it when `ctx.fetch` is called in NodeJS environment.

**Comment by pmelab** [comment]
I rolled the first attempt. unfortunately, I'm not able to consistently run the integration test suite, since it randomly aborts with segfaults. I think it still needs fixes for header handling, but I can't tell for sure. Need to find more time to fix the tests on my environment.
