### ISSUE TITLE
Shoot a live demo

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#27]
It would be great to shoot a small live demo of how the process of using `msw` looks like. It can be converted into a GIF later and put at the top of the README file.

The demo would consist of the following steps:

1. Installing the package.
1. Writing `mocks.js`
1. Running your app and demonstrating that the Mock Service Worker works.

**Comment by hehehai** [comment]
@kettanaito What kind of program do you use for the demo if you want to record it? The react app or the vue app?

I tried to create a simple vue demo using codesandbox, but the service worker could not respond to the data. I think it was the domain name.

If it could be a demo like codesandbox, it would be a great start!

**Comment by kettanaito** [comment]
@hehehai the problem with sandboxes is that you cannot execute `npx` (or any other commands) in its environment. One of the prerequisites for working with MSW is to copy its `mockServiceWorker.js` to your public directory. Even when manually copied into a sandbox, I have doubts what you see as "public" is actually the public directory of the served app. We can try, however, I haven't attempted to upload the Service Worker manually, it may work.

I think in terms of shooting a demo you can use the `examples/create-react-app` in this repository. I'd probably rework the UI to be more, em, presentable :) But having a sandbox with the example is a nice start, I totally agree. Do you mind trying uploading the `mockServiceWorker.js` manually to the public folder of a sandbox?

**Comment by hehehai** [comment]
@kettanaito codesandbox [react msw example](https://codesandbox.io/s/msw-react-example-rwjno)

Have you looked at this example?
I do not know why MSW does not capture and respond to information normally

**Comment by kettanaito** [comment]
@hehehai, thanks for sharing. I've had a brief look into that and can see that Service Worker failed to register. There are also infinite errors regarding an invalid RegExp, which may be related to the usage of `:username` parameter in the path. I've removed the parameter and trying to mock an exact URL. Will update this thread with the result.

**Comment by kettanaito** [comment]
I'm going to shoot a quick tutorial once the following pre-requisites are done:

- #100 
- #107

**Comment by kettanaito** [comment]
The pre-requisites for this task are done, and I'm preparing a setup and script for an introductory tutorial. I see no reason for this ticket anymore. Will update the README once the tutorial is public.
