### ISSUE TITLE
TypeError: (0 , _node.setupWorker) is not a function - NextJS + monorepo

### ISSUE THREAD

**Issue by sunpietro** [mswjs/msw#270]
I'm trying to configure msw to get it working with NextJS app placed in monorepo. I've setup `jest` with the following config:
```javascript
// setupTests.js
import '@testing-library/jest-dom';
import { worker } from './mocks/server';

beforeAll(() => {
    // Enable the mocking in tests.
    worker.listen();
});

afterEach(() => {
    // Reset any runtime handlers tests may use.
    worker.resetHandlers();
});

afterAll(() => {
    // Clean up once the tests are done.
    worker.close();
});
```

And that's how the worker looks like:
```javascript
// mocks/servers.js
import { setupWorker } from 'msw/node';
import { rest } from 'msw';
import post from './data/posts.json';

export const worker = setupWorker(
    rest.get('https://jsonplaceholder.typicode.com/posts/1', (req, res, ctx) => {
        return res(ctx.delay(1000), ctx.status(200), ctx.json(post));
    }),
);
```
I have no idea why am I getting the `TypeError: (0 , _node.setupWorker) is not a function` error when running tests.
![Screenshot 2020-07-09 at 10 11 39](https://user-images.githubusercontent.com/1736658/87014580-a1302e80-c1cc-11ea-99d0-702dc32b34f6.jpg)
Any help and suggestions would be appreciated.

**Comment by kettanaito** [comment]
Hey, @sunpietro. Please use `setupServer` from `msw/node`, not `setupWorker`:

```diff
// mocks/server.js
-import { setupWorker } from 'msw/node'
+import { setupServer } from 'msw/node'

-export const worker = setupWorker(
+export const server = setupServer(
// Your request handlers remain the same
```

```diff
// setupTests.js
-import { worker } from './mocks/server';
+import { server } from './mocks/server';

beforeAll(() => {
    // Enable the mocking in tests.
-    worker.listen();
+    server.listen();
});

afterEach(() => {
    // Reset any runtime handlers tests may use.
-    worker.resetHandlers();
+    server.resetHandlers();
});

afterAll(() => {
    // Clean up once the tests are done.
-    worker.close();
+    server.close();
});
```

> `setupServer` is designed to have an identical API to `setupWorker`, but is focused on running in NodeJS environment (such as where your tests are run). You cannot use `setupWorker` with Jest, because it runs in NodeJS where Service Worker API is not present.

You can refer to the [NodeJS integration](https://mswjs.io/docs/getting-started/integrate/node) in the docs for more details and explanation.

Let me know if that helped.

**Comment by sunpietro** [comment]
Thanks, it works!
