### ISSUE TITLE
Support CalDAV methods

### ISSUE THREAD

**Issue by TimDaub** [mswjs/msw#287]
According to your [documentation](https://mswjs.io/docs/api/rest#methods), the methods contained in the [CalDAV specifications](https://tools.ietf.org/html/rfc4791) (e.g. `REPORT`) are not included.

On your readme.md you claim: 

> Use Express-like routing syntax to capture outgoing requests.

However, express supports these routing methods: http://expressjs.com/en/5x/api.html#routing-methods

Are you interested in support them at at one point?

**Comment by kettanaito** [comment]
Hey, @TimDaub. Thanks for raising this.

When we say "Express-like syntax" we emphasize the syntax itself (`x.get(handler)`), not the entire API compatibility with ExpressJS.

> Are you interested in support them at at one point?

I'd need to look more into the spec, but I'm positive that supporting them can be useful. That looks like a separate request handler to me, something like:

```js
import { caldav } from 'msw'

caldav.report(...)
```

Could you please give me an example of how you use CalDAV methods in your application?

**Comment by TimDaub** [comment]
> When we say "Express-like syntax" we emphasize the syntax itself (`x.get(handler)`), not the entire API compatibility with ExpressJS.

Understood! 

> I'd need to look more into the spec, but I'm positive that supporting them can be useful.
> Could you please give me an example of how you use CalDAV methods in your application?

Actually, I'm just starting out myself. I'm happy that you're considering adding these methods!
What I'd find useful is:

- to have an api that allows me to easily create my own namespace (for e.g. caldav)
- or by manually specifying the entire handler somewhere.

I'll report back with samples of how I'm using these methods as soon I have them 👋

**Comment by kettanaito** [comment]
> to have an api that allows me to easily create my own namespace (for e.g. caldav)

There is such API, actually. It's not documented yet, but you can create your own request handlers as long as they abide the request handler API. Here's an example:

```js
// src/mocks/handlers/caldav.js
import { restContext } from 'msw'

export function createCalDAVHandler(method) {
  return (mask, resolver) => {
    return {
      // Determine if a captured request is a CalDAV request.
      predicate(req) {
        const hasMatchingUrl = compareTwoUrls(req.url, mask)
        const hasSameMethod = req.method === method

        return hasSameMethod && hasMatchingUrl
      },

      // Define which functions are exposed in `ctx.*()`.
      // Here, let's return the same map of functions
      // that's used for `rest.*()` handlers.
      defineContext() {
        return restContext
      },

      // Pass response resolver as-is.
      resolver,
    }
  }
}

export const caldav = {
  report: createCalDAVHandler('REPORT')
}
```

Once defined, you can use that custom request handler:

```js
import { setupWorker } from 'msw'
import { caldav } from './caldav'

const worker = setupWorker(
  caldav.report('/user', (req, res, ctx) => {...})
)

worker.start()
```

> That is, basically, how such namespace would be implemented internally in MSW.

This is a bare example, and it may not be enough for complete usage, but it should give you an idea. I agree that this API needs to be refined and documented, and this is on the documentation improvement roadmap. 

I'm thankful if you give it a try and share the insights with us!

**Comment by TimDaub** [comment]
Examples of how I'm using `REPORT`:

- https://github.com/TimDaub/simple-caldav/blob/6d52cef9de24ac46c5c268a83cf4a2e1b616f40b/src/index.js#L98
- https://github.com/TimDaub/simple-caldav/blob/6d52cef9de24ac46c5c268a83cf4a2e1b616f40b/src/index.js#L172

As I'm proceeding to implement, more methods are potentially used... I will keep you posted.

**Comment by TimDaub** [comment]
- `PROPFIND`: https://github.com/TimDaub/simple-caldav/blob/8005fdea7d33a1ceeebf214c3c7e54d4bd831867/src/index.js#L227

On another note: Take a look at the [`syncCollection`](https://github.com/TimDaub/simple-caldav/blob/8005fdea7d33a1ceeebf214c3c7e54d4bd831867/src/index.js#L260) that is calling an endpoint periodically to check for updates since the last call.
An explanation of what's happening with the sync token can be found [here](https://sabre.io/dav/building-a-caldav-client/), starting at "Getting the first sync-token"

**Comment by kettanaito** [comment]
Do I understand correctly that the CalDAV support would imply:

1. Create a new request handler scoped under the `caldav` namespace.
1. Add the CalDAV methods to that namespace.
1. Match any outgoing request's method with those namespaces (similar to how `rest` works).

Is there any other functionality needed? I mean, do CalDAV requests abide by the REST API spec? Or do they introduce some unique features (sync, subscriptions, etc.)?

**Comment by TimDaub** [comment]
I think you're three points make sense. However, CalDAV is not REST compliant as server and client can indeed share state when using a sync-token. An example of this can be seen in [this blog post](https://sabre.io/dav/building-a-caldav-client/) and my own [`syncCollection` method](https://github.com/TimDaub/simple-caldav/blob/master/src/index.js#L323).

Disclaimer: I ended up writing my own library to mock HTTP responses. An example: https://github.com/TimDaub/expressively-mocked-fetch/blob/master/test/index.test.js#L9-L24
So feel free to close if you're not interested anymore.

**Comment by kettanaito** [comment]
@TimDaub, thanks for an update. If you decide to extend MSW with CalDAV support I will be thankful.
I'm closing this task until there's more people requesting this.
