### ISSUE TITLE
RFC: Request handler API

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#290]
## What

Need to refine an existing Request handler API to be publicly usable. 

The Request handler API is already designed with the support of creating custom request handlers for about any purpose (support of a specific communication convention, embed application's logic into handlers, etc.). However, if you take a look at the implementation example on the library's side, it uses quite a few internal functions, which may be useful to expose in the public API:

- `getCleanUrl`
- `isStringEqual`
- `match`
- The entire `log()` function.

Instead of proxying single functions from internal/external packages, MSW should expose a high-level API that can help developers build their own request handlers. Such high-level API may include:

- `matchesUrl()`, that would clean and match two given URLs just as MSW does for REST API.
- `log()`, a ready-to-use logging function (call signature preserved).

## Motivation

- #287 (support for CalDAV methods)
- Allows developers to create custom request handlers for internal and public usage (i.e. publishing in an NPM package):

```js
import { websockets } from 'msw-websockets-handlers'
import { setupWorker } from 'msw'

setupWorker(
  websockets.on('message', () => {...})
)
```

### Type declaration

https://github.com/mswjs/msw/blob/6001b790fbaafc21f8e7b922e172f4bd271f5272/src/handlers/requestHandler.ts#L54-L106

### Implementation example

https://github.com/mswjs/msw/blob/6001b790fbaafc21f8e7b922e172f4bd271f5272/src/rest.ts#L50-L147

**Comment by marcosvega91** [comment]
I think that the features that you list could be enough to create custom libraries.
I was thinking about `websocket` and It would be a great feature to add to MSW. I'm only afraid that `websocket` can't be intercepted by `service worker` 😢

**Comment by kettanaito** [comment]
@marcosvega91, yeap, we've got the WebSocket feature request opened here #156.

**Comment by kettanaito** [comment]
With #319 the request matching API is now publicly exposed as `matchRequestUrl`. This may help developers in building their custom request handler while reusing the same request matching logic as MSW uses internally.

**Comment by kettanaito** [comment]
We may have to expose a few internal functions (i.e. default loggers) for a more comfortable creation of custom handlers, but I find the current state of the request handler API sufficient for most purposes: 

https://github.com/mswjs/msw/blob/327b384938b1fdf44e77c5bd79e91b7fab0aaad4/src/utils/handlers/requestHandler.ts#L63-L122

I will document this in the recipe and close this.
