### ISSUE TITLE
Question: Is it possible to mock direct requests using the setupWorker? 

### ISSUE THREAD

**Issue by luistak** [mswjs/msw#293]
Is it possible to do something like this:
https://mswjs.io/docs/getting-started/integrate/node#direct-usage

Using a worker instead of a server?

**Comment by kettanaito** [comment]
Hey, @luistak. What do you mean by "direct request"?

If you mean a request to an absolute URL, then of course you can. Both server and client counterpart of MSW have the same support for request URLs. The exception you've mentioned is that in NodeJS one must have absolute request URLs (not the library's limitation).

For example, here's how you mock a response to a GitHub API:

```js
// src/mocks.js
// 1. Import mocking utils.
import { setupWorker, rest } from 'msw'

// 2. Define request handlers and response resolvers.
const worker = setupWorker(
  rest.get('https://github.com/octocat', (req, res, ctx) => {
    return res(
      ctx.delay(1500),
      ctx.status(202, 'Mocked status'),
      ctx.json({
        message: 'Mocked response JSON body',
      }),
    )
  }),
)

// 3. Start the Service Worker.
worker.start()
```

Let me know if this is what you meant.

**Comment by luistak** [comment]
Hum... 

It really works, but I found a bug using `msw` with`create-react-app`

If there is a homepage link in your package.json like this: `https://www.yourdomain.com/${SOMETHING}`

The `SOMETHING` suffix will be attached to your PUBLIC_URL, then every request won't reach those mocked requests

**Comment by luistak** [comment]
> Hum... just found a bug using create-react-app
> 
> If there is a homepage link in your package.json like this: `https://www.yourdomain.com/${SOMETHING}`
> 
> The `SOMETHING` suffix will be attached to your PUBLIC_URL, then every request won't reach those mocked requests

I fixed it removing the homepage from the script then adding the `SOMETHING` suffix using `cross-env` on the build script 😄 

```
"build": "cross-env PUBLIC_URL=/SOMETHING/ react-scripts build",
```

**Comment by Justinohallo** [comment]
This needs to be in the docs somewhere. 

We introduced a PUBLIC_URL env variable and it broke everything.

**Comment by kettanaito** [comment]
Hi, @Justinohallo. The setup with a custom “homepage” property is listed under the browser integration: https://mswjs.io/docs/getting-started/integrate/browser#using-homepage-property-in-packagejson

**Comment by Justinohallo** [comment]
Hi @kettanaito ,

For some reason, that set up did not work for me. 

However, I was able to use the .env files for CRA:https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env

In our case, we only need the homepage configuration in production, so we moved our PUBLIC_URL to .env.production and everything works correctly. 

In my opinion, this is a much simpler solution than the one in the docs. It may be worth adding as a secondary method upon further testing.

**Comment by kettanaito** [comment]
Thanks for the suggestion, @Justinohallo. Please, could you open a pull request [to the docs repo](https://github.com/mswjs/mswjs.io) with the solution that worked for you? We could then add it to the docs and have others benefit from your knowledge. Thanks.
