### ISSUE TITLE
When specifying the endpoint, not matching any mocked endpoint 

### ISSUE THREAD

**Issue by risaac** [mswjs/msw#294]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.19.5   |
| node | 12.18.1    |
| OS   | Windows 10 Pro    |

## Request handlers

```js
import { rest } from 'msw';
import { setupServer } from 'msw/node';

//Also tried http://localhost:*, http://localhost:5000/todo*, http://localhost:*/todo* 
const handlers = [
  rest.get('/todo', (req, res, ctx) => {
    return Promise.resolve(res(ctx.json({
      currentPage: 1,
      pageSize: 1,
      pageCount: 1,
      totalRowCount: 0,
      result: [],
    })));
  })]

const server = setupServer(...handlers);

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());
```

## Actual request

```js
// Example of making a request. Provide your code here.
fetch("http://localhost:5000/api/todo").then(result => {
      console.log('LOOK AT ME', result);
      return result;
    });
```

## Current behavior

The request URL is coming in empty. Also, the request not mapping to the correct path, only works when I use wildcard "*". 

## Expected behavior

Intercepting the call and routing to the correct mocked endpoint.

**Comment by kettanaito** [comment]
Hey, @risaac. Thanks for asking this.

I can see that your actual request calls the `/api/todo` endpoint, while in your request handler you are matching against `rest.get('/todo')`.  Make sure to set the request path so it matches the _entire path_ of your request:

```js
rest.get('/api/todo', (req, res, ctx) => {...})
```

To give you more insights, this is what request handlers would expect:

- `rest.get('/todo')` would expect `http://localhost:XXXX/todo` (doesn't match `/api/todo`).
- `rest.get('/api/todo')` would expect `http://localhost:XXXX/api/todo` (which seems to be the request you are making).

Also, please, take a moment to read about [absolute request URLs in NodeJS](https://mswjs.io/docs/getting-started/integrate/node#direct-usage), it's useful if you are running your test outside of a DOM-like environment (i.e. outside of jsdom).

Considering `http://localhost:5000` is your application's address (`location.origin`) during tests, then establishing a `rest.get('/api/todo')` request handler will be enough. If the application's and API endpoint addressed differ, then the API is de-facto external, and its full URL should be present in the request handler.

Let me know if this helps.

**Comment by risaac** [comment]
@kettanaito yes I agree, apologies for the confusion that was a bad copy pasta. Correct, that will not work. 

I got it to work by hard-coding the applications address like you said. I have that address in a config, so it worked out. I was not able to get it to play nice with the wildcard. It only worked when using the wildcard by itself.

**Comment by kettanaito** [comment]
So in the end your API calls are against an external address?

I believe asterisk should work, as in `*/todo` should match `/api/todo`. You can try it out in the [path matching REPL](https://mswjs.io/docs/basics/path-matching#repl) we have in the docs. This is the values I provide:

- Path: `*/todo`
- Actual request URL: `/api/todo`

This produces a match, disregarding the hostname.

**Comment by risaac** [comment]
I see, thank you!

**Comment by steve-taylor** [comment]
> Also, please, take a moment to read about [absolute request URLs in NodeJS](https://mswjs.io/docs/getting-started/integrate/node#direct-usage), it's useful if you are running your test outside of a DOM-like environment (i.e. outside of jsdom).

Even with jsdom, msw doesn't match requests unless the absolute URL is specified. Seems like a bug, either in the implementation or the docs.
