### ISSUE TITLE
Async handler typescript error on graphql handler

### ISSUE THREAD

**Issue by benmonro** [mswjs/msw#296]
## Describe the bug
When using an async handler, I am getting the following error:

![image](https://user-images.githubusercontent.com/399236/88566621-20a26800-cfeb-11ea-972a-ce9723d2b9c8.png)

## Environment

- `msw: 0.19.5`
- `nodejs: 12.16.1`
- `yarn: 1.22.4`

> Please also provide your browser version.

## To Reproduce
```js
msw.query(`GetFoo`, async (req, res, ctx) => {
  return res(ctx.data({foo:"bar"}));
});
```

## Expected behavior
no TS error

**Comment by kettanaito** [comment]
Hey, @benmonro. Could you please verify if this issue is still reproducible when using `msw@0.20.0`? Thanks.

**Comment by benmonro** [comment]
yes, it appears to still be reproducible in VSCode

![image](https://user-images.githubusercontent.com/399236/88958172-f227c580-d254-11ea-8117-594745cb66bc.png)

**Comment by kettanaito** [comment]
Proper type annotations have been provided. Expect the release in the next patch version.
