### ISSUE TITLE
Flaky: "rest-api/redirect.test.ts" integration test

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#301]
## Details

- `test/rest-api/redirect.test.ts`
- [Failed CI job](https://app.circleci.com/pipelines/github/mswjs/msw/759/workflows/473e90d1-f4af-4c17-9224-8dd447da3cea/jobs/1155)

**Comment by msutkowski** [comment]
I ran this test quite possibly about 1,000 times and was unable to make it fail. The only thing I could find while researching this that seemed remotely plausible was in regards to resource availability in the server instance running the tests... which means to me is that sometimes CircleCI has a bad day 😅 . 

There is [also this issue,](https://github.com/puppeteer/puppeteer/issues/3471) that doesn't appear to be relevant to the implementation of this test... but some of the more recent comments there would make me believe that this [commit on 7/30 where puppeteer version is bumped to `5.2.1`](https://github.com/mswjs/msw/commit/784bf741b81e3959b2e62ad283134aeae8b1b999#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) potentially resolved this.

I'd recommend just closing this out until it comes back up, which I don't suspect it will at this point.

**Comment by kettanaito** [comment]
Thank you for looking into this, @msutkowski. I'm closing this until we encounter it again. It's been some time since I've stumbled upon this failing test on CI, and it might have been indeed a CircleCI or other external issue. There's a few things we can do to minimize external dependencies in tests, and I will plan them out a little later.
