### ISSUE TITLE
Erroring in next.js even if `.start()` called only in browser

### ISSUE THREAD

**Issue by ezhikov** [mswjs/msw#305]
## Describe the bug
Adding msw in next.js project. In `_app.tsx` I have following code: 

```typescript
import { worker } from "../mocks/browser";

if (process.env.NODE_ENV === "development" && process.browser) {
  worker.start({ serviceWorker: { url: `${Router.basePath}/mockServiceWorker.js` } });
  import("@mos-utils/acs").then(function ({ configure }) {
    configure({ mock: "authorized" });
  });
}
```

despite this condition I get error:

```
Error: [MSW] Failed to execute `setupWorker` in a non-browser environment. Consider using `setupServer` for NodeJS environment instead.
```

## Environment

- `msw: ^0.19.5`
- `nodejs: 12.18.0`
- `yarn: 1.22.4`

> Please also provide your browser version.

Browser: Microsoft Edge Version 86.0.587.0 (Official build) dev (64-bit)

## Expected behavior

No error if `worker.start` called only in browser environment

**Comment by kettanaito** [comment]
Hey, @ezhikov. Thanks for reaching out with this.

Could you please refer to the [NextJS example](https://github.com/vercel/next.js/pull/13731) when setting up MSW with your NextJS project? We are working hard to establish that official NextJS example, and there's been a few gotchas introduced that result into proper usage of handlers/browser/server.

My guess is that `process.browser` doesn't guarantee that the call context of the module is an actual browser runtime. It may sound confusing, but sometimes a module is marked as a browser one, but it's get called in a NodeJS process (i.e. during the build). 

The integration in the aforementioned example explicitly checks the type of `window`:

```js
if (process.env.isMockingEnabled && typeof window !== 'undefined') {
  const { worker } = require('../mocks/browser')
  worker.start()
}
```

Doing so will eliminate the error you are experiencing. Please let me know if that worked. Thanks.

**Comment by ezhikov** [comment]
I tried with `typeof​ ​window​ !== ​'undefined'` with same result. I see the difference that I make import es style and in example it is required inside. I'll try this approach tomorrow and will update with results

**Comment by ezhikov** [comment]
It works with both `process.browser` and `require` inside if statement. It still feels a bit odd because I have to mix different import styles.

**Comment by kettanaito** [comment]
@ezhikov, you must require the `mocks/browser` conditionally. Since you call 

```js
import { worker } from "../mocks/browser";
```

on the top-level of your `_app.tsx` module, you get the following call stack:

```
- ../mocks/browser
- { worker} export
- worker = setupWorker()
```

If `setupWorker` function is called in a NodeJS environment you will get the exception you are witnessing:

```
Error: [MSW] Failed to execute `setupWorker` in a non-browser environment. Consider using `setupServer` for NodeJS environment instead.
```

My bad in overlooking your import statement. 

Make sure to import the module that calls `setupWorker` conditionally:

```js
// _app.tsx
// No imports here

if (process.env.isMockingDisabled && process.browser) {
  const { worker } = require('../mocks/browser')
  worker.start()
}
```

Not only that ensures that you won't get the error due to the correct usage of `setupWorker`, but also makes your `browser` import conditional, so the module doesn't end up in your production bundle.

Hope this helps.
