### ISSUE TITLE
Export has or is using name 'ParsedRestRequest' from external module

### ISSUE THREAD

**Issue by mattcosta7** [mswjs/msw#325]
## Describe the bug
When building a library that exports a function that generates a configured rest object, using typescript, a type error `Export has or is using name 'ParsedRestRequest' from external module ` occurs.  This is often due to an exposed method using a type that is not exported.  In this case, it appears that adding export to the ParsedRestRequest interface fixes the issue

## Environment

- `msw: 0.20.3`
- `nodejs: 14.7`
- `npm: 6.7`
- Typescript 3.9

> Please also provide your browser version.

## To Reproduce
1. Build a library that exports a function to generate a rest mock
2. Attempt to build
3. See error:
Exported variable '....' has or is using name 'ParsedRestRequest' from external module "..../node_modules/msw/lib/types/rest" but cannot be named.

## Expected behavior
Can build 

Updating the node_modules types to export the interface locally seems to make this work

**Comment by kettanaito** [comment]
Hey, @mattcosta7. Thanks for reaching out with this.

Please, is it sufficient to export the interface, or should it also be exported from the `msw` package type definitions?

Also, would you be interested in shipping a pull request for this? I'd be glad to help you during the process.

**Comment by mattcosta7** [comment]
@kettanaito I'm not sure offhand.  I only briefly add to the one line in the generated types.  

I should be able to test and verify a bit this weekend to open a pr (would do it sooner but I don't have an ok to do open source work on work time)
