### ISSUE TITLE
Must Provide Source Error

### ISSUE THREAD

**Issue by benmonro** [mswjs/msw#328]
## Describe the bug
when using msw w/ testcafe, testcafe sends a POST to `/messaging` but when MSW checks to see if this request matches a route, an error is thrown saying `Must provide source`.

## Environment

- `msw: 0.20.3`
- `nodejs: 12.18.0`
- `npm: 6.x`

## To Reproduce
see comments here: https://github.com/mswjs/msw/issues/259#issuecomment-670966154

## Expected behavior
request should _not_ throw any errors and be allowed to proceed to the original request.

**Comment by kettanaito** [comment]
@benmonro, thank you for the investigation and the fix!

The changes are published in [`0.20.4`](https://github.com/mswjs/msw/releases/tag/v0.20.4).
