### ISSUE TITLE
Intercept graphql request only by target path

### ISSUE THREAD

**Issue by minipai** [mswjs/msw#330]
**Is your feature request related to a problem? Please describe.**
Once I setup graphql request handler, e.g.
```
const api = graphql.link('http://localhost:3001/graphql')
```

all the post request is intercepted and throw me an error

![Screen Shot 2020-08-09 at 12 18 52 PM](https://user-images.githubusercontent.com/239570/89723524-fa44e980-da3a-11ea-9d9d-2806c1f9d8b1.png)

**Describe the solution you'd like**
Intercept only request on graphql server

**Comment by kettanaito** [comment]
Hey, @minipai! 

Could you please include what error is being thrown? Is it `Must provide source` one?

**Comment by minipai** [comment]
Yes, it's `Must provide source` ...
At `v0.19.5` I can use a `rest.post` to seta handler to take over the request, but it doesn't work on `v.20`.

I'll try to set a minimal repo that can reproduce the issue.

**Comment by kettanaito** [comment]
We are currently tackling the "Must provide source" issue in #329 and the fix should be published soon. Stay tuned.

**Comment by minipai** [comment]
Thank you very much, glad it's addressed.
