### ISSUE TITLE
override the match function in createHandler class. 

### ISSUE THREAD

**Issue by ingmothman** [mswjs/msw#34]
### What: 
I propose providing a way to supply an alternative function to match the endpoints in the SW. which opens the app for customization according to the open/closed principle.

### Why: 
I am trying to achieve a very similar behavior as in this snippet: https://github.com/GoogleChrome/samples/blob/gh-pages/service-worker/mock-responses/service-worker.js#L24
I need to only serve the mock for some of the endpoints having the X-Mock-Response and regardless of the API base domain URL. which allows me to use both the live API and mock API at the same time. 

### How: 
add additional optional param to the createHandler called matchResolver ( you might want to send more than just the URL param to be but rather the complete request metadata. or adding this same param to the start function and using it inside the interceptRequest function.

**Comment by kettanaito** [comment]
Hello, @osmancode. That sounds like a great suggestion.

Technically, it should be possible to achieve this at the moment by using a wildcard (`'*'`) to match all resources, and providing a header presence check:

```js
import { composeMocks, rest } from 'msw'

const { start } = composeMocks(
  rest.get('*', (req, res, { json }) => {
    if (req.headers['X-Mock-Response']) {
      // In case the header is present, mock the response
      return res(json({ mocked: true }))
    }

    // Perform the original request otherwise
    return fetch(req)
  })
)

start()
```

> I am not fully sure about the `fetch()` part, as the recommended way to get the original response. However, that's how it's achieved in the Mock Service Worker.

## Implementation details

I think it would be suitable to adjust the call signature of the handler functions passed to `composeMocks` to be more generic, while those handlers grouped under the `rest` namespace would be a high-order functions with certain predicates built in (matching a fixed method and URL path). Referring to this interface:

https://github.com/open-draft/msw/blob/3bb93d7d53c7d8334f2b432a0ddf8384d2648af3/src/handlers/createHandler.ts#L32

1. Schema entry getter (handler) should be a function of `request` that returns `Boolean` (actual request match verdict) and executes a resolver function when the request matches. Generally, I see no reason for the schema entry to assume any kind of matching, which would allow to provide a custom handler exactly how you require.

```ts
type SchemaEntryGetter = (req: Request, handler: ResponseHandler) => Boolean
```

2. Standard `rest` namespace method then could be implemented as abstractions over the aforementioned generic schema entry getter function. Here's a basic schematics:

```ts
// rest.ts
export const get = (mask: Mask, handler: ResponseHandler): SchemaEntryGetter => {
  return (req) => {
    // each of the "rest[abc]" methods can be generated, as they follow the same
    // request method matching wrapper on top of a resolver execution.
    if (req.method === 'GET' && internalMatchMask(mask, req.url)) {
      resolver(...)
    }
  }
}
```

3. The usage of custom handlers would look roughly as follows:

```ts
import { SchemaEntryGetter, ResponseHandler, composeMocks } from 'msw'

const handleRequestGroup = (handler: ResponseHandler): SchemaEntryGetter => {
  return (req, res, context) => {
    if (req.headers['X-Mock-Response']) {
      handler(req, res, context)
    }
  }
}

const { start } = composeMocks(
  handleRequestGroup((req, res, { json }) => {
    res(json({ mocked: true })
  })
)

start()
```

**Comment by kettanaito** [comment]
I've added the support for this. Please see how to [declare custom request handler](https://github.com/open-draft/msw/tree/3f71b4cc7f5f295872265c99f26dbe5d68efe439#custom-request-handler).

**Please update to `msw@0.4.0` to have this support.** Let me know if this solves the issue for you.

**Comment by ingmothman** [comment]
WOW, thank for the quick response. I will upgrade and let you know.  
Thanks.

**Comment by kettanaito** [comment]
@osmancode, hi! Please, did those changes help you achieve what you wanted?
