### ISSUE TITLE
Generics for rest handles

### ISSUE THREAD

**Issue by timdeschryver** [mswjs/msw#345]
**Is your feature request related to a problem? Please describe.**

The TS example on the homepage shows thats you could use generics for your REST handlers.
But, this isn't supported (yet).

**Describe the solution you'd like**

Rest handlers should be able to accept generics and use it to infer the request/response types.

**Describe alternatives you've considered**

/

**Additional context**

Example from the homepage:
```ts
import { setupWorker, rest } from 'msw'
interface LoginBody {
  username: string
}
interface LoginResponse {
  username: string
  firstName: string
}
const worker = setupWorker(
  //        👇 notice the generic here
  rest.post<LoginBody, LoginResponse>('/login', (req, res, ctx) => {
    const { username } = req.body
    return res(
      ctx.json({
        username,
        firstName: 'John'
      })
    )
  }),
)
worker.start()
```

**Comment by kettanaito** [comment]
This is addressed and will be available in the next release.
