### ISSUE TITLE
Cannot use scope by itself if mockServiceWorker.js is not in the same directory.

### ISSUE THREAD

**Issue by josephspurrier** [mswjs/msw#347]
## Describe the bug

I want msw to only intercept routes at `/api` and have the JS file here at the root: `/mockServiceWorker.js`. 

When I set up the service worker like this (with mockServiceWorker.js at `/mockServiceWorker.js`):

```javascript
worker.start({
  serviceWorker: {
    options: {
      scope: "/api",
    },
  },
});
```
This is the error message I get - it says "undefined":

```
[MSW] Failed to register a Service Worker:
mFailed to register a ServiceWorker for scope ('http://localhost:3000/api') with script ('http://localhost:3000/undefined'): The script has an unsupported MIME type ('text/html').
```

## Environment

- `msw: 0.20.5`
- `nodejs: 12.16.1`
- `npm: 6.14.7`

> Please also provide your browser version
Microsoft Edge 84.0.522.52 (Official build) (64-bit)

## To Reproduce
1. Run this code

```javascript
import { setupWorker, rest } from "msw";

// Define request handlers and response resolvers.
const worker = setupWorker(
  rest.get("/api/v1", (req, res, ctx) => {
    return res(
      ctx.delay(1500),
      ctx.status(202, "Mocked status"),
      ctx.json({
        message: "Mocked response JSON body",
      })
    );
  })
);

worker.start({
  serviceWorker: {
    options: {
      scope: "/api",
    },
  },
});
```

2. Open your browser -> open the console.

## Expected behavior
I expect that I can have have the mockServiceWorker.js at `/mockServiceWorker.js` and only have it scoped to: `/api`.  If I do add this option: url: "/mockServiceWorker.js", then it won't pick up any requests at all, but I expect it to pick up any requests at /api/*.

## Screenshots

![image](https://user-images.githubusercontent.com/2394539/90987177-0bbbe480-e557-11ea-9f91-d63194f73b1e.png)

**Comment by kettanaito** [comment]
Hey, @josephspurrier. Thanks for reaching out with this.

There are a few things I spot. First of all, there seems to be an issue in how MSW merges custom and default options, so whenever you provide a custom `serviceWorker` key, it seems to ignore the default worker script location, so you see `with script ('http://localhost:3000/undefined')` in the error message. This is something we will address and ship a new release.

The other point that I'd highlight, is that the worker scope is not the API scope. A worker's scope controls which _pages_ the worker can control. It doesn't affect nor limit what endpoints those pages reference. For example, if you register a worker at `/api` scope, this means that only requests that pages under `/api/*` make would reach the worker.

Consider this scenario: you have an `/api/a` page and it makes a request to `/foo`. As I understand your intention, you want that request to be ignored, and only requests to `/api/*` to be intercepted. Registering the worker under `/api` scope **won't do that**. If there is a `/bar` page that would make a request to `/api/X`, it won't be intercepted, as the `/bar` page lies outside of the worker's scope in this case.

> You can see a [StackOverflow explanation on Service Worker scope](https://stackoverflow.com/a/35780776) to get a better understanding.

To ensure that only `/api/*` _requests_ get intercepted, include that prefix in all your request handlers. Requests that don't match your described routes will not get intercepted.

```js
rest.get('/api/v1', resolver),
rest.post('/api/user, resolver),
```

When in doubt, use our [Request matching REPL](https://mswjs.io/docs/basics/path-matching#repl) to see if a given request would match the mask. 

Let me know if you have any other questions. Thanks.

**Comment by kettanaito** [comment]
I've tackled the issue with the wrong merge of options. The fix will be released soon.

**Comment by josephspurrier** [comment]
Ah, thank you for clarifying, yes, that makes more sense now on how the scope works. I appreciate the fast responses!
