### ISSUE TITLE
Support more types passed to `context.json` helper

### ISSUE THREAD

**Issue by wyze** [mswjs/msw#349]
## Describe the bug
The [json](https://github.com/mswjs/msw/blob/847ec554646d67eec561b64c0843d340c6ef485c/src/context/json.ts) method on `context` object should support more types than `Record<string, any>`. Anything that results in a valid `JSON.stringify` should be supported.

## Environment

- `msw: 0.20.5`
- `nodejs: 12.16.1`
- `npm: 6.13.4`

> Please also provide your browser version. (N/A)

## To Reproduce
1. Create a `rest` request handler.
2. Use the `context.json` method.
3. Try passing anything other than an object or array.
4. See the type error.

## Expected behavior
I would expect no type error to occur when passing anything that would result in a valid `JSON.stringify` call.

## Screenshots
![image](https://user-images.githubusercontent.com/186971/91071352-ae2ea300-e5fd-11ea-8071-a7f5b622005f.png)

**Comment by kettanaito** [comment]
Hey, @wyze! Thank you for suggesting this.

This makes perfect sense, any valid JSON should be accepted as an argument to `ctx.json()`. Please, would you be interested in issuing a pull request to extend this support? I'd gladly assist on code review and any questions you may have. Let me know.

**Comment by wyze** [comment]
> Please, would you be interested in issuing a pull request to extend this support?

Definitely! I will work it up now.
