### ISSUE TITLE
(Question?) Assert on body & headers at network level

### ISSUE THREAD

**Issue by tncho** [mswjs/msw#378]
**Is your feature request related to a problem? Please describe.**
Greetings once again @kettanaito , I hope you're doing well in these difficult times!

Our team has stumbled upon the need to test GTM (Google Tag Manager) / Google Analytics, basically events being tracked in the browser. Our initial approach was to fire those events via user interaction, such as user clicks, and make assertions on the request body being dispatched (event names, and payloads). I do have access to **req.body**, using react-testing-library and 'server.use(...handlers)', but I can't really run any assertions on it (req.body). There's currently no way for us to test the app's reaction to those events as they're merely requests.

**Describe the solution you'd like**
Is there any way to test google analytics requests being fired? Possibly making assertions on requests without expecting the component to handle them, but only triggering them. For example, with body / headers. How would we go about testing those, if each request / response is only testable internally by the component using it?

**Describe alternatives you've considered**
Mocking 'window.dataLayer' and making imperative assertions on calls / pushes to that array being made. Avoiding this would be ideal!

**Additional context**

MSW @ latest
React @ 16.13.0
react-testing-library @ 10.4.9
Jest @ 26.2.2

Thanks in advance ! :hammer_and_wrench: :man_technologist:

**Comment by marcosvega91** [comment]
Hi @tncho thanks for opening the issue :).

The main idea under MSW and testing-library is to make tests as real as possible, simulating what the user can do using your app.
In this case the user has no perception of GTM or google analythics, so I think that for this special case you could test technical details.

I think that you can do something similar


```js
import { rest } from 'msw'
import { setupServer } from 'msw/node'
const server = setupServer()
test('should make request to GTM', () => {
 
  let isGTMcalled = false
  server.use(
    rest.get('......', (req, res, ctx) => {
      isGTMcalled = true
      return res(ctx.json({ success: true }))
    }),
  )

  ....your render.....

 expect(isGTMcalled).toBeTruthy()
})

**Comment by kettanaito** [comment]
Hey, @tncho. Thanks for reaching out.

[Asserting requests](https://mswjs.io/docs/recipes/request-assertions) is often a sign of implementation detail testing and is actively discouraged. However, I understand that in your case the user has no visible feedback of GTM events, as they are rather internal analytics than a user-facing feature. In that case I'd store all the requests in a list and assert that list upon respective triggering of a GTM event.

```js
const requests = []
const server = setupServer(
  rest.get('/path/to/gtm.js', (req, res, ctx) => {
    // Store a request record in the list.
    requests.push(req)
    // Respond with an empty successful response.
    return res()
  })
)

test('dispatches the "getCart" event', () => {
  // trigger GTM event in your code

  const cartEvent = requests.find((request) => {
    return request.body.eventType === 'getCart'
  })

  expect(cartEvent).toBeTruthy()
  expect(cartEvent).toHaveProperty(['payload', 'cartId'], 'abc-123')
})
```

Let us know if this helps.

**Comment by tncho** [comment]
It was helpful indeed. Thanks again!
