### ISSUE TITLE
Recommended integration with react-scripts (create-react-app)

### ISSUE THREAD

**Issue by kentcdodds** [mswjs/msw#38]
I have a few ideas for hope this could work, but I was wondering whether anyone had recommendations for hope to integrate this with an unejected react-scripts app.

**Comment by kettanaito** [comment]
Hi, @kentcdodds. Thanks for raising this. 

Please take a look at the [existing example](https://github.com/open-draft/msw/tree/8429b5a6fd71e88ed9c3c4d060dce90a0b0c2870/example), which illustrates how to use MSW in a fresh `create-react-app` project (non-ejected). In a nutshell, the process can be described as follows:

```bash
# Bootstrap a new CRA project
$ npx create-react-app msw-example
$ cd msw-example

# Install the MSW library
$ npm install msw --save-dev

# Runt the "init" command, which copies the `mockServiceWorker.js` to your public directory.
# This is needed in order for WDS to serve the Service Worker file,
# and for the Service Worker to register and access the application's requests.
$ node_modules/.bin/msw init public

# Create a mocking definition file
$ touch src/mocks.js

# Write mocking definitions...
```

I've also just published the tutorial on [Mocking REST API](https://redd.gitbook.io/msw/tutorials/mocking-rest-api), which may come at handy when working with the library. Let me know if it's helpful, or in case you have any issues. Thanks!

**Comment by kentcdodds** [comment]
Ah, this is very interesting! So the service worker itself is pretty basic and handling the request is all handled by the main thread. Very interesting! Probably going back and forth from service worker to main thread more than you'd want in production, but this isn't for production so no big deal!

Thanks! I'm excited to use this!

**Comment by kettanaito** [comment]
@kentcdodds, exactly. Service worker acts as the request interception point, which signals any outgoing request to the main thread (the MSW library that's subscribed to that message channel). The main thread then matches a request against the request handlers defined, and executes first found response resolver upon match. The result of calling that response resolver is signaled back to the Service Worker and used as the mocked response (which would be a cached response in a conventional usage scenario).

Glad you liked the project and once more thankful for the feedback!
