### ISSUE TITLE
Typescript errors when using ctx.errors in GraphQL mocking

### ISSUE THREAD

**Issue by lynxtaa** [mswjs/msw#381]
## Describe the bug
After upgrading from v0.20.5 to v0.21.1 I'm having issues with this code:

```ts
server.use(
  graphql.mutation('UpdateUser', (req, res, ctx) =>
    res(ctx.errors([{ message: 'Forbidden' }])),
  ),
)
```

Typescript (v4.0.2) show an error: 
![Screenshot 2020-09-12 10 57 34](https://user-images.githubusercontent.com/22496946/92990645-cf8cfb80-f4e6-11ea-9f9b-f5cfb735ae67.png)

Tests are passing as before.. Am i doing something wrong? 

## Expected behavior
Expect it to work as before.

Thank you for this awesome library!

**Comment by kettanaito** [comment]
Hey, @lynxtaa. Thanks for reaching out!

I believe this is being tackled as a part of #377. Please wait for the next patch release somewhen today. Thanks!

**Comment by lynxtaa** [comment]
> 
> 
> Hey, @lynxtaa. Thanks for reaching out!
> 
> I believe this is being tackled as a part of #377. Please wait for the next patch release somewhen today. Thanks!

Awesome! Thank you!

**Comment by cevr** [comment]
@lynxtaa Off topic but, what editor theme are you using ? 😅

**Comment by lynxtaa** [comment]
@cevr It's [Moonlight](https://marketplace.visualstudio.com/items?itemName=atomiks.moonlight)

**Comment by cevr** [comment]
@lynxtaa Thank you 😄
