### ISSUE TITLE
Give more guidelines if mocking fails

### ISSUE THREAD

**Issue by KnisterPeter** [mswjs/msw#386]
**Is your feature request related to a problem? Please describe.**

When a request is not mocked in msw the error of not mocking the request is sometimes hard to understand.
For example if in a GraphQL setup and mock is created for a query, but the tested unit actually does a mutation, msw will fail.
The error I've seen here was ```Network error: request to http://localhost:8080/api failed, reason: connect ECONNREFUSED 127.0.0.1:8080```.

**Describe the solution you'd like**

What would be helpful in this case is that msw will look at the existing (setup) mocks and suggest if there are cases which could match.
Like: ```You mocked a query with name 'some-query' and there is a mock for a mutation with that name. Did you want to use that?```

**Comment by kettanaito** [comment]
Hey, @KnisterPeter! Thanks for reaching out.

This suggestion makes total sense. At the same time it's quite tricky to figure out which request handlers may be suitable for this or that actual request. 

I can suggest you to use the [`onUnhandledRequest`](https://mswjs.io/docs/api/setup-worker/start#onunhandledrequest) option of your worker/server, which you can configure to error on any request that doesn't have a matching handler.

```js
worker.start({ onUnhandledRequest: 'error' })
```

Our philosophy with MSW is that it's "transparent" by default, meaning it won't block nor warn/error on un-mocked requests. This way your app continues to behave the same way it usually does. With the aforementioned option you **can** make it warn/error/execute an arbitrary callback on any unhandled request.

I think that's the best way to get the best DX and keep such requests handling explicit on your side. Hope this helps!

**Comment by KnisterPeter** [comment]
Hi @kettanaito,
we already have ```worker.start({ onUnhandledRequest: 'error' })``` enabled. This does not help that well. We debugged quite some time to detect that we used the wrong mock method (`query` instead of `mutation`).
The suggestion by `msw` was that an unmocked request should be mocked using `msw.rest...` (if I remember correctly). The only helpful part here was, that we have had an unmocked request.

It would be at least helpful (in case of onUnhandledRequest = 'error') to maybe output the headers and the body.
I know this already from `nock` which is at least a bit more helpful.

**Comment by kettanaito** [comment]
Oh, it never occurred to me from that perspective. My apologies for closing the issue prematurely! 

Basically, you're saying we can have an original request-based suggestions, which may include checking query over mutation and vice versa in GraphQL. I like the idea.

**Comment by hsavit1** [comment]
I am also seeing a similar error `ApolloError: request to http://localhost:3000/graphql/ failed, reason: connect ECONNREFUSED 127.0.0.1:3000` in my Demo React Native repo https://github.com/hsavit1/MSWDemo

**Comment by tigerabrodi** [comment]
> It would be at least helpful (in case of onUnhandledRequest = 'error') to maybe output the headers and the body.

@kettanaito Is this something we want to implement? Do you have any other ideas in mind?

I would like to try implementing this if you want.

In `onUnhandledRequest`, we do have access to the `request` from the parameters.

In case of an "error", we would have to expand that particular case :+1:.

#### Code of onUnhandledRequest
![Screenshot from 2020-12-05 19-34-26](https://user-images.githubusercontent.com/49603590/101260533-06af2980-3731-11eb-8519-d4ab9063ae81.png)

**Comment by kettanaito** [comment]
Thanks for volunteering, @tigerabrodi. I think I'll take this one and try to add the following DX improvements:

- Suggest similar request handlers when encountered an unhandled request. Account for typos. 
- Suggest handlers based on the request type (REST/GraphQL).
- Change the suggested "dummy" handler implementation based on the request type (now we always recommend creating a REST API request handler).
