### ISSUE TITLE
mock json file

### ISSUE THREAD

**Issue by brendonco** [mswjs/msw#387]
Hi,

Can we mock a json file and output as json file as well?  Tried below but doesnt work.

```
rest.get(
    '/config/config.json',
    (req, res, ctx) => {
      return res(ctx.json(appConfig));
    }
  )
```

**Comment by marcosvega91** [comment]
Hi @brendonco thanks for reaching us 😄 .

I think that you can use [binary response](https://mswjs.io/docs/recipes/binary-response-type) for your use case, like the following code.

```js
import { rest } from 'msw'
import configuration from './data/config.json'

export const handlers = [
  rest.get('/config.json', async (req, res, ctx) => {
    const jsonBuffer = await fetch(configuration).then((res) =>
      res.arrayBuffer(),
    )
    return res(
      ctx.set('Content-Length', jsonBuffer.byteLength.toString()),
      ctx.set('Content-Type', 'application/json'),
      ctx.body(jsonBuffer),
    )
  }),
]
```

I don't know if it can be a solution for you

**Comment by kettanaito** [comment]
Hey, @brendonco. Could you please clarify what is the expected behavior?

Using the code example you've posted returns an `application/json` response body with the given JSON.

```js
import jsonFile from './file.json'

rest.get('/config.json', (req, res, ctx) => {
  return res(ctx.json(jsonFile))
})
```

I feel there's more information missing to your question. Thanks.

**Comment by kettanaito** [comment]
These two suggestions above should work just fine. I'm treating this as solved, unless more details are provided.
