### ISSUE TITLE
Couldn't find change logs

### ISSUE THREAD

**Issue by balavishnuvj** [mswjs/msw#390]
Usually, change for is at root directory in a file named `CHANGELOG.md`. Would great if anyone could point to changelogs.

**Comment by balavishnuvj** [comment]
#391

**Comment by msutkowski** [comment]
https://github.com/mswjs/msw/releases

**Comment by balavishnuvj** [comment]
Thank you @msutkowski. Usually, people look at CHANGELOG.md. I have given a PR for the same.

**Comment by kettanaito** [comment]
The `CHANGELOG.md` file has been added.
