### ISSUE TITLE
Always receiving TypeError: Network request failed

### ISSUE THREAD

**Issue by spruce-bruce** [mswjs/msw#400]
## Describe the bug
In my jest tests, if I call `server.listen()` all of my network requests inside of the test fail with the generic fetch error `TypeError: Network request failed`. These requests succeed if I don't attempt to run msw at all.

The failure occurs for EVERY request, regardless of whether or not msw has a handler that matches the request or not.

My test looks something like this:
```
import { setupServer } from "msw/node";
import { rest } from "msw";

const handlers = [
  // behavior is the same regardless of whether or not I have any handlers defined
];

const server = setupServer(handlers);
describe("Some Thing", () => {
  beforeAll(() => server.listen());
  afterEach(() => server.resetHandlers());
  afterAll(() => server.close());

  test('example test', () => {
    await fetch(
      "https://api.fake.com/something/i/know/works",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ foo: "bar" }),
      }
    );
  })
}
```

I am adding react-testing-library tests (using msw on the recommendation of KCD) to an older react application. The app was created with CRA ~3.5 years ago. I've updated react-scripts to a more recent version just in case this was the cause, but I've had no luck.

I think it's likely that either my configuration is wrong, or that I have a dependency problem, but the error from fetch is so opaque that I'm finding myself stuck. I don't know if there are any debug tools available to inspect or trace the path of this these failing requests to find out where they're getting jammed up. 

## Environment
My react application sits in a yarn workspace monorepo, but when I isolate the app from its "siblings" and just do `npm i && npm test` I see the same behavior.

- `msw: 0.21.2`
- `nodejs: 10.18.1` & `nodejs: 12.16.3`
- `npm: 6.14.4`
- `yarn: 1.22.4`
- `react-scripts: 3.2.0` which installs `jest: 24.9.0`
- I run my tests with `jest-environment-jsdom-sixteen: 1.0.3`

## To Reproduce
I'm not yet sure how to reproduce. I'm not even sure if this is a real bug. I think it's most likely a misconfiguration on my part or a weird dependency issue.

## Expected behavior
I expect that network requests are either handled by msw handlers or are passed through to be handled by the network.

**Comment by spruce-bruce** [comment]
I'm going to try and set things up in a "pure" environment and try and repro. If I can't repro I'll add deps one at a time until I find the failure (or don't).

**Comment by marcosvega91** [comment]
Hi @spruce-bruce thanks for raising this 😄 

You should call `setupServer` in this way `setupServer(...handlers)`. Let me know if this will solve your issue.

Thanks

**Comment by spruce-bruce** [comment]
Well that did it. I feel like a dummy, but that probably saved me another 4-8 hours of time so thank you a LOT!

I promise I have the `setupServer()` docs open and have been reading through them looking for my mistake. I don't know where I got the idea that this function could take an array.

I'm happy to close this (or for you to close this). 
This problem was particularly difficult for me to solve on my own through normal debugging and googling and closed issue skimming and all that. Do you think there's anything that should be done (throw?) when the server is set up so incorrectly that it breaks every network request?

**Comment by marcosvega91** [comment]
I know the library but sometime I make the same mistake hahahaha. I think that also other people can have this kind of problem, maybe we can add a check on setupServer and setupWoker functions. What do you think?

**Comment by spruce-bruce** [comment]
That would certainly have helped save me a big chunk of time. I'm brand new to msw so I'm not entirely sure what the preference would be there. 

My instinct is to do some kind of assertion about the type of the variable(s) being passed into `setupWorker` and `setupServer` and throw on a mismatch, but I know there can be debate about this kind of a pattern.

**Comment by marcosvega91** [comment]
Hi @spruce-bruce what do you think of this check? This can be added also on `setupServer` function

```diff
diff --git a/src/setupWorker/setupWorker.ts b/src/setupWorker/setupWorker.ts
index 7e4caf3..9f490cd 100644
--- a/src/setupWorker/setupWorker.ts
+++ b/src/setupWorker/setupWorker.ts
@@ -42,6 +42,14 @@ let listeners: Listener[] = []
 export function setupWorker(
   ...requestHandlers: RequestHandlersList
 ): SetupWorkerApi {
+  requestHandlers.forEach((handler) => {
+    if (typeof handler !== 'object' || !('parse' in handler))
+      throw new Error(
+        `[MSW] The handlers passed to setupWorker function are not of the right type.
+          A common mistake is to call setupWorker in this way setupWorker(requestHandlers),
+          you should instead call it as setupWorker(...requestHandlers)`,
+      )
+  })
   const context: SetupWorkerInternalContext = {
     worker: null,
     registration: null,
```

**Comment by kettanaito** [comment]
Perhaps let’s check if the given handlers are not an Array? Throw an error in that case.

**Comment by marcosvega91** [comment]
`requestHandlers` is always an array because it will contain all the `args`. We could, of course, check if the first element of `requestHandlers` is an array and do the following

```diff
diff --git a/src/setupWorker/setupWorker.ts b/src/setupWorker/setupWorker.ts
index 7e4caf3..f35391d 100644
--- a/src/setupWorker/setupWorker.ts
+++ b/src/setupWorker/setupWorker.ts
@@ -42,6 +42,13 @@ let listeners: Listener[] = []
 export function setupWorker(
   ...requestHandlers: RequestHandlersList
 ): SetupWorkerApi {
+  requestHandlers.forEach((handler) => {
+    if (Array.isArray(handler))
+      throw new Error(
+        `[MSW] setupWorker function receive every handler as an arg.
+          You should call it as setupWorker(...requestHandlers) with requestHandlers the array of handlers.`,
+      )
+  })
   const context: SetupWorkerInternalContext = {
     worker: null,
     registration: null,
```

**Comment by spruce-bruce** [comment]
I'm not familiar enough with the internals to contribute to the conversation about how best to do the type check, but it seems like either of those options would work well from the perspective of the client code!

**Comment by benschac** [comment]
I had the same issue.`TypeError: Network request` is extremely hard to understand. It took me quite a bit of time to debug, as well. I also noticed that you'd get this error when you have an undefined variable in your request handler. More specific error messages would be welcomed.

**Comment by kettanaito** [comment]
The fix has been merged and more useful error messages will be published in the next release. Thanks to everyone for contributing.

**Comment by spruce-bruce** [comment]
I'm not sure if commenting on this closed issue is the right move, but I'm standing up CRA + msw on a new project and I'm running into this exact same problem.

I know it's something dumb with my setup. I know it's not the same dumb thing I did last time (I'm not passing handlers as an array instead of destructuring them), and I know that my tests pass when I comment out msw things.

I am both asking for help (if anybody happens upon this post), but also noting that I'm not a dumb person and I've successfully gone through this process in the past, and I'm still stuck here scratching my head.

```
import React from "react";
import { render, screen, waitFor } from "@testing-library/react";
import { rest } from "msw";
import { setupServer } from "msw/node";
import userEvent from "@testing-library/user-event";

import SubmissionFormContainer from "./SubmissionFormContainer";

const handlers = [
  rest.post('http://localhost:9000/redemptions', (_req, res, ctx) => {
    return res(
      ctx.status(201)
    )
  })
]
const server = setupServer(...handlers);

describe("Submission Form Interactions", () => {
  beforeAll(() => server.listen());
  afterEach(() => server.resetHandlers());
  afterAll(() => server.close());

  test("Successful submission displays a success message", async () => {
    render(<SubmissionFormContainer />);
    userEvent.type(screen.getByLabelText(/Invoice Number/i), "test123");
    userEvent.click(screen.getByText(/Submit/i));
    await waitFor(() =>
      expect(
        screen.getByText(/redemption submitted successfully!/i)
      ).toBeInTheDocument()
    );
  });
});
```

**Comment by kettanaito** [comment]
Hey, @spruce-bruce. No worries, let's figure it out together.

The first thing I'd recommend is to enable the [`onUnhandledRequest` option](https://mswjs.io/docs/api/setup-server/listen#onunhandledrequest). The library will warn/error you if your test makes a request that you don't have described in your request handlers. That's exactly the situation you're experiencing. 

Replace your `beforeAll` hook with this:

```js
beforeAll(() => server.listen({ onUnhandledRequest: 'error' }));
```

We've got a few other recommendations to try out if this one doesn't help in the [Debugging uncaught requests](https://mswjs.io/docs/recipes/debugging-uncaught-requests) recipe. Please read through it.

I'm suspecting a hard-coded `localhost:9000` to be the culprit.

**Comment by spruce-bruce** [comment]
Awesome! Thanks for the link! I hadn't found my way to the debugging page yet. Running with the debug output on led me to solve my problem immediately, and now I know!

`2021-03-04T18:54:47.370Z XHR POST http://localhost:9000/redemptions middleware function threw an exception! TypeError: Object.fromEntries is not a function`

I was working in a shell that had node 10 installed by default. I updated to node 14, which is the version I want to be running anyway, and tests pass no problem! Thanks!

**Comment by kettanaito** [comment]
The `Object.fromEntries is not a function` will be solved in #633. Currently, we don't support Node.js 10, which is a regression and it will be fixed.

**Comment by Smankusors** [comment]
Hey, I got this too. I was confused why it's throwing error on me. I have a handler like this below in my React app.

```
rest.post('http://backend/api/auth', (req, res, ctx) => {
  return res(
    ctx.status(200), 
    tx.json({"auth_header": "Bearer [test_bearer_token]"})
  );
}),
```

Now I have a typo there, sorry my bad.

It could be more time saving if the error shows up in the console instead of just "Network request failed"? Doing something like `i = 1 / 0` in the handler will definitely result an error, but I'm curious why the error is not showing up in the console? 🤔

**Comment by kettanaito** [comment]
@Smankusors, I understand your concerns and think this is a valid point. 

Keep in mind that MSW treats your handlers as server-side code. It's not such in actuality, but it is treated that way because that's the area you're mocking. If there was a similar `1 / 0` issue on the server, that'd likely result in a 500 response being returned and you'd see `Network request failed` in your client code. Well, that's exactly what you see with MSW. Except if you look into that failed request you can see a stack trace as the response body that the library shared with you. I think the current experience, although somewhat unconventional, is actually quite good. 

I'm open to any suggestions for exceptions handling. Feel free to spawn a discussion and see you there!

**Comment by Smankusors** [comment]
Yeah, but should it show the server-side logs too? Or maybe separate log files for the handlers code?

**Comment by kettanaito** [comment]
@Smankusors, we may experiment and propagate the occurred `error` before sending it to the worker:

https://github.com/mswjs/msw/blob/11bb2441e102666184188f9f576ac65e59b1be9d/src/utils/worker/createRequestListener.ts#L84-L94

Adding a `console.error(error)` may be enough to surface exceptions from the handlers. 

Would you be interested in opening a pull request?

**Comment by Smankusors** [comment]
> Would you be interested in opening a pull request?

well, let's experiment it 😃

**Comment by Smankusors** [comment]
no wait, the code on createRequestListener is never called when I tried to test the app. I tried to console.log everywhere, but they never shows up.

Also, I just saw that this Network request failed error shows up because it's **timeout**. For some reason when the handler is failing, it  never responded.

Then I find the code below

https://github.com/mswjs/msw/blob/11bb2441e102666184188f9f576ac65e59b1be9d/src/handlers/RequestHandler.ts#L235

After I try with try-catch, I'm able to make the error shows up in the console, well something like this

```
      try {
        result = this.resolverGenerator || (await resolver(req, res, ctx))
      } catch (error) {
        console.error(error)
        return null
      }
```

To be honest, this is kinda ugly... What's the best way to handle this btw? @kettanaito

**Comment by Smankusors** [comment]
@kettanaito  hmm... should I create a separate issue? Or maybe we should continue this on #754?

**Comment by kettanaito** [comment]
@Smankusors Please open a new issue where we can discuss this behavior. Resolver promise rejections should fail the function, propagating upwards.

**Comment by Smankusors** [comment]
alright lets continue on #971

**Comment by MajidBabaeifar** [comment]
I had the same problem. I put the return of the handler in a try and in catch I got the actual error. it said (res) is not a function! when I looked more carefully I found out that I've called the rest.get function like below :
rest.get("url", (res, req, ctx) => {
    return res( .... 
    
which is wrong because I didnt follow the right order of res and req!
