### ISSUE TITLE
Test overriding isolation

### ISSUE THREAD

**Issue by yekver** [mswjs/msw#407]
I use jest with puppeteer to run my e2e tests. If I run `jest --maxWorkers=5` instead for `jest --runInBand` then I will probably face with a race condition problem when some test use request overriding and will affect all other tests, because it's not scoped only to this test.

Am I right?

**Comment by marcosvega91** [comment]
Hi @yekver thanks for reaching us.

It could happen.

As we suggest the server instance should be one. If you add handlers in some tests they will be added to the same shared server instance. This will cause this kind of issues

**Comment by yekver** [comment]
Are there anything we can do to deal with this concurrency and make per-test overriding isolated?

Or this is by design and won't be fixed?

**Comment by marcosvega91** [comment]
Call of `setupServer` performs patching of necessary modules (`http/XMLHttpRequest`). A possible solution is to run multiple instances, but is discouraged at the moment because of patching. I don't know what we can do for now to make it better.

**Comment by kettanaito** [comment]
As @marcosvega91 has mentioned, request interception in NodeJS is achieved by patching request issuing modules. That patching is done for the entire process. 

In that way MSW works almost identical to [Nock](https://github.com/nock/nock). Would anybody be interested in looking how Nock handles this scenario? We can learn a thing of two from them.

**Comment by marcosvega91** [comment]
I think that only `http` and `https` modules should have this problem. `JSDOM` for example should already handle multiple instances of `window`. What do you think if we try to patch `http`/`XMLHttpRequest` one time? If you call `server.listen` we can increment a counter and decrement on `server.close`. All mocks are restored only when counter is 0. In this way we can patch everything one time and multiple `server` instances could work together.

**Comment by kettanaito** [comment]
Let's discuss this issue in #474. Thanks.
