### ISSUE TITLE
How to register a handler for every request?

### ISSUE THREAD

**Issue by tysonxor** [mswjs/msw#409]
I cannot seem to find anything in the issues or docs to mock a request for every call. For example, lets say my app makes the following requests:

1) GET /stuff
2) GET /stuff
3) GET /stuff

It seems that I would need to duplicate the request handler to mock each call

rest.get('/stuff', handler)
rest.get('/stuff', handler)
rest.get('/stuff', handler)

Is there any way to simply register the handler once for every call to /stuff?

**Comment by juhanakristian** [comment]
```
Is there any way to simply register the handler once for every call to /stuff?

```
AFAIK this is exactly how MSW works. You define the handler once and it will be called every time the endpoint is called.

Are you seeing some other behavior in your case?

**Comment by marcosvega91** [comment]
As suggested by @juhanakristian you should mock the request once and the magic should happen 🚀 .
If you are testing your application there will be some cases when you need to add a new handler for the same request. For example when you want to test an HTTP error. BTW most of the time you will add the handler once. If you have any particular case please let us know 😃

**Comment by tysonxor** [comment]
Oh ok great! Thats good to know.. I must be doing something wonky in my test suite.

Thanks everyone

**Comment by marcosvega91** [comment]
You're welcome 👍 😄
