### ISSUE TITLE
Forward undefined requests

### ISSUE THREAD

**Issue by zaharzagrava** [mswjs/msw#416]
**Is your feature request related to a problem? Please describe.**
I want to use a mock-service-worker to mock only declared requests, everything else should be forwarded to the network.

**Describe the solution you'd like**
A method forwardToNetwork, to shich we pass the req object:

```ts
rest.get("*", (req, res, ctx) => {
  return forwardToNetwork(req);
})
```

**Describe alternatives you've considered**
I have not found an alternative yet.

**Additional context**
With this feature, this request of redux devtools in my storybook should be forwarded:

![image](https://user-images.githubusercontent.com/31539383/95015086-c01b5100-0653-11eb-9995-d86977baa155.png)

**Comment by kettanaito** [comment]
Hey. This is how MSW works by default: any request without a request handler is bypassed. You can also bypass a request in the request handler by short-circuiting the function. See more https://mswjs.io/docs/basics/response-resolver#conditional-response
