### ISSUE TITLE
doc: Documentation suggestions

### ISSUE THREAD

**Issue by hehehai** [mswjs/msw#42]
[Getting started Configure](https://redd.gitbook.io/msw/getting-started#configure)

```bash
npx msw init [PUBLIC_DIR]
```

**Comment by kettanaito** [comment]
Hi, @hehehai. Thanks for the suggestion, I love it. I haven't figured out how to make GitBook projects publicly editable, so I will update the Getting started step manually for now.

**Comment by kettanaito** [comment]
Updated! [Getting started](https://redd.gitbook.io/msw/getting-started) page uses `npx msw init` as the initialization command. Thank you once more.
