### ISSUE TITLE
Allow access to service worker primitives in onUnhandledRequest

### ISSUE THREAD

**Issue by cdaringe** [mswjs/msw#426]
**Is your feature request related to a problem? Please describe.**

Context:

- on _some_ unmocked requests, I need to apply retry logic. this retry logic is very easy to apply in `worker.addEventListener("fetch", cb)` cb handlers.
- only one worker per origin is permitted, so my soln must play nicely with msw
- [onUnhandledRequest](https://mswjs.io/docs/api/setup-worker/start#onunhandledrequest) allows me to specify a callback, however that callback appears to be comprised of msw primitives, not raw `event` or `event.request` passed to the worker

**Describe the solution you'd like**

`onUnhandledRequest` to be called _directly_ from the autogenerated worker w/ the worker primitives, _or_, worker primitives exposed and permitted for use in `onUnhandledRequest`.

currently, there's a message bus that:

- [execs onUnhandledRequest](https://github.com/mswjs/msw/blob/e1656555e925d672b576e974716ad8e5e0a8aa18/src/utils/handleRequestWith.ts#L78-L82)
- then the worker gets the `MOCK_NOT_FOUND` event and executes

```js
        case "MOCK_NOT_FOUND": {
          return resolve(getOriginalResponse());
```

I'm unclear how this flow works successfully when `onUnhandledRequest` exists _and_ the `MOCK_NOT_FOUND` flow runs--it seems like that is permitting the fetch to receive response datas from both entities? Perhaps some light could be shed here :)

**Describe alternatives you've considered**

- allow a callback directly inline in the generated `MOCK_NOT_FOUND` block
- allow access to raw service worker event/request datas in `onUnhandledRequest`

**Additional context**

My temp solution has been to modify the `MOCK_NOT_FOUND` block:

```js
        case "MOCK_NOT_FOUND": {
          // return resolve(getOriginalResponse());
          return resolve(onRetryWorkerFetch(request, getOriginalResponse));
          // onRetryWorkerFetch then execs getOriginalResponse, and on some conditions
          // retries the cloned request a few times
        }
```

**Comment by marcosvega91** [comment]
hi @cdaringe thanks for reaching us :).

Have you looked at [patching request](https://mswjs.io/docs/recipes/response-patching) page? I think that a possible solution for your case is to mock the request and make the original request in the handler. In this way you will not have problem with `onUnhandledRequest`.

To do so you can use the internal `ctx.fetch` function or you can use your own fetch function but you should pass a custom header `x-msw-bypass` with value `true` to bypass MSW interceptor. What do you think? This solution can solve your problem?

**Comment by kettanaito** [comment]
Hey.

The purpose of `onUnhandledRequest` is to specify a developer-oriented callback once the library knows it cannot handle a request, as it doesn't have a corresponding request handler. There are a few things to keep in mind:

- The callback is called _after_ the lookup for handlers is done. **You cannot affect a request at this point**, so handling a retry or returning a generic mocked response is out of scope of this callback.
- The callback is called _on the client_, and does not have access to the worker scope (only to the worker registration).

In MSW the only way to affect a response is via request handlers. Once you've configured worker/server you cannot affect how requests are handled (apart from runtime handlers via [`worker.use()`](https://mswjs.io/docs/api/setup-worker/use)/[`server.use()`](https://mswjs.io/docs/api/setup-server/use)). That's also a reason why `onUnhandledRequest` is assigned on the _already configured_ worker/server instance, and not as a part of request handlers list.

I'm not sure if MSW is the right tool to apply a retry logic in general. Retry is a form of _response_ handling, while the library has only 2 ways of working with responses: mock them, and bypass requests so the original response is retrieved. I suppose you technically can get an original response, analyze it, and incorporate some sort of retry mechanism. Just keep in mind that the library is not originally designed for this purpose.

> Executing `onUnhandledRequest` in the worker is not possible, as you cannot send functions between the client and the worker (only textual data is permitted).

## Permissive request handler

I think what you are looking for is a permissive request handler that would act as a fallback for unhandled requests where you _can handle their responses_. 

```js
// This is an example of a custom request handler
// that captures any request and executes a given resolver.
function otherwise(resolver) {
  return {
    predicate: () => true, // match all requests,
    resolver,
  }
}

setupWorker(
  // ...your handlers
  otherwise((req, res, ctx) => {
    // implement your retry logic
  })
)
```

> Utilize things like [`ctx.fetch()`](https://mswjs.io/docs/api/context/fetch) to get the original response of the captured request and see if you need to apply a retry.

**Comment by cdaringe** [comment]
To be clear, I'd prefer MSW to not be involved at all here as well. I think we're aligned on that.  However, due to the nature of service workers and the fact that MSW is coupled to the `fetch` event, I have no choice but play nicely within MSW APIs  because I do need MSW's otherwise awesome provisions, therefore need its worker. In fact, my original desired approach was to use _a secondary worker_ to handle my requirements, which unfortunately didn't work due browser constraints. My stack is `browser-app => [huge-blackbox-of-infrastructure]`, where that blackbox is 99.99% reliable. I just happen to be making thousands of requests cumulatively on a daily basis, making that 0.01% failure rate statistically probable.

In response to the great feedback above:

> You cannot affect a request at this point

Agreed

> The callback is called on the client, and does not have access to the worker scope (only to the worker registration).

Agreed

> I'm not sure if MSW is the right tool to apply a retry logic in general

Agreed


My original two suggestions were

> allow access to raw service worker event/request datas in onUnhandledRequest

...and we're now aligned that this is not valid a solution, as these resources span across system boundaries

> allow a callback directly inline in the generated MOCK_NOT_FOUND block

I'm still interested in something _like_ this. I'm still interested in hooking it at the worker level specifically because it allows me to _detach_ from MSW for non-mocking concerns. By this point, MSW is already saying "i'm not responsible for this, let the browser do its work for this fetch."  And, that's great--let me handle that stuff outside of MSW if MSW isn't mocking it. The proposed solution, `otherwise(...)`, above still forces me into MSW APIs and data-structures, which I'm optimistic that we can align on, specifically regarding that it feels undesirable to have to use MSW for non-mocked requests/responses.

I have two ideas here that I wouldn't mind some feedback on that I think can get us out of this pickle, dare i say gracefully?

Option 1: In the MSW worker, only `event.respondWith(...)` when we know 100% MSW has a mock resolver for the request. This could be achieved by letting the _worker_ do the route matching. The service worker would not need to consult the client code over the bridge to know if mocking is required. In this world, during resolver registration, matchers are sync'd to worker memory. When a `fetch` comes in, the `fetch` event handler can now synchronously choose to no-op, or, to handoff responding to the mock handlers.

Option 2: in the `MOCK_NOT_FOUND` block, sniff for a userland function, e.g. `onMockNotFound(event)`. if present, call it with the event, otherwise, resume the status quo handling. 


Both options _require_ that users _add code_ to the worker, either via concatenation, an `importScripts(...)` call, or _direct edits_. Anyone wanting to use worker APIs with MSW are already mostly faced with this reality, so that shouldn't be a hard stop, I wouldn't hope. I may, for example, have an entry:

```js
// my-worker.js
importScripts("/myAppsWorker.js", "/mockServiceWorker.js")
// ^ my fetch handler or retries here!   ^ msw here!

```

Option 2 is cheap and easy. The more time I spend staring at this response the more I'm into it!

**Comment by kettanaito** [comment]
You make a good point that if we matched requests in the worker we could `event.respondWith()` only when necessary. Unfortunately, that's not possible due to the nature of data transmitted between the client and the worker (cannot send functions, and request handlers are functions).

> In reality there's much more to the client-side execution of request handlers. This brings a tremendous amount of benefits: you can write them in the same language as the rest of your code, reuse existing code, abstract and generate to your liking. 

Request handlers must execute in the client's context, so from the worker's perspective the patch matching happens _within_ `event.respondWith()`. I describe this behavior [in this comment](https://github.com/mswjs/msw/issues/412#issuecomment-705431590), I highly recommend reading it.

The same goes with executing an arbitrary callback in the worker's scope: you cannot pass the callback (function) from the client to the worker. You have rightfully mentioned that you'd have to modify the worker script to have the callback defined within its context in order to do something like this. 

If I may, what puts a limitation of "only one worker per origin is permitted"? As far as I know there's no limit towards the count of workers controlling a single client. Is there some peculiar behavior exhibited between multiple workers attempting to handle the `fetch` event from the same client? I'd like to know more about this. 

I'm not sure you've addressed my suggestion to use a permissive handler (i.e. the `otherwise` function I illustrated). It won't require you to fiddle with the worker, while granting you the ability to react to any unhandled request and execute any callbacks to your liking within the client's context. 

I'm also not sure why do you want to integrate a retry functionality on the worker's side. This is something often done as a part of your request client (fetch/axios/etc.). Did you consider implementing retry in this layer? I can see a lot of benefits of doing so, in particular to retain a transparent nature of request handling in the worker and a straightforward code discovery of the retry logic. 

One point I may add is that we ask you to copy the worker script to your project so that you see what's going on there, but also so it _becomes your asset_. With that, you can modify and extend the worker script to your liking. As long as you don't break the existing functionality and upgrade the script once the library asks you so, you should be fine with adding custom callbacks to the worker script. Perhaps consider doing this as well, as I don't find a sufficient motivation to extend the worker for this use case. One of the core principles of the library is for the worker to remain as simple as possible.

**Comment by cdaringe** [comment]
> ...  the client and the worker (cannot send functions) ... I describe this behavior in this comment

Right. All of this behavior makes sense, including the duplication of reqs in the network tab. To be fair though, matching requests should only happening on _strings_ in msw, not functions, right? Thus, `on-string-route-match` ? `event.respondWith(...)` : `no_op`. With that said, it is probably very challenging to do matching in worker code, as it likely requires parsing GQL queries, where some fancy regex+filtering is probably all that is required for rest handlers. Because of that alone, I'm happy to remove that idea as a solution.

> If I may, what puts a limitation of "only one worker per origin is permitted"?

`serviceWorker.register(...)` by default uses the the default scope. The browser only permits one worker on a scope. If i did `serviceWorker.register("/msw.js")` and `serviceWorker.register("/custom-app-stuff.js")`, only one will stick, iirc. In my case, I do generally want a shared scope. I _could_ feasibly load my worker on a different scope, but would require some non-trivial path analysis.

> I'm not sure you've addressed my suggestion to use a permissive handler 

A few reasons--`otherwise` exposes msw primitives, not worker primitives (e.g. `MockedRequest`). We want worker primitives/APIs for our use case. Further, we are retrying static assets, not just JSON/xml _data_. If I retry a `GET /something.css` or a binary, will MSW serialize that well across the bridge?

> Did you consider implementing retry in this layer

Ya, good question. I'm actually already retrying our API calls :smile:--this effort is really for 3rd party code and bundled-framework-runtime code retrieving assets that periodically fail. Unfortunately, there are various HTTP inducing APIs that are simply out-of-reach in vendor-space. 😬 

>  Perhaps consider doing this as well, as I don't find a sufficient motivation to extend the worker for this use case

Sure. In fact, that's what we did--edit the worker. Re: registration scope, I'd just cordially suggest that MSW "hogs" the worker `fetch` event, for lack of better terms. The fetch handler's more-or-less unconditional `event.respondWith(...)` suggests that if you're using MSW, then your site's service worker is all MSW or the highway. I think it's fair to assume that other _worker_ logic ought be able to play nicely with MSW.  Perhaps my case is niche enough to just say "edit the worker for these cases", and that's probably OK. In my above option #2, I really liked that I was able to:

- ship code without editing MSW
- use my worker code in tandem with MSW
- load both into the same worker registration.

Pretty nifty traits! The API change could be just adding one conditional and call-expression:
```js
        case "MOCK_NOT_FOUND": {
          if (typeof onMockNotFound === "function") {
            return onMockNotFound(event);
          } else {
            return resolve(getOriginalResponse());
          }
```

**Comment by kettanaito** [comment]
> If I retry a GET /something.css or a binary, will MSW serialize that well across the bridge?

You can handle any data with MSW, which includes text and [binary data](https://mswjs.io/docs/recipes/binary-response-type), as long as you set the respective `Content-Type` headers.

> The browser only permits one worker on a scope

That appears to be true. I've put down [an example of using multiple Service Workers](https://github.com/kettanaito/service-worker-multiple) on a single scope via `importScript()` for you. There you can see how to append your worker to the `mockServiceWorker.js` (or vice-versa) and also that _both_ workers can react to the `fetch` event. The worker you import at the top of another worker script will be executed first, which gives you a request flow control. I suppose that if the first worker handles a response in its `fetch` event, the second worker won't have it triggered, or its request will be marked as resolved. Please analyze and improve that example to suit your needs.

> The API change could be just adding one conditional and call-expression:

I explained this in an extensive detail that you cannot pass functions (`onMockNotFound`) from the client to the worker. It breaks the execution context and is in general a bad idea to stringify a function to later evaluate in another context. Such call back would be defined on the _client_ and may reference client code that won't execute in the worker. 

I'd have to conclude this issue as something we shouldn't address, backing it with the following summarizing statements:

- Exposing worker primitives as a part of MSW API is a context leak and it should be avoided;
- Custom callbacks cannot be defined on the client and executed in the worker's context (see explanation above);
- You may still change the worker script to your liking (i.e. using `importScript` to import another worker within it);
- MSW is not a Service Worker orchestration library, hence if you need to coordinate workers (even if one of them is MSW's worker) you should use other tools designed specifically for that. 

I hope that the `importScript` solution works for your use case.

**Comment by cdaringe** [comment]
> I explained this in an extensive detail that you cannot pass functions (onMockNotFound) from the client to the worker

As mentioned above, I'm not talking about a client function. I'm talking about an in scope function in the worker. In my example, I pasted: `importScripts("/myAppsWorker.js", "/mockServiceWorker.js")`. `myAppsWorker.js` would be hosting `onMockNotFound`.

In this regard, I can participate in the worker with MSW.

**Comment by kettanaito** [comment]
Relying on a global callback function that is most likely absent for most of the users is a sign of a bad design. The worker script contains only the absolutely crucial logic with the intention of reducing its complexity by moving as much as possible to the client, not vice versa. 

If my assumptions about the accumulative nature of the fetch event handling in 2 workers are true, then in case of an unmocked request you should fall through to your custom worker’s fetch. Can you please try to confirm this behavior?
