### ISSUE TITLE
Example rest-react show body as string and not as object

### ISSUE THREAD

**Issue by ghost** [mswjs/msw#427]
## Describe the bug
Example rest-react show body as string and not as object

## Environment

- `msw: latest`
- `nodejs: v12.18.3`
- `npm: 6.14.6`

> Please also provide your browser version.

## To Reproduce
1. Go to https://github.com/mswjs/examples/tree/master/examples/rest-react
2. Install repo and start it up with yarn or npm
3. In src/mocks/handlers.js - console.log(req.body) on line 5
4. Click on Username input and type anything then click "submit"
5. Open dev tools and look at console log message
6. See below what console log return
7. handlers.js:6 {"username":"test"}

## Expected behavior
I was expected console log to show handlers.js:6 {username:"test"}
If body is a string and not an object, you cannot do req.body.username 

## Screenshots
![console](https://user-images.githubusercontent.com/20955623/96363143-ab01f000-1132-11eb-866e-6997db8bb098.png)

## Code
```
import { rest } from "msw";

export const handlers = [
  rest.post("/login", (req, res, ctx) => {
    const { username } = req.body;
    console.log(req.body);
    console.log(req.body.username);

    return res(
      ctx.json({
        id: "f79e82e8-c34a-4dc7-a49e-9fadc0979fda",
        username,
        firstName: "John",
        lastName: "Maverick",
      })
    );
  }),
];

```
];

**Comment by kettanaito** [comment]
Hey, @stephyswe. Thank you for reporting this.

It's an issue caused by the request does not containing the `Content-Type: application/json` header. It gets performed as `text/plain`, so the library rightfully treats its body as a string. 

[This `fetch()` call](https://github.com/mswjs/examples/blob/0d2f30604cc8fb64ec6db277d5db627602e2a2c9/examples/rest-react/src/LoginForm.js#L25-L30
) must include the proper content type header. Please, would you be interested in making a pull request with a fix?

**Comment by ghost** [comment]
Oh I get it.. its the default way fetch works. sorry. 
Yeah using axios did the trick. 
```
 axios
        .post("/login", { username })
        // Update the state with the received response
        .then((res) => setUserData(res.data));
```

Not sure how to do that on fetch calls
this method didn't work fully
```
const sendRequest = (url, method, body) => {
    const options = {
      method: method,
      headers: new Headers({ "content-type": "application/json" }),
      mode: "no-cors",
    };

    options.body = JSON.stringify(body);

    return fetch(url, options);
  };
sendRequest("/login", "POST", { username })
```

**Comment by stephyswe** [comment]
I tried using this fix and got same issue.

```
const sendRequest = (url, method, body) => {
    const options = {
      method: method,
      headers: new Headers({ "content-type": "application/json" }),
      mode: "no-cors",
    };

    options.body = JSON.stringify(body);

    return fetch(url, options);
  };
```
sendRequest("/login", "POST", { username })

**Comment by kettanaito** [comment]
I believe it should be a plain object, not the `Headers` instance as the value of the `headers` property of the fetch options.

```js
fetch(url, { headers: { 'Content-Type': 'application/json' } }
```
