### ISSUE TITLE
Typescript: 'ExecutionResult<Schema>' is not assignable to parameter of type 'ResponseTransformer<any>'

### ISSUE THREAD

**Issue by aganglada** [mswjs/msw#428]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.21.2   |
| node | 14.7.0     |
| OS   | MacOS     |

## Request handlers

```js
export const schemaOperation = graphql.operation(async (request, response) => {
  try {
    const result = await graphqlRequest<Schema>(
      schema,
      request.body?.query as string,
      root,
      null,
      request.body?.variables,
    )

    if (result.errors) {
      throw result.errors
    }

    return response(result)
                    ^^^^^^
  } catch (error) {
    console.error(error)
  }
})
```

## Current behavior

Error on returning response 
```
Argument of type 'ExecutionResult<Schema>' is not assignable to parameter of type 'ResponseTransformer<any>'.
  Type 'ExecutionResult<Schema>' provides no match for the signature '(res: MockedResponse<any>): MockedResponse<any>'.ts(2345)
``` 

![Screenshot 2020-10-19 at 13 09 15](https://user-images.githubusercontent.com/922348/96449129-4fa43080-120c-11eb-9162-2859c52abb80.png)

**Comment by kettanaito** [comment]
Hey, @aganglada. Thanks for reaching out.

The `response` composition function requires a proper context utility to be passed. In this case this should be the [`ctx.data()`](https://mswjs.io/docs/api/context/data) utility to return a GraphQL data. 

```js
export const schemaOperation = graphql.operation(async (request, response, context) => {
  // the rest of your handler
  return response(context.data(result.data))
}
```

Keep in mind that in case of GraphQL you may want to propagate the `result.errors` to the client as well. You can do that in the similar fashion, using the [`ctx.errors()`](https://mswjs.io/docs/api/context/errors) utility and provide it the `result.errors` you get.

**Comment by aganglada** [comment]
Nice, that fixed some of my issues 😃 
In what regards to errors, the graphql errors is a readonly array, whereas `context.errors` is expecting an array of GraphqlError
![Screenshot 2020-10-19 at 13 55 04](https://user-images.githubusercontent.com/922348/96453926-0efbe580-1213-11eb-878f-58b98efa5401.png)

Is that expected?

**Comment by kettanaito** [comment]
🤔 Can you try to mark the `Partial<GraphQLError>[]` as `readonly` by modifying the MSW's type annotations? What result would that produce?

**Comment by aganglada** [comment]
Closing as the main topic of this issue is already resolved, thanks @kettanaito 💯
