### ISSUE TITLE
TypeScript 4.1 and template literal types to infer Request Params

### ISSUE THREAD

**Issue by timdeschryver** [mswjs/msw#429]
**Is your feature request related to a problem? Please describe.**

Coming from https://github.com/mswjs/msw/pull/421
We could try to infer the request params from the URL by using template literal types (introduced in TS 4.1).
See this [example](https://www.typescriptlang.org/play?ts=4.1.0-pr-40336-88#code/C4TwDgpgBAogHsATgQwMbAEoHsCuwIAKyKAtgM4A8AKlBAhAHYAmZUZSAlgwOYB8UAXgBQUNpx616zVlRFQA-FAwRUWREwrtEXbgBox2nrzkAuKDTr5pUAAYASAN5cAZhERQAysGLAAviccXNygiUl8AekCGV3dldl8bOUUHAG0AayguEOJkEigAHyg0iBAsZ1gEFHRsPEIc8go44F4AXTMtHV9Tc0krFlsomM9vRD8Ap2jg0NyEpKhUjKzpkjaDTu6HXwBuISFQSBDBCqQ0TFx8ZcoAcnCwLHYycJM79gBJJiveHd2f-egAYSO8BO1XOdVI11u92Aj2e0PeT1UJBIjGA70+312QA)(not mine).

**Describe the solution you'd like**

I think this can be done within 2 steps

- [ ] Update to TS 4.1
- [ ] Try to use template literal types, because I'm not 100% sure if it works within this situation

**Describe alternatives you've considered**

The current solution is to provide a generic for the params.

**Additional context**

/

**Comment by kettanaito** [comment]
Hey, @timdeschryver. Thank you for suggesting this. I think path parameters matching in this way would be much more versatile and seamless for the developer. I wonder how TS works when that path string is dynamically constructed?

It looks like bumping to `typescript: 4.1.x` wouldn't even be a breaking change, as we rely on `4.0.x` at the moment. That being said, how should we handle such TypeScript updates for the consumers of the library? Should we specify a TypeScript version in the `peerDependencies`?

**Comment by timdeschryver** [comment]
That's a good question.

I'm not familiar with the template expression but I think dynamically constructed won't get inferred automatically. The developer will have to provide the generic manually, as she has to do today.

About the TypeScript  version, we'll have to try it first. I do think it would be breaking because it's a new feature, it could be that the type will be `any` or `unknown` in earlier version but again, I'm not sure about it.

Sorry if I can't provide answers on this one (yet).
I'll try to play with it later, as soon as v4.1 is released (it's currently in beta).

**Comment by tigerabrodi** [comment]
@kettanaito You had a label here "help wanted"?

Is there anything I could do from my side in this particular issue?

**Comment by timdeschryver** [comment]
I didn't do anything for this, but now that TS 4.1 is released this issue can be implemented now.
Once it is, we can decide if it actually improves the DX.

If you want to take this @tigerabrodi , feel free to do so from my end.

**Comment by tigerabrodi** [comment]
@timdeschryver This looks pretty complex :sweat_smile:, I'd be down to review the PR or assist on this one though :100:

**Comment by tigerabrodi** [comment]
Even if I was to implement it, may I ask where in the code? Also the current solution uses a generic right?

**Comment by timdeschryver** [comment]
To be honest, I'm not sure either about the where and the how 😅
I can try something and ping you for a review if you'd like.

**Comment by tigerabrodi** [comment]
@timdeschryver Yeah for sure! I would also checkout the PR locally :tada: 

Something I forgot to ask though, how will this "inferring" be better than using generics? I have not read about it, but am really curious :smiley:

**Comment by timdeschryver** [comment]
You wouldn't need to add a generic manually, it would just work 🧙‍♂️

**Comment by tigerabrodi** [comment]
@timdeschryver Ahhh lit :metal: TypeScript ain't playing this time :smile: :joy:

As mentioned, I can review the PR, would also checkout the changes locally :tada: :raised_hands:

**Comment by timdeschryver** [comment]
Fyi, I'm working on this in [infer-req-params](https://github.com/mswjs/msw/compare/infer-req-params).
Sadly, from the looks of it, this change brings a breaking change with it, and we might lose the possibility to type the request body and response (perhaps this is a good thing? see https://effectivetypescript.com/2020/08/12/generics-golden-rule/). 
Will take a second look at it during the week to see if we could resolve this.

**Comment by timdeschryver** [comment]
After giving this some thought, I don't think it will work with the existing generics.
I mean, it will be it won't look pretty, you would have to provide the URL as a generic...

```ts
rest.get<any, ResponseType, 'https://api.github.com/users/:username/messages/:messageId'>(
  rest.get('https://api.github.com/users/:username/messages/:messageId', () => ....)
```

I also tried to support both but this would require a lot of types and I don't know if it's worth it, and if it's even possible in the end.

How do we want to proceed with this, because at first I didn't think that it would be this "destructive".

**Comment by kettanaito** [comment]
Thanks for looking into this, @timdeschryver.

It shouldn't be necessary to provide a new generic to represent a URL. Or, properly said, we'd have to add a new generic but it'd be inferred from the value of the URL. [Here's an example](https://www.typescriptlang.org/play?ts=4.1.0-pr-40336-88#code/C4TwDgpgBAogHsATgQwMbAEoHsCuwIAKyKAtgM4A8AKlBAhAHYAmZUZSAlgwOYB8UAXgBQUNpx616zVlRFQA-FAwRUWREwrtEXbgBox2nrzkAuKDTr5pUAAYASAN5cAZhERQAysGLAAviccXNygiUl8AekCGV3dldl8bOUUHAG0AayguEOJkEigAHyg0iBAsZ1gEFHRsPEIc8go44F4AXTMtHV9Tc0krFlsomM9vRD8Ap2jg0NyEpKhUjKzpkjaDTu6HXwBuISFVBnYoAAtkZgAbYIEoCgBVDAAZXsZ+jqMAChxEM7M7+-1ECBkLBnABubjMbzA9TIZngSDQmFw+GWlF+vAAlIJ+CCsBwmJiBPwHHIAcBPgwoAwcGczkIukITuc3G8AORHYDAMAw8LhZBgDgAOm4HGARxwACMBaoSOEwFh2GRwiY5ewAJJMJXSkiMYDqln6SHQglEuQ8qAAYWQwFQR0BUAARCYefbMhTkFAwIgsMAsKozlBkKwAO4QGkCuRQ0hkAUq3VMOnooRAA) that does it.

I think it's a matter of adding a new URL generic on the `RestHandler`:

https://github.com/mswjs/msw/blob/67facbc424412c76b4abdba5c92fe77152898a8f/src/handlers/RestHandler.ts#L91-L98

And then providing either `RestRequestType<ExtractParams<URL>>` or `RestRequestType<RequestParams` (if explicitly provided):

https://github.com/mswjs/msw/blob/67facbc424412c76b4abdba5c92fe77152898a8f/src/handlers/RestHandler.ts#L97

Does this sound right? I may be missing something.

**Comment by timdeschryver** [comment]
You're right but if I remember correctly, this doesn't play nice when we assign defaults to generics.
This can be seen [here](https://github.com/mswjs/msw/compare/infer-req-params#diff-8048e028e22b718f0aea6f65dcebd0dda66494a24482a8ee3712d54b96ee04a4R70).

**Comment by kettanaito** [comment]
Based on the recent type issues (#627), we should also consider backward-compatibility when using this. I don't suppose template literal types will be backward-compatible, which would make this a breaking change. Not sure if it's a feature good enough to drop TypeScript < 4 support.

**Comment by msutkowski** [comment]
@phryneas If you get some free time, would you mind chiming in on this at your leisure if you have any ideas about how we can handle this or better test for regressions as part of our CI? I was thinking about pulling the type test matrix we have in RTK, but was hoping you might have some advice. Thanks!

**Comment by kettanaito** [comment]
While inferring path parameters from a request handler URL would be a nice experience, I don't think that TypeScript currently supports the way to properly infer parameters this way. For example:

```ts
type Url = '/:service/fixed/:service'

// "service" parameter must be an array of strings.
type Params = ExtractParams<Url> // { "service": string[] }
```

String segments inference is done by mapping the string structure explicitly (although with inferring "rest" which is great). Use cases like multiple parameters with the same name are too complex for TS to cover. 

I vote for explicit request parameters type, which is how the library functions now.
