### ISSUE TITLE
Allow configuring "homepage"

### ISSUE THREAD

**Issue by Gonusi** [mswjs/msw#431]
Usinc Create React App, if I configure a "homepage" in my `package.json` the service-worker.js fails to load, because prefix is not added to service-worker.js path. 

**package.json:**
`"homepage": "/mypath"`

**app is loaded at:**
`http://localhost/mypath`

**service-worker.js is attempted to load from:**
`http://localhost/service-worker.js` 

**service-worker.js should load load from:**
`http://localhost/mypath/service-worker.js` 

It would be a nice feature to be able to configure this. Thanks for a great package!

**Comment by kettanaito** [comment]
Hey, @Gonusi. Thanks for reaching out.

You can provide a custom Service Worker URL where MSW would try to find the worker script using the `serviceWorker.url` option of the `worker`:

```js
const worker = setupWorker(...)

worker.start({
  serviceWorker: {
    url: '/mypath/mockServiceWorker.js'
  }
})
```

> [Read more in the docs](https://mswjs.io/docs/api/setup-worker/start#serviceworker)

**Comment by Gonusi** [comment]
Thank you, I managed to miss it by only looking for it in the "setupWorker" section.
