### ISSUE TITLE
Supported Node versions QUESTION

### ISSUE THREAD

**Issue by eduardosanzbBCG** [mswjs/msw#437]
Hi, I'd like to know if you have a list of supported versions for Node.js
Thanks

**Comment by kettanaito** [comment]
Hey, @eduardosanzbBCG. 

The library is tested in NodeJS `12.18.0`, and we should guarantee `12.x` support. There's no information about its operability on other NodeJS versions. Would you be interested to test it out?

Note that this concerns only the [NodeJS API](https://mswjs.io/docs/api/setup-server) of the library. You can use the browser interception in pretty much [any modern browser](https://caniuse.com/serviceworkers).

**Comment by kettanaito** [comment]
I'm closing this since it's not an issue per-say. Please, if you have a chance, provide us with the NodeJS compatibility map from your findings, it'd be of a great help. Thank you.
