### ISSUE TITLE
The worker start method is not synchronous.

### ISSUE THREAD

**Issue by zzau13** [mswjs/msw#442]
In any browser version and last  `msw`
Service worker is not in start when react application starts. In other words, a race condition occurs despite the default configuration.
https://github.com/botika/hey-react-pokemon/blob/master/src/index.jsx#L13-L18

In this application it means that the first call is not intercepted.

**Comment by philals** [comment]
Give this ago.

// index.tsx

```
async function render() {
  if (process.env.REACT_APP_MOCKED_DATA === "true") {
    // eslint-disable-next-line
    const { worker } = require("./mock-api/browser");

    await worker.start({
      waitUntilReady: true
    });
  }

  ReactDOM.render(<App />, document.getElementById("root"));
}

render();
```

Note: waitUntilReady

**Comment by kettanaito** [comment]
Hey. The start method was never synchronous: it registers a service worker, which itself is an async action.

If you experience issues with requests that happen on mount, consider following this recipe: https://mswjs.io/docs/recipes/deferred-mounting

However, I wonder why those issues truly happen. I’ll look into your repo for more details.

**Comment by zzau13** [comment]
My bad. Thanks all!
