### ISSUE TITLE
Request matches when request paths has same suffix

### ISSUE THREAD

**Issue by pkkummermo** [mswjs/msw#444]
## Describe the bug
If the suffix matches, a request is mocked with the value between the suffix and path param. This leads to me not being able to have

`/users/1/somepath`
and 
`/users/somepath`

as both of these match. The temporary fix is to change the order of these, but that's not really the correct answer to this.

## Environment
Browser
- `msw: 0.21.3`
- `nodejs: 13.14.0`
- `npm: 6.14.4`

## To Reproduce

1. Go to https://mswjs.io/docs/basics/request-matching
2. Write `/user/:userId/endofpath` in Request handler URL and `/user/0251e7ac/test/abc/endofpath` in Actual request URL
3. See that it matches the path between.

## Expected behavior
It should not match

## Screenshots

![image](https://user-images.githubusercontent.com/1799456/97961074-e3503200-1db2-11eb-89d7-37d34cf0b26f.png)

**Comment by marcosvega91** [comment]
Hi @pkkummermo thanks for raising this :).

What you are saying is correct, thanks !!! I'll fix in a while :).

The issue is causing by https://github.com/mswjs/node-match-path/blob/e1e0fac2c335629ac1dd345c297e76d5ea922c92/src/pathToRegExp.ts#L18-L20 because we are not removing `/`

**Comment by kettanaito** [comment]
The fix from @marcosvega91 has been published in [`node-match-path@0.5.2`](https://github.com/mswjs/node-match-path/releases/tag/v0.5.2). 

@pkkummermo could you please re-install your project's dependencies (`npm install --force`) and let us know that the issue is fixed? Thanks.

**Comment by pkkummermo** [comment]
@kettanaito 
No go, but the package-lock of `msw` says 
```
"node-match-path": "^0.4.4",
```
Which I guess means that it will only keep bumping patches, not minors.

**Comment by kettanaito** [comment]
Thanks for letting me know. The fix will propagate in the next release of `msw` then.

**Comment by pkkummermo** [comment]
Thank you so much for the quick fix :)
