### ISSUE TITLE
My request is not intercepted/mocked in NodeJS (tests) If this doesn’t look right

### ISSUE THREAD

**Issue by tony-go** [mswjs/msw#446]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | ^0.21.2   |
| node | 12.12.0     |
| OS   | 10.15.7 (Catalina)    |

## Request handlers

```js
// Example of declaration. Provide your code here.
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const server = setupServer(
  rest.get(`${API_URL}/brands?query=""`, (req, res, ctx) => {
    return res(
      ctx.json({
        cursor: "super-cursor",
        data: [
          { id: 1, title: "Lu" },
          { id: 2, title: "Milka" },
        ],
      })
    );
  })
);

beforeAll(() => {
  server.listen();
  setToken("fakeToken");
});
afterEach(() => server.resetHandlers());
afterAll(() => {
  server.close();
  deleteToken();
});

describe("my test", () => {

   it("should render 'no data' text when list of item is empty", async () => {
      server.use(
        rest.get(`${API_URL}/brands?query=""`, (req, res, ctx) => {
          return res(
            ctx.json({
              cursor: "super-cursor",
              data: [],
            })
          );
        })
      );

      render(<BrandView />);

      await waitFor(() => {
        expect(screen.getByText("No Data")).toBeInTheDocument();
      });
    });

    it("should pop the error message when request failed", async () => {
      const message = "Something happen!";
      server.use(
        rest.get(`${API_URL}/brands?query=""`, (_, res, ctx) => {
          return res(ctx.json({ message }));
        })
      );

      render(<BrandView />);

      await waitFor(() => {
        expect(screen.getByText(message)).toBeInTheDocument();
      });
    });

})
```

## Actual request

```js
return await fetch(`${API_URL}/brands?query=${query}`, {
    headers: {
      ...headers,
      Authorization: `Bearer ${token}`,
    },
  }).then((data) => data.json());
```

## Current behavior

My second test fails. The UI's behavior is the same as the first test. Maybe there is an overlap? It's like the second test was run with the first mock.

## Expected behavior

My second test should be run with the second mock.

**Comment by kettanaito** [comment]
Hey, @tony-go. Thanks for reaching out with this issue.

Can you please drop the query parameter (`?query`) from all your request handlers and see if that makes any change?

```diff
-rest.get(`${API_URL}/brands?query=""`, (req, res, ctx) => {
+rest.get(`${API_URL}/brands`, (req, res, ctx) => {
```

Make sure to omit it for the initial `setupServer` call, as well as the runtime overrides `server.use`. 

> Learn more why query parameters should be dropped [in the FAQ section](https://mswjs.io/docs/faq#why-should-i-drop-query-parameters-from-a-request-handler-url).

**Comment by tony-go** [comment]
Hi @kettanaito 👋 

Thanks for this quick response. Hope all is fine on your side.

I try to remove the query parameter, but unfortunately, it seems that doesn't make any change.

Maybe It could be something linked with concurrency? If Jest run test in parallel for example. (Not sure about that I'll check) What do you think?

**Comment by tony-go** [comment]
I try the [runInBand](https://jestjs.io/docs/en/cli.html#--runinband) option to run all test sequentially but nothing ... :/

**Comment by kettanaito** [comment]
Currently the `setupServer` API cannot run in a concurrent mode, as it patches `http`/`https` instances _per process_. That may leak mocking rules from one test to another. Using `--runInBand` Jest option, as you've mentioned, does solve that issue. If that wasn't the case, I'd suspect something else to be at play here. 

Could you check the value of the `API_URL` between the tests? Its difference may affect the mocking.

**Comment by tony-go** [comment]
Hi @kettanaito 👋 

I already check this ^^But I'll double check 💪

**Comment by kettanaito** [comment]
I also see that in your section test `"should pop the error message when request failed"` you are testing a failure scenario, but your request handler responds with a successful response:

```js
server.use(
  rest.get(`${API_URL}/brands"`, (_, res, ctx) => {
    return res(ctx.json({ message }));
  })
);
```

Ensure you add a proper 4xx-5xx status code on your response (via [`ctx.status()`](https://mswjs.io/docs/api/context/status)) so that your response is a valid REST API error response.

**Comment by kettanaito** [comment]
@tony-go, I've moved your test into a [reproduction repository](https://github.com/kettanaito/msw-446) with a minimal UI logic around it. Both tests pass rendering the correct result, applying the runtime handler.

Please use that repo as a reference to investigate further. I'm closing this, as there is no evident issue on MSW side.

**Comment by tony-go** [comment]
@kettanaito thanks ^^
