### ISSUE TITLE
Question: how to record server responses to auto generate/update mocks?

### ISSUE THREAD

**Issue by andreawyss** [mswjs/msw#451]
I remember reading a few month ago a twitter post (but cannot find it now), it was not yours, about some other utility lib that would make it simple to record http traffic to automate/simplify creating/updating mocks.

Any suggestions on what that lib was or other ideas on how to speed up writing mocks.

Thank you

**Comment by kettanaito** [comment]
Hey, @andreawyss. It's nice to hear from you!

I think the library you're referring to is [msw-webarchive](https://www.npmjs.com/package/@tapico/msw-webarchive). It generates request handlers from the given HAR file that you can record directly in your browser.

As to general suggestions on this topic, I don't have a strong opinion yet, but I do encourage you to try the aforementioned library and share your experience with us. I think that lib is quite suitable for your use case, but there's always a room for improvement. 

Let me know how it goes.

**Comment by andreawyss** [comment]
Thank you. Yes that was the one. I will let you know.
