### ISSUE TITLE
Issue in msw integration with React Storybook. msw intermittently intercepts requests.

### ISSUE THREAD

**Issue by gauravshah786** [mswjs/msw#452]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.21.3   |
| browser | Chrome 86.0.4240.183    |
| OS      | macOS Catalina 10.15.7   |

## Request handlers
![Screen Shot 2020-11-11 at 6 57 45 PM](https://user-images.githubusercontent.com/15170391/98890510-05038600-2451-11eb-884a-953749a4f6c7.png)

![Screen Shot 2020-11-11 at 6 58 02 PM](https://user-images.githubusercontent.com/15170391/98890527-0d5bc100-2451-11eb-9388-89e05cc92e12.png)

![Screen Shot 2020-11-11 at 6 58 14 PM](https://user-images.githubusercontent.com/15170391/98890498-f74e0080-2450-11eb-9bbe-ee1a57fd8b89.png)

![Screen Shot 2020-11-11 at 6 59 02 PM](https://user-images.githubusercontent.com/15170391/98890482-ebfad500-2450-11eb-9ccc-d883c7f309e7.png)

## Actual request
![Screen Shot 2020-11-11 at 7 11 26 PM](https://user-images.githubusercontent.com/15170391/98890956-f9fd2580-2451-11eb-8371-5be0c0a0393b.png)

## Current behavior
As can be seen from the logs, the requests were being intercepted initially and then it was not able to match the request.
Sometimes on the first time loading of the story also throws error of unhandled fetch requests.

![Screen Shot 2020-11-11 at 7 08 52 PM](https://user-images.githubusercontent.com/15170391/98890965-01243380-2452-11eb-8475-deb8f6a07266.png)
![Screen Shot 2020-11-11 at 7 09 07 PM](https://user-images.githubusercontent.com/15170391/98890975-04b7ba80-2452-11eb-8342-178c0ab2186c.png)

## Expected behavior
I am expecting msw to intercept fetch requests consistently. Sometimes, the fetch requests are not intercepted on the first storybook load and sometimes when revisiting the story also does not fetch data from msw.

**Comment by gauravshah786** [comment]
I checked another issue: https://github.com/mswjs/msw/issues/354. Not sure if it is something related. I tried to follow the example in: https://github.com/mswjs/examples/tree/master/examples/with-storybook

**Comment by gauravshah786** [comment]
It was caused because of the use of fetch mock and msw in the same project. It was error on my part.

**Comment by kettanaito** [comment]
Thank you for finding the time to investigate it further, @gauravshah786. Glad to hear the root cause is known.
