### ISSUE TITLE
[TypeScript] missing return types of the setupServer method.

### ISSUE THREAD

**Issue by ofekdeitch-fiverr** [mswjs/msw#455]
## Describe the bug
Hi!
I'm creating a mocked server as described in the guides:

```jsx
import { rest } from 'msw';
import { setupServer } from 'msw/node';

server = setupServer( ... my mocks )
```

I looked at [the code](https://github.com/mswjs/msw/blob/a446e9b1d5/src/node/createSetupServer.ts#L45), and it seems that an object is returned that contains all of the listen, use, close, etc. methods. So I understand from this that TypeScript simply does type inference when using the result of this method.

It could be great to have a type definition for this (I sometimes pass this server object to methods and don't want to use the any type).

Since I'm going to declare these types anyway in my project, I thought it would be better to just add them to this project so everybody could enjoy it.

What do you think?
Thanks 👍

**Comment by Nnadozie** [comment]
Came here to open this issue. Looking forward to your PR @ofekdeitch-fiverr, if the maintainers agree.

**Comment by marcosvega91** [comment]
Hi @ofekdeitch-fiverr :)

I think that it could be a nice to have. BTW a workaround could be to use `typeof` operator.

**Comment by ofekdeitch-fiverr** [comment]
@marcosvega91 @kettanaito 
Hi, 👋  
Please review my PR: (whenever you have the time)
https://github.com/mswjs/msw/pull/458
