### ISSUE TITLE
[v0.22.0] Not parsing JSON body

### ISSUE THREAD

**Issue by otaciliolacerda** [mswjs/msw#462]
## Describe the bug
Hi, I am not sure if this is a bug or was a planned changed but after upgrading msw to the latest version, part of my tests started to fail. I fount this [commit](https://github.com/mswjs/msw/commit/e6b60c0fbc467850ca3a4cbd117ad900bf19dd66) that changes the condition to parse the body.

Now when we have the following header:
```
Content-Type: application/json; charset=UTF-8
```

The body is not parsed.

## Environment

- `msw: 0.22.0`
- `nodejs: 12.19.0`
- `npm: 6.14.8`

## To Reproduce
1. Create a REST request handler
2. Send a request with json body and add header `Content-Type: application/json; charset=UTF-8`
3. `req.body` inside the request handler will be a string

## Expected behavior
When the `content-type` header is `application/json`, the body is automatically parsed.

**Comment by kettanaito** [comment]
Hi, @otaciliolacerda. Thanks for reporting this. 

That's a great catch, I believe that commit overlooks the `charset` as a part of the `Content-Type` request header. Reverting the logic to use `.includes()` should resolve the issue.

Would you be interested in shipping a pull request?

**Comment by otaciliolacerda** [comment]
Yes, I will take a look on this. Thanks for the super fast reply.

**Comment by kettanaito** [comment]
`.includes` may be susceptible to errors if the `Content-Type` header includes an arbitrary content type, or a content type that includes the phrase "json" but does not represent an actual JSON content type. However, I still suggest we revert to `.includes` and address that only when such issue arises.
