### ISSUE TITLE
MSW alongside Nock

### ISSUE THREAD

**Issue by neurosnap** [mswjs/msw#477]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.22.3   |
| node | 12.18.3     |
| OS   | mac osx 10.15.7     |

We currently have a relatively large test suite that uses `nock`.  We want to switch over to `msw` but don't want to do it in a single massive PR.  How would anyone recommend we run `msw` alongside `nock`?

My first guess is instead of starting the msw server in our setup test file, we should instead just start the server inside our tests that want to use msw.

**Comment by kettanaito** [comment]
Hey, @neurosnap. Thanks for reaching out.

I wouldn't recommend mixing `nock` and `msw`, as they both affect native request issuing modules (`http`/`https`). Both of them operating on a single NodeJS process may lead to unexpected behavior during your tests.

> My first guess is instead of starting the msw server in our setup test file, we should instead just start the server inside our tests that want to use msw.

You can try this, but ensure that your tests run in a single thread (i.e. with `--runInBand` option in case of Jest). Patching of the request issuing modules is per-process and it may leak the state between irrelevant tests.
