### ISSUE TITLE
Migrating to msw from nock

### ISSUE THREAD

**Issue by neurosnap** [mswjs/msw#478]
**Is your feature request related to a problem? Please describe.**

We currently have a relatively large test suite that uses nock. We want to switch over to msw but don't want to do it in a single massive PR. How would anyone recommend we run msw alongside nock?

**Describe alternatives you've considered**

My first guess is instead of starting the msw server in our setup test file, we should instead just start the server inside our tests that want to use msw.

**Comment by kettanaito** [comment]
Hey, @neurosnap.

You should be good to go with enabling MSW explicitly for certain test suites. Just remember to:

1. Clean up after test runs with `server.close()`.
1. Run tests in sequence, not in parallel (i.e. with the `--runInBand` option in Jest). Running tests in parallel may leak mocking from/to tests that use `nock` and vice versa, as they both would be sharing a single process.

To prevent repetitive setups of `server.listen`/`server.close`, consider creating a [custom test environment](https://jestjs.io/docs/en/configuration#testenvironment-string) and using it in those modules you wish to use MSW in:

```js
/**
 * @jest-environment ./envs/msw.js
 */
```

Other testing frameworks should have support for custom environments as well.

**Comment by neurosnap** [comment]
Hey @kettanaito 

Thanks for your timely feedback!  I like the idea of creating a custom test environment, but we are using typescript so our handlers are also written in typescript, which seems to be incompatible with test-environment files.  Regardless I wrote what I thought would work:

```js
const JSDOMEnvironment = require('jest-environment-jsdom');
const { setupServer } = require('msw/node');

const { handlers } = require('./packages/test/msw/handlers');

module.exports = class MSWEnvironment extends JSDOMEnvironment {
  constructor(config, options) {
    super(config, options);
    this.server = setupServer(...handlers);
  }

  async setup() {
    await super.setup();
    this.server.listen();
  }

  async teardown() {
    this.server.close();
    await super.teardown();
  }

  runScript(script) {
    const run = super.runScript(script);
    this.server.resetHandlers();
    return run;
  }
}
```

**Comment by kettanaito** [comment]
That environment looks fantastic!

Let us know how the incremental adoption goes and if we can be of any help.

**Comment by kettanaito** [comment]
I’ll close this since there’s no issue. Feel free to comment/reopen if you stumble upon any MSW-related obstacle.
