### ISSUE TITLE
POST is not intercepted in a dockerised enviroment that uses a network bridge

### ISSUE THREAD

**Issue by fasatrix** [mswjs/msw#479]
## Environment
**docker on windows running linux containers**
 **docker version**
```
Client: Docker Engine - Community
 Cloud integration: 1.0.1
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

## Request handlers

```js
import React from 'react';
import ReactDOM from 'react-dom';
import './css/index.css';
import App from './components/App';
import { CookiesProvider } from 'react-cookie';
import { MockedRequest } from 'msw';

async function render() {
    if (process.env.REACT_APP_MOCKED) {
        document.cookie = 'JSESSIONID=GSGJSGJSHGSH';
        document.cookie = 'name="Blueberry Developer"';
        // eslint-disable-next-line
        const { worker } = require("./mocks/browser");
        await worker.start({
            waitUntilReady: true,
            serviceWorker: {
                url: `${process.env.PUBLIC_URL}/mockServiceWorker.js`,
            },
            onUnhandledRequest: (req: MockedRequest) => {
                console.error('Found an unhandled %s request to %s', req.method, req.url.href);
            },
        });
    }

    ReactDOM.render(
        <CookiesProvider>
            <React.StrictMode>
                <App />
            </React.StrictMode>
        </CookiesProvider>,
        document.getElementById('root'),
    );
}

render();
```

## Actual request

```js
    function createGitHubRepo(payload: ICreateRepo): void {
        fetch(`${backEndHost}/api/v1/repos/create`, {
            method: 'POST',
            mode: 'cors',
            credentials: 'include',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ name: payload.repoName, description: payload.description }),
        })
            .then(async (res) => {
                if (res.status === 201) {
                    const r = await res.json();
                    setState({ success: true, error: false, body: r });
                } else if ([400, 415].includes(res.status)) {
                    setState({ success: false, error: true, body: { clone_url: '', url: '' } });
                } else if (res.status === 500) {
                    setState({ success: false, error: true, body: { clone_url: '', url: '' } });
                }
            })
            .catch((err) => {
                throw new Error(err);
            });
    }
```

## Current behavior
Architecture:
I have my react App running on docker fully mocked via MSW. 
**Command run** 
**docker run -it --rm --network app --name catalogue -p 3001:3001 -v "C:\Projects\step-enablement-catalogue\web":/workspace--bind 0.0.0.0 -w /workspace--entrypoint "npm" node:lts run mock**

I run my playwright tests within a docker container with the following command:
**docker run -it --network app --rm --name playwright -v "C:\Projects\step-enablement-catalogue\web\e2e_tests":/workspace -e TEST_URL=http://catalogue:3001 -w /workspace --entrypoint "npm" mcr.microsoft.com/playwright run test-pipeline**

The two containers see each other via a network bridge named "app" (command: **docker network create --driver bridge app** )

## What is happening?
Scenarios executed:
 1) App running on my computer (win 10), Tests executed via my computer ---> all tests pass including those that fires POST requests (MSW responds well) 
 2) App running on docker container,  Tests executed via my computer ---> all tests pass including those that fires POST requests (MSW responds well) 
3) App running on docker container,  Tests executed within a different container ---> Not all tests pass, the one that fires POST request are not triggering an MSW response

## Expected behavior

Test should pass even in the third scenario an MSW should respond to POST even within a container

## Screenshots
Screenshots for first and second scenarios:

![image](https://user-images.githubusercontent.com/16127426/100399007-ef7b9680-30b5-11eb-91f8-1d39801267e1.png)

![image](https://user-images.githubusercontent.com/16127426/100397599-7711d700-30af-11eb-9539-0f4788019363.png)

Unfortunately as the dockerised version runs headless I can only provide console logs captured from playwright code and a screenshot captured from playwright tests. As you can see the Test has clicked on the "Submit" button and from logs you can see that request POST has been fired properly but MSW doesn't seem to be responding.

![image](https://user-images.githubusercontent.com/16127426/100399142-7c265480-30b6-11eb-99a9-e94d577833cf.png)

[output.txt](https://github.com/mswjs/msw/files/5605339/output.txt)

**As you can see the POST goes to 404**
`[1A[999D[K  [2mconsole.log[22m
    POST http://catalogue:3001/api/v1/repos/create {"user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/88.0.4324.0 Safari/537.36","content-type":"application/json","accept":"*/*","origin":"http://catalogue:3001","referer":"http://catalogue:3001/step-enablement-github-service","cookie":"JSESSIONID=GSGJSGJSHGSH; name=\"Blueberry Developer\""}
[2m[22m
[2m      [2mat [22m[2mutils/commonUtils.ts[2m:34:17[22m[2m[22m

[999D[K  [2mconsole.log[22m
    404 http://catalogue:3001/api/v1/repos/create`

**Comment by marcosvega91** [comment]
Hi @fasatrix thanks for reaching us 😄 ,

I'll try to explain what is going on here. 

MSW uses service worker to intercept requests in the browser. Unfortunately one of the limitation of SW is that if your run it on a domain different from localhost you need a ssl certification. You can go [here](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) under `Why is my service worker failing to register?` section. This is your case, you can see a log in your attached file `[MSW] Failed to register a Service Worker:`. 

The strange part is the your second case is working. Could you share more info about that case? Which domain are you using for your application in that case?

**Comment by fasatrix** [comment]
> Hi @fasatrix thanks for reaching us 😄 ,
> 
> I'll try to explain what is going on here.
> 
> MSW uses service worker to intercept requests in the browser. Unfortunately one of the limitation of SW is that if your run it on a domain different from localhost you need a ssl certification. You can go [here](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) under `Why is my service worker failing to register?` section. This is your case, you can see a log in your attached file `[MSW] Failed to register a Service Worker:`.
> 
> The strange part is the your second case is working. Could you share more info about that case? Which domain are you using for your application in that case?

Hi there , thanks for your reply.. In the first and second scenario as you can see from the screenshot the URL is localhost. In the third scenario , docker, to reach the app I have use the container name.. this how docker with network bridge communicate with each other.. strange thing is that I have three mocks and two of them are working (GET) but not the POST.

**Comment by fasatrix** [comment]
> > Hi @fasatrix thanks for reaching us 😄 ,
> > I'll try to explain what is going on here.
> > MSW uses service worker to intercept requests in the browser. Unfortunately one of the limitation of SW is that if your run it on a domain different from localhost you need a ssl certification. You can go [here](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) under `Why is my service worker failing to register?` section. This is your case, you can see a log in your attached file `[MSW] Failed to register a Service Worker:`.
> > The strange part is the your second case is working. Could you share more info about that case? Which domain are you using for your application in that case?
> 
> Hi there , thanks for your reply.. In the first and second scenario as you can see from the screenshot the URL is localhost. In the third scenario , docker, to reach the app I have use the container name.. this how docker with network bridge communicate with each other.. strange thing is that I have three mocks and two of them are working (GET) but not the POST.

Also the third point in your link clearly doesn't apply to me  as you can see from the first two screenshots origin and mock URL are totally different 🤣

**Comment by marcosvega91** [comment]
It's strange that GET requests are intercepted in the third case, as in my post above MSW is not working because service worker is not registered because of SSL issue.

**Comment by fasatrix** [comment]
> It's strange that GET requests are intercepted in the third case, as in my post above MSW is not working because service worker is not registered because of SSL issue.

That's what I am trying to say  here.  MSW behaviour looks inconsistent across the board and I am not sure neither why or how I can work around it. Regardless imho mock solutions should be able to function in virtualised infrastructure such us dockers or kubernetes as this is how technology unfolds these days ( deploy cointeinerised apps fully mocked ----> test rapidly ---> deploy to the next stage ---> repeat)

Anyhow grazie Marco per l'aiuto ;-)

**Comment by marcosvega91** [comment]
I understand about docker, I use it too and you're right. I have never tried but I think that a self signed certificate could solve the problem. In the next days I'll try to create a small repo on GitHub to test some solutions.

Grazie a te 😊

**Comment by fasatrix** [comment]
> I understand about docker, I use it too and you're right. I have never tried but I think that a self signed certificate could solve the problem. In the next days I'll try to create a small repo on GitHub to test some solutions.
> 
> Grazie a te 😊

Awesome 👍

**Comment by marcosvega91** [comment]
Hi @fasatrix I have made this example repo https://github.com/marcosvega91/msw-ssl

I don't have used docker for this example but it should be the same. Anyway, I'll add it later.

In your docker environment, you could create a certificate on your container using [mkcert](https://github.com/FiloSottile/mkcert) for the domain `catalogue` and then run your test using the address `https://catalogue:3001` instead of `http://catalogue:3001`

**Comment by fasatrix** [comment]
> Hi @fasatrix I have made this example repo https://github.com/marcosvega91/msw-ssl
> 
> I don't have used docker for this example but it should be the same. Anyway, I'll add it later.
> 
> In your docker environment, you could create a certificate on your container using [mkcert](https://github.com/FiloSottile/mkcert) for the domain `catalogue` and then run your test using the address `https://catalogue:3001` instead of `http://catalogue:3001`

Grazie mille Marco and amazing response. Will let you how how it goes

**Comment by fasatrix** [comment]
@marcosvega91  An update.

I am not getting this error while trying to register the service worker

**ERR [MSW] Failed to register a Service Worker:
    mFailed to register a ServiceWorker for scope ('https://catalogue:3001/') with script ('https://catalogue:3001/mockServiceWorker.js'): An SSL certificate error occurred when fetching the script.**

Caertificate has been create via mkcert using this handy docker (https://github.com/vishnudxb/docker-mkcert):

**docker run -d -e domain=catalogue --name mkcert -v "C:\myproject\mkcert-data":/root/.local/share/mkcert vishnunair/docker-mkcert**

Then used in the node startup script:

**"scripts": {
    "start": "HTTPS=true SSL_CRT_FILE=./mkcert-data/catalogue.pem SSL_KEY_FILE=./mkcert-data/catalogue-key.pem react-scripts start"
}**


Same happens if I install mkcert manually on my laptop and generates the pem files

Any idea to why is it still failing to register? 

Appreciate your help

**Comment by kettanaito** [comment]
Note that if it’s a self-signed certificate you need to enable your browser to trust such certificates. By default Service Worker won’t register on a secure host with a non-trusted certificate.

**Comment by marcosvega91** [comment]
Where are you trying to access your application?. Remember that because of the certificate is self signed you need to install the CA certificate on every device that need to access your application. So if you need to access your application from playwright container you need to install also th CA there.

If you have created the certificate from your computer you can then run `mkcert -CAROOT` that will print the folder containing the CA file

**Comment by fasatrix** [comment]
> 
> 
> Where are you trying to access your application?. Remember that because of the certificate is self signed you need to install the CA certificate on every device that need to access your application. So if you need to access your application from playwright container you need to install also th CA there.
> 
> If you have created the certificate from your computer you can then run `mkcert -CAROOT` that will print the folder containing the CA file

So the containerised react APP is using the cert via npm scrip (**HTTPS=true SSL_CRT_FILE=./mkcert-data/catalogue.pem SSL_KEY_FILE=./mkcert-data/catalogue-key.pem react-scripts**)t, where as the Playwirght Test container is using those certs via 

export NODE_EXTRA_CA_CERTS=/workspace/mkcert-data  before running the test 

my npm script int he playwright container is the following:

   **"test-pipeline": "export NODE_EXTRA_CA_CERTS=/workspace/mkcert-data  && npm install && cross-env PIPELINE_URL=https://catalogue:3001 npx jest CreateRepoPage.spec.ts"**

When you say I need to install the CA container in the playwright APP does that mean that I Will have to "mkcert install" there too? That does sound right unless you mean I need to copy the CA into the playwright container? In that case would the location matter?

Content of the cert folder
![image](https://user-images.githubusercontent.com/16127426/100555733-64431080-3302-11eb-8cfd-e5082d367557.png)

**Comment by marcosvega91** [comment]
I have updated my repo with a working docker example.

You need to add the certificate to the trust store on your test container. I have created a `Dockerfile` from the playwright image and installed the correct certificate in that container.

Be sure that your `cert.pem` and `key.pem` are created for domain `catalogue`

```bash
mkcert -key-file ./mkcert-data/key.pem -cert-file ./mkcert-data/cert.pem localhost catalog
```

**Comment by fasatrix** [comment]
> 
> 
> I have updated my repo with a working docker example.
> 
> You need to add the certificate to the trust store on your test container. I have created a `Dockerfile` from the playwright image and installed the correct certificate in that container.
> 
> Be sure that your `cert.pem` and `key.pem` are created for domain `catalogue`
> 
> ```shell
> mkcert -key-file ./mkcert-data/key.pem -cert-file ./mkcert-data/cert.pem localhost catalog
> ```

Thanks @marcosvega91  this is very helpful, I am still getting MSW failed to register but trying a few things. I noticed that your test run full head and if not too much trouble would mind confirming that MSW registers properly even if you run playwright headless (**await chromium.launch({ headless: true})**)? This way I can exclude all possible issues other than with my local machine/env



Thanks

**Comment by marcosvega91** [comment]
it's already headless, I have created the config file `jest-playwright.config.js` with that option. 
I try to recap the steps:

1. Create create for your domain ( catalogue)
2. Create CA in your local pc
3. Copy all created file under a folder shared with containers
4. Use certificate in your react application
5. Install certificate in your test container

I have seen that you have used NODE_EXTRA_CA_CERTS. In this case is not useful because you are using the browser. Be sure to install the CA certificate. 

I have added also this two important steps in my case

```
RUN mkdir -p $HOME/.pki/nssdb
RUN certutil -d sql:$HOME/.pki/nssdb -N --empty-password
```
To create a space for Chromium to load certificate

**Comment by fasatrix** [comment]
> 
> 
> it's already headless, I have created the config file `jest-playwright.config.js` with that option.
> I try to recap the steps:
> 
>     1. Create create for your domain ( catalogue)
> 
>     2. Create CA in your local pc
> 
>     3. Copy all created file under a folder shared with containers
> 
>     4. Use certificate in your react application
> 
>     5. Install certificate in your test container
> 
> 
> I have seen that you have used NODE_EXTRA_CA_CERTS. In this case is not useful because you are using the browser. Be sure to install the CA certificate.
> 
> I have added also this two important steps in my case
> 
> ```
> RUN mkdir -p $HOME/.pki/nssdb
> RUN certutil -d sql:$HOME/.pki/nssdb -N --empty-password
> ```
> 
> To create a space for Chromium to load certificate

Grande Marco, funziona adesso!
The reasons to why it wasn't working for me is because I am mounting the directory containing the certs after building the image and of course that didn't work(image had the cert directory empty). As soon as I added an additional copy (copy the certs from local to docker) the installation did pick the certs and installed them. I learned quite a lot from this exercise and once again thanks for your patience and direction

Thanks alot

**Comment by marcosvega91** [comment]
Thank you too, this discussion will be useful for other person too I think ☺️. I'll close the issue, alla prossima 😉
