### ISSUE TITLE
Return a stream from Mocked Response

### ISSUE THREAD

**Issue by yairkukielka** [mswjs/msw#480]
Would it be possible stream content?

**Comment by kettanaito** [comment]
Hey, @yairkukielka. That's a great suggestion. 

While I research the streams and think of a good recipe/integration test, would you mind sharing your use case? It'd help us understand how the API should be extended.

**Comment by kettanaito** [comment]
It should be possible to return a `ReadableStream` as the mocked response body using a similar recipe as the [Binary response](https://mswjs.io/docs/recipes/binary-response-type):

```js
import { setupWorker, rest } from 'msw'
import base64Image from 'url-loader!../fixtures/image.jpg'

const worker = setupWorker(
  rest.get('/image', async (req, res, ctx) => {
    // Convert any data into a ReadableStream via "fetch"
    const stream = await fetch(base64Image).then((res) => res.body)

    // Return the stream from the mocked response.
    return res(ctx.body(stream))
  }),
)

worker.start()
```

Handling of the mocked stream response should not differ from the handling of an actual streamed response. 

Could you please try this suggestion and let me know if it works for you?

**Comment by yairkukielka** [comment]
Great! Thank you! I'll try it and get back to you

**Comment by yairkukielka** [comment]
In my use case, in the browser, I just want to read the text response as a stream, because the response is very large (and not in json format).

It turns out that on the worker side we don't seem to have to do anything special. Doing

```
return res(ctx.body('hey there'))
```

or even with 

```
return res(
  ctx.json({
    firstName: 'John',
    age: 38,
  }),
)
```

we can consume a stream on the client side. Just using 
```
fetch('myurl')
.then((res) => {
  const reader = res.body().getReader(); // reader is a ReadableStream
  const { done, value } = await reader.read();
  ...
})
```

So, it seems we simply have to read it as a normal ReadableStream on the fetch client side. I guess it will be similar when using nodejs.

**Comment by kettanaito** [comment]
Hi, @yairkukielka. Please let us know if you're facing any problems, as you've reopened the issue. Thanks.
