### ISSUE TITLE
Middleware for Requests

### ISSUE THREAD

**Issue by balavishnuvj** [mswjs/msw#481]
**Is your feature request related to a problem? Please describe.**
Middlewares would help in building dev tools/extend MSW without having to fork the repo.

Let's say we want to "monitor" all the requests that are responded by the server. So that we can assert the requests made.
Middleware/emitting responded event would help in building that.

**Describe the solution you'd like**
Should be able to add "middleware" or event emitted.

```js
server.middlewares(middleware)
```

**Describe alternatives you've considered**
Right now to achieve this, we can add some logic to catch request in each handler.

```js
let loginRequests = [];

server.use(
    rest.post('/login', (req, res, ctx) => {
        loginRequests.push(req);
        return res(ctx.json({ data: 'data'}));
    }),
);
```
But this would have to duplicated and we can't reliably abstract this logic out.

**Comment by kettanaito** [comment]
Hey, @balavishnuvj. Thanks for raising this.

I think this feature would be useful, yet let's try to come up with a few more usage examples for it? Once there are more use cases it can handle, we can have a better look at the end API.

**Comment by kettanaito** [comment]
We can establish an event-based API that could also support request start/finish notifications (#388) for users to execute their logic.

```js
const worker = setupWorker(...)
worker.events.on('request-start', listener)
worker.events.on('request-end', listener)
```

You could then use this API in your tests to monitor all requests like so:

```js
const loginRequests = []
const server = setupServer(...)

server.events.on('request-intercepted', (req) => {
  loginRequests.push(req)
})
```

Would this work for your use case?

**Comment by balavishnuvj** [comment]
yeah emitting event would work well for this use case.

**Comment by zikaari** [comment]
Since our use case is just to assert and check for any misbehaving network parts, we set up a custom network recorder for one of our codebases, `msw` could possibly adopt a variant of this:

This was heavily inspired by the Network panel in Chrome devtools.

```ts
export type NetworkTransaction = {
  request: HttpRequest<any>;
  response: HttpResponse<any>;
}

export type NetworkRecording = {
  readonly transactions: ReadonlyArray<NetworkTransaction>;
  readonly lastRequest: NetworkTransaction['request'];
  stop(): void;
}

export type NetworkRecordingConfig = {
  /**
   * Sets the limit of the recorder at which `afterLimit` action will be taken
   *
   * @default 20
   */
  maxKeyframes?: number;

  /**
   * Action to take once max limit is reached.
   *
   * `'stop'` - stops the recorder
   *
   * `'fifo'` - first in, first out. shifts the frame stack by one to make space for a new frame
   *
   * @default 'stop'
   */
  afterLimit?: 'stop' | 'fifo';

  /**
   * Only record frames who's request URL match the given pattern
   *
   * By default will record all requests and responses until max limit is reached
   */
  filter?: RegExp;
}

const createServer = () => ({
	startNetworkRecording: (config: NetworkRecordingConfig) => { /* implement */ }
})
```

**Comment by kettanaito** [comment]
You can now use the [Life-cycle events API](https://mswjs.io/docs/extensions/life-cycle-events).

**Comment by Secretmapper** [comment]
My use case is to check how my app handles errors (403, 401, 500) gracefully. I thought I could use a cookie that a middleware would check, and if present, bails out and returns the proper status code early on. Is there any easy way to achieve this right now in msw?

**Comment by kettanaito** [comment]
@Secretmapper you can encapsulate this logic into a high-order resolver:

```js
import { setupWorker, rest } from 'msw'

function withError(resolver) {
  return (req, res, ctx) => {
    // Customize the predicate and response error
    // according to your needs.
    if ('shouldError' in req.cookies) {
      return res(ctx.status(403))
    }

    return resolver(req, res, ctx)
  }
}

const worker = setupWorker(
  rest.get('/user', withError((req, res, ctx) => {
    return res(ctx.json({ success: true }))
  }))
)

worker.start()
```

**Comment by silentsiri** [comment]
> @Secretmapper you can encapsulate this logic into a high-order resolver:
> 
> ```js
> import { setupWorker, rest } from 'msw'
> 
> function withError(resolver) {
>   return (req, res, ctx) => {
>     // Customize the predicate and response error
>     // according to your needs.
>     if ('shouldError' in req.cookies) {
>       return res(ctx.status(403))
>     }
> 
>     return resolver(req, res, ctx)
>   }
> }
> 
> const worker = setupWorker(
>   rest.get('/user', withError((req, res, ctx) => {
>     return res(ctx.json({ success: true }))
>   }))
> )
> 
> worker.start()
> ```

of course this solution is good, but the "middleware" like koa is better in my opinion

in my case, i want a whitelist to passthrough the matched request.

I found that the event lifecycle api happen post-factum, so it's unsuitable in my case

> Life-cycle events happen post-factum and cannot affect related requests/responses.

but if has the middleware, it seems too simple :D

```javascript
// fake code
const worker = setupWorker(
  rest.get('/user', (req, res, ctx) => {
    return res(ctx.json({ success: true }))
  })
)

// becuase of exsiting `use` api
worker.addMiddlewareApi((req, res, ctx, next) => {
  if (whilteList.includes(req.url)) {
    return req.passthrough();
  }
  next();
});
```

and the case in #1231 metioned is different with mine, i had these handlers, but i want to ignore it in conditional

**Comment by silent-tan** [comment]
#1231

**Comment by silent-tan** [comment]
#1231

**Comment by kettanaito** [comment]
@silent-tan, middleware is an appealing concept but it'd complicate the library's internals quite a bit. MSW still remains a straightforward request -> response matcher, and I wouldn't introduce concepts like middleware, at least at its current state. 

Note that with the addition of explicit `req.passthrough()`, you can prepend a handler that would be your middleware in the most direct sense of the word:

```js
import { rest } from 'msw'

// Match all HTTP requests.
const whitelistMiddleware = rest.all((req, res, ctx) => {
  // If the request is in the whitelist,
  if (whitelist.includes(req.url.href)) {
    // ...perform it as-is.
    return req.passthrough()
  }
})

export const handlers = [
  whitelistMiddleware,
  // ...other handlers.
]
```

Handlers are resolved in order, so the whitelist middleware will apply to all captured requests. If the condition is true, then the explicit `req.passthrough()` will instruct MSW to perform this particular request as-is. If not, the middleware is not returning anything, which means response lookup will fall through it, and continue with the other handlers below.

**Comment by silentsiri** [comment]
@kettanaito many thanks, that's what i need.

I just can't find the document of the `rest.all` api 😭 .

**Comment by kettanaito** [comment]
A good catch, @silent-tan! Adding `rest.all()` to the docs [here](https://github.com/mswjs/mswjs.io/pull/206).
