### ISSUE TITLE
Add "[MSW] Mocking disabled." console message

### ISSUE THREAD

**Issue by yairkukielka** [mswjs/msw#485]
Would currently get this console message when MSW is enabled: `[MSW] Mocking enabled.`

It would be great to add the `[MSW] Mocking disabled.` when it's disabled.

My use case:
I'm building a small web app to mesure the performance of a web library. I'm mocking backend calls with MSW. I added a checkbox that can be used to toggle activation, deactivation of the mocking and it would be great to have confirmation in the console with this message.

Thank you!

**Comment by kettanaito** [comment]
Hey, @yairkukielka. Thanks for the suggestion.

Would you be interested in creating a pull request with this improvement? It should be a matter of adding the log as a part of `.stop()`:

https://github.com/mswjs/msw/blob/8a5f573aed97dadce448df7e4acfb0d23d8eb18c/src/setupWorker/stop/createStop.ts#L9-L13

In the case of the `[MSW] Mocking disabled` message, it could be a simple `console.log`, as there is nothing to group. You can reference the implementation of the `[MSW] Mocking enabled` from `.start()` to see how such messages respect the `quiet` option:

https://github.com/mswjs/msw/blob/8a5f573aed97dadce448df7e4acfb0d23d8eb18c/src/setupWorker/start/utils/activateMocking.ts#L10-L14

**Comment by tigerabrodi** [comment]
@kettanaito I'd love to work on it as you suggested in Discord, seems also like a great way for me to get a bit more familiar with the repo :two_hearts:

**Comment by kettanaito** [comment]
That'd be awesome, @tigerabrodi! If you don't mind, I've assigned this issue to you, so others know somebody's taking care of it. Looking forward to our discussion on the code review.

**Comment by tigerabrodi** [comment]
@kettanaito Defo, no worries, thanks for the opportunity :smiling_face_with_three_hearts:
