### ISSUE TITLE
Compose a mocked response object using an actual response

### ISSUE THREAD

**Issue by Tomasgil-karvi** [mswjs/msw#492]
**Is your feature request related to a problem? Please describe.**

I want to use an actual response to compose a mocked response object.

**Describe the solution you'd like**
```
export const handlers = [
    rest.get(
        "url",
        async (req, res, ctx) => {
            const response = await fetch('url')
            let result = await response.json()
            result.x = ['new value']
            return res(result)
        }
    ),
];
```

**Describe alternatives you've considered**

**Additional context**

**Comment by kettanaito** [comment]
Hey, @Tomasgil-karvi. 

Use the `ctx.fetch` utility to fetch the original response and compose your mocked response based on it. There's more information in the [response patching recipe](https://mswjs.io/docs/recipes/response-patching).
