### ISSUE TITLE
Typescript error in compose.d.ts in CRA project

### ISSUE THREAD

**Issue by Rotarepmi** [mswjs/msw#499]
## Describe the bug
This error occurred during the build of CRA project, not during the mocking in tests.

```
TypeScript error in  /node_modules/msw/lib/types/utils/internal/compose.d.ts(3,12):
',' expected.  TS1005

    1 | declare type ArityOneFn = (arg: any) => any;
    2 | declare type PickLastInTuple<T extends any[]> = T extends [
  > 3 |     ...rest: infer U,
      |            ^
    4 |     argn: infer L
    5 | ] ? L : never;
    6 | declare type FirstFnParameterType<T extends any[]> = Parameters<PickLastInTuple<T>>[any];
```

## Environment

- `msw: 0.24.1`
- `nodejs: 15.0.1`
- `npm: 7.0.3`

- `typescript: 3.9.7`
- `react-scripts: 3.4.4`

**Comment by chrisguttandin** [comment]
Hi @Rotarepmi, I think this is a duplicate of #491. Are you able to update TypeScript to version 4?

**Comment by Rotarepmi** [comment]
Hi @chrisguttandin, thanks for the answer.
This is a duplicate. Didn't searched in the closed issues, sorry. 
Currently I'm not able to update TS to v.4, but at least I know what is wrong here :)

Closing
