### ISSUE TITLE
Can't handle big data.

### ISSUE THREAD

**Issue by olegKusov** [mswjs/msw#503]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.21.3   |
| browser | firefox 83.0     |
| OS      | macos 11  |

## Request handlers

```js
const prepare = async () => {
  if (process.env.NODE_ENV === 'development') {
    const {worker} = await require('./mocks/browser');
    return worker.start();
  }
  return Promise.resolve();
};
```

example of mock
![изображение](https://user-images.githubusercontent.com/28058268/101775867-295e8b00-3b01-11eb-900e-26a709f49655.png)

## Actual request

```js
export const getAxiosConfig = () => {
  const csrf = Cookie.get('csrftoken');

  const axiosConfig: AxiosConfigType = {
    baseURL: BASE_URL,
    headers: apiToken ? {Authorization: `Token ${apiToken}`, 'X-CSRFToken': csrf} : {},
  };

  return axiosConfig;
};

const getAxiosRequest = <T>(
  type: 'get' | 'post' | 'delete',
  route: string,
  data?: object,
  headers?: object
) => {
  const baseConfig = getAxiosConfig();
  const axiosConfig = {
    ...baseConfig,
    headers: {
      ...baseConfig.headers,
      ...(headers || {}),
    },
  };

  switch (type) {
    case 'delete':
      return axios.delete(route, axiosConfig);
    case 'get':
      return axios.get<ApiResponseProps<T>>(route, axiosConfig);
    case 'post':
      return axios.post<ApiResponseProps<T>>(route, data || {}, axiosConfig);
    default:
      return axios.get<ApiResponseProps<T>>(route, axiosConfig);
  }
};

const genericRequest = <T>(type: 'get' | 'post' | 'delete', headers?: object) => async (
  route: string,
  data?: object
) => {
  return new Promise<ApiResponseProps<T>>((resolve) => {
    const encodeQuery = () => {
      if (!data) {
        return '';
      }
      return `?${Object.keys(data)
        .map((k) => `${encodeURIComponent(k)}=${encodeURIComponent((data as any)[k])}`)
        .join('&')}`;
    };
    const routeWithSlash = route.slice(-1) === '/' ? route : `${route}/`;
    const url = type === 'post' ? routeWithSlash : routeWithSlash + encodeQuery();
    getAxiosRequest<T>(type, url, data, headers)
      .then((response) => {
        resolve(response.data);
      })
      .catch(() => {
        resolve({
          err: {
            detail: 'Internal client Error',
            code: -1,
          },
        });
      });
  });
};

export const netPOST = <T>(route: string, data: object, headers?: object) =>
  genericRequest<T>('post', headers)(route, data);

export const netGET = <T>(route: string, data?: object) => genericRequest<T>('get')(route, data);
```

# Example of making a request. Provide your code here.
```js
const res = await netGET<DashboardTemplate[]>(`${clientID}/${appID}/templates/list/`);
```

## Current behavior
I used static urls without patterns line /:app/:template/apps/list. But know, when I change static /30/20/template/apps/list to /:app/:template/apps/list it can't see mocks of endpoints on full page reload (with not full reload it works well, for example if i first open login page and then go to main page).

When I reload page it can't handle mocking. I think it's problem with mock size it's 327KB. Sometimes it loads but sometimes it fails (90% of attempts fail).

Moreover it even can't handle urls where is no params. for example "/clients/". I don't know why it's happening but it starts after i changed some endpoints from static urls to urls with dynamic params.

## Expected behavior

See mock urls on full page reload.

**Comment by kettanaito** [comment]
Hi, @olegKusov.

Can you please clarify what in your opinion causes the issue:

1. A big amount of request handlers created.
1. A big size of data that certain handlers send (i.e. a huge JSON).

I cannot figure out what exactly is going on by the info you've provided (what exactly is `mock size`?). Thanks.

**Comment by olegKusov** [comment]
> Hi, @olegKusov.
> 
> Can you please clarify what in your opinion causes the issue:
> 
> 1. A big amount of request handlers created.
> 2. A big size of data that certain handlers send (i.e. a huge JSON).
> 
> I cannot figure out what exactly is going on by the info you've provided (what exactly is `mock size`?). Thanks.

this happens when i add conditional params. ":param". i dont know why its happening

**Comment by timdeschryver** [comment]
@olegKusov can you create a reproduction? It would help us to troubleshoot this and help you.

**Comment by kettanaito** [comment]
I'm closing this until we get a reproduction repository, sorry. 

Try using the debugging tools available to you to narrow down the issue. It often lies elsewhere of MSW, but of course there's a chance we can ship an improvement. Thanks.
