### ISSUE TITLE
Typescript error: expecting "," in type PickLastInTuple (utils/internal/compose)

### ISSUE THREAD

**Issue by maurealtrends** [mswjs/msw#512]
## Describe the bug
After installing and following the steps provided in the documentation, I tried to run my app (CRA) but a Typescript compilation error arise (see screenshot attached).

## Environment

- `msw: ^0.24.2`
- `nodejs: 15.3.0`
- `npm: 7.0.14`
- `typescript: ^3.9.5`
- `react: ^16.13.1"`
- `react-dom: ^16.13.1"`
- `react-scripts: 3.2.0`

## `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es2016",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": ["src"]
}
```

## To Reproduce
1. Follow the complete guide up until [Verify and Inspect](https://mswjs.io/docs/getting-started/integrate/browser#verify--inspect)
2. Run your CRA app
3. See error

## Expected behavior
I expected the app to build succesfully.

## Screenshots
![image](https://user-images.githubusercontent.com/47781631/102217006-bbc4ad00-3eba-11eb-9d73-5a758fe9b56c.png)

**Comment by chrisguttandin** [comment]
Hi @maurealtrends, I believe this is a duplicate of #491. Is it possible for you to update TypeScript to v4?

**Comment by maurealtrends** [comment]
> Hi @maurealtrends, I believe this is a duplicate of #491. Is it possible for you to update TypeScript to v4?

I'll try right now and get back to you as ASAP 😉

**Comment by maurealtrends** [comment]
It worked!

Thank you very much and sorry for the inconvenience.

**Comment by chrisguttandin** [comment]
No problem. I'm happy that we could solve it so quickly.
