### ISSUE TITLE
Unable to intercept React Native Image source URI requests in Jest tests

### ISSUE THREAD

**Issue by wKovacs64** [mswjs/msw#517]
I'm trying to use msw in Jest tests (so, Node) to intercept React Native's `Image` component network requests. I have no need to leverage msw in RN itself at this time, so this should pertain purely to Node integration (as I understand it). I messed around with various uses of `react-native-url-polyfill` and `node-fetch` to no avail, but they are not currently utilized in the reproduction below.

## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.24.2   |
| node | 14.15.1 |
| OS   | Windows 10 and macOS Big Sur     |

## Request handlers

```js
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const server = setupServer(
  rest.get('anything-other-than-source-uri-provided-to-image', () => {...})
)

server.listen({ onUnhandledRequest: 'error' })
```

## Actual request

```js
<Image source={{ uri: 'https://some-unhandled-uri' }} />
```

## Current behavior

Test renders the component without errors.

## Expected behavior

Expected msw to throw as there is no handler defined for the source URI provided, and `onUnhandledRequest` is set to `'error'`.

## Full Reproduction

https://github.com/wKovacs64/msw-rn-test

**Comment by kettanaito** [comment]
Hey, @wKovacs64. Thanks for reporting this.

We'd have to investigate this. Perhaps assets are loaded in some other way, which circumvents requests interception provisioned by MSW. If you find out anything, please post here.

**Comment by marcosvega91** [comment]
Hi @wKovacs64 thanks for reaching us :).

I'll try to explain my opinion on this issue.

I think that this approach is not possible with native modules and MSW. `Image` component should fetch images using ios/android native code so I think that we can't do more here. Another problem is that DOM is not really rendered using  jest and `@testing-library/react-native` because the library uses [`Test Renderer`](https://reactjs.org/docs/test-renderer.html) under the hood. 😢

**Comment by wKovacs64** [comment]
> I think that this approach is not possible with native modules and MSW. `Image` component should fetch images using ios/android native code so I think that we can't do more here.

This is what I was afraid of, yeah. ☹️ The `Image` component does accept some fetch-like props (e.g. `method`, `headers`, etc.) so I was hoping it might be an XHR but I suspect you're right.

**Comment by kettanaito** [comment]
Can somebody please enable MSW with a permissive handler and see if it catches the request for the image URL?

```js
setupServer(
  rest.get('*', (req) => console.log(req.url.href))
)
```

**Comment by marcosvega91** [comment]
I have tried also with `DEBUG=*` but I don't see any log from interceptors. I only see about patching

**Comment by kettanaito** [comment]
Per @marcosvega91:

> Image component should fetch images using ios/android native code so I think that we can't do more here.

It doesn't seem we can tackle this on the library's side. If anybody finds out more details, please comment here. Thanks.
