### ISSUE TITLE
Forward leading slash to match the page's hostname

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#52]
Current behavior expects the developer to either specify an entire hostname (`http://backend.com/users`) or use a wildcard (`*/users`) to handle request URI.

## Motivation

It's familiar to developers to specify routes with a leading slash and expecting the hostname to be matched implicitly.

## Expected behavior

When provided the route `/users` MSW would match any `/users` requests that are fired from the _current page's hostname_:

- `http://localhost:8080/users`

**However, it won't match the same paths from the different hostname:**

- `https://api.dev.backend/users`

**Comment by kentcdodds** [comment]
Perfect. Thank you!

**Comment by kettanaito** [comment]
@kentcdodds thank you for illustrating how confusing this gets in [your stream](https://www.youtube.com/watch?v=9Dcj-OrsIc8&feature=youtu.be&t=4674). This should be a trivial change.

**Comment by kettanaito** [comment]
Released in `0.5.1`. Examples in the documentation were updated to use the leading slash without a wildcard, where applicable.

- [Mocking REST API](https://app.gitbook.com/@redd/s/msw/tutorials/mocking-rest-api)
