### ISSUE TITLE
Call Count Matcher

### ISSUE THREAD

**Issue by martinfrancois** [mswjs/msw#526]
**Is your feature request related to a problem? Please describe.**
When I use `msw` in unit testing, I would like to make sure that for example an API call was only performed once by a component and would like the test to fail if a call was made more than once (since that wouldn't be the expected behavior).
Currently using `msw` this is quite messy, as every call needs to be saved into a variable and checked against in each of the handlers. This may be acceptable for one handler, but when using multiple handlers this gets messy really quickly and requires a lot of boilerplate code.

**Describe the solution you'd like**
Extend the response handlers in a way to allow to add matchers for the amount of calls the response handlers should match for.

For example, a simple way would be to just match for exact counts:
```
rest.get('/projects', (req, res, ctx) => { ... }, 2)
```
Which would in this case match for **exactly 2**.

To make it more flexible, instead of just allowing to specify an exact amount of matches, I could imagine a separate count matcher class which can be used, similar to how it's done in [mockito](https://javadoc.io/static/org.mockito/mockito-core/3.7.0/org/mockito/Mockito.html#4):
```
rest.get('/projects', (req, res, ctx) => { ... }, atLeast(1))
rest.get('/projects', (req, res, ctx) => { ... }, times(2))
rest.get('/projects', (req, res, ctx) => { ... }, atMost(3))
```

To prevent this from being a breaking change, I would add this as an optional parameter at the end of the current `rest` methods, which would make the signature be `mask: ..., resolver: ..., countMatcher?: ...`. Omitting this optional parameter would result in the same behavior as before.

Every match beyond that would result in an **unhandled request** as is already the case when a request handler is not present for a request. It can then be handled by `onUnhandledRequest` as is already possible. 

**Describe alternatives you've considered**
- As mentioned before, it would be possible to define a `const` for each request handler and then incrementing the count in every different `const` for each different request handler and adding corresponding logic in every request handler to check if the count is reached. But this adds a lot of boilerplate code, making the code less readable and more difficult to maintain, which goes against what `msw` wants to achieve.
- [fetchMock](https://www.npmjs.com/package/fetch-mock) has an option to match for calls as described here, but only works with `fetch` and doesn't work in the browser

**Comment by kettanaito** [comment]
Hey, @martinfrancois. Thanks for reaching out.

While this is a useful feature, MSW does not include any assertion API on purpose, so I wouldn't expect such assertions to come natively in MSW. You should be able, however, to leverage other APIs to achieve your goal. For instance, we've only recently released the [Life-cycle events API](https://mswjs.io/docs/extensions/life-cycle-events) that you can leverage to provision assertions on request calls count:

```js
test('my test', () => {
  const dispatchRequest = jest.fn()
  server.on('request:start', dispatchRequest)

  expect(dispatchRequest).toHaveBeenCalledTimes(1)
})
```

I also highly recommend adding an assertion on the arguments passed to `dispatchRequest`, which is a `req` object. You may wish to check its `req.url` and method to make a good test out of such an assertion. 

Hope this helps.
