### ISSUE TITLE
Cannot mock 204 response

### ISSUE THREAD

**Issue by abrudin** [mswjs/msw#530]
## Describe the bug
It seems to be impossible to construct a 204 (No content) response. When I just invoke
`return res(ctx.status(204))`
I get the following error:
**_Failed to construct 'Response': Response with null body status cannot have body_**
It does not help trying to add `ctx.json({})` or `ctx.body(null)` - the body seems to end up as the empty string regardless. This fails when msw is trying to invoke `const response = new Response(payload.body, payload)` in the function `createResponseListener` as responses with status 204 are not allowed to have any body.

## Environment

- `msw: 0.25.0`
- `Chrome: 87.0.4280.141`

**Comment by marcosvega91** [comment]
Hi @abrudin thanks for rasing this :).

I have opened a PR with the fix. The problem is that in the `service worker` `response.text()` has been called. But the return value of that method is an empty string if the body is null.

**Comment by abrudin** [comment]
@marcosvega91 It makes me really comfortable using this library with this incredibly low response time on issues - just don't push yourself too hard :)

**Comment by marcosvega91** [comment]
We are trying to make our best :)

**Comment by SerkanSipahi** [comment]
@marcosvega91 The issue still exists and it seems that https://github.com/mswjs/msw/commit/40920214c1c22a06d640cc3a1006528e2ba6e679 is not merged. 
Did that has any reason? Can I help?

In my case status-code 204 with a json response produces exactly the same error what @abrudin above described.

**Comment by kettanaito** [comment]
Hi, @SerkanSipahi. The change you're referencing has been successfully merged:

https://github.com/mswjs/msw/blob/9a43bc9cba49f3c18b1ab1ed700d3f41f9fe86f5/src/mockServiceWorker.js#L129-L130

Could you please ensure you're running `msw@0.29.0`?

```sh
# To verify
$ npm ls msw

## To install latest
$ npm install msw@latest
```

> In my case status-code 204 with a json response produces exactly the same error

Perhaps the response you're composing is not a valid HTTP response? A response with a 204 status code cannot have a response body, that'd be a violation of the spec. Can you please try composing a mocked 204 response _without_ any response body?

```js
return res(ctx.status(204))
```

**Comment by SerkanSipahi** [comment]
@kettanaito 

You are right. It was my mistake. The 204 response contained an empty ( {} ) body payload in my case. As you suggested `res(ctx.status(204))` is the right way here.

Thank you for your support and time.

**Comment by andredewaard** [comment]
`res(ctx.status(204))` will throw an error
`The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal`
any solution to this?
