### ISSUE TITLE
GraphQL handlers incorrectly match REST handlers when the JSON body contains a query key

### ISSUE THREAD

**Issue by baseten** [mswjs/msw#532]
## Describe the bug
In our app we need to maintain both REST and GraphQL endpoints and need to mock both simultaneously for some tests. Unfortunately we happen to have a REST `POST` request with a JSON request body containing the key `query`. This causes the error `Body must be a string`, as any GraphQL request handler attempt to parse it during the handler matching stage here: https://github.com/mswjs/msw/blob/9c894760fef38f84d8fd4841a837a5ab6e1c5ec7/src/graphql.ts#L143

## Environment

- `msw: 0.25.0`
- `nodejs: 10.15.3`
- `npm: 6.4.1`

## To Reproduce
1. Call `setupServer` with both a `rest.post` and `graphql.query` handler
2. In the code under test fire an API POST request containing a JSON body with a `query` key
3. Tests fail to run with `Body must be a string` error

## Expected behavior
The GraphQL handler should not attempt to parse the REST API body. I appreciate this is tricky as `query` is really the only defined way to determine if a `POST` request is GraphQL or not. Perhaps if `query` is not a string in this case, rather than throwing an error it could be assumed that the handler doesn't match?

This is a similar issue as faced with the unhandled endpoint mechanism: https://github.com/mswjs/msw/issues/527

**Comment by kettanaito** [comment]
Hey, @baseten. Thanks for raising this up. This issue is known (see #489) and is currently under discussion. Unfortunately, there's no reliable way to tell apart a GraphQL query and a seemingly compatible regular REST API request.

**Comment by baseten** [comment]
Ah sorry missed the existing issue. Yes, agree there's not a reliable way to test for, potentially it could be solved by whitelisting the GraphQL endpoint URL as described here: https://github.com/mswjs/msw/issues/527#issuecomment-756854204
