### ISSUE TITLE
Do not listen to all messages posted on broswer

### ISSUE THREAD

**Issue by juanca** [mswjs/msw#536]
## Describe the bug

MSW reads all posted messages as MSW messages. However, _anything_ can post a message. In particular, the react dev tools posts messages all the time. With MSW installed, MSW will throw uncaught exceptions.

![image](https://user-images.githubusercontent.com/841084/104357552-34228c00-54c2-11eb-9a38-799c00882897.png)

## Environment

- `msw@0.24.4`
- `nodejs: v14.15.1`
- `npm: 6.14.4`

Google Chrome Version 87.0.4280.141 (Official Build) (x86_64)
macOS Big Sur 11.1

## To Reproduce

1. Install React Developer Tools
2. Run test suite (on a browser) with MSW
3. See error in console

## Expected behavior

There shouldn't be any errors.

## Screenshots

Here is a screenshot of the failing line in MSW:

![image](https://user-images.githubusercontent.com/841084/104358016-c0cd4a00-54c2-11eb-9350-3ba1b01f4d0a.png)

And more stack traces (which all seem to be related to react-dev-tools):

![image](https://user-images.githubusercontent.com/841084/104358220-fb36e700-54c2-11eb-9138-ab0ea7de114a.png)

**Comment by kettanaito** [comment]
Hey, @juanca. Thanks for raising this, it's a great point. 

MSW should check if the incoming message is MSW-related before attempting to operate with it.

**Comment by timdeschryver** [comment]
Hi, I can take this one if no one is working on it.
If that's OK, would be enough to verify that we have to client, or would all of our messages have a MSW tag (a property)?

**Comment by kettanaito** [comment]
Absolutely, @timdeschryver! I'd be thankful if you took a look. 
I was thinking to add an integration test where we create another, irrelevant worker posting some messages, and asserting that MSW doesn't react to that. Didn't get to do that yet, but would appreciate it if you took over.

**Comment by timdeschryver** [comment]
I am struggling to write tests for this as I can't reproduce this, neither with the React Devtools enabled.
Do you have a project that you can share as a reproduction @juanca ?

**Comment by kettanaito** [comment]
Can we reproduce it by introducing this kind of worker?

```js
// test/msw-api/extraneous-worker.js
self.addEventListener('activate', (event) => {
  const channel = new MessageChannel()

  // Continuously communicate with the client.
  setInterval(() => {
    event.client.postMessage('dummy-message', [channel.port]
  }, 1000)
})
```

> We should also clean up the established interval once the extraneous worker deactivates. 

```js
// test/msw-api/extraneous-worker.mocks.js
import { setupWorker, rest } from 'msw'

// Perform a basic "setupWorker" configuration. 
const worker = setupWorker(...)
worker.start()

navigator.serviceWorker.register('./extraneous-worker.js')
```

I wonder if our current testing setup will support the registration of another worker. Worth a try.

**Comment by timdeschryver** [comment]
Thanks for the tip @kettanaito , but sadly that didn't work either.
I didn't know this, but you can only have one service worker per origin. 
The snippet you shared, overwrites the mock service worker.

**Comment by kettanaito** [comment]
Ouch. Got it.
I suspect something additional at play, as I’ve used MSW on React projects with DevTools enabled and never encountered this issue.

Can it be an outdated DevTools on either side?

**Comment by marcosvega91** [comment]
I think that to replicate the issue you can simply call `window.postMessage` on a page of puppeteer using `page.evaluate`

```ts
const runtime = await runBrowserWith(path.resolve(__dirname, 'mocks.ts'))

runtime.page.evaluate(() => {
   window.postMessage({
       source: 'external-message',
   });
})
```

**Comment by kettanaito** [comment]
@marcosvega91 a great point. We don't have to have a separate worker, as the issue is when the client posts a message not intended for MSW. Sounds like that should work.

**Comment by timdeschryver** [comment]
I also tried that @marcosvega91 , but the MSW doesn't receive that message either.
At least, I tried that in the browser itself... I'll try that in a test later today

**Comment by timdeschryver** [comment]
I was too curious, the test specs also don't receive that message.

**Comment by kettanaito** [comment]
Not sure if [`window.postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) per se is the right API to post a message to a worker. Per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), its main purpose is a cross-origin communication between the `window` objects. 

We communicate with a worker instance currently using one of these methods:

1. Get a worker reference and call `worker.postMessage()`.
2. Get a `message` event received from the worker, and do `event.ports[0].send()` in response. 

The logic to get a worker instance is described here: 

https://github.com/mswjs/msw/blob/b99be78eede52ebde08c48fc78f773cce3840a6c/src/setupWorker/start/utils/getWorkerInstance.ts#L10

However, taking this into account, the only way this issue may occur is when MSW unexpectedly retrieves another worker's instance and treats it as its own. Since we're getting the worker instance by its registration URL, I don't think this is likely. Unless there's a bug with the `getWorkerInstance` function itself that's causing it.

**Comment by juanca** [comment]
I will commit some time this week to set up an env. 

As for reproducibility, I have a coworker with a similar setup (Chrome, Devtool, MSW) that found the same errors. 

More to come! Feel free to keep this thread active as a nice reminder. :)

**Comment by marcosvega91** [comment]
Just one question about the log that I see in the issue,
What is the function `sayHelloToBackend` ? maybe could help

![image](https://user-images.githubusercontent.com/5365582/104958268-f9dc5180-59cf-11eb-961a-200c89bff826.png)

**Comment by juanca** [comment]
I can't find `sayHelloToBackend` in my recent run of my tests but here is a relevant snippet:

![image](https://user-images.githubusercontent.com/841084/104975360-5418ea80-59af-11eb-97f1-80e622e75a2c.png)

**Comment by juanca** [comment]
Oh, here's the first error's stack trace:

![image](https://user-images.githubusercontent.com/841084/104975563-d2758c80-59af-11eb-96e3-2df692b0b886.png)

**Comment by juanca** [comment]
I got it to reproduce in the examples repo. Here is [the relevant commit.](https://github.com/juanca/examples/commit/97358b200bfec4c0b1b5be269a88461e1d84f341)

```
git clone ...
cd examples
yarn install
cd with-karma
yarn install
yarn test
```

![image](https://user-images.githubusercontent.com/841084/105543711-f508ed80-5cae-11eb-8d14-fac9c8e43a67.png)

**Comment by juanca** [comment]
An observation:

The test does not fail because MSW handles all desired requests successfully. The undesired requests (from other sources) throw an exception but it does not affect the outcome of the test. 

While it is not blocking test development, it is annoying to see a few unhandled exceptions per test. When you have a codebase with 1k+ tests, this can become overwhelming.
