### ISSUE TITLE
event.target gets cleared after handling first promise in Safari (jn storybook?)

### ISSUE THREAD

**Issue by kazdegroot** [mswjs/msw#537]
## Describe the bug
The Promise in respondWith handles actually sending the response in a 'then' handler. At this point the target on the original event seems to be cleared, which makes `const client = await event.target.clients.get(clientId)` fail, which only breaks the mocked response, but shows warnings for all responses (even those that aren't mocked).

Works fine in Brave

## Workaround

Replacing `const client = await event.target.clients.get(clientId)` @ `mockServiceWorker.js:193` with `const client = await self.clients.get(clientId)` seems to fix the issue here, but I'm not familiar enough with service workers to determine if using the 'global' context over the one passed through the event presents its own issues.

## Environment

- `msw: 0.25.0`
- `nodejs: v15.2.0`
- `npm: 7.0.10`
- Browser: `Safari: 14.0.2`

## To Reproduce
1. Add msw to storybook
2. Visit in Safari
3. Get errors because the mocked endpoint fails to load and console warnings for most other network calls

## Expected behavior
Get the correct response from the mocked endpoint and no console warnings.

## Screenshots
<img width="1234" alt="Schermafbeelding 2021-01-13 om 11 39 41" src="https://user-images.githubusercontent.com/92598/104441687-4bca4500-5594-11eb-892c-a526b5fa421f.png">

**Comment by kettanaito** [comment]
Hi, @kazdegroot. Thanks for reporting this.

I believe this has been fixed as a part of #564 and #565. This also looks the same as #558. 

I'm closing this. Please update to `0.26.0` once it's out and follow the instructions in its release notes.

**Comment by kazdegroot** [comment]
Cool, thanks!
