### ISSUE TITLE
Log matched requests in a browser's console

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#55]
Those requests which have matched the request handlers defined in the `composeMocks()` call should be logged into a browser's console.

## Motivation

- Easier and faster for the developer to see if something has been mocked

## Specification

1. Each request matched against the defined mock definition is logged into the console.
1. The log entry of the matched request looks as follows:

```
[MSW] 10:10:02 GET /users
```

3. The log entry is represented by `console.group`, clicking on which reveals the following information:

    3.1. Intercepted request.
    3.2. Request handler used.
    3.3. Resolved mocked response object.

**Comment by hehehai** [comment]
@kettanaito I think it would be nice to have a configuration to turn it on. The mock's print message would be mixed with the application's print message, and while we can do some printing styles, it would be better for the developer to choose whether to turn it on or not. What do you think?

**Comment by kettanaito** [comment]
@hehehai, a good call. It would be good accept such logging preference via an argument. I wonder, where should it be provided? 

I though of providing it to the `start()` function, but it accepts two optional arguments that control Service Worker registration, and may still be useful. Providing them both in order to set the third argument with the logging level feels redundant.

**Comment by kettanaito** [comment]
Since Mock Service Worker is recommended for development only, I see little worry over seeing too many messages. At the least you can always filter the console messages based on type and RegExp to find what you were looking for.

On the other hand, logging matched requests would improve the developer's experience dramatically when working with the library.
