### ISSUE TITLE
getCallFrame does not need to throw + test in other browsers

### ISSUE THREAD

**Issue by Aprillion** [mswjs/msw#562]
## Describe the bug

As discussed in live stream, https://github.com/mswjs/msw/blob/5b232eb181c9b78bc0fb26954b448e5ccd26ed24/src/utils/internal/getCallFrame.ts does not need the Error to be thrown, just `new Error().stack` is enough.

---

The difference between browsers should not an issue after all, but FTR: Chrome and Node, unlike Firefox and Safari, contain the error message on the 1st line of stack (but the fist line in Firefox/Safari will be `getCallFrame` itself, so doing `frames.slice(1)` is safe). In any case, probably best to test in multiple browsers just in case.

Executing `(function a() { console.log(new Error().stack) })()` in Chrome:
```
Error
    at a (<anonymous>:1:29)
    at <anonymous>:1:50
```

in Firefox:
```
a@debugger eval code:1:28
@debugger eval code:1:1
```

**Comment by kettanaito** [comment]
Hey, @Aprillion. Thanks for putting this issue down. 

Please, would you be interested in tackling it? 

You're right, the error message position shouldn't matter, as we `frame.slice(1)` it and then go through each line and find the first one that didn't originate from tne `node_modules/msw/(umd|cjs})` package. What may differ is the format of the stack line—that would be nice to test in different browsers.

Our current setup runs tests in Puppeteer (Chromium). I'm not aware if you can use FireFox with Puppeter, but I expect that you can't. Manual testing in that browser should be enough.

**Comment by Aprillion** [comment]
> Please, would you be interested in tackling it?

I hope I will get to it later today (assuming all tests in a fresh clone on windows will be green)...

**Comment by Aprillion** [comment]
So `getCallFrame` is covered with some unit tests which are green after the change:
```
PASS  src/graphql.test.ts
PASS  src/rest.spec.ts
```

But the unit tests don't call it, only import and it was not covered with any integration tests, so I will try to add a test.

FTR: One of the integration tests was failing on Win even after doing a fresh clone => I will just ignore it:

```
 FAIL  msw-api/setup-server/printHandlers.test.ts
  ● lists all current request handlers

    expect(jest.fn()).toBeCalledWith(...expected)

    Expected: "[rest] GET https://test.mswjs.io/book/:bookId
      Declaration: C:\\Users\\Peter\\git\\msw\\test\\msw-api\\setup-server\\printHandlers.test.ts:13:8   
    "
    Received
           1: "[rest] GET https://test.mswjs.io/book/:bookId
      Declaration: C:\\Users\\Peter\\git\\msw\\lib\\umd\\index.js:3732:35
    "
           2: "[graphql] query GetUser (origin: *)
      Declaration: C:\\Users\\Peter\\git\\msw\\lib\\umd\\index.js:3732:35
    "
           3: "[graphql] mutation UpdatePost (origin: *)
      Declaration: C:\\Users\\Peter\\git\\msw\\lib\\umd\\index.js:3732:35
    "
```

*Update*: Support for Node in Windows added in the PR, making the existing integration tests green.

**Comment by Aprillion** [comment]
Oh wait, `printHandlers.test.ts` is actually the test that executes `getCallFrame`, watch mode just didn't detect it. Argh, so not creating a PR yet :(
