### ISSUE TITLE
request: include a CONTRIBUTING.md file in the github repo

### ISSUE THREAD

**Issue by adeelibr** [mswjs/msw#571]
**Is your feature request related to a problem? Please describe.**

Having a CONTRIBUTING.md file can help people trying to contribute to this great open source project. It's a small guide setup that tell how they can fork & make PR & also have information how to setup up local environment, including what are the minimum set of steps they need to ensure before they make a PR. to ensure it merges smoothly.

**Describe the solution you'd like**

A great example is something like
- https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md
- https://github.com/testing-library/react-testing-library/blob/master/CONTRIBUTING.md

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by kettanaito** [comment]
Hi, @adeelibr. Thanks for reaching out.

We do have the [Contributing guidelines](https://github.com/mswjs/msw/blob/master/.github/CONTRIBUTING.md) in the repo. They are located in the `.github/CONTRIBUTING.md` file.
