### ISSUE TITLE
Infinite loading when refreshing the page in NextJS

### ISSUE THREAD

**Issue by NguyenTrungMax** [mswjs/msw#578]
## Describe the bug
Hello @kettanaito 
I add msw to nextjs with server side rendering, which make hot reloading in Nextjs not work.

I tested and saw that at my local, when editting code then waiting it display on screen, but not. I have to Ctrl + f5.
If it's lucky it will show up, otherwise the machine will hang with the words '**waiting for existing socket**' .

But when I close tab and open new tab, it's ok, But that's really inconvenient, if I comment require('../mocks') in _app.js file. It's oke

## Environment

- `msw: 0.26.1`
- `nodejs: 12.18.2`
- `npm: 6.14.5`

> Version chrome: 88.0.4324.104

## To Reproduce
Link repo: [https://codesandbox.io/s/serverless-fog-mex0z?file=/package.json:352-358](url)

## Screenshots
![image](https://user-images.githubusercontent.com/34021640/106700637-d3492800-6617-11eb-8b41-58e6197b8998.png)

**Comment by kettanaito** [comment]
Hey, @NguyenTrungMax. Thanks for reporting this. I can verify that's indeed how the latest NextJS example works.

Unfortunately, per NextJS collaborator @rafaelalmeidatk, the only way to trigger a fast refresh for server-side computations (i.e. `getServerSideProps`) is to edit something explicitly imported/used in those methods. As MSW request interception is established for the entire process and not individual methods to guarantee uniformity, changing the handlers doesn't result in the server-side methods being re-evaluated, and so you don't see the updates. Refreshing the page works because you let the server-side methods execute again with the updated handlers (updates are still in place, they just don't trigger a hot update of the server-side methods). 

There isn't much we can do with this on the library's side. 

> otherwise the machine will hang with the words 'waiting for existing socket' .

This sounds like an interesting issue I haven't encountered. Does this happen on the raw NextJS usage example? Please provide the reproduction steps for this and any amount of details you deem necessary. Thanks.

**Comment by NguyenTrungMax** [comment]
Hi, @kettanaito .
Thanks for taking care of my problem.

That is the steps I took to recreate it.
1 Download and install the example with-msw project
2 Add a server side rendering configuration like repo link above.
3 Run and write the function that prints to console.log ('content')
4 Write a certain function and wait for 10-20 seconds or import anything like "Import Link from 'next / link"
5 Next, you will not see it refreshed in the browser, because there is no 'content' printed on the screen. If you f5 you will see that the tab is frozen even though the project has compiled successfully

**Comment by jedfoster** [comment]
I don't think this is fully fixed. I'm seeing infinite refresh behavior in my own next.js app, same as I was seeing in the OP's sandbox. My app uses msw v0.28.1, so I forked the OP's sandbox and updated to the latest msw, v0.28.2, and still see this behavior. 

## Environment
msw: 0.28.2
nodejs: 12.18.2
npm: 6.14.6

Chrome: 89.0.4389.114

## To Reproduce

Code Sandbox: https://codesandbox.io/s/busy-water-u8u1d
Standalone web view: https://u8u1d.sse.codesandbox.io/

Open the Chrome dev tools and refresh the result web view pane and it may go into an infinite refresh loop. You will definitely see the loop if you open the standalone web view in a new window.

This is how I have my dev tools configured: 

<img width="707" alt="Screen Shot 2021-04-22 at 15 39 01" src="https://user-images.githubusercontent.com/79984/115793413-f1096c00-a380-11eb-86b1-c7708725f2f4.png">

---

It's entirely possible I'm simply doing service workers wrong, but if so, please provide some documentation on how the dev tools should be configured for working with msw.

Happy to open a new ticket if necessary.

**Comment by ronkorving** [comment]
I also see an infinite "refresh" loop, on a Vue application with HMR. One of the problems is that this infinite refreshing is making it really hard to debug and find out what's going on, or I would provide more data.

**Comment by ronen-e** [comment]
I had the same effect when using HMR in `development` environment.
The problem resolved after I unchecked "**Update on reload**".

<img width="485" alt="Screen Shot 2021-07-27 at 6 41 05 PM" src="https://user-images.githubusercontent.com/10486251/127184357-44048fce-023b-4095-a761-34010e45d309.png">

Enabling "**Update on reload**" afterwards did not cause the problem to repeat itself
<img width="461" alt="Screen Shot 2021-07-27 at 6 43 54 PM" src="https://user-images.githubusercontent.com/10486251/127184821-3f0eede3-d9cb-4f7c-bc93-6e0962bee88c.png">


**Note**: you also need to uncheck "Bypass for network" for the service worker to mock responses when devtools panel is open

**Comment by kettanaito** [comment]
I believe that the original issue has been fixed, and the similar behavior you're experiencing is caused by something else. Issues like #788, #785, and #834 can be related. One of the contributors has already prepared a fix that _may_ resolve this.

**Comment by hariombalhara** [comment]
Had the same issue. Following worked for me to stop infinite reload
1. Ensure there is no other tab open with the same domain. In my case, it was there, closed it.
2. Unregister the ServiceWorker(Applications -> ServiceWorker in Chrome DevTools) and then refresh the page

**Comment by squalvj** [comment]
lmao i got this infinite loop while running in the server side using Next.JS with graphql, i solved it by removing unecessary data that outside the requested query, and it solve my infinite loop.

**Comment by theprojectsomething** [comment]
Can confirm the issue as described remains ... ~~definitely appears linked to multiple tabs. Steps from @hariombalhara have resolved for the short term.~~

**Comment by crisfcodes** [comment]
I'm having this issue, I've tried unregistering the worker and refreshing the page with no luck, the page becomes unresponsive so it's quite difficult to debug.

@kettanaito would be great if you could give us some insights about how to debug the problem
