### ISSUE TITLE
Browser refresh and hot-reloads cause error "TypeError: Cannot read property 'postMessage' of undefined"

### ISSUE THREAD

**Issue by AriPerkkio** [mswjs/msw#580]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.26.1   |
| browser | Chrome 87    |
| OS      | Win10     |

## Request handlers

[Handler from MSW examples](https://github.com/mswjs/examples/blob/master/examples/rest-react/src/mocks/handlers.js) with additional delay `ctx.delay(1000)`.

```js
import { rest } from "msw";

export const handlers = [
    rest.post("/login", (req, res, ctx) => {
        const { username } = req.body;

        return res(
            ctx.json({
                id: "f79e82e8-c34a-4dc7-a49e-9fadc0979fda",
                username,
                firstName: "John",
                lastName: "Maverick",
            }),
            ctx.delay(1000), // Increase if unable to reproduce the issue
        );
    }),
];
```

## Actual request

https://github.com/mswjs/examples/blob/83603a4619abb09447322d88bb88a7e4d6a2c91c/examples/rest-react/src/LoginForm.js#L18-L36

```js
fetch("/login", {
    method: "POST",
    body: JSON.stringify({ username })
});
```

## Current behavior

Seen in browser console. 

```
mockServiceWorker.js:256 Uncaught (in promise) TypeError: Cannot read property 'postMessage' of undefined
    at mockServiceWorker.js:256
    at new Promise (<anonymous>)
    at sendToClient (mockServiceWorker.js:245)
    at mockServiceWorker.js:206
```

https://github.com/mswjs/msw/blob/1769a1e2647a35ace2485837cd7622b8a5e5d545/src/mockServiceWorker.js#L244-L258

## Expected behavior

No errors should be visible. Maybe MSW should expect `client` to be falsy in some edge cases.

## Repro:

This issue can be reproduced by navigating back in browser before request resolves. In my real use case this is triggered by hot-reloads of `webpack-dev-server` and/or `react-refresh`. I think these might also come from full page reloads. 

1. Clone https://github.com/mswjs/examples
2. Prepare project as instructed (+ `npx msw init public` for latest mockServiceWorker)
3. Add delay to handler as shown above
4. `npm run start` in rest-react example
5. Once app has started change URL to `http://localhost:3001/?temp`
6. Type user to text input. Wait for request to start and press browsers back button before request resolves
7. Error is shown in browser JS console

Edit: Also reproduced without changing URL:
1-4: as above
5. Type user to text input. Wait for request to start and refresh page.
6. Error is shown in browser JS console

**Comment by kettanaito** [comment]
Hey, @AriPerkkio. Thank you for reporting this.

Based on the reproduction steps, it looks that the `client` becomes `undefined` as the execution context is destroyed (navigation back in the browser history). To my best knowledge, each client-worker session generates a unique client instance, so it's not per application but per connection. 

Apart from handling a potentially undefined `client`, perhaps we could ensure that any pending requests are aborted once the navigation occurs?

**Comment by timdeschryver** [comment]
I can take this one, I like the idea to cancel pending requests. 
I tried to implement this in #506, but I wasn't able to. I'm confident I can do it now, now that I'm more familiar with MSW internals 😅.

**Comment by kettanaito** [comment]
@timdeschryver, that'd be awesome! Let me know if you need any help.

**Comment by timdeschryver** [comment]
I verified that #589 resolves this issue.
