### ISSUE TITLE
Issues with CRA PUBLIC_URL environment variable specified

### ISSUE THREAD

**Issue by cjones26** [mswjs/msw#582]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.26.1   |
| browser | Chrome 88 / Firefox 85     |
| OS      |  Linux / Windows    |

## Request handlers

I pulled the request handlers directly from both the [example code](https://github.com/mswjs/examples/blob/master/examples/rest-react/src/mocks/handlers.js) and the [main msw GitHub page](https://github.com/mswjs/msw#usage-example).

```js
import { setupWorker, rest } from 'msw';

// Start the mocking conditionally.
if (process.env.NODE_ENV === 'development') {
  const worker = setupWorker(
    rest.post('/login', (req, res, ctx) => {
      const { username } = req.body;

      return res(
        ctx.json({
          id: 'f79e82e8-c34a-4dc7-a49e-9fadc0979fda',
          username,
          firstName: 'John',
          lastName: 'Maverick',
        })
      );
    }),
    rest.get('https://github.com/octocat', (req, res, ctx) => {
      return res(
        ctx.delay(1500),
        ctx.status(202, 'Mocked status'),
        ctx.json({
          message: 'Mocked response JSON body',
        })
      );
    })
  );
  worker.start({
    serviceWorker: {
      url: `${process.env.PUBLIC_URL}/mockServiceWorker.js`,
    },
  });

  window.worker = worker;
}
```

## Actual request

The following were inserted within the [examples's `LoginForm.js`](https://github.com/mswjs/examples/blob/master/examples/rest-react/src/LoginForm.js):

```js
// In order to test the first handler
const handleFormSubmit = useCallback(
  (event) => {
    // Prevent the default behavior, as we don't want
    // for our page to reload upon submit.
    event.preventDefault();

    // Perform a POST /login request and send the username
    fetch('/login', {
      method: 'POST',
      body: JSON.stringify({
        username,
      }),
    })
      .then((res) => res.json())
      // Update the state with the received response
      .then(setUserData);
  },
  [username]
);

// In order to test the second handler
  useEffect(() => {
    fetch('https://github.com/octocat')
      .then((res) => res.json())
      .then((value) => console.log('value: ', value));
  }, []);
```

## Current behavior

When we have the PUBLIC_URL environment variable set within `.env` like so:

```
PUBLIC_URL=/relative-test-path
```

Both handlers are shown as registered properly:

![Both handlers properly registered](https://user-images.githubusercontent.com/465272/107123172-17cc0200-686a-11eb-8242-03d4c2800532.png)

When attempting to test the first (POST) handler, which is pulled directly from the [example](https://github.com/mswjs/examples/tree/master/examples/rest-react), we see that the the handler is not respected (even if we change the URL explicitly to "http://localhost:3001/login" or "http://localhost:3001/relative-test-path/login"), as CRA takes over and redirects:

![First handler](https://user-images.githubusercontent.com/465272/107123377-37aff580-686b-11eb-9830-31eb3bee04f2.png)

When attempting to test the second handlers (which is fired on page load, a simple GET request as shown in the main msw usage example), we can see the handler is not respected as we receive a CORS error:

![Second handler](https://user-images.githubusercontent.com/465272/107123462-b86ef180-686b-11eb-9394-501aa071721f.png)

![Network tools CORS Error](https://user-images.githubusercontent.com/465272/107123477-cf154880-686b-11eb-9275-d88329a726b4.png)

## Expected behavior

As soon as we remove the `PUBLIC_URL` from `.env` and restart CRA, everything works as expected--both handlers work properly:

![Working properly](https://user-images.githubusercontent.com/465272/107123596-611d5100-686c-11eb-87e0-75102eac7de4.png)

## Screenshots

See above.

**Comment by Justinohallo** [comment]
What is the purpose of your PUBLIC_URL ? If it is for production, put it into an .env.production file at the root of your directory and remove it from the .env file. https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env

I had the exact same issue, but we only used our PUBLIC_URL for production so it may not fit your use case. 

Alternatively, you can try something like this if you want to move your PUBLIC_URL into your package.json : https://mswjs.io/docs/getting-started/integrate/browser#using-homepage-property-in-packagejson

However, I was not able to get the package.json approach to work.

**Comment by kettanaito** [comment]
Hi, @cjones26. Thanks for reporting this.

Please, could you follow the [Debugging uncaught requests](https://mswjs.io/docs/recipes/debugging-uncaught-requests) guidelines? They may reveal some additional information about the issue. Specifically, I'm curious what the `onUnhandledRequest` option will tell you. Thanks.

**Comment by cjones26** [comment]
@kettanaito -- I forgot to add that I had already tried this (with both `warn` and `error` -- neither provide any sort of output in the console), here's what I did:

```
  worker.start({
    serviceWorker: {
      url: `${process.env.PUBLIC_URL}/mockServiceWorker.js`,
    },
    onUnhandledRequest: 'error',
  });
```

And here's the network & console tabs after firing off both requests (on page load & submit button):

![Network tab](https://user-images.githubusercontent.com/465272/107125214-857e2b00-6876-11eb-9c4c-e41a28a9359b.png)

![Console tab](https://user-images.githubusercontent.com/465272/107125254-ae062500-6876-11eb-813b-1e448524579f.png)

@Justinohallo -- excellent suggestion -- it did in fact work 👍🏻 , though I'd like to see why this issue is occurring in the first place!

**Comment by kettanaito** [comment]
I think the cause for the issue is the scope of the worker (`url: ${process.env.PUBLIC_URL}/mockServiceWorker.js`).

**Comment by cjones26** [comment]
Got it.  So if I remove that string interpolation (and completely remove all service workers), when I attempt to load the page, the mws service worker cannot be found, which is the reason I added it in the first place:

![Not found](https://user-images.githubusercontent.com/465272/107125630-181fc980-6879-11eb-8483-d59d05a0e76b.png)

Any reason why you would suspect that's causing the issue?

**Comment by Justinohallo** [comment]
@kettanaito I think the suggestion above would be a decent addition to the MSW docs. I found it to be much easier given that my setup only uses the homepage / PUBLIC_URL in production.

**Comment by kettanaito** [comment]
@cjones26 you can clearly see that the `/octocat` request fails due to the "CORS error". The request you make is blocked by the CORS policy of the browser. See #592 for more details and resolution suggestions. There wasn't any issue with registering the worker in your case, it seems. 

@Justinohallo, we'd love to add it to the docs. Please, what exact suggestion has solved the issue for you?
