### ISSUE TITLE
Subsequent Requests From Same Endpoint

### ISSUE THREAD

**Issue by Justinohallo** [mswjs/msw#586]
**Is your feature request related to a problem? Please describe.**
I have an app that pulls financial data from an API. My user flow allows users to buy and sell assets. Right now, I have 1 mocked endpoint and response for a specific stock (use Amazon as an example). I would like to be able to test the rest of my application under the scenario that the user has bought AMZN at $3250, and then 5 minutes later sells at $3240. The issue is that my mocked data only includes the initial $3250 and I cannot figure out how to implement the $3240 on the second request. 

**Describe the solution you'd like**

I would like to provide an array of responses to a specific endpoint so that when I am testing the items are called in order. The exact same endpoint needs to be used in both scenarios. 

- 1 Endpoint
- Multiple Responses based on a sequence of requests

**Describe alternatives you've considered**

I will simply use the $3250 mock price for now. I am not sure how else I could handle this without changing my codebase.

**Comment by kettanaito** [comment]
Hey, @Justinohallo. 

You can achieve what you've described with the [`res.once()` API](https://mswjs.io/docs/api/response/once). When you respond using that API your mocked response will only be used once. The handler that produces the one-time response will be marked as skipped for the rest of the execution, allowing subsequent requests to fall through and be caught be other handlers. 

Here's how you can set up the API communication scenario you've described:

```js
import { setupWorker, rest } from 'msw'

setupWorker(
  rest.get('/stock/amazon', (req, res, ctx) => {
    // Respond with the 3250 price upon the first request.
    return res.once(ctx.json({ stockPrice: 3250 })
  }),

  // Notice an identical request handler.
  rest.get('/stock/amazon', (req, res, ctx) => {
    // For all the consequent requests respond with the 3240 price.
    return res(ctx.json({ stockPrice: 3240 })
  }),
)
```

MSW looks up a relevant request handler from top to bottom. Leverage that and the `res.once()` API to handle complex request sequences that your app may be handling. 

If you find this setup too verbose, consider abstracting the responses into helper functions and reusing those. You may also want to introduce a state in your handlers, for example by creating a user object, updating it depending on the request, and responding with conditional data based on the current user's state on runtime.
