### ISSUE TITLE
Fetch does not receive the response object

### ISSUE THREAD

**Issue by slim-hmidi** [mswjs/msw#591]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.26.2 |
| node | 14.15.4 |
| OS   | windows 10|

## Request handlers

```js
// Example of declaration. Provide your code here.
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const server = setupServer(
  rest.get('/functions', () => {
     return res(
      ctx.status(200),
      ctx.set('Content-Type', 'application/json'),
      ctx.json([{id: 1, name: 'function1'}, {id: 2, name: 'function2'}]),
    );
})
)

server.listen()
```

## Actual request

```js
describe('My function', () => {
  it('should call successfully the function', async () => {
    try {
      const functionList= await fetch('/functions'); // edited
      console.log('functionList', functionList);
    } catch (err) {
      console.error(err);
    }
  });
});
```

## Current behavior

the fetch does not return any response neither an error.

## Expected behavior

Return the mocked data or throw an exception if there is an error.

**Comment by kettanaito** [comment]
Hey, @slim-hmidi. Thanks for reporting this.

Please, what library do you use for `fetch`? Native `window.fetch` has no `.get` method, so it must be some library you are using. In case you were intending to use native `fetch`, consider rewriting its call signature:

```js
// This translated to a "GET /functions" request. 
const functionList = await fetch('/functions')
```

Also, it would be useful to know in what environment does your test run (browser/Node)? Tests in Node have no `fetch` exposed unless you add a polyfill.

**Comment by slim-hmidi** [comment]
@kettanaito thanks for your answer, actually I'm using react-create-app and I'm create tests for the components that calling some apis using native fetch.
my client wrapper:
```
type Headers = Record<string, string>;

interface Config {
  method: string;
  headers: Headers;
  body?: BodyInit | null;
}

interface ClientObject {
  method?: string;
  customConfig?: {
    headers?: Headers;
  };
  body?: unknown;
}

export const client = async <T>(
  url: string,
  clientObj: ClientObject,
): Promise<T> => {
  const headers: Headers = {
    'Content-Type': 'application/json',
  };

  const config: Config = {
    method: clientObj.body ? 'POST' : 'GET',
    ...clientObj.customConfig,
    headers: {
      ...headers,
      ...(clientObj.customConfig ? clientObj.customConfig.headers : {}),
    },
  };
  if (clientObj.body) {
    config.body = JSON.stringify(clientObj.body);
  }
  let data;
  try {
    const response = await window.fetch(url, config);
    data = await response.json();
    if (response.ok) {
      return data;
    }
    throw new Error(response.statusText);
  } catch (err) {
    return Promise.reject(err.message ? err.message : data);
  }
};

client.get = <T>(url: string, clientObj: ClientObject = {}) => {
  return client<T>(url, clientObj);
};
```

**Comment by kettanaito** [comment]
I highly suggest you following the [Debugging uncaught requests](https://mswjs.io/docs/recipes/debugging-uncaught-requests) guidelines. If you wish one of the maintainers to look into the issue, please create a minimal reproduction repository that illustrates your issue. Thanks. 

Specifically, try this as the first debugging step:

```js
const server = setupServer(...)

server.listen({
  onUnhandledRequest: 'error' // <-- add this option 
})
```

It's most likely that you are targeting an incomplete/wrong request URL in your request handler. That causes the request to never be intercepted and you don't get the response back.
