### ISSUE TITLE
Not responding with correct status code

### ISSUE THREAD

**Issue by flexwie** [mswjs/msw#595]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.26.2   |
| node | 14.15.4     |
| OS   | Windows 10     |

## Request handlers

```js
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const handlers = [
  rest.patch("/api/Resources/:id", (req, res, ctx) => {
    if (!req.headers.has("Authorization")) {
      return res(ctx.status(401));
    }

    let element = serverData.findIndex((e) => e.id === req.params.id);

    if (element === -1) {
      // this code block is entered
      return res(ctx.status(404), ctx.text(""));
    } else {
      return res(ctx.status(204), ctx.text(""));
    }
  }),
  rest.get("/api/Resources", (req, res, ctx) => {
    if (!req.headers.has("Authorization")) {
      return res(ctx.status(401));
    }

    return res(
      ctx.status(200),
      ctx.json({
        "@odata/stuff": "string",
        values: serverData,
      })
    );
  }),
];

const server = setupServer(...handlers);
```

## Actual request

```js
fetch(`${baseUrl}/${data.id}`, {
      method: "PATCH",
      headers: authHeaderWithContentType,
      body: JSON.stringify(data),
    }).then(handleResponse);

const handleResponse = (response: Response): Promise<any> => {
  console.log(response.status);
  if (response.ok) {
    if (isJson(response)) {
      return response.json();
    } else {
      return response.text();
    }
  } else {
    console.log(response.statusText);
    const error = new ResponseError(response.statusText);
    error.response = response;
    throw error;
  }
};
```

## Current behavior

It returns 200 as a status code. This changes when I change the status code of the second route. The code block that is supposed to return a 404 status is entered but doesn't return as it seems. Am I missing something?

## Expected behavior

It should return a 404 status code causing the fetch request to throw an error.

**Comment by kettanaito** [comment]
Hey, @flexwie. Thanks for raising this. 

Keep in mind that 4xx/5xx responses do _not_ trigger the `catch` block of `fetch`, neither do they throw an exception. They resolve the same as a successful response:

> _Evaluating the success of responses is particularly important when using fetch because bad responses (like 404s) still resolve._
> —[Working with Fetch API, Google](https://developers.google.com/web/ilt/pwa/working-with-the-fetch-api)

Based on your code, the `element` doesn't exist and the handler falls into the 404 clause, correct? 

Here are some things to look out for:

1. Does your app makes more than 1 `PATCH /api/Resources/:id` request?
2. Try returning some text in that 404 case. Do you still see the response body text? Is the status code still wrong?

Please create a reproduction repository and share it here if you want for one of the maintainers to look into the issue. Thanks.

**Comment by flexwie** [comment]
Hey @kettanaito,
we added that handleResponse function to throw an error if the status code is >2xx.

`element` does exists and is -1 (aka not found in the array), what is what I am describing with my test case:
```typescript
it("should throw error on unknown id", async () => {
    const { update } = useResourceService(mockState as any);

    const response = async () =>
      await update({
        id: "123-456-78",
        no: "123",
        name: "New Name",
      });

    expect(response).toThrowError();
  });
```
When I try to return some text along the 404 status, the fetch call receives an undefined body and still a 200 status code.

I will try reproduce this issue in a repository and come back to you!
Thanks for you assistance so far!

**Comment by flexwie** [comment]
I recreated the error in this repository:

https://github.com/flexwie/msw_error

Running `npm test` will result in a failed test run. I have uncommented another test, that is using the samen handler succesfully for better readability.

**Comment by marcosvega91** [comment]
Hi @flexwie,

the `update` function is async so to await that the HTTP request has thrown an error you should do as follows

`await expect(response).rejects.toThrow("Not Found")`

Let me know if this will solve your problem 😄 . The status code that you see in your log is the GET request.

**Comment by kettanaito** [comment]
Shoot, you're fast, @marcosvega91! 

Yes, Marcos is right: if you are testing an async function to reject, you must use the `.rejects()` chaining operation in Jest:

```js
expect(response).rejects.toThrowError(ResponseError)
```

> Note that `await` isn't necessary when using `.rejects()`. 

Once you've changed that, your test starts passing.

One thing, you'd probably want to make your assertion more strict so it doesn't pass on _any_ error but only when the intended error happens:

```js
import { ResponseError } from './serviceHelpers'

expect(response).rejects.toThrowError(ResponseError)
```

**Comment by flexwie** [comment]
Hey @marcosvega91 and @kettanaito, 
thanks for your suggestions!

They are not resolving this issue for me (can't use `rejects()` because the promise is already handled in the service helper), but as this seems to be a problem with my tests rather than with msw I will try to figure out how I can structure them differently and eventually come back to this with a solution if somebody else is having a similar issue in the future!

**Comment by flexwie** [comment]
Wrapping the API call in a separate promise did the trick for me here:

```typescript
const { update } = useResourceService(mockState as any);

const response = new Promise<void>(async (resolve, reject) => {
  try {
    await update({
      id: "123-456-78",
      no: "123",
      name: "New Name",
    });

    resolve();
  } catch (error) {
    reject(error);
  }
});

expect(response).rejects.toThrowError();
```

Not really good-looking but it works!
Thanks everybody for your help!

**Comment by kettanaito** [comment]
> can't use rejects() because the promise is already handled in the service helper

Not sure why is that, since only changing the assertion line makes the test correct and passing:

```diff
-expect(response).toThrowError()
+expect(response).rejects.toThrowError()
```

You don't have to edit your logic to achieve that, that's just the right way to assert rejections of asynchronous functions. In your case the async function is `response`, nothing else. It doesn't matter how promises are handled in the underlying functions (`update`), the _wrapper_ is asynchronous so it must be awaited.
