### ISSUE TITLE
Request handler not matched when URL query params are used

### ISSUE THREAD

**Issue by Bloodyaugust** [mswjs/msw#601]
## Describe the bug
With the following request handler: `rest.get('/user', ...)`

And the following request: `fetch('/user?id=123')`

No request handler is matched. The Path Matching REPL tool (which says it "ignores query parameters and hashes") seems to back up this result. Here's a test there: https://mswjs.io/repl/?path=%2Fuser&url=%2Fuser%3Fid%3D123

In addition, the Query Parameters example page seems to think this should work (and it does not). See: https://mswjs.io/docs/recipes/query-parameters#examples

## Environment

- `msw: 0.26.0`
- `nodejs: 12.19.0`
- `npm: 6.14.8`
Note: I imagine it is not solely this set of versions that are broken, as the REPL example site is also broken.

> Please also provide your browser version.
- `chrome: Version 88.0.4324.150 (Official Build) (x86_64)`
- `jsdom: 16.4.0`

## To Reproduce
1. Try the Path Matching REPL here: https://mswjs.io/repl/?path=%2Fuser&url=%2Fuser%3Fid%3D123
2. Write a simple, `get` and no path param handler
3. Make a request against it with a query parameter, like `/user?id=123` and observe failure to mock

## Expected behavior
The handler should be seen as a match regardless of the presence of URL query params.

**Comment by Bloodyaugust** [comment]
This ended up being a misconfiguration of the server on my end! I do believe the REPL tool is still busted though. I can create a new issue for that, if this is the right place for it.

**Comment by kettanaito** [comment]
Glad you've resolved this, @Bloodyaugust. Please, if you find an issue with the REPL, report it in the [website repository](https://github.com/mswjs/mswjs.io) so we could look into it. Thanks.
