### ISSUE TITLE
rfc: update `start()` API to resolve with registration or reject

### ISSUE THREAD

**Issue by cdaringe** [mswjs/msw#603]
## Environment

n/a

## Request handlers

...any handlers

```js
worker.start()
```

## Actual request

n/a

## Current behavior

`worker.start()` returns `null` if the worker does not register.

## Expected behavior

if the worker does not start, i expect a rejection with a failure message.

without it, i regularly get silent failures, or handle the failure poorly by throwing a generic, non-indicative error message.

## Screenshots

n/a

**Comment by kettanaito** [comment]
Hey, @cdaringe. Thanks for the suggestion, I think it's a great one.

Please, would you be interested in shipping a pull request with these changes? Our team will support you throughout the process and would be extremely thankful for your involvement.
