### ISSUE TITLE
GraphQL File Upload is not intercepted in NodeJS

### ISSUE THREAD

**Issue by lynxtaa** [mswjs/msw#611]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.26.2   |
| node |  15.9.0    |
| OS   |  Ubuntu   |

## Request handlers

```js
/**
 * @jest-environment node
 */

import { createReadStream } from 'fs'

import FormData from 'form-data'
import { graphql } from 'msw'
import { setupServer } from 'msw/node'
import fetch from 'node-fetch'

const server = setupServer()

server.listen({ onUnhandledRequest: 'warn' })

it('file upload', async () => {
  const query = `
    mutation UploadFile($file: Upload!) {
      uploadFile(file: $file)
    }
  `

  server.use(
    graphql.mutation('UploadFile', (req, res, ctx) =>
      res(ctx.data({ uploadFile: true })),
    ),
  )

  const form = new FormData()

  form.append('operations', JSON.stringify({ query, variables: { file: null } }))
  form.append('map', JSON.stringify({ '0': ['variables.file'] }))
  form.append('0', createReadStream(__filename))

  const response = await fetch('http://localhost:1234/api/graphql', {
     method: 'POST',
     body: form,
  })
})
```

## Current behavior

```
 [MSW] Warning: captured a request without a matching request handler:
    
      • POST http://localhost:1234/api/graphql
```

## Expected behavior

Expected GraphQL File Upload request to be intercepted. What am I doing wrong?

P.S. Thanks for this awesome library!

**Comment by kettanaito** [comment]
Hey, @lynxtaa. Thanks for reporting this. 

I'm not experienced with GraphQL uploads, but I'll try to help. Can you try sending a JSON request body instead?

```js
const response = await fetch('http://localhost:1234/api/graphql', {
  method: 'POST',
  headers: {
    'content-type': 'application/json'
  },
  body: JSON.stringify({
    query,
    variables: {
      file: null,
    },
    map: {
      0: ['variables.file']
    }
    fileContents: [createReadStream(__filename)]
  }),
})
```

I'm not sure if sending the file's content as a readable stream works. In case the suggestion above doesn't resolve the issue, please try reading the file's content in its entirety first, and then send the text content in `fileContents`. 

## Insights

Since you're getting the following warning

```
[MSW] Warning: captured a request without a matching request handler:
```

it means that MSW couldn't find any request handlers for the request that happened. Since your query definition looks good, I suspect that it's the parsing stage that fails in your case:

https://github.com/mswjs/msw/blob/a41665157111d5ddc194f82cfd377597aece2049/src/handlers/GraphQLHandler.ts#L125-L129

GraphQL request handlers will attempt to parse each suitable request and in case of a multi-part payload will normalize the variables. Here's how we parse such requests:

https://github.com/mswjs/msw/blob/a41665157111d5ddc194f82cfd377597aece2049/src/utils/internal/parseGraphQLRequest.ts#L103-L131

**Comment by lynxtaa** [comment]
@kettanaito I've expected graphql upload to work since https://github.com/mswjs/msw/pull/543 is merged. In a real scenario I can't send a JSON since I'm using external library for sending graphql requests which uses node-fetch and form-data.

Thanks for suggestions, I'll try more digging and maybe send a PR

**Comment by kettanaito** [comment]
I see. I still think MSW should support that. If you're comfortable with that, try debugging the `parseGraphQLRequest` function, specifically what `parsedOperations` it produces and what the `parseQuery` function returns. It does look like a parsing issue, but not a syntactical one as those would surface in your test.

**Comment by kettanaito** [comment]
@lynxtaa, I think my suggestion above is not correct. I've overlooked that we have a custom abstraction over multi-part GraphQL requests:

https://github.com/mswjs/msw/blob/33a65840171c6587fca14436eebc6011a5e7cec0/test/graphql-api/utils/executeGraphQLQuery.ts#L69-L82

In the end, using a `FormData` instance is the correct way to go, so I think your request example is ok.

I'm afraid this is related to how `FormData` works in NodeJS (#599).

**Comment by lynxtaa** [comment]
I've been experimenting with different FormData polyfills. Here are my observations:

## @jest-environment node
```ts
import { readFileSync } from 'fs'

import FormData from 'form-data'
import { graphql, rest } from 'msw'
import { setupServer } from 'msw/node'
import fetch from 'node-fetch'

const server = setupServer()

beforeAll(() => {
	server.listen({ onUnhandledRequest: 'warn' })
})

beforeEach(() => {
	server.resetHandlers()
})

afterAll(() => {
	server.close()
})

const query = `
	mutation UploadFile($file: Upload!) {
		uploadFile(file: $file)
	}
`

// Doesn't work. Prints:
// [MSW] Warning: captured a request without a matching request handler:
// • POST http://localhost:1234/api/graphql
it('GRAPHQL file upload with node-fetch, form-data', async () => {
	server.use(
		graphql.mutation('UploadFile', (req, res, ctx) => {
			console.log(req.body)
			return res(ctx.data({ uploadFile: true }))
		}),
	)

	const form = new FormData()

	form.append('operations', JSON.stringify({ query, variables: { file: null } }))
	form.append('map', JSON.stringify({ '0': ['variables.file'] }))
	form.append('0', readFileSync(__filename))

	await fetch('http://localhost:1234/api/graphql', { method: 'POST', body: form })
})

// Works but req.body is a string
it('REST with node-fetch, form-data', async () => {
	server.use(
		rest.post('http://localhost:1234/api/graphql', (req, res, ctx) => {
			console.log(req.body) // ----------------------------638935769006777650385780  Content-Disposition: form-data; name="operations" ...
			return res(ctx.json({ data: { uploadFile: true } }))
		}),
	)

	const form = new FormData()

	form.append('operations', JSON.stringify({ query, variables: { file: null } }))
	form.append('map', JSON.stringify({ '0': ['variables.file'] }))
	form.append('0', readFileSync(__filename))

	const response = await fetch('http://localhost:1234/api/graphql', {
		method: 'POST',
		body: form,
	})
	expect(response.ok).toBe(true)
})
```

## @jest-environment jsdom

```ts
import 'whatwg-fetch'
import { graphql, rest } from 'msw'
import { setupServer } from 'msw/node'

const server = setupServer()

beforeAll(() => {
	server.listen({ onUnhandledRequest: 'warn' })
})

beforeEach(() => {
	server.resetHandlers()
})

afterAll(() => {
	server.close()
})

const query = `
	mutation UploadFile($file: Upload!) {
		uploadFile(file: $file)
	}
`

// Works OK but prints:
// [MSW] Warning: captured a request without a matching request handler
// • POST http://localhost/api/graphql
it('GRAPHQL file upload with whatwg-fetch and JSDOM', async () => {
	server.use(
		graphql.mutation('UploadFile', (req, res, ctx) => {
			console.log(req.variables) //  { file: File {} }
			return res(ctx.data({ uploadFile: true }))
		}),
	)

	const form = new FormData()

	form.append('operations', JSON.stringify({ query, variables: { file: null } }))
	form.append('map', JSON.stringify({ '0': ['variables.file'] }))
	form.append('0', new File([''], 'image.png'))

	await fetch('/api/graphql', { method: 'POST', body: form })
})

// Works OK
it('REST file upload with whatwg-fetch and JSDOM', async () => {
	server.use(
		rest.post('/api/graphql', (req, res, ctx) => {
			console.log(req.body) // FormData {}
			return res(ctx.json({ data: { uploadFile: true } }))
		}),
	)

	const form = new FormData()

	form.append('operations', JSON.stringify({ query, variables: { file: null } }))
	form.append('map', JSON.stringify({ '0': ['variables.file'] }))
	form.append('0', new File([''], 'image.png'))

	await fetch('/api/graphql', { method: 'POST', body: form })
})
```

**Comment by GuySerfaty** [comment]
Hey, any new with upload for graphql? it feels pretty important.

**Comment by kettanaito** [comment]
I've just recently added some tests for file uploads with Axios (#1855), and I'm rather certain this works with GraphQL as well (there's no difference internally). Also, take a look at the [File uploads recipe](https://mswjs.io/docs/recipes/file-uploads) in the docs.
