### ISSUE TITLE
Proposal: Allow to define general configuration

### ISSUE THREAD

**Issue by JanStevens** [mswjs/msw#617]
Hi :wave:,

At November Five, we are a big fan of MSW and slowly adopt it on all our projects. We mainly build applications that talk with an external API. What we would like to do is set global configuration of MSW once.

For example a `baseUrl` option would allow us to specify the external API so our `rest` calls become much cleaner.

```javascript
// 🙈  those urls are really that long...
setupWorker(...handlers, { baseUrl: 'https://bs-ssl.frontend-api.external-client.com/api/internal/v4/` })

rest.get('/user', (req, res, ctx) => { ... }
```

Of course `baseUrl` is trivial but it would be a good first start to have some general global configuration. We currently use a constant to define the baseUrl and always have to interpolate it before the endpoint mock. This is often forgotten by new developers causing a lot of headaches why mocks are not working.

Regards

**Comment by kettanaito** [comment]
Hey, @JanStevens. Thank you for the feedback and this suggestion!

We've partially touched a `baseUrl` concept in #406, but concluded it as an overcomplication. As you can also specify a RegExp as the request's route, it becomes unintuitive for you what URL would be matched given the base URL and the expression. It also puts a lot of heavy-lifting on the library's shoulders to merge those two together reliably. I'm speaking about this scenario:

```js
const worker = setupWorker(...handlers, { baseUrl: 'https://api.github.com' })

rest.get(/User/) // What do you expect to match?
``` 

Generally, I see configuration as a thing that can quickly grow out of control. Don't get me wrong, I understand your concerns and don't wish people to repeat themselves when declaring handlers. I just don't think a global configuration is a solution to that problem.  

> API-wise, I see global configuration like above applicable when it affects the internal logic of the library. For example, if MSW had a request matching logic A but now migrates to logic B, you could specify which logic to use via the configuration.

## Suggestion

I can suggest creating a custom request handler and embedding the `baseUrl` into it. That'd be both deterministic and clear for anybody writing mocks.

```js
// src/mocks/support.js
import { RestHandler, RESTMethods } from 'msw'

const BASE_URL = 'https://api.github.com'

function createRestHandler(method) {
  return (url, resolver) => {
    const absoluteUrl = new URL(mask, BASE_URL).toString()
    return new RestHandler(method, absoluteUrl, resolver)
  }
}

export const rest = {
  head: createRestHandler(RESTMethods.HEAD),
  get: createRestHandler(RESTMethods.GET),
  post: createRestHandler(RESTMethods.POST),
  put: createRestHandler(RESTMethods.PUT),
  delete: createRestHandler(RESTMethods.DELETE),
  patch: createRestHandler(RESTMethods.PATCH),
  options: createRestHandler(RESTMethods.OPTIONS),
}
```

Then use your custom `rest` request handler:

```js
// src/mocks/handlers.js
import { setupWorker } from 'msw'
import { rest } from './support'

setupWorker(
  // Captures "https://api.github.com/repos/:owner/:name" requests.
  rest.get('/repos/:owner/:name', resolver) 
)
```

> You can name your custom `rest` based on the domain you're covering, for example `githubAPI`. That would make your handlers more clear: `githubAPI.get(...)`. 

I understand that's a rather verbose setup, and we'd love to provide some changes on the library's side to make it easier. Perhaps expose some internal request handler builder methods to utilize (such as `createRestHandler`). We also need to export the `RestHandler`/`GraphQLHandler` publicly. 

Would this suggestion work for you? What are your thoughts about it?

**Comment by JanStevens** [comment]
Hi @kettanaito,

Thanks for the extended comment! I of course understand that keeping the API surface small makes this easier to maintain and reason about. Your solution seems more than acceptable and I think we can make it work, it at least gives us a possibility to add some magic on top.

Looking forward for a new release that includes #619 

Regards
