### ISSUE TITLE
Path errors on windows

### ISSUE THREAD

**Issue by sebwalle** [mswjs/msw#623]
## Describe the bug
Getting the following error messages when running in a test environment when doing server.use(rest.get(...)) after setting up. Works first but throws error when trying to change a route to return something else after initialization.

```
    Invalid URI "c:/Users/..projectdir../services/web/src/util/toastr.js"

      at Request.init (node_modules/request/request.js:273:31)
      at new Request (node_modules/request/request.js:127:8)
      at request (node_modules/request/index.js:53:10)
      at Object.createClient (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:358:29)
      at XMLHttpRequestImpl.send (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:642:31)
      at XMLHttpRequest.send (node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:309:34)
      at node_modules/node-request-interceptor/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts:387:29

```
and the same error for /node_modules/stacktrace-js/stacktrace.js, node_modules/jquery/dist/jquery.js, /node_modules/node-request-interceptor/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts etc. 

## Environment
- OS: windows 10
- `msw: 0.26.2`
- `nodejs: 12.13.0`
- `npm: 6.14.11`

> Please also provide your browser version. 
Using on CL

## To Reproduce
1. setup server
2. after setting up and listen() , do server.use(rest.get(...))

## Expected behavior
it should work, works on coworkers machine with everything the same (node version, npm, lib version (same repo)). Only difference is he is using OSX and me windows 10. Works in the pipeline as well running linux.

**Comment by msutkowski** [comment]
@sebwalle Can you confirm that you're using absolute paths? ie: `rest.get('https://my.full.url/path', () => {})`?

**Comment by sebwalle** [comment]
@msutkowski no, relative, e.g.: ` rest.get('/api/...` and it works in the beginning, only when trying to edit the same path to do something else after initializing does it throw that error.

**Comment by msutkowski** [comment]
> @msutkowski no, relative, e.g.: ` rest.get('/api/...` and it works in the beginning, only when trying to edit the same path to do something else after initializing does it throw that error.

We'll have to look into this - but a quick solution would be to just use absolute paths if you're able to. If you're able to set up a quick repro, that'd help a ton. As a side note, does this happen if you run it in WSL?

**Comment by sebwalle** [comment]
Checked now, works in WSL, so I'll just use that. Absolute paths didn't work unfortunately (but works in WSL so the URLs are correct).
We are running React created by create-react-app, but now when I tried to make a simple project reproducing the issue it all works (both relative and absolute). Must be some config we have that breaks it. Feel free to close this issue if you don't feel a need to investigate further.

**Comment by kettanaito** [comment]
I can give it a try on a Windows machine and update this issue. From the error message, it seems that there was an attempt to create a URL instance from a relative path that was resolved against your `process.cwd` or similar. MSW doesn't handle relative URL paths in Node.js, JSDOM (or another DOM-like environment) does. Since Jest polyfills `window.location`, relative URLs get resolved against the stub, which I believe is `http://localhost`. In pure Node.js relative URLs cannot exist (nothing to be relative to). 

Most likely the issue was indeed somewhere in your setup. @sebwalle thank you for looking into it. Could you please update us on what caused this issue? It'd be useful for posterity.

**Comment by msutkowski** [comment]
> I can give it a try on a Windows machine and update this issue. From the error message, it seems that there was an attempt to create a URL instance from a relative path that was resolved against your `process.cwd` or similar. MSW doesn't handle relative URL paths in Node.js, JSDOM (or another DOM-like environment) does. Since Jest polyfills `window.location`, relative URLs get resolved against the stub, which I believe is `http://localhost`. In pure Node.js relative URLs cannot exist (nothing to be relative to).
> 
> Most likely the issue was indeed somewhere in your setup. @sebwalle thank you for looking into it. Could you please update us on what caused this issue? It'd be useful for posterity.

I can also help look into this next week. Won't have access to a windows machine until then 🎉

**Comment by sebwalle** [comment]
I never did find the issue, since it works in WSL that is good enough for me, too many other pressing issues to take care of 😅. Both relative and absolute paths works in WSL (using the ubuntu app), but neither works on windows with our conf. Only relative paths tested working on OSX, but would assume the absolute would as well.

**Comment by kettanaito** [comment]
I've tried this on Windows 10 and din't experience the issue. Here's the test file:

```js
import { rest } from 'msw';
import { setupServer } from 'msw/node'

const server = setupServer(
  rest.get('/user', (req, res, ctx) => res(ctx.json({ id: 1 })))
)

beforeAll(() => server.listen())
afterAll(() => server.close())

test('applies runtime handler on Windows 10', async () => {
  server.use(
    rest.get('/user', (req, res, ctx) => res(ctx.json({ id: 2 })))
  )

  const res = await fetch('/user')
  expect(await res.json()).toEqual({ id: 2})
});
```

The test passes successfully. It must have been something in your configuration that made relative request URLs in tests resolve against your `process.cwd()`.
