### ISSUE TITLE
mockServiceWorker is in pending state indefinitely

### ISSUE THREAD

**Issue by aishwarya257** [mswjs/msw#634]
Code Sandbox demo: https://codesandbox.io/s/cold-sea-jos8q?file=/src/index.tsx

Please check the network tab in the above demo and mockServiceWorker file is not dowloaded at all 

Version: 

 "msw": "0.27.0"

**Comment by kettanaito** [comment]
Hi, @aishwarya257.

Does this issue happen outside of sandbox (i.e. on your local machine)? Codesandbox is rather intricate when it comes to registering custom workers, so there may be flaky behavior. That's not the case when working with the library locally.

**Comment by aishwarya257** [comment]
Yes, you are right. It happens only with sandbox and works fine in my local machine. Now I have a different problem, the request is intercepted upon clicks, but the request that happens on page load is not intercepted and the actual API is called.

**Comment by aishwarya257** [comment]
I tried this and it works out the box. https://mswjs.io/docs/recipes/deferred-mounting Thank you for the prompt response. I'm closing this issue.
