### ISSUE TITLE
Requests not mocked using Angular and Spectator

### ISSUE THREAD

**Issue by IanGrainger** [mswjs/msw#635]
## Environment
```
ng --version

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.7
Node: 12.18.4
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.6
typescript                      4.0.7

{
"os": {
    "platform": "win32",
    "distro": "Microsoft Windows 10 Pro",
    "release": "10.0.18363",
    "codename": "",
    "kernel": "10.0.18363",
    "arch": "x64",
    "codepage": " 850",
    "logofile": "windows",
    "build": "18363",
    "servicepack": "0.0",
    "uefi": false,
    "hypervisor": true,
    "remoteSession": false
  },
"versions": {
    "kernel": "10.0.18363",
    "openssl": "1.1.1g",
    "systemOpenssl": "",
    "systemOpensslLib": "",
    "node": "12.18.4",
    "v8": "7.8.279.23-node.39",
    "npm": "6.14.6",
    "yarn": "",
    "pm2": "",
    "gulp": ": 2.2.0",
    "grunt": "",
    "git": "2.20.0.windows.1",
    "tsc": "3.9.7",
    "mysql": "",
    "redis": "",
    "mongodb": "",
    "apache": "",
    "nginx": "",
    "php": "",
    "docker": "19.03.5",
    "postfix": "",
    "postgresql": "",
    "perl": "",
    "python": "3.7.3",
    "python3": "",
    "pip": "19.0.3",
    "pip3": "19.0.3",
    "java": "13.0.2",
    "gcc": "",
    "virtualbox": "",
    "bash": "",
    "zsh": "",
    "fish": "",
    "powershell": "5.1.18362.1171:",
    "dotnet": "
    }
}
```

I'm trying to use MSW in an Angular project with Spectator.

Repo showing the problem is here: https://github.com/IanGrainger/angular-spectator-msw-test

## Current behavior

When I run `ng test` the test fails. MSW logs that it's started, but doesn't intercept the request.

## Expected behavior

The test should pass.

**Comment by timdeschryver** [comment]
Because the request is async you will have to wait until the response is received.
I'm not familiar with Spectator, but this is how it would seem with Angular Testing Library

```ts
import { HttpClientModule } from '@angular/common/http';
import { render, screen } from '@testing-library/angular';
import { TestComponent } from './test.component';

fdescribe('TestComponent', () => {
  it('should show test string', async () => {
    await render(TestComponent, {
      imports: [HttpClientModule],
    });

    expect(screen.getByText('Test string here')).toBeDefined();
    // 👇 notice that we wait until the text is visible
    expect(await screen.findByText(/http:\/\/dogimage\/msw.jpg/)).toBeDefined();
  });
});
```

**Comment by IanGrainger** [comment]
Usually you can just `await fixture.whenStable` and then
`fixture.detectChanges`. with real network requests (which are also async).

Seems strange that this doesn't work for MSW requests. It certainly used to
as I used the two together on my last project..

**Comment by timdeschryver** [comment]
Thanks for the clarification @IanGrainger , I'll have another look later.

**Comment by timdeschryver** [comment]
@IanGrainger  do you have an example where it does work? 
I debugged this again, but it seems like the failing expect is done before the request is made.
I would  also suggest awaiting on the worker to be started because this is an `async` process.

```ts
import { worker } from './mocks/browser';

beforeAll(async () => {
  await worker.start();
});
```

**Comment by IanGrainger** [comment]
I tried awaiting start, actually, and it helped a bit I thought. But then
still didn't work consistently.

I used it in a project at work before, so I can't show that code, I'd have
to go back to the older versions of everything and setup a new project.

**Comment by kettanaito** [comment]
There should be no issues running MSW in Angular tests right now. Make sure to:

- Update to the latest version of `msw` (0.39.1 at the moment of writing);
- Update other dependencies (`msw` requires `typescript >= 4.3` to compile);
- Construct your tests properly (await asynchronous operations, adhere to best practices established by your framework). 

If you encounter any issues, please open a new issue with a link to the reproduction repository where I can take a look at it. Thanks.
