### ISSUE TITLE
Bypassed requests made to the firebase emulator result in a timeout

### ISSUE THREAD

**Issue by rdjpalmer** [mswjs/msw#636]
## Describe the bug

Bypassed requests made to the firebase emulator result in a timeout.

## Environment

- `msw: 0.27.0`
- `nodejs: 15.0.1`
- `npm: 7.0.3`
- `jest: 26.0.1`

## To Reproduce

[See repro case](https://github.com/rdjpalmer/firebase-msw-timeout)

## Expected behavior

Requests made to the firebase emulator should bypass msw entirely, and succeed.

## Additional information

I've tried also supplying handlers which should still result in msw being bypassed, per https://github.com/mswjs/msw/issues/234#issuecomment-646869533.

Might be that this is tied to #414.

**Comment by matt-kinton** [comment]
I'm also seeing the same problem. I got around it temporarily with this which very clean haha.

```
const realResponseResolve = async (req: any, res: any, ctx: any) =>
    res(ctx.json(await ctx.fetch(req).then((res: Response) => res.json())));

export const testServer = setupServer(
    rest.get('*/*', realResponseResolve),
    rest.post('*/*', realResponseResolve),
    rest.put('*/*', realResponseResolve),
    rest.patch('*/*', realResponseResolve),
    rest.delete('*/*', realResponseResolve),
    rest.options('*/*', realResponseResolve)
);
```

**Comment by marcosvega91** [comment]
Hi @rdjpalmer, we are sorry that you're facing this issue. This is caused by streams used by firestore. I have created a PR with issue #602. A temporary workaround is to comment these lines https://github.com/mswjs/msw/blob/ec64cdd7cc01e699180fce090723ab2f3006de70/src/mockServiceWorker.js#L120-L134 if you are not using [lifecycle-events](https://mswjs.io/docs/extensions/life-cycle-events)

**Comment by Mattinton** [comment]
Is there a workaround for setupServer @marcosvega91?

**Comment by matt-kinton** [comment]
@marcosvega91 I don't think this works for setupServer?

**Comment by marcosvega91** [comment]
I didn't see that the issue was for `setupServer`. I have updated now my PR and it seems fixed for the browser. I'll check on node what is happening

**Comment by marcosvega91** [comment]
I have opened a PR [here](https://github.com/mswjs/node-request-interceptor/pull/95) that should resolve this issue

**Comment by marcosvega91** [comment]
It's the case to leave the issue opened until `node-request-interceptor` is updated in msw?

**Comment by kettanaito** [comment]
@marcosvega91, let's leave it closed, update NRI, and then let the users test it out.

**Comment by rdjpalmer** [comment]
@marcosvega91 thanks for looking into this so quickly. Much appreciated. I'll test the fix out as soon as I get a chance

**Comment by rdjpalmer** [comment]
It's taken me awhile, but I've finally tested the fix. Works a treat, thanks @marcosvega91!
