### ISSUE TITLE
Unmentioned breaking change in 0.27.0: `MockedRequest` has no `params` field

### ISSUE THREAD

**Issue by Enet4** [mswjs/msw#639]
## Description

When updgrading msw into 0.27, an existing valid program could fail to type check because `MockedRequest` no longer has a `params` field (change introduced [here](https://github.com/mswjs/msw/commit/703ddf3c86dc39f77c6f012a112ee5ddcf9b3eae#diff-508e0ee011a71f37cb9b911d0798a17fa5d5f4dfbb18cba250e6ac7dc0e74f13L46) in commit 703ddf3c).

This is not _exactly_ a bug, so much as a discrepancy of expectations that could still be clarified with an edit to the releases page, making migration to msw 0.27 a bit more fluid. As such, alongside the remaining migration recommendations, the page could include something like this:

> `MockedRequest` no longer exposes `params`, use `RestRequest` instead.

## Environment

- `msw: 0.27.x`
- `nodejs: 12.18.2`
- `npm: 6.14.5`

## To Reproduce
This code still works and type checks correctly with msw 0.26.2, but fails with 0.27.1.
```typescript
import { rest, MockedRequest } from 'msw';

rest.post('http://localhost/foo/:user/bar', (req: MockedRequest, res, ctx) => {
    let { user } = req.params;
})
```

## Expected behavior

While it is reasonable for the code above to fail with the latest version, a guideline to replace `MockedRequest` with one of the shiny new type definitions in the GitHub releases page would be rather welcome.

**Comment by kettanaito** [comment]
Hey, @Enet4. Thank you for pointing this out! 

Rewriting the request handlers API was a massive refactoring, it appears that things got overlooked. That being said, I've updated the [0.27.0 release notes](https://github.com/mswjs/msw/releases/tag/v0.27.0) to mention the `MockedRequest` changes you've described above. Thank you.
