### ISSUE TITLE
TypeScript 3.9.9 can't type check lib/utils/internal/compose.d.ts

### ISSUE THREAD

**Issue by someden** [mswjs/msw#641]
Same bug as was in #615, but with typescript version 3.9.9

## Environment

- `msw: 0.27.1`
- `nodejs: 12.18.3`
- `npm: 6.14.6`
- `typescript: 3.9.9`

## Steps to reproduce the behavior:
```bash
$ yarn add msw typescript@3
$ echo "import { setupWorker } from 'msw'" >> index.ts
$ yarn tsc --noEmit index.ts
```
Error:
```
node_modules/msw/lib/types/utils/internal/compose.d.ts:6:8 - error TS1005: ',' expected.
6     arg: any,
         ~

node_modules/msw/lib/types/utils/internal/compose.d.ts:7:12 - error TS1005: ',' expected.
7     ...rest: infer LastArg
             ~

Found 2 errors.
```

**Comment by timdeschryver** [comment]
Hi, I don't think that this is the same issue.
I think the issue here is that we're using [variadic tuple types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types), which were introduced in TS 4.0.
See #491 and #512 for more info.

**Comment by kettanaito** [comment]
Thanks for reporting this. 

MSW uses type definitions that rely on TypeScript >=4.0 features. Please upgrade your TypeScript versions to use the latest types of MSW. Thanks.
