### ISSUE TITLE
[MSW] Mocking enabled, but doesn't work

### ISSUE THREAD

**Issue by rtatarinov4xxi** [mswjs/msw#644]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.27.1   |
| browser | Chrome 89.0.4389.82  |
| OS      | Ubuntu 20.04     |

## Request handlers

```js
const serverApi = (path) => {
  return new URL(
    `/api${path}`,
    'https://api.something.net',
  ).toString();
};

export const worker = setupWorker(
  rest.get(serverApi(`/some_rout`), (req, res, ctx) => {
    const query = req.url.searchParams;
    const company_id = query.get('id');

    return res(ctx.status(404, 'Custom status text'));
  }),
);

worker.start({
  serviceWorker: {
    url: '/public/mockServiceWorker.js',
  },
});
```

## Actual request
Request to real server called, and worker doesn't intercept it. Also, I can't get mocks result

## Expected result
Request to real server canceled, and worker returns actual data from `setupWorker` fn

**Comment by kettanaito** [comment]
Hi. Whenever your request is not intercepted when you think it should be, [follow this guide](https://mswjs.io/docs/recipes/debugging-uncaught-requests). Share your findings with us here once you do. Thanks.

**Comment by kettanaito** [comment]
If none of the pieces of advice from the mentioned guide help, please create a reproduction repository where we can look at the issue.

**Comment by rtatarinov4xxi** [comment]
Thanks, I try to create repository, because `onUnhandledRequest` doesn't track my server requests. But I can produce more information before I will create a repository with example. Now I try to debug my app with methods:
```js
worker.on('request:start', (req) => {
  console.log('request:start');
});

worker.on('request:match', (req) => {
  console.log('request:match');
});

worker.on('request:unhandled', (req) => {
  console.log('request:unhandled');
});

worker.on('request:end', (req) => {
  console.log('request:end');
});

worker.on('response:mocked', (res, reqId) => {
  console.log('response:mocked');
});

worker.on('response:bypass', (res, reqId) => {
  console.log('response:bypass');
});
```

Nothing happened. Also, when I try debug serviceWorker I found `self.addEventlistener('fetch')` in my `mockServiceWorker.js` haven't been call. 

And I have the socket channel in my app. But also client gets some of data by rest api. And this functionality I wanna mock

**Comment by kettanaito** [comment]
Looks like you are not registering the worker. In fact, if there's no console error, then your `worker.start()` is not called anywhere in your app. Otherwise, it would produce an exception explaining what went wrong. 

Sorry, without a reproduction repository it's a blind guess.

**Comment by kettanaito** [comment]
Closing this as no reproduction repository was provided. More than happy to reopen and investigate once there is a reliable way to do so.
