### ISSUE TITLE
No error message is showed when worker.start() failed because browser doesn't support Service Workers

### ISSUE THREAD

**Issue by mongjong59** [mswjs/msw#650]
## Describe the bug
No error message is showed in the console of the browser when `worker.start()` failed because browser doesn't support Service Workers. It was until I digged into [the source code](https://github.com/mswjs/msw/blob/e5827120009180cbc38956e899a91751cec7d3c2/src/setupWorker/start/createStart.ts#L34) that I found the root cause. Might be due to the `startWorkerInstance` function is async.

## Environment

- `msw: 0.27.0`
- `nodejs: 8.17.0`
- `npm: 6.13.4`

> Chrome 88.0.4324.182 (Official Build) (x86_64)

## To Reproduce
1. Set up msw within a `create-react-app` project without https being set up
2. Run `npm start`
3. Visit the local server to browser and go to "Console" tab in DevTools. No error message should show up.

## Expected behavior
At the end of step 3, user should see a console message saying
`[MSW] Failed to register a Service Worker: this browser does not support Service Workers (see https://caniuse.com/serviceworkers), or your application is running on an insecure host (consider using HTTPS for custom hostnames).`

**Comment by kettanaito** [comment]
Hey, @mongjong59. Thanks for reporting this.

I'm trying to follow your reproduction steps, but not getting this behavior. The steps I do:

1. `npx create-react-app msw-https`
2. `yarn add msw && yarn msw init public`
3. `HTTPS=true npm start`

> Since by default CRA is served over HTTP, you won't see the HTTPS insecure host-related error. I'm adding the `HTTPS=true` environmental variable according to [these instructions](https://create-react-app.dev/docs/using-https-in-development/) for CRA to run locally over HTTPS.

When the app is loaded, I see an error that browser is unable to fetch the worker script over HTTPS due to insecure origin:

```
Uncaught (in promise) Error: [MSW] Failed to register a Service Worker:

Failed to register a ServiceWorker for scope ('https://localhost:3000/') with script ('https://localhost:3000/mockServiceWorker.js'): An SSL certificate error occurred when fetching the script.
```

Is this the same behavior you're experiencing? If not, could you please provide more detailed reproduction steps? Thanks.

**Comment by mongjong59** [comment]
Hi @kettanaito, thank you for the prompt response. Your reproduction is step is different from what I specified: to reproduce my issue, you need to host CRA **without HTTPS** as described in the step 1 in "How to reproduce". And in this circumstance, you should see the error message as coded here. https://github.com/mswjs/msw/blob/e5827120009180cbc38956e899a91751cec7d3c2/src/setupWorker/start/createStart.ts#L35-L39
But I never see it and have to read the source code to troubleshoot. I believe running the application over http is one of the cases this error is designed for. But the error is never showed. Thus, a user of `msw` who is not aware of "Service Workers cannot be supported over HTTP" or accidentally hosting their application over HTTP will have a hard time debugging the issue. 

Another way to think about this is to how can we get the error message coded on createStart.ts#L35-L39 to show up?

In a word, an exception that is designed by `msw` to throw is never throwed.

**Comment by msutkowski** [comment]
@mongjong59 I created a repro with your instructions, and things work as expected: https://github.com/msutkowski/msw-localhost

If you're still seeing this issue, can you please create a repro on GitHub or Codesandbox so we can review your implementation?

As a reference, these are the exact steps I used:

1. `yarn create react-app msw-localhost`
2. `yarn add msw && yarn msw init public`
3. Modify `index.js` to setup a worker with a basic handler
4. Add a fetch call to `useEffect` in `App.js`
5. Visit http://localhost:3000, check console / network tab.

Additional resource regarding service workers, localhost, and HTTPS: https://developers.google.com/web/fundamentals/primers/service-workers/#you_need_https

**Comment by mongjong59** [comment]
Thank you all very much. I'm only able to reproduce with one of my project which I cannot publish publicly. Close this issue for now.
