### ISSUE TITLE
Integration/collaboration with mgdg

### ISSUE THREAD

**Issue by kentcdodds** [mswjs/msw#651]
Hey @kettanaito, my friend @donovanhiland is working on a project to help mocking graphql data: https://github.com/ravnhq/mgdg

I don't really have a use case for it myself, but it looks interesting and I thought you might be interested in seeing whether it's something you can point to in the docs for folks who are trying to mock graphql data.

**Comment by kentcdodds** [comment]
cc @Bdpluim

**Comment by kettanaito** [comment]
Thanks for suggesting this, @kentcdodds! We've been working on a tool for data-driven mocking and have [released it recently](https://github.com/mswjs/data). It utilizes an abstract model definition and can generate GraphQL schema based on models, which looks similar to what mgdg is doing. 

I would recommend mdgd when applicable, but for now, I'll close this, as @mswjs/data provides much more power to the end-user and has a native MSW integration.
