### ISSUE TITLE
EBADPLATFORM when npm install --save-dev msw on Windows 10

### ISSUE THREAD

**Issue by amd-9** [mswjs/msw#656]
## Describe the bug
Running `npm install --save-dev msw` on Windows 10 produces an error

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  undefined
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

## Environment

- `msw: 0.27.1`
- `nodejs: 15.12.0`
- `npm: 7.6.3`

## To Reproduce
1. Run `npm install --save-dev msw`
2. See error

## Expected behavior
`msw` is susscessfully installed on Windows 10 environment

**Comment by kettanaito** [comment]
Hey, @amd-9. Thanks for reporting this. 

I'll switch to a Windows machine and try to reproduce this. 

Meanwhile, leaving the dependency tree for `fsevents`:

```
msw@0.27.1
├─┬ chokidar@3.5.1
│ └── fsevents@2.3.2
├─┬ jest@26.6.3
│ └─┬ @jest/core@26.6.3
│   └─┬ jest-haste-map@26.6.2
│     └── fsevents@2.3.2  deduped
├─┬ rollup@2.39.1
│ └── fsevents@2.3.2  deduped
└─┬ webpack-dev-server@3.11.2
  └─┬ chokidar@3.4.1 invalid
    └── fsevents@2.1.3  extraneous
```

**Comment by timdeschryver** [comment]
I can also confirm that MSW can be installed on Windows 10 (node v14.16.0).
Just a wild guess, but have you tried using npm v6, or yarn?

**Comment by amd-9** [comment]
> I can also confirm that MSW can be installed on Windows 10 (node v14.16.0).
> Just a wild guess, but have you tried using npm v6, or yarn?

Thanks for advice! I've checked another PC with Windows 10 running:
```
nodejs: 12.3.1
npm: 6.14.8
```
Installation process was successfull without errors. Only with warnings:

`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`

**Comment by kettanaito** [comment]
That doesn't seem to be a warning originating from MSW though. All the packages dependent on `fsevents` I've listed above are dev dependencies and are not installed when you run `npm install msw` in your project. 

@amd-9, can you please try the following?

```sh
mkdir test
cd test
npm init -y
npm install msw
```

Does it still print that warning?

**Comment by amd-9** [comment]
@kettanaito sure!

On machine with nodejs `12.3.1` result was

```
PS C:\test> npm install msw

> msw@0.27.1 postinstall C:\test\node_modules\msw
> node -e "try{require('./config/scripts/postinstall')}catch(e){}"

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ msw@0.27.1
added 77 packages from 122 contributors and audited 78 packages in 4.143s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C:\test>     
```
On machine with `nodejs 15.12.0` (suprisingly):

```
PS C:\test> npm install msw

added 77 packages, and audited 78 packages in 4s

8 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\test>
```

**Comment by kettanaito** [comment]
To clarify: that warning shouldn't affect your experience with MSW. It's stated in the message that `fsevents` is an _optional_ dependency. I don't see anything we can do on the library's side, it's the way `fsevents` behaves, not being our direct dependency.
