### ISSUE TITLE
Mocks are not resetted between tests (or better HOW to reset mocks between tests)

### ISSUE THREAD

**Issue by florianmatz** [mswjs/msw#657]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.27.0   |
| node | 14.9.0     |
| OS   | Mac OS 10.15.7     |

## Request handlers

mocks/handlers.ts:
```ts

import facade from './db/facade.json';

const handlers = [

  rest.get('/baumassnahmen/:id/details', (req, res, ctx) =>
      const { id } = req.params;
      if (id && Number(id) in facade.baumassnahmen.details) {
         return res(ctx.delay(); ctx.json(facade.baumassnahmen.details[id].details);
      }
     
      .....

  ),

 rest.put('/baumassnahmen/:id/details', (req, res, ctx) => {
        const { id } = req.params;

        if (id && Number(id) in facade.baumassnahmen.details) {
            const newData = req.body as Projektdetails;

            // Update Detail
            facade.baumassnahmen.details[Number(id)].details = newData;

            // Update Overview
            const overviewItem = facade.baumassnahmen.uebersicht.find(item => item.id === id);

            if (overviewItem) {
                (overviewItem.status as IStatus) = newData.status;
                overviewItem.faelligkeitsdatum = newData.faelligkeitsdatum;
            }

            return res(ctx.delay(), ctx.json(req.body));
        }
       
        ....
     
    }),
   ... more handlers ...
 ];
```

mocks/server.ts
```ts

import { setupServer } from 'msw/node';
import { rest } from 'msw';
import handlers from './handlers';

const server = setupServer(...handlers);
export { server, rest };
```

## Actual request

SWR
```ts
const useProjektdetails = (): IUseFetchData => {
    const { param1: projectId }: { param1: string } = useParams();
    const { data, error }: UseFetchData = useSWR(projectId ? endpoints.projektdetails(projectId) : null);
    return { data, error };
};
```

Axios Fetch (supplied via SWRConfig)
```ts
    fetch: async url => {
        try {
            const { data } = await axiosInstance.get(url, await getHeaders());
            return data;
        } catch (error) {
            const { response } = error;
            console.log(
                `Daten konnten nicht geladen werden: Payload: ${response.data.error} | Status-Text: ${response.statusText}`
            );
            throw error;
        }
    },
```

## Tests

setupTests.ts
```ts
import { cache } from 'swr';
import { server } from './mocks/server';

beforeAll(() => server.listen());

afterEach(() => {
    server.resetHandlers();
    cache.clear();
});

afterAll(() => server.close());
```

Tests
```ts

    describe('My Dummy Test', () => {

        test('A: Update a component with PUT', async () => {
             const Wrapper = () => {
                 const { data } = useProjektdetails();
                 return data && <MyComp data={data} />;
             };

            render(Wrapper);

            // Updates data in my facade.db 
            const putButton = await screen.findByText('PUT');

            userEvent.click(putButton);
            await screen.findByText('PUT done...');

        });

       test('B: Test after put', async () => {
           const Wrapper = () => {
               // DATA is now corrupted by the value put in the test before... 
               const { data } = useProjektdetails();
               return data && <MyComp data={data} />;
           };
           render(Wrapper);
           await screen.findByText('Await something');
       });

    });

```

## Problem description

Say you have a test A that performs a PUT within the tested component. The handlers modifies the imported db file (facade.json). The component get's re-rendered due to the SWR-Hook. I expect a value, everything i fine. 

Now, I have a test B, that also uses the SWR-Hook. But now I get the data manipulated in the previous test, which causes it to fail, because I rely on fresh, original data from the facade.db...

Its definitely no SWR-caching thing, double checked on that, the cache is clear.

## Expected behavior

Data returned from facade.db is fresh and in original state in the following tests. Just like in the Browser, when you reload the page.

## What I've tried
Restart the server after each test, but unfortunately with errors... 

## Idea

Expose a method like server.resetHandlers(); server.resetMocks(); ?! I don't know. 
Does anybody have an idea how to get around this?

**Comment by timdeschryver** [comment]
Hi, this does feel like a problem with the shared state (`facade`) between the two tests.
To take a closer look at this, a reproduction will be of great help.

**Comment by kettanaito** [comment]
> Data returned from facade.db is fresh and in original state in the following tests. Just like in the Browser, when you reload the page.

That won't work the same in Node.js because there's no "refresh" of the execution context in Node. All your logic runs (often) in a single thread, so any changes you make to your data persist in that process. This is now Node works and this is completely expected. 

It looks like you're mutating your fixtures object and expect MSW to somehow restore it back to the previous state. Since you're introducing that object, it's your responsibility to reset it whenever necessary. For example, you can clone that object before mutations and write your own `reset` function that re-assigns that object to the initial state:

```js
import clone from 'clone-deep'
import facade from './db/facade.json'

const initialState = clone(facade)

function resetFacade() {
  facade = initialState
}

// Perform mutations with your fixture
```

> Uses [clone-deep](https://www.npmjs.com/package/clone-deep) package, but you can clone your data in any way suitable.

**Comment by florianmatz** [comment]
@kettanaito 

Just came up with a similiar quick and dirty solution:

```ts
import initialFacade from './db/facade.json';

/** Construct to be able to reset facade after CRUD in jest-test */
const getFacade = () => cloneDeep(initialFacade);
let facade: any = process.env.REACT_APP_ENV !== 'test' ? initialFacade : getFacade();

export const resetFacade = (): void => {
    facade = getFacade();
};
```

Calling resetFacade in test's that perform a CRUD Operation on the facade.

and in setupTests:

But maybe [https://github.com/mswjs/storage](url) will kind of be a future alternative :P ?

**Comment by kettanaito** [comment]
A good point. We are working on the data modeling library and considering the reset API.
