### ISSUE TITLE
Can't install the service worker in Electron renderers with `nodeIntegration` enabled

### ISSUE THREAD

**Issue by tessro** [mswjs/msw#661]
## Describe the bug

Invoking `worker.start()` in an Electron renderer fails if `nodeIntegration` is enabled. This happens because `process` is defined, which causes `isNodeProcess` to return true. As a result, it's not possible to use `msw` in these windows. (`msw`'s node server doesn't work in that environment either, since `fetch` calls use the Chromium network stack, not Node's.)

Electron provides `process.type` with value `"renderer"` in these situations. Would it be satisfactory for `isNodeProcess` to return false in that case? If so, I'm happy to put up a PR!

## Environment

- `msw: 0.27.1`
- `nodejs: 12.18.3`
- `npm: 7.6.3`

> Please also provide your browser version.

Electron 11.3.0 / Chromium 87

## To Reproduce

1. Create Electron `BrowserWindow` with `nodeIntegration: true`
2. Create an `msw` service worker and invoke `worker.start()`
3. Open DevTools, view Console
4. See error:
```
[MSW] Failed to execute `setupWorker` in a non-browser environment. Consider using `setupServer` for Node.js environment instead.
```

## Expected behavior

Service worker is installed

**Comment by kettanaito** [comment]
Hey, @paulrosania. Thank you for discovering this.

So you suggest adding a special case for the Electron renderer process in `isNodeProcess`?

```js
if (process?.type === 'renderer') {
  return true
}
```

> [isNodeProcess.ts](https://github.com/mswjs/msw/blob/655c93f83b7fcebe9a9093cacd7d891939028d29/src/utils/internal/isNodeProcess.ts)

While I think that solution may work, I have a few concerns with this approach. It makes the logic dependent on Electron implementation details, specifically on the way Electron marks the process type. We need to be cautious with escape hatches like this because most likely the renderer process _is_ a Node.js process. The environment check on the library's side is to prevent failure scenarios that are known beforehand. `setupWorker` won't function in a non-browser environment, so we short circuit when such environment is detected. 

> This may be a good reason to re-consider if relying on the `process` being present is the best way to determine a non-browser environment. Perhaps that would be the correct fix. 

Could you please try the suggested fix locally and see how your Electron application behaves?

**Comment by tessro** [comment]
Ah, I see the messiness of this.

When `nodeIntegration` is enabled, *both* `window.fetch` and the Node.js HTTP stack are available, and they do not share underlying infrastructure. I suppose this change would flip the behavior, so `window.fetch` would be shimmed but it would no longer be possible to mock out Node.js HTTP calls?

If I understand correctly, that would mean mocking correctly in this scenario requires configuration by the implementor, so `msw` knows what to do. 🤔

I can confirm that with the added guard, I am able to run `setupWorker` in the renderer, but I'm assuming this is going to cause problems for folks who are using the Node.js integration to make Node-based HTTP calls and would prefer to use `setupServer`.

**Comment by kettanaito** [comment]
This has been resolved as a part of #823 and is available after [0.31.1](https://github.com/mswjs/msw/releases/tag/v0.32.1). Please install the latest version of MSW to have the fix.

**Comment by tessro** [comment]
Amazing! Thank you!

**Comment by Pagebakers** [comment]
I think there has been a regression. I'm not able to run msw in Electron anymore.

```
Unhandled Runtime Error
Error: [MSW] Failed to execute `setupWorker` in a non-browser environment. Consider using `setupServer` for Node.js environment instead.
```

**Comment by Akallabet** [comment]
@kettanaito it looks like the new lib [is-node-process](https://github.com/mswjs/is-node-process/blob/main/src/index.ts), which msw relies upon, doesn't have this change
```
if (process?.type === 'renderer') {
  return true
}
```
If I understood correctly, this was [the accepted fix](https://github.com/mswjs/msw/issues/661#issuecomment-805375397)?

**Comment by kettanaito** [comment]
Hey, @Akallabet. That appears to be the case. Would you be interested in adding that condition to `is-node-process` so we could test it out?

**Comment by alissawix** [comment]
@kettanaito @Akallabet  any news on this?
