### ISSUE TITLE
React native nodejs interception error

### ISSUE THREAD

**Issue by kevinmamaqi** [mswjs/msw#669]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.28.0   |
| node | 15.11.0     |
| OS   | 11.2.3     |

### server.js
```
import {rest} from 'msw';
import {setupServer} from 'msw/node';

const handlers = [
	rest.post('/v1/login', (req, res, ctx) => {
		return res(ctx.status(200), ctx.json({message: 'Username or email error'}));
	}),
];

export const server = setupServer(...handlers);
```

### Jest setup
```
import {server} from './mocks/server';

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

```

## Actual request
In the test it triggers a button that launches the axios request.

```
const login = async () => {
		try {
			setIsLoading(true);
			const response = await axios({
				method: 'post',
				url: '/v1/login',
				data: {email, password},
			});
			setIsLoading(false);
			goToSplashScreen();
		} catch (error) {
			setIsError(true);
			console.error(error); // It logs the error
			setIsLoading(false);
		}
	};
```

## Current behavior
I get multiple errors (or multiple time the same error):
```
 console.error
    [MSW] Error: captured a request without a matching request handler:

      • POST http://localhost/v1/login

    If you still wish to intercept this unhandled request, please create a request handler for it.
    Read more: https://mswjs.io/docs/getting-started/mocks

      at onUnhandledRequest (node_modules/msw/node/lib/index.js:7120:21)
      at node_modules/msw/node/lib/index.js:7620:25
      at fulfilled (node_modules/msw/node/lib/index.js:50:58)
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15
      at flush (node_modules/asap/raw.js:50:29)

  console.error
    [MSW] Error: captured a request without a matching request handler:

      • POST http://localhost/v1/login

    If you still wish to intercept this unhandled request, please create a request handler for it.
    Read more: https://mswjs.io/docs/getting-started/mocks

      at onUnhandledRequest (node_modules/msw/node/lib/index.js:7120:21)
      at node_modules/msw/node/lib/index.js:7620:25
      at fulfilled (node_modules/msw/node/lib/index.js:50:58)
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15
      at flush (node_modules/asap/raw.js:50:29)

```
## Expected behavior
I expect to be intercepted by msw and return the response I placed for error.

## Screenshots
Not applicable

**Comment by kettanaito** [comment]
Hey, @kevinmamaqi. 

First things first, you are not creating an error response in your handler:

```
return res(ctx.status(200), ctx.json({message: 'Username or email error'}));
           ^^^^^^^^^^^^^^^
```

Returning 200 responses won't trigger any error-related handling in your request client, and your test that asserts an error will fail. Instead, pass 4xx/5xx response status code to `ctx.status` to compose a proper error response. 

> Read about [mocking error responses](https://mswjs.io/docs/recipes/mocking-error-responses).

The second issue regarding "Error: captured a request without a matching request handler" error is related to your actual request URL not matching the URL you have defined in the handler. You can do the following to catch the culprit:

1. Check whether you're using any `baseUrl` with axios, or augment the request URL in any other way.
2. Call `server.printHandlers()` right in your test suite. See that the `/v1/login` handler is there.
3. Set up a "transparent" handler that will catch all requests, and inspect what the actual request URL is:

```js
// your.test.js
server.use(
  // See the printed request URL and compare it to the URL in your handler.
  rest.post('*', (req, res, ctx) => console.log(req.url.toString()))
)
```

If none of the above helps, please submit a reproduction repository and share the link here.

**Comment by kettanaito** [comment]
Closing, as I doubt this is an issue with MSW. Please provide a reproduction repository to prove otherwise. Thanks.

**Comment by kevinmamaqi** [comment]
Sorry for late reply and thanks for closing it @kettanaito

As you pointed out I was using axios.baseUrl and that was the problem.
