### ISSUE TITLE
Support for browsers without service workers

### ISSUE THREAD

**Issue by LarsDenBakker** [mswjs/msw#675]
I am working on adopting MSW in our projects and recommending it to other developers. In our company we are in the unfortunate situation where we still have to support older browsers like IE11, and possibly other environments where service workers might not be available such as embedded browsers inside native mobile applications.

I did some tinkering and I have a working version where this library works on those browser by overriding XMLHttpRequest and fetch on those browsers, based on the work that's already there for use inside node js.

It would be great if we could add this to the MSW project as an option besides the service worker and nodejs implementation. Is this something you would be interested in reviewing a PR for?

**Comment by msutkowski** [comment]
Hey @LarsDenBakker, thanks for your feedback! There is an open RFC for that here: https://github.com/mswjs/msw/issues/663. Feel free to chime in :)

**Comment by LarsDenBakker** [comment]
Ah, I missed that one. Thanks!
