### ISSUE TITLE
`req.params` undocumented breaking change + typings not matching: Regression 0.26.x-0.27.x 

### ISSUE THREAD

**Issue by AriPerkkio** [mswjs/msw#682]
Kind of related to https://github.com/mswjs/msw/issues/639 but this is an actual bug in the code. 

## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.28.1   |
| browser | Chrome 88     |
| OS      | win10     |

## Request handlers

[Handler from MSW examples](https://github.com/mswjs/examples/blob/master/examples/rest-react/src/mocks/handlers.js) with `req.params` logging.

```js
import { rest } from "msw";

export const handlers = [
    rest.post("/login", (req, res, ctx) => {
        console.log("req.params", req.params);
        const { username } = req.body;

        return res(
            ctx.json({
                id: "f79e82e8-c34a-4dc7-a49e-9fadc0979fda",
                username,
                firstName: "John",
                lastName: "Maverick",
            }),
        );
    }),
];
```

## Actual request

https://github.com/mswjs/examples/blob/83603a4619abb09447322d88bb88a7e4d6a2c91c/examples/rest-react/src/LoginForm.js#L18-L36

```js
fetch("/login", {
    method: "POST",
    body: JSON.stringify({ username })
});
```

## Current behavior

```js
export const handlers = [
    rest.post("/login", (req, res, ctx) => {
        console.log("req.params", req.params);
                ^^^  req.params {}   // msw@0.26.2
                ^^^  req.params null // msw@0.27.2
                ^^^  req.params null // msw@0.28.1
```

## Expected behavior

`req.params` should never be `null`. 

https://github.com/mswjs/msw/blob/443ce4535a61efb01a9f7990ebfc230a2ba59541/src/handlers/RestHandler.ts#L82

I have a custom request handler which is utilized across multiple projects. This handler is accessing `req.params` with `Object.entries` method. When no params are present the call will throw with `msw@0.27.x`. With `msw@0.26.x` the `req.params` always had value. 

If `null` is expected behaviour (👎 ) the typings should be fixed:

```diff
- params: ParamsType
+ params?: ParamsType
```

If `req.params` should always hold a value (👍 ) the code should be fixed.

**Comment by AriPerkkio** [comment]
[Caused by `node-match-path`](https://github.com/mswjs/node-match-path/blob/master/src/match.ts#L7) missing `strictNullChecks` in its [`tsconfig.json`](https://github.com/mswjs/node-match-path/blob/master/tsconfig.json).

Repro: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLJzAgFsg3gKGWQFsNsIBnALmQCMB7egGwjhEOQAc4o5jrkAJQgJ6UACYAeCmCigA5gBpkMuSHkA+fAF98+USBnIoEAI410mHAF48HUlco1ZAVwiKO3XvxogXTJg9dIA

**Comment by kettanaito** [comment]
Hey, @AriPerkkio. Thanks for reporting this. 

node-match-path should return `null` if there are no parameters, it's MSW that should coerce `null` to an empty object here:

https://github.com/mswjs/msw/blob/443ce4535a61efb01a9f7990ebfc230a2ba59541/src/handlers/RestHandler.ts#L147-L155

I'm pretty sure the coercion was there but must have been lost during the request handlers rewrite. 

Please, would you be interested in opening a pull request with this change in MSW?

**Comment by AriPerkkio** [comment]
Thanks for pointers. I'll setup PR this week.

Typings of `node-match-path` should also be fixed, right? With `params: Record<string, string> | null;` this would have been reported by typescript in MSW code base.

**Comment by kettanaito** [comment]
Yeah, you're right, `null` should be listed in the union there. Let me know if you have any questions during the contribution, I'd be glad to help. See you in the code review!
