### ISSUE TITLE
Using MSW with Cypress: Breaks after the initial run due to missing `masterClient.id`

### ISSUE THREAD

**Issue by nielsboecker** [mswjs/msw#685]
## Describe the bug
I love MSW and have chosen it in my current project in the hope of using the same mocked responses for local development setup and different testing tools.

I have now tried to use it in combination with Cypress. When running my app in development (MSW installed and ready) and then visiting it in Cypress (headed mode), everything works as expected when running a test first. However, subsequent runs cause an error.

## Environment

- `msw: ^0.28.0`
- `nodejs: 14.15.1`
- `npm: 6.14.9`
- `yarn: 1.22.10`
- `Browser: Chrome 89.0.4389.114 (Official Build) (x86_64) run by Cypress`

## To Reproduce
1. Start an application with MSW activated
2. Run tests -> Pass, requests served by MSW
3. Run tests again

## Expected behavior
Subsequent test runs should behave equally as the first run and pass.

## Actual behavior
Cypress errors:
```
The following error originated from your test code, not from Cypress.

  > Fetching resource at '/__cypress/tests?p=cypress/support/index.js' failed

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
```

Error in the console:
```
mockServiceWorker.js:279 [MSW] Failed to mock a "GET" request to "http://localhost:3000/__cypress/tests?p=cypress/integration/manager/main.ts": TypeError: Cannot read property 'id' of undefined
```

Might also be related to https://github.com/mswjs/msw/issues/405.

## Code excerpts
<details>
<summary>Click here to show</summary>

src/mock/browser.ts
```typescript
import {setupWorker, rest, SetupWorkerApi} from 'msw'
import { handlers } from './handlers'

export const worker = setupWorker(...handlers)

export type WindowWithMSW = typeof window & {
    msw: {
        worker: SetupWorkerApi,
        rest: typeof rest
    }
}

// Expose methods globally to make them available in integration tests
(window as WindowWithMSW).msw = { worker, rest };
```

src/.../DevModeApp.tsx
```typescript
...
if (appDevMode !== undefined) {
    worker.start();
}
...
```

cypress/integration/some-test.ts
```typescript
describe("Something", () => {
    beforeEach(() => {
        cy.visit("/");
    })

    it("tests something", () => {
        // Do something that triggers network requests; MSW is already running and intercepts them
        // or to change them per test, access window.msw
    })
})
```
</details>

**Comment by nielsboecker** [comment]
## Analysis
This seems to be caused by the logic around MSW's clients in [mockServiceWorker.js](https://github.com/mswjs/msw/blob/master/src/mockServiceWorker.js).

In the first run, there are two WindowClients in `allClients`:
```
[
  // A) The top-level Cypress frame
  {
    frameType: "top-level"
    id: "103fe17c-a7c8-48c7-8849-27c970643e28"
    url: "http://localhost:3000/__/#/tests/integration/manager/main.ts"
    ...
  },
  // B) The application under test, running inside an iframe
  {
    frameType: "nested"
    id: "786cb5cc-b032-4135-8d54-6afcbd4b8607"
    url: "http://localhost:3000/"
    ...
  }
]
```

In the first test run, the first FetchEvent for the API call comes from B), which is correct, and gets handled correctly.
```
{
  clientId: "786cb5cc-b032-4135-8d54-6afcbd4b8607"
  request: Request {method: "GET", url: "https://api.example.com", headers: Headers, destination: "", referrer: "http://localhost:3000/", ...}
  ...
}
```

Now, let's re-run the tests. The first FetchEvent to end up in `handleRequest` is a request by the Cypress framework:
```
{
  clientId: "498c213e-86d0-4ea9-87b2-1c38a7de0e5a"
  request: Request {method: "GET", url: "http://localhost:3000/__cypress/tests?p=cypress/support/index.js", headers: Headers, destination: "", referrer: "http://localhost:3000/__cypress/iframes/integration/manager/main.ts", ...}
  ...
}
```

At this point, `allClients` look like this:
```
[
  // A) Same, the top-level Cypress frame
  {
    frameType: "top-level"
    id: "103fe17c-a7c8-48c7-8849-27c970643e28"
    url: "http://localhost:3000/__/#/tests/integration/manager/main.ts"
    ...
  },
  // B) is missing because the application under test has not loaded yet!
  // C) Another nested Cypress framework thing appeared (this is the one that issued the FetchEvent we are currently handling)
  {
    frameType: "nested"
    id: "498c213e-86d0-4ea9-87b2-1c38a7de0e5a"
    url: "http://localhost:3000/__cypress/iframes/integration/manager/main.ts"
    ...
  }
]
```

And `activeClientIds` looks like this:
```
[
  // The ID of the application under test B), which has not loaded yet
  "786cb5cc-b032-4135-8d54-6afcbd4b8607"
]
```

So essentially this request should just be passed through. However, [handleRequest](https://github.com/mswjs/msw/blob/master/src/mockServiceWorker.js#L110) calls [resolveMasterClient](https://github.com/mswjs/msw/blob/master/src/mockServiceWorker.js#L89). As the client is not `top-level` and the ID is not present in `activeClientIds`, this function returns undefined. Hence, `client` is `undefined`, and therefore the conditional `if (client && activeClientIds.has(client.id))` breaks!

## Workaround

I added a return statement to `handleRequest` after line 112 in my copy of `mockServiceWorker.js`:
```typescript
async function handleRequest(event, requestId) {
  const client = await resolveMasterClient(event)
  const response = await getResponse(event, client, requestId)

  if (client === undefined) {
    return response
  }
  ...
```

This does the trick. The unrelated Cypress requests just return the response directly, and the requests issued by the actual application under test get handled by MSW as expected.

However, the file explicitly says not to modify it, and I am not 100% if my change does not cause any other unintended effects.

**Comment by nielsboecker** [comment]
I have now changed my setup a bit.

Initially, I tried to follow [this approach](https://blog.sapegin.me/all/react-testing-4-cypress/) and fully reuse my MSW local development setup for the Cypress tests. However, that caused some other issues (namely, on the CI server it behaved differently from local execution. failing occasionally).

I am no longer baking the service worker into the application for Cypress. Instead, I use the Cypress-native `cy.intercept()` functionality. I've extracted the mock responses into a separate module, so I can reuse them in my MSW handlers and the Cypress interceptors. This is working mich more reliable, so I have also removed the workaround described above.

**Comment by kettanaito** [comment]
Thanks for the detailed investigation, @nielsboecker! 

From what I can see in the current worker script, if the `client` is `undefined`, the `response` will be returned anyway:

https://github.com/mswjs/msw/blob/77d16128ef8ea5f337c156767bee3b4fb4f4a783/src/mockServiceWorker.js#L111-L139

I'm closing this issue but if anybody stumbles upon this, please open a new one with a reproduction repository. Thanks.
