### ISSUE TITLE
NextJS with config basePath results in no handler matches

### ISSUE THREAD

**Issue by toneworm** [mswjs/msw#690]
## Summary
I'm working on a NextJS project that requires a basePath to be set for deployment to a specific path in production. I've used MSW in the past and not had any problems but from an afternoon of experimentation I've found basePath seems to mess up any handler route matching.

Changing basePath to anything but `''` causes relative and absolute URLs to stop working.

I created a simplified example with create-next-app and posted relevant parts below.

Any ideas what I might be doing wrong or suggestions how to fix?

Thanks!

## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.28.1   |
| browser | Chrome 89.0.4389.114     |
| OS      | Windows 10     |

## Request handlers (setup)

```js
// mocks/setup
import { setupWorker, rest } from 'msw'

if (typeof window !== 'undefined') {
  interface Response {
    name: string
  }

  const worker = setupWorker(
    rest.get<Response>('https://books.com/books', (req, res, ctx) => {
      return res(
        ctx.json({
          name: 'Dusty ol book',
        })
      )
    })
  )

  worker.start({
    serviceWorker: {
      // url: '/mockServiceWorker.js',
      url: '/my-base-path/mockServiceWorker.js',
    },
  })
}

```

## next.config.js
```js
module.exports = {
  //  basePath: '',
  basePath: '/my-base-path',
}
```

## _app.tsx
```tsx
require('../mocks/setup')

import type { AppProps } from 'next/app'

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}

export default MyApp
```

## Index page (Actual Request)

```js
import { useEffect } from 'react'

const IndexPage = () => {
  const loadStuff = async () => {
    const res = await fetch('https://books.com/books')
    const json = await res.json()

    console.log(json)
    // without base-path
    // { name: 'Dusty ol book' }

    // with base-path
    // [MSW] Failed to mock a "GET" request to "https://books.com/books": TypeError: Failed to fetch
  }

  useEffect(() => {
    loadStuff()
  }, [])

  return <div>...</div>
}

export default IndexPage

```

**Comment by kettanaito** [comment]
Hey, @toneworm. Thanks for reporting this.

It must have to do with the Service Worker scope, as when I set the `basePath` option and add a `console.log` statement in the `mockServiceWorker.js` "fetch" event handler, it doesn't get evaluated upon a request. This usually means that the worker cannot intercept the request, which is often due to its scope. 

I'm not sure at the moment what to suggest here, this needs more investigation, but it's likely to be a Service Worker configuration issue (i.e. the lack of the correct `serviceWorker.options.scope` value).

**Comment by toneworm** [comment]
Thanks for the response, I've settled for removing basePath for development at the moment and changing it back before deploying to production which isn't ideal but at least i get all that msw goodness for testing.

**Comment by kettanaito** [comment]
## How to use `baseUrl` with Mock Service Worker

It's possible to use MSW with the `baseUrl` set in the `next.config.js`. It comes down to these points:

- Configure the `Service-Worker-Allowed` response header in NextJS.
- Provide the root-level custom scope in `serviceWorker.options.scope`.

```js
// next.config.js
module.exports = {
  basePath: '/prefix',
  async headers() {
    return [
      {
        // Append the "Service-Worker-Allowed" header
        // to each response, overriding the default worker's scope.
        source: '/(.*)',
        headers: [
          {
            key: 'Service-Worker-Allowed',
            value: '/',
          },
        ],
      },
    ]
  },
}
```

```js
// src/mocks/browser.js
import { setupWorker, rest } from 'msw'

const worker = setupWorker(
  // Note that request handler URL is always relative to the _root_.
  // You need to account for the "basePath" yourself here.
  rest.get('/prefix/user', (req, res, ctx) => {
    return res(ctx.json({ firstName: 'John ' }))
  })
)

worker.start({
  serviceWorker: {
    // Specify the worker script URL relative to the _root_.
    url: '/prefix/mockServiceWorker.js',
    options: {
      // Override the scope to the root ("/").
      // By default, the worker is scoped to its location on your server,
      // which in this case would be "/prefix".
      scope: '/',
    },
  },
})
```

Once set up, the `/prefix/user` request will be successfully intercepted:

<img width="837" alt="Screen Shot 2021-05-27 at 13 22 22" src="https://user-images.githubusercontent.com/14984911/119817738-9ec2ea00-beee-11eb-9874-ecd79e5219e5.png">
