### ISSUE TITLE
Error: Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by kboul** [mswjs/msw#692]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.28.1   |
| node | 12.22.1     |
| OS   | ubuntu  18.04 LTS   |

## Request handlers

**actual test**

```
test('async ', async () => {
  renderWithAllProviders(<Topbar {...props} />, reduxState);

  const projectSettings = screen.getByLabelText('bookmarks icon');
  userEvent.click(projectSettings);

  const bookmark = await screen.findByText('a title');
  // console.log(screen.debug());
});
```

**handlers**
```
import { rest } from 'msw';

import { baseUrl } from '../constants';  // const baseUrl = 'http://localhost:8000/api';

export const handlers = [
  rest.get(`${baseUrl}/favorites/`, (req, res, ctx) => {
    return res(
      ctx.json([
        {
          id: 1,
          last_accessed: '2021-04-01T07:01:52.176463Z',
          module: 'some module',
          title: 'a title',
          url: 'some url',
          user: 106
        }
      ])
    );
  })
];
```

## Actual request

The request is being performed using a custom hook and it is a get request using fetch API
  ```
useEffect(() => {
    const fetchBookmarks = async () => {
      const bookmarks = await getBookmarks();  
      setBookmarksList(bookmarks);
    };
    fetchBookmarks();
  }, []);
```

I have setup everything according to the documentation. 
I also removed this line 
`serviceWorker.unregister();`
The project is setup with create-react-app. I am not sure if I should use the browser or node configuration. In a small project I have used setup with node configuration using create-react-app and everything works as expected. 

**mocks/server**
```
import { setupServer } from 'msw/node';
import { handlers } from './handlers';

// Setup requests interception using the given handlers.
export default setupServer(...handlers);
```

setupTests
```
import '@testing-library/jest-dom/extend-expect';

// configure msw
import server from './mocks/server';

// Establish API mocking before all tests.
beforeAll(() => {
  // onUnhandledRequest is optional
  server.listen({ onUnhandledRequest: 'warn' });
});

// Reset any request handlers that we may add during the tests,
// so they don't affect other tests.
afterEach(() => server.resetHandlers());

// Clean up after the tests are finished.
afterAll(() => server.close());
```

I have also tried including this chunk
```
// Start the mocking conditionally.
if (process.env.NODE_ENV === 'development') {
  const { worker } = require('./mocks/browser');
  worker.start();
}
```
but made no difference.

## Current behavior

At the moment I am receiving multiple times the following error which implies the same URL without the correct port (8000) comparing to the one I am using
```
console.warn
      [MSW] Warning: captured a request without a matching request handler:
      
        • GET http://localhost/api/favorites/
```

```
  console.error
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/home/kboul/Documents/Apps/earthnetviewer/esa_react/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
          at Request.<anonymous> (/home/kboul/Documents/Apps/earthnetviewer/esa_react/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
          at Request.emit (events.js:326:22)
          at Request.onRequestError (/home/kboul/Documents/Apps/earthnetviewer/esa_react/node_modules/request/request.js:877:8)
          at ClientRequestOverride.emit (events.js:314:20)
          at ClientRequest.<anonymous> (/home/kboul/Documents/Apps/earthnetviewer/esa_react/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/createClientRequestOverride.ts:329:14)
          at ClientRequest.emit (events.js:314:20)
          at Socket.socketErrorListener (_http_client.js:427:9)
          at Socket.emit (events.js:314:20)
          at emitErrorNT (internal/streams/destroy.js:92:8) undefined
```
## Expected behavior

I expect to have logged on the console a list of bookmarks. But rather I get the message No bookmarks found which is the expected message to be displayed once there are no bookmarks (empty list).
## Screenshots

![Screenshot from 2021-04-13 17-08-52](https://user-images.githubusercontent.com/14216599/114566540-10b2dd00-9c7b-11eb-96c2-af05b89074cc.png)

**Comment by kettanaito** [comment]
Hey, @kboul. Thanks for reporting this. 

There's a mismatch between an actual and expected request URL. This likely means that the endpoint you hit in a test does not have the URL you've specified in your request handler.

**Please, could you run `server.printHandlers()` in your test and see the URL of the request handler?** You will see a console log output when you run your test afterward, listing all the active request handlers with their methods and URLs.

I bet that the `baseUrl` constant is somehow not defined, or doesn't equal what you expect it to be. This often happens if you forget to load environmental variables in your test, given your constants depend on them. Based on your info above, I can see that you expect the `baseUrl` to be `http://localhost:8000/api`, but the actual request is made against `http://localhost/api` (implied port `80`, _not_ `8000`). This means that `baseUrl` is an empty string when run in Node.js.

**Comment by kboul** [comment]
Hello kettanaito,

Thank you very much for your response. 

I logged `server.printHandlers()` 

```
import server from '../../../../../mocks/server';

test('async ', async () => {
  renderWithAllProviders(<Topbar {...props} />, reduxState);

  console.log(server.printHandlers());

  const projectSettings = screen.getByLabelText('bookmarks icon');
  userEvent.click(projectSettings);

  const bookmark = await screen.findByText('Seismic - Viewer - 246');
  // console.log(screen.debug());
});
```

and got
```
[rest] POST http://localhost:8000/api/auth/login/

      at node_modules/msw/node/lib/index.js:7687:29
          at Array.forEach (<anonymous>)

    console.log
      [rest] GET http://localhost:8000/api/earthview/main_json/

      at node_modules/msw/node/lib/index.js:7687:29
          at Array.forEach (<anonymous>)

    console.log
      [rest] GET http://localhost:8000/api/exports/

      at node_modules/msw/node/lib/index.js:7687:29
          at Array.forEach (<anonymous>)

    console.log
      [rest] POST http://localhost:8000/api/earthview/set_theme/

      at node_modules/msw/node/lib/index.js:7687:29
          at Array.forEach (<anonymous>)

    console.log
      [rest] GET http://localhost:8000/api/favorites/
```


As you can see `baseUrl` is defined there. It is not an empty string. And keep getting the same error. 
Also I replaced baseUrl variable with the string value of baseUrl at all instances and still the same error. How can this be resolved? Could you please a give a hint how to set the variable when running tests on Node js environment?

**Comment by kettanaito** [comment]
Check your `getBookmarks` method (I assume that's where you make a request). It looks like it doesn't respect the `baseUrl`, performing a request against `localhost:80`.

**Comment by kboul** [comment]
Thank you very much for your help. That was the issue!

Best Regards
