### ISSUE TITLE
requestHandler override isn't immediately used in test

### ISSUE THREAD

**Issue by midanosi** [mswjs/msw#694]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.27.1   |
| node | v12.20.1     |
| OS   | MacOS     |

## Request handlers

```js
// Example of declaration. Provide your code here.
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const server = setupServer(
  graphql.query("Roles", (_req, res, ctx) => res(ctx.data({}))) // return empty object by default
)

server.listen()

```

## Actual request

```js
// apollo useQuery hook
export const ROLES_QUERY = gql`
    query Roles {
        roles
    }
`
const { data, error } = useQuery(ROLES_QUERY)
console.log('data', data)
```

##  test code that fails (using @testing-library/react)

```js
test("some roles query test", () => {
    server.use(
        graphql.query("Roles", (req, res, ctx) =>
            res(
                ctx.data({
                    roles: ["roleA", "roleB"],
                }),
            ),
        ),
    )
  render(<HeaderMenu />)
  // logs data: {}
```

## test code that succeeds

```js
test("some roles query test", async () => {
    server.use(
        graphql.query("Roles", (req, res, ctx) =>
            res(
                ctx.data({
                    roles: ["roleA", "roleB"],
                }),
            ),
        ),
    )
  // only difference here
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms))
  await wait(0)
  // only difference here

  render(<HeaderMenu />)
  // logs data: { roles: ["roleA", "roleB"]}
```

## Current behavior

apollo query returns `data: {}`

## Expected behavior

apollo query to return `data: { roles: ["roleA", "roleB"] }`

## Thoughts + Question

This was a head-scratcher to figure out. Especially as `server.printHandlers()` run directly after server.use() did always indicate the override as succeeding.
Is there a more elegant way to solve this do you think? Or have a better idea of the root cause of why this wait(0) is needed? Has anyone else has run into issues like this?

**Comment by kettanaito** [comment]
Hey, @midanosi. Thanks for reporting this.

Please, could you ensure there is no caching in place when you make the request? Here's how you can [clean cache in Apollo](https://mswjs.io/docs/faq#apollo-client):

```js
// your.test.js
import { client } from './your-apollo-client'

beforeAll(() => {
  client.cache.reset()
})
```

> The latest API may differ, so please double-check with the GraphQL client you're using. 

If the `server.printHandlers()` shows the added handler as the first in the list, then it's active and will affect the traffic. One of the reasons you still see the previous response may be caching. Let's eliminate that and continue debugging, if necessary.

**Comment by midanosi** [comment]
Hi @kettanaito , thanks for your reply.
I believe that I already have caching turned off; this is what I had already
```js
import ApolloClient from "apollo-boost" // 0.4.8
const client = ApolloClient({...})

if (process.env.NODE_ENV === "test") {
    client.defaultOptions = {
        watchQuery: {
            fetchPolicy: "no-cache",
        },
    }
}
```

and also in my jest setup file:
```js
afterEach(() => {
    server.resetHandlers()

    // and clear apollo cache
    client.stop() // https://github.com/apollographql/apollo-client/issues/3766#issuecomment-578075556
    client.clearStore()
})
```
And from your suggestion just now, I tried client.cache.reset() too (both with and without running stop and clearStore functions also). But I still had the same test failing.

For a bit more context, this test file is testing whether a certain header element appears when a certain role string is returned in the roles query. Some tests override graphql.query("Roles", ...), and others don't.

I have some really strange behaviour here, because I realise now that I've written 2 tests that doing the exact same thing - testing that if roles query contains 'roleA', then expect element to be found. And one of the 2 tests is passing, the other not. I found that switching the order of tests would make this one test pass sometimes, which lends credence to it being a caching problem.

We were just about to migrate from apollo v2 to apollo v3 (actually already done, were just waiting for an MR with this migration from apollo MockedProvider -> msw (amongst other things) to go in first. I'll see if this caching problem goes away with any selection of the caching reset functions (will be a few days until get to this at least). And can use my wait(0) hack as a fallback in the meantime.

If that still doesn't resolve the issue, if I can find the time, I could see about making a public codesandbox to replicate the issue

**Comment by kettanaito** [comment]
Can you try running your tests sequentially? If using Jest, use [`--runInBand` option](https://jestjs.io/docs/cli#--runinband). MSW doesn't currently support concurrent runs in Node.js (#474), so if you have multiple tests appending runtime handlers, things may interfere with unrelated tests. 

Also try running both tests _individually_, not as a part of the same test run. Does the second one still fail?

**Comment by midanosi** [comment]
Good questions - I had tried both of these already, but didn't detail this before now, sorry. Using `--runInBand`, 1 of the 2 tests still fail (for completeness, I am using `--maxWorkers=50%` normally). And running each test individually makes both tests pass.
And to verify, I just tried these two things again and got the same results.

**Comment by kettanaito** [comment]
Please set up a reproduction repository for us to look at. Not much can be done without it. Thanks.

**Comment by wtlin1228** [comment]
I have the same issue when I want to override the graphql query. 

```js
// apps/frontend-react-query/src/hooks/__tests__/usePosts.spec.ts

import { renderHook } from '@testing-library/react-hooks';
import { graphql } from 'msw';
import { setupServer } from 'msw/node';
import wrapper from '../../test/wrapper';
import usePosts from '../usePosts';

const mockPosts = [
  {
    message: 'Post 1',
    author: {
      email: '-e1uxQe0vezIwRE5cfSIn',
    },
    id: '3Wa0_kWdPiO9b4kern4uv',
  },
  {
    message: 'Post 2',
    author: {
      email: '-e1uxQe0vezIwRE5cfSIn',
    },
    id: 'pi_MSRZVwicgSSWqPM_wv',
  },
];

const server = setupServer(
  graphql.query('Posts', (req, res, ctx) => {
    return res(
      ctx.data({
        posts: mockPosts,
      })
    );
  })
);

beforeAll(() => {
  server.listen();
});

afterAll(() => {
  server.close();
});

test('should get posts', async () => {
  const { result, waitFor } = renderHook(() => usePosts(), { wrapper });

  await waitFor(() => result.current.isSuccess);

  expect(result.current.data).toEqual(mockPosts);
});

test('should get errors', async () => {
  server.use(
    graphql.query('Posts', (req, res, ctx) => {
      return res(ctx.status(500, 'There is Error'));
    })
  );

  const { result, waitFor } = renderHook(() => usePosts(), { wrapper });

  await waitFor(() => result.current.isError);

  // expect isError will be true, but it's false
  // expect isSuccess is false but it's true, and receive the mockPosts
  console.log(result.current);

  expect(result.current.error).toEqual('There is Error');
});

```

This is my repo: https://github.com/wtlin1228/nx-graphql-fullstack

Steps for reproduction:
1. `$ npm i`
2. `$ npm run test frontend-react-query` (There is only one test for frontend-react-query now)

**Comment by wtlin1228** [comment]
I'm sorry, there is no bug. My tests wait for the wrong value.

**Comment by midanosi** [comment]
It took a month, but I attempted to make a reproduction. Can be found here: https://github.com/midanosi/msw_repro_694

Key word; _attempted_. I tried doing everything as similarly as possible to the codebase I originally came across it in... but the tests always pass, and I didn't come across anything that would help me guess what is causing it.

By the few thumbs up on this ticket, does seem like there are others coming across this problem though. **I think it'd be good if others getting the same bug could detail similarities/differences to my setup to figure out where the problem lies.** e.g. is anyone having this problem with rest, or is it only graphql? different node versions?

I'm annoyed that I can't be of more help! To others attempting to reproduce, feel welcome to use my repository as a base if you think that would be helpful.

**Comment by sebinsua** [comment]
I had a similar issue where it seemed like `.use` didn't work and the previous requests were being used. But, it turned out that this was nothing to do with `msw` and was happening because [`recoil` doesn't support clearing the cache](https://github.com/facebookexperimental/Recoil/issues/972#issuecomment-841848081). Just mentioning this in case there are other people like myself going down rabbit holes...

**Comment by kettanaito** [comment]
@midanosi, could you please confirm that you're correctly resetting the Apollo cache after each test? Otherwise, Apollo may respond with obsolete data that is different from what you've defined in your mocks.

```js
// test/my.test.js
import { client } from './your/apollo/client'

afterEach(() => {
  client.cache.reset()
})
```

**Comment by midanosi** [comment]
> @midanosi, could you please confirm that you're correctly resetting the Apollo cache after each test? Otherwise, Apollo may respond with obsolete data that is different from what you've defined in your mocks.
> 
> ```js
> // test/my.test.js
> import { client } from './your/apollo/client'
> 
> afterEach(() => {
>   client.cache.reset()
> })
> ```

Yes, I'm afraid I was already doing this.
And I had code to account for old and new versions of Apollo. Code seen here in my attempted_reproduction git repo, is the same as what I had when I raised this ticket https://github.com/midanosi/msw_repro_694/blob/main/src/setupTests.js

Tbh with so many other unrelated and obscure issues with Apollo I've had over the past year, I wouldn't be so surprised if this is entirely an Apollo problem.

**Comment by kettanaito** [comment]
You can see the list of all request handlers by running `server.listHandlers()` _before_ you make the request in your rest:

```js
const server = setupServer(initialHandlers)

it('test', () => {
  server.use(runtimeHandler)
  server.listHandlers()
  makeRequest()
})
```

If you see the request override in the printed list, then it's unlikely to be an MSW issue. If you don't, then something is not right with the library, or setup.

Could you please try listing the handlers and post what you see here?

**Comment by agiveygives** [comment]
I was able to reproduce the issue here using swr and msw https://github.com/agiveygives/msw-runtime-handler-issue

It will pass about 50% of the time.

<details>
  <summary>Here are the two api responses and handler lists</summary>

### using the initially configured handlers
  
  ```
console.log
    undefined

      at App (src/App.tsx:21:11)

  console.log
    [rest] GET https://pokeapi.co/api/v2/pokemon
      Declaration: C:\Users\andrewg\Desktop\Projects\msw-cache-issue\src\__mocks__\msw\handlers.ts:7:8

      at node_modules/msw/node/lib/index.js:7780:29
          at Array.forEach (<anonymous>)

  console.log
    [rest] GET https://pokeapi.co/api/v2/pokemon/:pokeName
      Declaration: C:\Users\andrewg\Desktop\Projects\msw-cache-issue\src\__mocks__\msw\handlers.ts:13:8

      at node_modules/msw/node/lib/index.js:7780:29
          at Array.forEach (<anonymous>)

  console.log
    [rest] GET *
      Declaration: C:\Users\andrewg\Desktop\Projects\msw-cache-issue\src\__mocks__\msw\handlers.ts:19:8

      at node_modules/msw/node/lib/index.js:7780:29
          at Array.forEach (<anonymous>)

  console.log
    undefined

      at Object.<anonymous> (src/__tests__/App.test.tsx:20:13)

  console.log
    {
      count: 1118,
      next: 'https://pokeapi.co/api/v2/pokemon?offset=10&limit=10',
      previous: null,
      results: [
        { name: 'bulbasaur', url: 'https://pokeapi.co/api/v2/pokemon/1/' },
        { name: 'ivysaur', url: 'https://pokeapi.co/api/v2/pokemon/2/' },
        { name: 'venusaur', url: 'https://pokeapi.co/api/v2/pokemon/3/' },
        { name: 'charmander', url: 'https://pokeapi.co/api/v2/pokemon/4/' },
        { name: 'charmeleon', url: 'https://pokeapi.co/api/v2/pokemon/5/' },
        { name: 'charizard', url: 'https://pokeapi.co/api/v2/pokemon/6/' },
        { name: 'squirtle', url: 'https://pokeapi.co/api/v2/pokemon/7/' },
        { name: 'wartortle', url: 'https://pokeapi.co/api/v2/pokemon/8/' },
        { name: 'blastoise', url: 'https://pokeapi.co/api/v2/pokemon/9/' },
        { name: 'caterpie', url: 'https://pokeapi.co/api/v2/pokemon/10/' }
      ]
    }

      at App (src/App.tsx:21:11)
  ```

 ### using the runtime handler

```
console.log
    undefined

      at App (src/App.tsx:21:11)

  console.log
    [rest] GET https://pokeapi.co/api/v2/pokemon
      Declaration: C:\Users\andrewg\Desktop\Projects\msw-cache-issue\src\__tests__\App.test.tsx:38:12

      at node_modules/msw/node/lib/index.js:7780:29
          at Array.forEach (<anonymous>)

  console.log
    [rest] GET https://pokeapi.co/api/v2/pokemon
      Declaration: C:\Users\andrewg\Desktop\Projects\msw-cache-issue\src\__mocks__\msw\handlers.ts:7:8

      at node_modules/msw/node/lib/index.js:7780:29
          at Array.forEach (<anonymous>)

  console.log
    [rest] GET https://pokeapi.co/api/v2/pokemon/:pokeName
      Declaration: C:\Users\andrewg\Desktop\Projects\msw-cache-issue\src\__mocks__\msw\handlers.ts:13:8

      at node_modules/msw/node/lib/index.js:7780:29
          at Array.forEach (<anonymous>)

  console.log
    [rest] GET *
      Declaration: C:\Users\andrewg\Desktop\Projects\msw-cache-issue\src\__mocks__\msw\handlers.ts:19:8

      at node_modules/msw/node/lib/index.js:7780:29
          at Array.forEach (<anonymous>)

  console.log
    undefined

      at Object.<anonymous> (src/__tests__/App.test.tsx:61:13)

  console.log
    {
      count: 1118,
      next: 'https://pokeapi.co/api/v2/pokemon?offset=10&limit=10',
      previous: null,
      results: [
        { name: 'bulbasaur', url: 'https://pokeapi.co/api/v2/pokemon/1/' },
        { name: 'ivysaur', url: 'https://pokeapi.co/api/v2/pokemon/2/' },
        { name: 'venusaur', url: 'https://pokeapi.co/api/v2/pokemon/3/' },
        { name: 'charmander', url: 'https://pokeapi.co/api/v2/pokemon/4/' },
        { name: 'charmeleon', url: 'https://pokeapi.co/api/v2/pokemon/5/' },
        { name: 'charizard', url: 'https://pokeapi.co/api/v2/pokemon/6/' },
        { name: 'squirtle', url: 'https://pokeapi.co/api/v2/pokemon/7/' },
        { name: 'wartortle', url: 'https://pokeapi.co/api/v2/pokemon/8/' },
        { name: 'blastoise', url: 'https://pokeapi.co/api/v2/pokemon/9/' },
        { name: 'caterpie', url: 'https://pokeapi.co/api/v2/pokemon/10/' }
      ]
    }

      at App (src/App.tsx:21:11)
```
</details>

**Comment by Elliot128** [comment]
Running into this issue as shown in @agiveygives's reproduction as well. Cannot do handler overrides in jest tests because of this.

**Comment by kettanaito** [comment]
While we're looking into the reproduction repository, try swapping `swr` with `fetch` to see if the intermittent responses aren't the request client's issue.

**Comment by agiveygives** [comment]
I could not reproduce the issue with fetch, and I did find an [issue on swr that was closed with a resolution on July 22nd](https://github.com/vercel/swr/issues/781#issuecomment-885146139). I tested with the resolution in their docs ( https://swr.vercel.app/docs/advanced/cache#reset-cache-between-test-cases ), and did not have any issues after implementing that.

For those that don't want to click links, add an empty provider to your SWRConfig for tests:
```
describe('test suite', async () => {
  it('test case', async () => {
    render(
      <SWRConfig value={{ provider: () => new Map() }}>
        <App/>
      </SWRConfig>
    )
  })
})
```

**Comment by kettanaito** [comment]
Please setup SWR accordingly to prevent shared state (in this case cache) between tests.
