### ISSUE TITLE
Browser stuck when including a CDN prod build web component in Angular project 

### ISSUE THREAD

**Issue by jrumandal** [mswjs/msw#701]
## Describe the bug
When including a remote script containing a prod build of an Angular web component while running msw, browser freezes.

## Environment

- `msw: 0.28.0`
- `nodejs: 10.16.3`
- `npm: 6.9.0`

> Google Chrome 88

## To Reproduce
1. Setup your msw as per guidelines and run it by including this script into `environment.ts`:
```typescript
// browser.ts
import { setupWorker, rest } from 'msw'
const worker = setupWorker(
  rest.post('/login', (req, res, ctx) => {
    const { username } = req.body
    return res(
      ctx.json({
        username,
        firstName: 'John'
      })
    )
  }),
)
worker.start({
  serviceWorker: {
    url: '...'
  }
});

export default { worker };

// environment.ts
import 'browser.ts';
```
2. Consume your hypothetical custom element tag inside a template and build angular in production, including msw
3. Include a generic web component/custom element prod build written in Angular as per [guideline](https://angular.io/guide/elements)
```html
<html>
<body>
  <script src="dist/main.bundle.js"></script>
  ...
  <script src="asset/web-component.bundle.ts"></script>
</body>
</html>
```

## Expected behavior
Behave normally without any performance or scripting issues.

**Comment by kettanaito** [comment]
Hey, @jrumandal. Thanks for reaching out.

Please set up a reproduction repository for this issue so we could look into it. Thanks.

**Comment by kettanaito** [comment]
It's been more than a week, so I deem this issue as either resolved or not an issue. I'm happy to look into it once the reproduction repository is provided. Thanks.
