### ISSUE TITLE
`TypeError [ERR_INVALID_URL]: Invalid URL: [object Object]` for requests not made with an `URL` object

### ISSUE THREAD

**Issue by lauraseidler** [mswjs/msw#705]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.28.1   |
| node | 15.14.0     |
| OS   | Debian     |

## Request handlers

```js
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const server = setupServer(
  rest.get('https://github.com', (req, res, ctx) => {
        return res(ctx.status(200));
    })
)

server.listen()
```

## Actual request

```js
import Wreck from '@hapi/wreck';

const request = async () => {
    return await Wreck.get('https://github.com');
}
```

## Current behavior
Requests made in application code that don't use the `URL` object can't be mocked, and cause an `Invalid URL` error:
```
    TypeError [ERR_INVALID_URL]: Invalid URL: [object Object]
        at new NodeError (node:internal/errors:329:5)
        at onParseError (node:internal/url:537:9)
        at new URL (node:internal/url:613:5)
        at CookieStore.get (/srv/node_modules/msw/node/lib/index.js:7404:28)
        at setRequestCookies (/srv/node_modules/msw/node/lib/index.js:7550:109)
        at /srv/node_modules/msw/node/lib/index.js:7609:21
        at Generator.next (<anonymous>)
        at /srv/node_modules/msw/node/lib/index.js:53:71
        at new Promise (<anonymous>)
        at __awaiter (/srv/node_modules/msw/node/lib/index.js:49:12) {
      input: '[object Object]',
      code: 'ERR_INVALID_URL',
      trace: [ { method: 'GET', url: 'https://github.com' } ]
    }
```

## Expected behavior

Requests somewhat comforming to the structure of an `URL` object can be mocked as well.

## Details

In my example, I'm using the `Wreck` module provided by Hapi to make HTTP requests. This causes the follow chain of events:
- Wreck [uses a simple object](https://github.com/hapijs/wreck/blob/master/lib/index.js#L96) to construct the `url` of the `request` (instead of the native `URL`)
- since msw calls `.toString` when [setting request cookies](https://github.com/mswjs/msw/blob/1562bfc901c930bffc8c5eb150bb855b54020676/src/utils/request/setRequestCookies.ts#L10) and [reading response cookies](https://github.com/mswjs/msw/blob/1562bfc901c930bffc8c5eb150bb855b54020676/src/utils/request/readResponseCookies.ts#L9), this causes the above mentioned error

This could be fixed by using `request.url.href` instead of `request.url.toString()`, which also seems to be the behaviour of calling `toString` on a standard `URL` object.

I'll be happy to provide a PR for this, but there might be a better way to support this (or it might not be desired to do so).

**Comment by kettanaito** [comment]
Hey, @lauraseidler. Thank you for raising this, and especially for a detailed investigation of why the issue occurs!

If the `url` module aims to be compatible with the native `URL` class, I'd say it's an issue on their side, as `.toString()` should return a read-only value of `url.href`:

> The `URL.toString()` stringifier method returns a `USVString` containing the whole URL. It is effectively a read-only version of `URL.href`.
> —[MDN: URL.toString()](https://developer.mozilla.org/en-US/docs/Web/API/URL/toString)

This means that both `url.toString()` and `url.href` must equal the same value, that being a full stringified URL. 

I've set up a [reproduction repository](https://github.com/kettanaito/url-to-string-issue) to see how `url` package behaves, and it seems to be compatible with the aforementioned behavior:

```js
const { URL: CustomURL } = require('url')

it('result of "url.toString()" equals to "url.href"', () => {
  const url = new CustomURL('https://example.com/?id=123')
  expect(url.toString()).toEqual(url.href) // OK
})
```

It must be something else in place. Can it be the `Wreck` module that augments the constructed URL somehow? It's always possible that we are not handling the stringified URL properly as well, but I wonder what circumstances make this issue surface.

**Comment by lauraseidler** [comment]
Hi @kettanaito,

sorry, I've amended the issue in the meantime - I dug a bit deeper and think it doesn't have to do with `url` after all - sorry, I didn't think anyone was gonna look at it this quickly, or I would've posted it as an update :)

**Comment by kettanaito** [comment]
No worries! 

Can you please confirm that `req.url` is a plain object and not the `URL` instance on this line?

https://github.com/mswjs/msw/blob/1562bfc901c930bffc8c5eb150bb855b54020676/src/utils/request/setRequestCookies.ts#L10

If that's the case, this means that our node interception doesn't handle the request URL properly. Here's the journey request takes before landing in `setRequestCookies`:

1. [interceptors](https://github.com/mswjs/interceptors) library intercepts a request.
2. The said library send the intercepted request to MSW, `req.url` must already be a `URL` instance:

https://github.com/mswjs/msw/blob/1562bfc901c930bffc8c5eb150bb855b54020676/src/node/createSetupServer.ts#L52

> Here's [the logic](https://github.com/mswjs/interceptors/blob/16fd35622efe6328497ade15e21a84f6afda0a93/src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts#L44) of how intercepted `ClientRequest` instances are handled in Node.js. I assume what `Wreck` uses `http`/`https` to make a request, which results in the `ClientRequest` instance.

It may also help to run your test with the `DEBUG` environmental variable and share what request processing info you see:

```sh
$ DEBUG=* npm test
```

We are specifically interested in what [this log](https://github.com/mswjs/interceptors/blob/16fd35622efe6328497ade15e21a84f6afda0a93/src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts#L149) prints out.

**Comment by lauraseidler** [comment]
The output of that log is the following:
```
  http normalizeHttpRequestParams resolved URL: {
  setHost: false,
  host: 'github.com',
  origin: 'https://github.com',
  searchParams: URLSearchParams {},
  protocol: 'https:',
  hostname: 'github.com',
  hash: '',
  search: '',
  pathname: '/',
  path: '/',
  href: 'https://github.com/',
  method: 'GET',
  headers: { host: 'github.com' },
  agent: Agent {
    _events: [Object: null prototype] {
      free: [Function (anonymous)],
      newListener: [Function: maybeEnableKeylog]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    defaultPort: 443,
    protocol: 'https:',
    options: { maxSockets: Infinity, path: null },
    requests: {},
    sockets: {},
    freeSockets: {},
    keepAliveMsecs: 1000,
    keepAlive: false,
    maxSockets: Infinity,
    maxFreeSockets: 256,
    scheduling: 'lifo',
    maxTotalSockets: Infinity,
    totalSocketCount: 0,
    maxCachedSessions: 100,
    _sessionCache: { map: {}, list: [] },
    [Symbol(kCapture)]: false
  }
} +0ms
```
This looks like a standard object to me that just somewhat looks like an `URL`, but not quite. 

Looking at the source code for `Wreck`, I think you are correct. The "url" is constructed with an empty object:
https://github.com/hapijs/wreck/blob/88fbe15b05a873b2c364a73e17a92805a56689b3/lib/index.js#L96

Then a bunch of properties are applied to this object, and it's at the end passed to `request` from `http`/`https`:
https://github.com/hapijs/wreck/blob/88fbe15b05a873b2c364a73e17a92805a56689b3/lib/index.js#L154
https://github.com/hapijs/wreck/blob/88fbe15b05a873b2c364a73e17a92805a56689b3/lib/index.js#L181

I suppose the easiest for this particular problem would be to implement a `toString` on the object constructed by Wreck.

However, e.g. `https` accepts either a string, a `URL` or an arbitrary `Object` (which looks to be a `URL` with extra parameters, but then missing e.g. the `toString` from `URL`): https://nodejs.org/api/https.html#https_https_request_url_options_callback, so it would also seem reasonable for msw to also support those.

**Comment by kettanaito** [comment]
I believe that looks like `RequestParams` object constructed by `Wreck`. It's _very_ strange that "interceptors" doesn't determine it as such and derives a URL instance from it (that's how it handles regular `RequestParams` that are used to make a request). Huh, once again, myriad ways to construct a request in Nodejs.

**Comment by lauraseidler** [comment]
I think what happens is that this condition is `true`:

https://github.com/mswjs/interceptors/blob/16fd35622efe6328497ade15e21a84f6afda0a93/src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts#L70

also supported by debug logs:
```
http normalizeHttpRequestParams given a URL: {
  setHost: false,
  host: 'github.com',
  origin: 'https://github.com',
  searchParams: URLSearchParams {},
  protocol: 'https:',
  hostname: 'github.com',
  hash: '',
  search: '',
  pathname: '/',
  path: '/',
  href: 'https://github.com/',
  method: 'GET',
  headers: { host: 'github.com' },
  agent: Agent {
    _events: [Object: null prototype] {
      free: [Function (anonymous)],
      newListener: [Function: maybeEnableKeylog]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    defaultPort: 443,
    protocol: 'https:',
    options: { maxSockets: Infinity, path: null },
    requests: {},
    sockets: {},
    freeSockets: {},
    keepAliveMsecs: 1000,
    keepAlive: false,
    maxSockets: Infinity,
    maxFreeSockets: 256,
    scheduling: 'lifo',
    maxTotalSockets: Infinity,
    totalSocketCount: 0,
    maxCachedSessions: 100,
    _sessionCache: { map: {}, list: [] },
    [Symbol(kCapture)]: false
  }
} +0ms
```
So the interceptor assumes if `origin` is present, it's a `URL`, and doesn't process it further?

**Comment by lauraseidler** [comment]
I've been able to reproduce this by adding an `origin` to one of the tests for this functionality - I've opened a tentative PR to fix this - though I'm not sure why the check was done on the `origin` field to begin with, so I might be missing something.

**Comment by lauraseidler** [comment]
Ah my bad, I made this close with the PR - I think it'll need a release of msw with the new version of the interceptors too to actually be "fixed" here?

**Comment by kettanaito** [comment]
No worries! We can bump the "interceptors" version in a new pull request here and add it to the next release.

**Comment by lauraseidler** [comment]
Sure, I can take care of that (the PR at least)

**Comment by tara-encora** [comment]
Getting this when mocking the api
TypeError: Invalid URL
        at new NodeError (node:internal/errors:399:5)
        at URL.onParseError (node:internal/url:566:9)
        at new URL (node:internal/url:646:5)
        at new URL (node:internal/url:643:22)
