### ISSUE TITLE
Possible memory leak in nodejs interception

### ISSUE THREAD

**Issue by mathanpec** [mswjs/msw#710]
## Describe the bug

I have a [simple repo](https://github.com/mathanpec/msw-memory-leak-test) with 16 test files where every test file does the same thing of firing a simple fetch call and asserting for the response from the MSW handler. But when we run all the test files one after the other the heap usage keeps increasing. But when I comment the MSW server instantiation and other MSW related code heap memory stays constant.

<img width="811" alt="Screenshot 2021-04-26 at 7 23 24 PM" src="https://user-images.githubusercontent.com/6211920/116099540-b2015080-a6c9-11eb-9f01-ef0f911047d3.png">

## Environment

- `msw: 0.28.2`
- `nodejs: v12.14.0`
- `npm: 6.13.4`

> Please also provide your browser version.

## To Reproduce
1. Clone the repo `https://github.com/mathanpec/msw-memory-leak-test`
2. Do `yarn install`
3. Execute `node --expose-gc ./node_modules/.bin/jest --silent --runInBand --detectOpenHandles --logHeapUsage`
4. I am specifically doing `node --expose-gc` and running GC in the AfterAll step to make sure there are no unused memory is left between test files.

## Expected behavior
Memory heap should be consistent between every file runs or there should be a very minimal change. Check the following screenshot from the same repo without MSW server initialisation and handlers

![image](https://user-images.githubusercontent.com/6211920/116100937-0822c380-a6cb-11eb-982b-6f27538b42a0.png)

**Comment by kettanaito** [comment]
Thank you for reporting this, @mathanpec! 

Please, do you have any insights as to where the memory heap originates from within MSW? Any help on this matter is highly appreciated.

**Comment by marcosvega91** [comment]
I have experienced the same issue some time ago when I was testing monkey patching.

**Comment by mathanpec** [comment]
Hi @kettanaito,

So I tried profiling the runs and this is what I could find,

![image](https://user-images.githubusercontent.com/6211920/116143032-3c60a900-a6f8-11eb-96c3-d4a003786722.png)

You can see `ClientRequestOverride` is being referenced recursively and when I looked at the code, `http.ClientRequest` is being monkey patched [here](https://github.com/mswjs/interceptors/blob/16fd35622efe6328497ade15e21a84f6afda0a93/src/interceptors/ClientRequest/index.ts#L47) but its not being set back to the original reference anywhere. This could be one possible cause but I am not very sure though.

**Comment by kettanaito** [comment]
That's a great observation, @mathanpec! I've opened a related issue in the interceptors repository. I think the fix should be straightforward—restore the patched version to the already stored original class. 

Please, would you be interested in making such a pull request happen?

**Comment by mathanpec** [comment]
Hi @kettanaito,

I did try restoring the patch version to the already stored original class. But still I am seeing heap memory is increasing consistently as shown in the image below though previous recursive `ClientRequestOverride ` is not showing up in the heap profile run.

![image](https://user-images.githubusercontent.com/6211920/116268977-6c14bd00-a79b-11eb-937f-092fb090cdd7.png)

And in the heap profile I couldn't find anything recursive now but I could see multiple copies of the same msw index file in memory as shown below. But I am not sure whether it is very relevant to the issue.

<img width="1122" alt="Screenshot 2021-04-27 at 9 01 55 PM" src="https://user-images.githubusercontent.com/6211920/116269773-1d1b5780-a79c-11eb-86b2-615033ca6afd.png">

**Comment by mathanpec** [comment]
Hi @kettanaito,

As mentioned in this [issue comment](https://github.com/mswjs/interceptors/issues/115#issuecomment-827923694), I tried removing the monkey patching of `clientRequest`  completely in the interceptor library and after that my heap memory usage stays constant now as in the below image,

![image](https://user-images.githubusercontent.com/6211920/116313350-49020180-a7cb-11eb-8588-2644dfa48a1f.png)

PR for the same: https://github.com/mswjs/interceptors/pull/116

**Comment by mathanpec** [comment]
Hi @kettanaito,

Can you pls take a look into this and let me know your thoughts on this?

**Comment by kettanaito** [comment]
Hey, @mathanpec. I've commented on the pull request. Will have to check it out and get back to you. Thank you for your work on this, it looks great!

**Comment by mathanpec** [comment]
Hi @kettanaito,

Thanks for looking into this and closing on this :) And Thanks a lot for this excellent library.

Also would be able to tell approximately when can we expect this fix to get released?

**Comment by kettanaito** [comment]
Thank you for the contribution, @mathanpec!
This fix should be released alongside #688, as both introduce breaking changes and I'd like to get it into a single minor version bump. Hope to get that done by the end of the month.
