### ISSUE TITLE
`get` request handler contains old version of changed object

### ISSUE THREAD

**Issue by corocoto** [mswjs/msw#711]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | ^0.19.5   |
| node | 14.16.0     |
| OS   | macOS BigSur 11.2.3     |

## Request handlers

```js
// handlers.js
import {rest} from 'msw';
import dataSchemas from '../fixtures/dataSchemas.json';
import dataSchemaFormPage from '../fixtures/dataSchemaFormPage.json';

const {
  DIONA_DATA_SCHEMAS,
  DIONA_DATA_SCHEMA_FORM_PAGE,
  DIONA_DATA_SCHEMA_FORM_PAGE_NOTE
} = APP_CONFIG;

const newDataSchemasObject = dataSchemas;

export const handlers = [
  rest.get(
    `${DIONA_DATA_SCHEMAS}?limit=null&expand=created_by`,
    (req, res, ctx) => {
      return res(ctx.json(newDataSchemasObject));
    }
  ),
  rest.patch(
    `${DIONA_DATA_SCHEMA_FORM_PAGE_NOTE({
      uuid: dataSchemaFormPage.note.uuid
    })}`,
    (req, res, ctx) => {
      const editNoteIndex = newDataSchemasObject.results
        .findIndex(note => note.uuid === dataSchemaFormPage.note.uuid);

      newDataSchemasObject.results[editNoteIndex] = {
        ...newDataSchemasObject.results[editNoteIndex],
        ...req.body
      };
      return res(ctx.json(req.body));
    }
  )
];
```

## Current behavior

`get` request is running after `patch` request. And when `get` is running, I get the old version of `newDataSchemasObject`.

## Expected behavior

I'm waiting to get the new version of `newDataSchemasObject`, because it changed inside of `patch` request handler.

## Screenshots

* Inside patch request handler (please, looking on the `name` property):

![image](https://user-images.githubusercontent.com/37180024/116235180-34d7e900-a766-11eb-8287-12e4ff12683e.png)

* Inside get request handler (also looking on the `name` property):

![image](https://user-images.githubusercontent.com/37180024/116236584-e6c3e500-a767-11eb-9076-818b51396113.png)

**Comment by kettanaito** [comment]
Hey, @corocoto. Thanks for reporting this.

Can you please include how you are making the actual requests? Ideally, have a reproduction repository with such a test for us to look at. Thanks.

**Comment by corocoto** [comment]
@kettanaito, I could find the solution for this case. 

The idea of this solution next:
1. Creating the `class` that includes method for changing it's own variable. The variable that we do some manipulations contains `dataSchemas` (`newDataSchemasObject`) object.
2. Creating the instance of this `class` and import it inside of test file. So, for my case, it needs for doing snapshot old version of instance (before we going into request handler) and compare it with new version (after when request is done).


So... The solution looks like this:

```js
import { rest } from 'msw';
import _ from 'lodash';
import dataSchemas from '../fixtures/dataSchemas.json';
import dataSchemaFormPage from '../fixtures/dataSchemaFormPage.json';

class DataSchemasMockService {
  constructor(data) {
    this.dataSchemas = data;
  }

  getData() {
    return this.dataSchemas;
  }

  updateResultsNoteName(uuid, name) {
    const note = _.find(this.dataSchemas.results, { uuid });
    note.name = name;
  }
}

export const dataSchemasMockService = new DataSchemasMockService(
  _.cloneDeep(dataSchemas)
);

const {
  DIONA_DATA_SCHEMAS,
  DIONA_DATA_SCHEMA_FORM_PAGE,
  DIONA_DATA_SCHEMA_FORM_PAGE_NOTE
} = APP_CONFIG;

export const handlers = [
  rest.get(
    `${DIONA_DATA_SCHEMAS}?limit=null&expand=created_by`,
    (req, res, ctx) => {
      const result = dataSchemasMockService.getData();
      return res(ctx.json(result));
    }
  ),
  rest.patch(
    `${DIONA_DATA_SCHEMA_FORM_PAGE_NOTE({
      uuid: dataSchemaFormPage.note.uuid
    })}`,
    (req, res, ctx) => {
      dataSchemasMockService.updateResultsNoteName(
        dataSchemaFormPage.note.uuid,
        req.body.name
      );
      return res(ctx.json(req.body));
    }
  )
];
```

@kettanaito, the main question that addressed to you. Should I drop the source code of test and information about how I'm making the actual requests?

**Comment by kettanaito** [comment]
Based on what you've shared, this is a question about how you handle the fixtures and their mutations and has nothing to do with the library. You can skip posting the reproduction repository, I don't think there's an issue to tackle here. 

To be clear: MSW is responsible for calling a response resolver whenever a matching request occurs. Your custom logic related to which fixtures you use, and whether their state changes or persists properly, is outside of the library's responsibility. It doesn't interfere, in other words, so any issue around that is likely an issue on the user's side.
