### ISSUE TITLE
proxy failed when using testing-library to test react App by window.fetch API

### ISSUE THREAD

**Issue by demongodYY** [mswjs/msw#714]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.28.2   |
| node | 14.4.0     |
| OS   | macOS 11.1 |    |
| jest | 26.6.3|
| testing-libarary/react | 11.2.6 | 

## Request handlers

```ts
//server.ts

import { rest } from 'msw';
import { setupServer } from 'msw/node';
const DATA_BASE_URL = '/api/data';

const handlers = [
  rest.get(`${DATA_BASE_URL}/tag/list`, async (req, res, ctx) => {
    const tags = [
      { id: '1', content: '苹果', type: 'recommand' },
      { id: '2', content: '汽车', type: 'recommand' },
      { id: '3', content: '电动汽车', type: 'recommand' },
      { id: '4', content: '香蕉', type: 'recommand' }
    ];
    return res(ctx.json(tags));
  })
];

const server = setupServer(...handlers);
export { server, rest };
```

```ts
//test-env.ts

import '@testing-library/jest-dom/extend-expect';
import 'fetch-reply-with';
import { server } from './server';

beforeAll(() => server.listen());

afterEach(() => server.resetHandlers());
afterAll(() => server.close());

```

## Actual request

```ts
const rRequest = async (url: string, config: any = {}) => {
  const defaultConfig = {
    headers: new Headers({
      'Content-Type': 'application/json'
    })
  };

  // const res = await fetch(url, R.merge(defaultConfig, config));   // when I use this line it will be get something wrong
  const res = await axios(url, R.merge(defaultConfig, config));   // this line is working
}
```

```ts
  it('Tags Search test', async () => {
    render(
      <Provider store={store}>
        <TagsSearchCard word="苹果" />
      </Provider>
    );
    expect(await screen.findByText(/苹果/i)).toBeInTheDocument();
  });
```

```ts
export default (props: ITagSearchCard) => {
  const { word } = props;
  const dispatch = useDispatch();
  const [tags, setTags] = useState([]);
  const searchTags = async (word: string) => {
    const res: any = await dispatch(fetchTagByWord(word));
    setTags(res);
  };
  useEffect(() => {
    searchTags(word);
  }, []);

  return <TagsCard tags={tags} />;
};
```

## Current behavior

I use msw in the testing-libarary/react with jest to test my React App like [example](https://github.com/mswjs/examples/tree/master/examples/rest-react). But when I use `window.fetch` in my component, it says `window.fetch` is `undefined`.

I tryied use library [fetch-reply-with](https://www.npmjs.com/package/fetch-reply-with) to fixed it. But it will to connect my server without msw.

I can use axios to resolved it now. But I want to konw how to use `window.fetch` in my code and using jest to test it by msw mock?

## Screenshots
if using `const res = await fetch(url, R.merge(defaultConfig, config));` like this: 

![image](https://user-images.githubusercontent.com/17036920/116339574-3eb62680-a810-11eb-9cee-da17df2265a9.png)

if using `const res = await axios(url, R.merge(defaultConfig, config)); ` like this:

![image](https://user-images.githubusercontent.com/17036920/116340048-10851680-a811-11eb-931f-394becb06d90.png)

**Comment by demongodYY** [comment]
I found `fetch` is working by using create-react-app, then I found this [polyfill](https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/jsdom.js).

I resolved this problem by add this in test-env file: 

```ts
import '@testing-library/jest-dom/extend-expect';
import { server } from './server';

if (typeof window !== 'undefined') {
  // fetch() polyfill for making API calls.
  require('whatwg-fetch');
} // https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/jsdom.js

beforeAll(() => server.listen());

afterEach(() => server.resetHandlers());
afterAll(() => server.close());

```

**Comment by kettanaito** [comment]
Hi, @demongodYY.

`fetch` doesn't exist in Node.js, you need to use a polyfill. CRA comes with a polyfill, but your custom setup needs it explicitly. 

I recommend using `whatwg-fetch` (used by CRA), or any other spec-compatible polyfill.

**Comment by demongodYY** [comment]
> whatwg-fetch

Thanks.

**Comment by demongodYY** [comment]
> Hi, @demongodYY.
> 
> `fetch` doesn't exist in Node.js, you need to use a polyfill. CRA comes with a polyfill, but your custom setup needs it explicitly.
> 
> I recommend using `whatwg-fetch` (used by CRA), or any other spec-compatible polyfill.

Thanks @kettanaito, I fixed it~
