### ISSUE TITLE
responseXML is null when returning valid xml

### ISSUE THREAD

**Issue by rrogowski** [mswjs/msw#715]
## Describe the bug
When intercepting an `XMLHttpRequest` in NodeJS, the mock resolver responds with valid XML, but the `responseXML` field on the XMLHttpRequest request object is `null`.

For example, given the following mock resolver:
```typescript
rest.get('*', (_, res, ctx) => {
  return res(ctx.xml('<node key="value">Content</node>'));
});
```

the corresponding XHR object looks as follows:
```javascript
XMLHttpRequestOverride {
  [...snip...]
  response: '<node key="value">Content</node>',
  responseType: 'text',
  responseText: '<node key="value">Content</node>',
  responseXML: null,
  responseURL: '',
  [...snip...]
}
```

I was wondering if this is actually an issue with some dependency of this library, rather than a bug with `msw` itself. If so, please help point me in the right direction!

## Environment

- `msw: 0.28.2`
- `nodejs: 12.13.0`
- `npm: 6.12.0`

> Please also provide your browser version.

## To Reproduce
1. Intercept any REST HTTP request in NodeJS.
2. Return a valid XML response, such as:
	```javascript
	return res(ctx.xml(myXmlString));
	```
3. Observe that `responseXML` on the XHR object is `null`.

## Expected behavior
The `responseXML` field should be a `Document` object when valid XML is returned.

## Screenshots
N/A

**Comment by rrogowski** [comment]
After some digging, I think this may be a bug in https://github.com/mswjs/interceptors. Perhaps a maintainer of this project can confirm? I may submit a PR to address this.

**Comment by kettanaito** [comment]
Hey, @rrogowski. Thank you for reporting this. That's indeed an issue. You're correct to conclude that it's an issue in the "interceptors" repository. Thank you for opening a pull request! It's great. I've reviewed it and left some questions.

**Comment by kettanaito** [comment]
The issue has been fixed by @rrogowski and will be released in the next version of "interceptors". Update on the MSW side will follow. Thank you for your contribution!

**Comment by kettanaito** [comment]
This is extremely funny in hindsight because `happy-dom`, and I suspect `jsdom` as well, do not implement proper XML response parsing and return `null`:

```ts
const request = new XMLHttpRequest()
request.open('POST', server.http.url('/xml'))
request.setRequestHeader('content-type', 'application/xml')
request.send('<node key="value">Content</node>')

reques.onload = () => {
  console.log(request.response) // XML string
  console.log(request.responseXML) // always null
}
```

But people expected MSW to fix that behavior, and we did. We won't be doing that anymore in the future versions of the library. If you happened to use a broken environment, all its ugly pieces will float to the surface since we have nothing to do with them.
