### ISSUE TITLE
mockServiceWorker.js resource remains in a"pending" status when I open up the Network tab

### ISSUE THREAD

**Issue by david2am** [mswjs/msw#721]
Hi, I am using msw to mock fetch API request in my project, I check the network tab and the mockServiceWorker.js resource remains in a"pending" status, additionally, the response retrieves index.html instead of the JSON response I mock in the handlers file. Maybe I am incurring a silly error but I didn't find some resource on the web that could help me, thanks in advance!

## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.28.2   |
| browser | Chrome 90.0.4430.93    |
| OS      | Windows 10    |

## Request handlers

I run ``` "dev": "webpack serve --mode development", ``` in CLI and these are my configurations

```js
// index.tsx
...
if (process.env.NODE_ENV === 'development') require('./mocks/browser');

const rootElement = document.getElementById('app');

ReactDOM.render(<ThemeProvider><App /></ThemeProvider>, rootElement);

// ./mock/browser.ts
import { setupWorker } from 'msw';
import { handlers } from './handlers';

const worker = setupWorker(...handlers);

worker.start();

// handlers
import { rest } from 'msw';

const baseURL = 'http://localhost:8080';

const handlers = [
  rest.get(`${baseURL}/navlink-routes`, (_req, res, ctx) => res(
    ctx.status(200),
    ctx.json({
      result: [
        { label: 'Shop', path: 'shop' },
        { label: 'Wishlist', path: 'wishlist' },
        { label: 'Checkout', path: 'checkout' },
      ],
    }),
  )),
  rest.get('*', (req, res, ctx) => res(
    ctx.status(500),
    ctx.json({ error: `Please add request handler for ${req.url.toString()}` }),
  )),
];

export { handlers };
```

## Actual request

```js
// Example of making a request. Provide your code here.
async function getData(): Promise<void> {
      try {
        const response = await fetch('http://localhost:8080/navlink-routes', { signal });

        if (!response.ok) throw new Error(`Server error ${response.status}`);

        const { result } = await response.json();
        setLinkList(result);
      } catch (e) {
        if (e.name !== 'AbortError') setError(true);
      }
    }
```

## Current behavior

![image](https://user-images.githubusercontent.com/36830835/116942051-7240e880-ac36-11eb-98d6-60aba613e9b6.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/36830835/116942162-b2a06680-ac36-11eb-94ca-f739e519fd2e.png)

**Comment by kettanaito** [comment]
Hey, @david2am. Thanks for reaching out. 

Could you please share your webpack configuration here? We need to make sure it isn't the issue with webpack not serving the worker script properly. Also, check that the `mockServiceWorker.js` file is present in [your public directory](https://mswjs.io/docs/cli/init#where-is-my-public-directory). It may help to build your app into a static HTML/JS and see if it can resolve the worker script then (may require some changes to enable MSW in production _for debugging only_).

I bet this is the issue with serving the file. Unfortunately, there's little I can suggest without a reproduction repository. Would you have time to prepare such and push it to GitHub?

On the unrelated note, you may replace this request handler:

```js
rest.get('*', (req, res, ctx) => res(
    ctx.status(500),
    ctx.json({ error: `Please add request handler for ${req.url.toString()}` }),
  )),
```

just by setting the [onUnhandledRequest](https://mswjs.io/docs/api/setup-worker/start#onunhandledrequest) option to "error":

```js
worker.start({ onUnhandledRequest: 'error' })
```

This option will throw a similar error you're doing at the moment, but handle any unknown requests, not just `GET` ones.

**Comment by david2am** [comment]
@kettanaito I wasn't set up a public directory properly I was using my dist directory which I created for production purposes calling:

``` webpack --mode production ```

Following your suggestion, I created a new public/ directory and call:

``` npx msw init public ```

That solves the issue, thanks for your help 👍

**Comment by kettanaito** [comment]
Glad it got resolved, @david2am!

**Comment by alabianca** [comment]
@kettanaito We are having the same issue in our project that uses a rather complicated configuration. 
What's odd to me is that the network request for `mockServiceWorker.js` remains in a pending state, but the mock handlers work correctly. So at a glance it all works as expected, but when looking at the network tab we have the request for the service worker in a pending state. 

We use React version: 17.0.2 and msw version: 0.39.2. 

We do not commit our public directory as our build pipeline generates it each time. We generated the mockServiceWorker.js using `npx init src/ --save` (placing it in src so it will be committed) . We then use the Webpack CopyPlugin to copy the file from src/ to the public directory in our case `/dist/apps/app1`. 

Our webpack output config looks like this.

```javascript
output: {
      filename: 'content/[name].[hash].js',
      path: path.resolve(`./dist/apps/app1`),
      publicPath: '/',
    },
```

As a result our public directory looks something like this
```
/content
       main.js
      vendor.js
      app.css
index.html
favicon.ico
mockServiceWorker.js
```

What could be causing the pending network request? I especially confused since everything works as expected

**Comment by alabianca** [comment]
I created [Issue 1233](https://github.com/mswjs/msw/issues/1233) since I can reproduce this in the msw react-rest example.
