### ISSUE TITLE
Custom resolver function for GraphQL

### ISSUE THREAD

**Issue by fragm3** [mswjs/msw#729]
**Is your feature request related to a problem? Please describe.**
I am looking to add MSW for mocking in a project, but I can't see any way to provide custom resolver functions for mock. I can see complete mock to be given https://github.com/mswjs/msw/blob/e31a344332f5951177bb17655a82c7cefe59445e/test/graphql-api/query.mocks.ts 
For a given type in the schema,  can we can provide a resolver function that will return the response for all values of that type?

**Describe the solution you'd like**
```
  {
    String: () => 'Some string',
    Connection: () => ({
      edges: [{
        node: {
          name: 'node1'
        }
      }]
    })
  }
```

With the example mocks above, the query below:

```
query TestQuery {
  Connection {
    edges {
      node {
        name
        description
      }
    }
    count
  }
}
```

should return data like:
```
{
  connection: {
    __typename: "Connection", // added by client
    edges: [
      {
        __typename: "Edge",
        node: {
          __typename: "Node",
          name: "node1",
          description: "Some string" // falls back to our resover for the String type
        }
      }
    ],
    count: -41 // random integer
  }
}
```

**Describe alternatives you've considered**
Tried looking for a solution, is `responseTransformer` the correct way to proceed?

**Comment by kettanaito** [comment]
Hey, @fragm3.

You may use the [graphql.operation](https://mswjs.io/docs/api/graphql/operation) handler to capture _all_ GraphQL operations and resolve them against a mocked schema. 

```js
import { graphql as executeGraphQL, buildSchema } from 'graphql'
import { graphql } from '.'

export const handlers = [
  graphql.operation(async (req, res, ctx) => {
    const { data, errors } = await executeGraphQL({
      schema: buildSchema(`
      # You can use your existing GraphQL schema here.
      type Connection {
        name: String!
      }
    `),
      source: req.body.query,
      variableValues: req.variables,
      // `rootValue` is used to resolve the values.
      rootValue: {
        Connection: {
          name: 'node1',
        },
      },
    })

    return res(ctx.data(data), ctx.errors(errors))
  }),
]
```

What this does is resolves the mocked request against an actual GraphQL schema. This means that all the `Connection` type files will be resolved according to the `rootValue`. 

I understand this may differ depending on your setup, so let me know if you're able to use this suggestion.

**Comment by fragm3** [comment]
@kettanaito thanks for the clarification, makes sense
