### ISSUE TITLE
npm ERR! notarget No matching version found for statuses@^2.0.0 when npm install

### ISSUE THREAD

**Issue by ayohana** [mswjs/msw#730]
## Describe the bug
Running ```npm install msw --save-dev``` on Windows 10 produces the following error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for statuses@^2.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'msw'
npm ERR! notarget
```

## Environment

- `nodejs: v14.16.0`
- `npm: 6.14.11`

## To Reproduce
1. Run ```npm install msw --save-dev```
2. See error

## Expected behavior
```msw``` is successfully installed

**Comment by kettanaito** [comment]
Hey, @ayohana. Thanks for reporting this.

This is strange, as [statuses@2.0.0](https://www.npmjs.com/package/statuses/v/2.0.0) does exist.

Could you please run the following command in the same project you're installing `msw`?

```sh
npm view statuses@2.0.0
```

Share the output of that command here. Thanks.

**Comment by ayohana** [comment]
> Hey, @ayohana. Thanks for reporting this.
> 
> This is strange, as [statuses@2.0.0](https://www.npmjs.com/package/statuses/v/2.0.0) does exist.
> 
> Could you please run the following command in the same project you're installing `msw`?
> 
> ```shell
> npm view statuses@2.0.0
> ```
> 
> Share the output of that command here. Thanks.

Thank you for the prompt reply, @kettanaito. I ran the command but it did not return any response. :(

**Comment by ayohana** [comment]
FYI @kettanaito, I've also tried running `npm install statuses` separately, and confirmed it's been successfully added to my `package.json`. I then tried running `npm install msw --save-dev` and it produced the exact same error as in the description above. Please advise.

**Comment by kettanaito** [comment]
Thanks for providing more info. Can you please check that you're not using a custom NPM registry/other means that would block the installation of the package?

You can check your NPM config by running
```sh
npm config list
```

I'm afraid I don't have much to advise at this point.

**Comment by ayohana** [comment]
@kettanaito 
I ran ```npm config list``` and below is the response. Can you help double check this for me?

A little more background on my project. It is in React/Typescript, and I use Visual Studio for development.

Thank you for your help!

```
; cli configs
metrics-registry = "https://myproject.com/_packaging/tps/npm/registry"
scope = ""
user-agent = "npm/6.14.11 node/v14.16.0 win32 x64"

; project config C:\Users\...\source\repos\myproject\.npmrc
@myproject:always-auth = true
@myproject:registry = "https://myproject.com/_packaging/csc/npm/registry/"
always-auth = true
registry = "https://myproject.com/_packaging/tps/npm/registry"

; userconfig C:\Users\...\.npmrc
//myproject.com/_packaging/csc/npm/registry/:email = "not-used@example.com"
//myproject.com/_packaging/csc/npm/registry/:username = "VssSessionToken"
//myproject.com/_packaging/tps/npm/:email = "not-used@example.com"
//myproject.com/_packaging/tps/npm/:username = "VssSessionToken"
always-auth = true
cache = "c:\\npm-cache"
msvs_version = "2015"

; builtin config undefined
prefix = "C:\\Users\\...\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\...\source\repos\myproject
; HOME = C:\Users\...
; "npm config ls -l" to show all defaults.
````

**Comment by kettanaito** [comment]
It looks like you have a custom NPM registry configured. I suspect that to be a culprit in some way. 

I may suggest setting the default registry and trying to install MSW:

```diff
// .npmrc
-registry=https://myproject.com/_packaging/tps/npm/registry
+registry=https://registry.npmjs.org/
```

We need to take the custom registry out to effectively triage if it's the reason. 

The `statuses` package is correctly specified as MSW's dependency, including its range version that's published to NPM. The issue is likely on your side with the custom registry you're using. Check how it works, any sorts of whitelists and permissions. I'm afraid I don't see an issue on the library's side to fix.
