### ISSUE TITLE
My Query Params are not being matched

### ISSUE THREAD

**Issue by jrock2004** [mswjs/msw#731]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.28.2   |
| node | 14.0     |
| OS   | Mac     |

## Request handlers

```js
import { rest } from 'msw';
import { setupServer } from 'msw/node';
import { events, resources } from '../../data/mockData';

import Calendar from '.';
import { zoomOptions } from '../Filter';

const server = setupServer(
  rest.get('/calendar-resources', (req, res, ctx) => {
    return res(ctx.json(resources));
  }),
  rest.get('/calendar-events', (req, res, ctx) => {
    return res(ctx.json(events));
  }),
  rest.get('/auth', (req, res, ctx) => {
    return res(ctx.status(200));
  }),
  rest.get('/real-time-calendar', (req, res, ctx) => {
    return res(ctx.status(200));
  })
);

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());
```

## Actual request

```js
export const getEvents = (endStr: string, startStr: string) => {
  return axios
    .get(`/calendar-events?startDate=${startStr}&endDate=${endStr}`)
    .then((res) => {
      return res.data;
    })
    .catch((e) => console.log('events', e));
};
```

## Current behavior

My API call is not getting intercepted in my tests. I tried using the REPL tool and it seems like it does not match it so not sure if this is an issue or something I am missing

## Expected behavior

API call is intercepted

## Screenshots

![image](https://user-images.githubusercontent.com/655716/117903914-6a202300-b29e-11eb-913e-131de27b342e.png)

**Comment by kettanaito** [comment]
Hey, @jrock2004. 

The [Path matching REPL](https://mswjs.io/repl) works on the premise that you strip URL query parameters from the actual request URL. This is done by MSW automatically and you will see a warning if your request handler URL contains query parameters (those are redundant to include). It's confusing we don't mention that in the REPL and is a good area for improvement. 


Your `rest.get('/calendar-events')` handler will match all these API calls:

- `/calendar-events`
- `/calendar-events?startDate=X&endDate=Y`

You can access the `startDate`/`endDate`/any other query parameters in your handler like so:

```js
rest.get('/calendar-events', (req, res, ctx) => {
  const startDate = req.url.searchParams.get('startDate')
  const endDate = req.url.searchParams.get('endDate')

  // Work with query parameters' values...
})
```

> Learn more about working with [Query parameters](https://mswjs.io/docs/recipes/query-parameters).

If the requests are still not matched, please follow this [debugging guidelines](https://mswjs.io/docs/recipes/debugging-uncaught-requests) where you'll likely find a solution to your issue. If the said guidelines prove to be ineffective in your case, please create a reproduction repository for us to look at. Thanks.

**Comment by jrock2004** [comment]
@kettanaito its not. In my terminal I’m seeing that it’s trying to call real api and it’s not picking it up

**Comment by kettanaito** [comment]
I've included the instructions to debug that issue above. If you've followed them and still experiencing the issue, please create a reproduction repository and push it to GitHub. Share the link to your reproduction repo here so we could take a look.
