### ISSUE TITLE
How to enable MSW in production

### ISSUE THREAD

**Issue by dmwallace** [mswjs/msw#737]
I'm using MSW with NextJS and it's working fine in development, but not at all in the production build.  Is this intentional, and if so is there a way to enable MSW in production?

**Comment by dmwallace** [comment]
Closing as this was an issue with how NextJS handles environment variables and not with msw, sorry

**Comment by kettanaito** [comment]
Hey, @dmwallace. Glad to hear you've resolved the issue.

Please note that MSW is a development tool, so you're unlikely to need it in production. Unless you're deploying an educational material or an app that _explicitly_ needs to speak to a mocked API, you'd rather ensure that MSW does not run in production.

**Comment by dmwallace** [comment]
Thanks, yes I agree and understand that I won't be using it on the production server, but I just wanted to test the performance of the production build with the mock api locally.  That was my use case in case anyone was wondering.  Thanks again for this great tool

**Comment by loia5tqd001** [comment]
What if I really want to deploy it to production *yet as an educational material*?

For example, I want to deploy it to Github Pages. The base URL is `loia5tqd001.github.io/my-repo/`, so it should find `mockServiceWorker.js` at `/my-repo/mockServiceWorker.js`, but it's complaining to me that:
```
Uncaught (in promise) Error: [MSW] Failed to register a Service Worker for scope ('https://loia5tqd001.github.io/') with script ('https://loia5tqd001.github.io/mockServiceWorker.js'): Service Worker script does not exist at the given path.

Did you forget to run "npx msw init <PUBLIC_DIR>"?
```
What should I do to make it understand correctly the ***scope***?

**Comment by kettanaito** [comment]
@loia5tqd001, MSW will always attempt to find the worker script at the root of your site, by default. If the worker's location differs, you need to explicitly tell MSW about that using the `serviceWorker.url` option:

```js
setupWorker({
  serviceWorker: {
    url: '/my-repo/mockServiceWorker.js'
  }
})
```

> Utilize environmental variables to have the proper worker script lookup in development and production. 

[Read more about the `serviceWorker.url` option](https://mswjs.io/docs/api/setup-worker/start#serviceworker). Bear in mind that the worker's location on your server controls what pages the worker is able to handle. That is called the worker's "scope" and is well described [here](https://mswjs.io/docs/recipes/debugging-uncaught-requests#verify-the-workers-scope).

**Comment by loia5tqd001** [comment]
Exactly what I need. Many thanks <3

**Comment by huajian123** [comment]
@loia5tqd001 @kettanaito Please tell me, after configuring like this, the originally requested path cannot be found. What is the reason?

**Comment by huajian123** [comment]
If it is under the root path, the request address is correct.
