### ISSUE TITLE
Some GraphQL queries don't get intercepted

### ISSUE THREAD

**Issue by ImLuze** [mswjs/msw#741]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.28.2   |
| browser | Chrome     |
| OS      | MacOS 11.3     |

## Request handlers

```js
// Example of declaration. Provide your code here.
import { setupWorker, rest } from 'msw'

const handlers: RequestHandler[] = [
    rest.post("*", (req) => console.log((req as any).href.url)),
    graphql.query("getSandwiches", (req, res, ctx) => {
        res(ctx.data({
            locations: MOCK_LOCATIONS
        }));
    })
];

const worker = setupWorker(...handlers)

worker.start();
```

## Actual request

Using Apollo-client to fetch GraphQL queries.

```js
function useGetSandwichesQuery(baseOptions?: ApolloReactHooks.QueryHookOptions<GetSandwichesQuery, GetSandwichesQueryVariables>) {
  return ApolloReactHooks.useQuery<GetSandwichesQuery, GetSandwichesQueryVariables>(GetSandwichesDocument, baseOptions);
}

const { data, loading, error } = useGetSandwichesQuery({ variables: { locationId } });
```

## Current behavior

The `getSandwiches` query is not being intercepted at all. I've followed the advice from [debugging-uncaught-requests](https://mswjs.io/docs/recipes/debugging-uncaught-requests).

`onUncaughtHandledRequest` doesn't seem to throw an error on this request, even when I remove the handler from the handlers array. It looks like it doesn't get intercepted at all. Even the `"*"` rest handler doesn't seem to log that particular query. I have 3 GraphQL queries, 1 gets intercepted correctly and throws an error that it isn't handled. 2 others don't seem to get intercepted at all. The unmocked version does work perfectly fine however.

`printHandlers` prints the handler correctly.

`<ROOT_URL>/mockServiceWorker.js` is available, so I guess the service worker is in the correct scope.

## Expected behavior

Expected all 3 GraphQL calls to be intercepted, `getSandwiches` should be mocked, while the other 2 should throw an error because of the `onUncaughtHandledRequest` option.

Is there anything else I can do to debug this?

**Comment by kettanaito** [comment]
Hey, @ImLuze. Thanks for reporting this and for the detailed description of the issue. 

How does the behavior of the handler change if you remove the `rest.post('*')` handler? 

May I ask you to prepare a reproduction repository for us to look at? That'd help us resolve the issue in the shortest term. Thanks for understanding.

**Comment by ImLuze** [comment]
@kettanaito thank you for the quick reply. Removing the rest handler unfortunately has the same results. I've added it as a way to debug this.

I can't share the repo I'm working on right now, but I'll see if I can create a minimal reproduction in a couple days. Life is quite busy at the moment so bear with me on this one 😅

**Comment by kettanaito** [comment]
Please update to `0.29.0` as it comes with the default `onUnhandledRequest` option that will warn you upon any unhandled request. That warning will also contain useful suggestions in case of typos. Get back to us once you've updated the library. 

> It looks like it doesn't get intercepted at all

This may mean that the request occurs outside of the worker's scope. Read about how to [Verify the worker's scope](https://mswjs.io/docs/recipes/debugging-uncaught-requests#verify-the-workers-scope).

**Comment by ImLuze** [comment]
First of all, very handy update! Thanks a lot for this! I've updated it to `0.29.0`. The issue still occurs, but I managed to dig a little deeper and found out the following:

2 out of the 3 requests resolve before I get the `[MSW] Mocking enabled.` message in the console. These also happen to be the only 2 requests which do not get intercepted. Might this have something to do with how requests get deferred until the worker has initialized?

I've tried to test this theory out by wrapping my `ReactDOM.render` function in a `setTimeout` to make sure that the `worker` has enough time to initialize before the app gets rendered. This does seem to resolve the issue. All 3 requests now happen after I get the `[MSW] Mocking enabled.` message in the console and all 3 requests get intercepted as expected.

I've tried to replicate this behavior in a separate repository but I must admit that I've failed to do so 😕. I've created a small frontend application using [graphqlzero](https://graphqlzero.almansi.me) as a fake GraphQL API. But no matter what I try, all the requests get intercepted correctly. I'm not entirely sure how to replicate this.

If you can think of anything else I can try or any other information I can gather, please let me know! I'll do my best to help!

**Comment by kettanaito** [comment]
Thanks for investigating this further, @ImLuze. 

I have a few suggestions you can try to narrow down the issue:

1. Set `onUnhandledRequest` to `"error"`:
```js
worker.start({ onUnhandledRequest: 'error' })
```

Run your app/tests now. If you _don't_ see any errors on unhandled requests, this means the worker is not active by the time your requests happen. Consider using [deferred mounting](https://mswjs.io/docs/recipes/deferred-mounting) to ensure your application renders after the worker has been registered. 

If you do see errors, they will contain suggestions as to what is wrong. Pay attention to query names, casing, typos, endpoints, and such to spot the issue. 

2. Follow the relevant steps from the [Debugging uncaught requests](https://mswjs.io/docs/recipes/debugging-uncaught-requests) recipe. The issue may also be with the worker's scope, which you'll learn how to verify on that page. 

The next step would be to look into a reproduction repository. I understand it's hard to prepare one, but try paying attention to the difference between your reproduction setup and your actual app. One of the points of preparing a reproduction repository is for you to figure out what's wrong by comparing minimal and actual usage scenarios.

**Comment by kettanaito** [comment]
I'm closing this as we haven't received any reproduction repository or evidence that there's indeed an issue with the library. We can still discuss this and will try to help you debug the problem. Otherwise, we're treating inactivity as a sign that the issue has been resolved.
