### ISSUE TITLE
Ambiguous URL not prioritized

### ISSUE THREAD

**Issue by czabaj** [mswjs/msw#742]
## Describe the bug

We have two ambiguous URL

* `/account/referrer/stats`
* `/account/referrer/:code`

Simply put, the first has a static `stats` path segment and the second has a parameter in the path at the same path position.

The problem is that the path with path parameter matches also requests for `stats` so the handler for `stats` never runs.

I admit this is a problem with API design, but, unfortunately, in our REST API, such ambiguousness is quite common.

React routing library `@reach/router` solves this nicely with [path ranking](https://reach.tech/router/ranking).

Is the MSW currently solve this problem in some way? If not, I can try to improve the matching algorithm if you wish.

## Environment

- `msw: 0.28.2`
- `nodejs: 14.16.0`
- `yarn: 1.22.0`

**Comment by kettanaito** [comment]
Hey, @czabaj.

Request handlers are sensitive to order: the first handler that matches will get used. You can list them in the exact order as in your reference in order for the exact `/stats` to match first, and let the other dynamic `:code` URLs to still fall through:

```js
const handlers = [
  rest.get('/account/referrer/stats', (req, res, ctx) => res(ctx.text('one'))),
  rest.get('/account/referrer/:code', (req, res, ctx) => res(ctx.text('two'))),
]
```

This means that `/account/referrer/stats` will match the first handler, while `/account/referrer/abc-123` the second.

**Comment by czabaj** [comment]
That's true!

I create handlers dynamically, so I just sorted the handlers by _route score_ in descending order and now it works!

Here is the code for ranking a route if anyone is interested

```JavaScript
// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copied unexported code from @reach/router
// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
const segmentize = (uri) =>
	uri
		// strip starting/ending slashes
		.replace(/(^\/+|\/+$)/g, '')
		.split('/');

const paramRe = /^:(.+)/;

const SEGMENT_POINTS = 4;
const STATIC_POINTS = 3;
const DYNAMIC_POINTS = 2;
const SPLAT_PENALTY = 1;
const ROOT_POINTS = 1;

const isRootSegment = (segment) => segment === '';
const isDynamic = (segment) => paramRe.test(segment);
const isSplat = (segment) => segment && segment[0] === '*';

/**
 * Returns a score for a path, higher score means higher "specificity"
 * @see https://reach.tech/router/ranking
 * @param {string} path - the path with path parameters and wildcards
 * @return {number}
 */
export const rankRoute = (path) => {
	return segmentize(path).reduce((score, segment) => {
		score += SEGMENT_POINTS;
		if (isRootSegment(segment)) score += ROOT_POINTS;
		else if (isDynamic(segment)) score += DYNAMIC_POINTS;
		else if (isSplat(segment)) score -= SEGMENT_POINTS + SPLAT_PENALTY;
		else score += STATIC_POINTS;
		return score;
	}, 0);
};
```

This might have some edge cases when used with MSW, but shall work for most cases.
