### ISSUE TITLE
Response composition silently fails

### ISSUE THREAD

**Issue by JesusTheHun** [mswjs/msw#748]
## Describe the bug

While this works
```ts
export const server = setupServer(
  rest.get(`${mockBaseUrl}/customers/me`, (req, res, ctx) => {
    return res(
      ctx.set('Content-Type', 'application/json'),
      ctx.body(JSONbig.stringify(me__one_organization)),
    )
  }),
)
```

This does not 
```ts
export const bigintResponse = createResponseComposition(undefined,[
  (res) => {
    if (res.body && res.headers?.get('content-type')?.endsWith('json')) {
      res.body = JSONbig.stringify(res.body)
    }
    return res
  }
])

export const server = setupServer(
  rest.get(`${mockBaseUrl}/customers/me`, (req, res, ctx) => {
    return bigintResponse(
      ctx.body(me__one_organization),
    )
  }),
)
```
`me__one_organization` is an object containing `BigInt` values.

## Environment

- `msw: 0.28.2`
- `nodejs: 14.16.1`
- `yarn: 2.4.1`

> Jest testing, so node is being used

## Expected behavior

Both scenarios should works.

## Additional information
While debugging it looks like the response composition is not even called

On a side not worth its own issue, the [doc](https://mswjs.io/docs/recipes/custom-transformer) about response composition is not up to date. Signature differs, the doc mention a single argument (object) with a `defaultTransformers` property while the latest version of msw accepts two arguments, the first one I'm not sure to understand and the second one the array of transformers to be composed.

**Comment by kettanaito** [comment]
Hey, @JesusTheHun.

The condition in your custom response composition checks that the response content-type ends with `json`. However, in your mocked response you're not setting the `Content-Type` (nethier you're using `ctx.json()` that sets is implicitly). If you inspect the `res.headers.get('content-type')` in your custom response composition, you're likely to see `text/plain`. This is why your composition isn't applied: this condition is not met:

```js
if (res.body && res.headers?.get('content-type')?.endsWith('json')) {
```

> Note that the outdated example from the docs uses `ctx.json()` and not `ctx.body()` in the handler. That's why the condition above was met. 

Although response composition may abstract certain repetitive behaviors, I find this case to be rather unique. BigInt cannot be serialized natively, and I highly suggest putting its custom serialization logic as close to the actual value as possible, that being in a _custom context utility_. Here's an example:

https://github.com/mswjs/msw/blob/8a816e0ff4128c02cae823bc44a3609407641b02/test/msw-api/setup-server/scenarios/custom-transformers.test.ts#L6-L22

With the custom `jsonBig` context utility, you can serialize JSON that contains BigInt without issues. 

`ctx.body` expects a valid response body, which JSON isn't. This means that you need to serialize JSON into a string to pass it to `ctx.body`, and you cannot do that without a custom serializer:

```js
return myCustomComposition(
  // This throws an exception, because BigInt cannot be serialized natively.
  // ctx.json({ value: BigInt(...) }),
  // This also throws an exception, because we're effectively extracted
  // serialization from "ctx.json" and are applying it manually now.
  ctx.body(JSON.stringifiy({ value: BigInt(...) }))
)
```

I hope my point as to why custom context utility is the best option here is clear. Let me know if you have any other questions.

**Comment by kettanaito** [comment]
Apologies for the outdated documentation, which also mentions a BigInt serialization as a part of the custom response composition. I'll fix that. 

> Historically, this outdated example had a place to exist because JSON body serialization was performed on the `res()` side. It has been refined since then, and now `ctx.json` serializes the JSON body upon invocation.

**Comment by kettanaito** [comment]
I've rewritten the related sections of the documentation to be up-to-date and more clear in the terminology they use. 

- [Response transformer](https://mswjs.io/docs/basics/response-transformer)
- [Custom response composition](https://mswjs.io/docs/recipes/custom-response-composition)

You can use those pages as the reference for your custom implementation. Thanks for bringing this up.
