### ISSUE TITLE
Add `ctx.cookie` to GraphQL context

### ISSUE THREAD

**Issue by hugo** [mswjs/msw#755]
**Is your feature request related to a problem? Please describe.**
The [documentation on cookies](https://mswjs.io/docs/recipes/cookies) advises that to set a cookie in a response, you should use the `ctx.cookie` method. When using the `rest` API this method is available. When using `graphql` it is not.

**Describe the solution you'd like**
I would like to be able to set cookies in the response from a GraphQL handler the same was as in a REST one.

**Describe alternatives you've considered**
Use `res.set('set-cookie', 'name=value')` 

**Additional context**
N/A

**Comment by kettanaito** [comment]
Hey, @hugo. Thanks for raising this. 

Could you share your use case when you need to set a response cookie when working with GraphQL?

**Comment by hugo** [comment]
Yes, sure. We have a GraphQL API that uses cookies for a few things. One example is login. We have a mutation that looks something like this:
```graphql
mutation Login($username: String!, $password: String!) {
  login(username: $username, password: $password) {
    error {
      code
      message
    }
  }
}
```
This would also set `token` as a cookie, assuming there was no error. Elsewhere in the application we look for this cookie and perform branching logic based on its content (JWT claims, for example). As I said above, we can use the lower level `set-cookie` header to handle this and/or manually assign to `document.cookie`. Obviously this is error prone, and would break if there is ever a change to `msw` that affects how cookies are handled, which is why I'd prefer to use the "blessed" method of setting them.

**Comment by kettanaito** [comment]
Thank you for more details. I think it'd be a good addition to have `ctx.cookie` in the GraphQL context. 

Please, @hugo, would you be interested in shipping a pull request?

This change is a matter of extending the `graphqlContext` object with the `cookie` utility:

https://github.com/mswjs/msw/blob/8a816e0ff4128c02cae823bc44a3609407641b02/src/handlers/GraphQLHandler.ts#L41-L48

The same way it's present in the `rest.*` handler:

https://github.com/mswjs/msw/blob/8a816e0ff4128c02cae823bc44a3609407641b02/src/handlers/RestHandler.ts#L61

We'd have to add an integration test for GraphQL handler + `ctx.cookie` combination, but I can help you with that, if necessary.

**Comment by hugo** [comment]
Thanks for the pointers, I’ll be happy to work on the PR for this.
