### ISSUE TITLE
Grapqhl requests not intercepted

### ISSUE THREAD

**Issue by NikoKodzhabashev** [mswjs/msw#757]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.29.0  |
| browser | Chrome     |
| OS      | Linux/ Pop_Os     |

## Request handlers

```js
// Example of declaration. Provide your code here.
import { setupWorker, rest } from 'msw'
const ourAPI = graphql.link('https://ourApi.com/graphql')


const worker = setupWorker(
  ourAPI.query('GetAuthorQuery', (req, res, ctx) => {
        console.log('HEREEEE')
    }),
)

worker.start()
```

## Actual request

Hook generated by GraphQL Code Generator with react-query
```js
// Example of making a request. Provide your code here.

const { data, loading, error }  = useGetAuthorQuery({id:1})

```

## Current behavior

GraphQL requests not intercepted.
I am getting this error/warning:
`captured a request without a matching request handler:
  • POST https://ourApi.com/graphql
`
P.S: rest requests are working.
## Expected behavior

Expect to be able to mock the grapqhl request.

**Comment by ricn** [comment]
@NikoKodzhabashev Did you find a solution to the problem? I'm experience the same thing.

**Comment by kettanaito** [comment]
Hey, @ricn. You can follow [this guide](https://mswjs.io/docs/recipes/debugging-uncaught-requests) that can help you find the solution.

**Comment by ricn** [comment]
@kettanaito I have followed the guide without any success. I think I will create a new issue with more details about the problem.

**Comment by kettanaito** [comment]
Yes, please do. Please create a reproduction repository for the issue also, it'll help us look into it faster and there's a decent chance you discover the issue when isolating it into a minimal scenario. Thanks.
