### ISSUE TITLE
msw integration with Next.js project

### ISSUE THREAD

**Issue by seanbruce** [mswjs/msw#765]
## Describe the bug
Next's dev server get stuck quickly after a few navigations.

## Environment

- `msw: 0.29.0`
- `nodejs: 12.19.0`
- `npm: 6.14.8`
- `yarn: 1.22.5`

> Please also provide your browser version.
Chrome windows 91.0.4472.77

## To Reproduce
I do have a working demo on my working laptop.  but I can't commit it to my personal GitHub repo due to company policy, I'm very sorry for the inconvience. here is how to reproduce the issue.
1. create a new Next project use creat-next-app using Typescript template.
2. complete the official learning course sections of `Pre-rendering and Data Fetching` and `Dynamic Routes`. so we have posts route for all blogs list and posts/[id] route for the individual blog.
3. set up msw follow by this [demo](https://github.com/vercel/next.js/tree/canary/examples/with-msw)
4. add `about` page, using static generation with this page by mocking API returning some data to display.
5. yarn dev start the dev server.
6. click 'posts' link from the index page, when 'posts' page loaded click the go back button from browser. 
7. repeat step 6 about 3~4 times.
8. next dev server get stuck, you can see all the following request stuck in pending status from Network panel of Chrome dev tool

This issue disappeared after I comment out `require('../mocks')` statement. I also find [this issue on next](https://github.com/vercel/next.js/issues/10061#issuecomment-632077342) mentioning that old service work would cause problom. but apparently, I can't remove mockServiceWorker.

Does anyone have the same issue?

**Comment by seanbruce** [comment]
In addition. if I run `yarn build` and `yarn start` the issue also disappeared which doesn't make sense to me, because I enable mocking both in dev and prod mode. could it be possible that this is some bug not about service worker msw's using but next dev server?

**Comment by seanbruce** [comment]
In dev mode. when this issue occurred, go to the Application panel of chrome dev tools, either clicking the 'Unregister' or 'stop' button of 'mockServiceWorker.js' makes the pending request come back immediately, but do so will disable msw.

**Comment by kettanaito** [comment]
Hey, @seanbruce. Thanks for reporting this. It'd take some investigation to see what's wrong. 

> if I run yarn build and yarn start the issue also disappeared which doesn't make sense to me, because I enable mocking both in dev and prod mode

Running a built app doesn't establish hot reloading, which is likely to be the factor at play here. 

> In dev mode. when this issue occurred, go to the Application panel of chrome dev tools, either clicking the 'Unregister' or 'stop' button of 'mockServiceWorker.js' makes the pending request come back immediately, but do so will disable msw.

Sure, since you're terminating the pending worker, it'll end the pending request.

**Comment by tkamenoko** [comment]
This issue seems to be similar to #642 .

**Comment by lightsound** [comment]
I have the same problem and could not find the cause.

**Comment by AnnaVih** [comment]
Same issue!!!

**Comment by dasblitz** [comment]
As mentioned in #642 I have the same issue. I don't know enough about service workers to really understand what's going on.

**Comment by webpro** [comment]
See https://github.com/mswjs/msw/issues/785#issuecomment-864542454

tl/dr; bug probably introduced in v0.25.0, downgrade to v0.24.4 may be a temporary work-around.

**Comment by seanbruce** [comment]
> See [#785 (comment)](https://github.com/mswjs/msw/issues/785#issuecomment-864542454)
> 
> tl/dr; bug probably introduced in v0.25.0, downgrade to v0.24.4 may be a temporary work-around.

downgrade to 0.24.4 and it works.

**Comment by kettanaito** [comment]
We've recently released a fix that fixed the dev server in NextJS so it doesn't get stuck (thanks to @takefumi-yoshii).

Could you please update to [0.33.1](https://github.com/mswjs/msw/releases/tag/v0.33.1) and let us know if the issue is gone? Pay attention that you'd have to update the worker script or have the `msw.workerDirectory` [configured](https://mswjs.io/docs/cli/init#options).

**Comment by dasblitz** [comment]
Just tried it and it looks like it's working. hmr no longer hangs in next dev mode, on refreshing the page multiple times there's always only one active webpack-hmr. Tnx!

**Comment by kettanaito** [comment]
I consider this issue fixed, NextJS integration should function properly now.

I'll update the official usage example in the NextJS repo once I have time. Thank you for understanding.
