### ISSUE TITLE
Add a version comment to the mockServiceWorker.js

### ISSUE THREAD

**Issue by ibratoev** [mswjs/msw#779]
**Is your feature request related to a problem? Please describe.**
When the `mockServiceWorker.js` in the public folder is updated it is not clear if this is by mistake or an upgrade to a new version.

**Describe the solution you'd like**
Add a comment near the top of the `mockServiceWorker.js` file with the npm package version that produced the file in the `public` directory. This would make it more discoverable which version of the file you have and it will be easier when updating.

**Comment by kettanaito** [comment]
Hi, @ibratoev. Thanks for suggesting that. 

The worker script does come with the hash sum that represents its version, but you're right that there's no connection between the `msw` package and the generated worker script hash sum. 

Generally, the worker script will be updated automatically to the correct one based on the installing `msw` package version, if you've got the `msw.workerDirectory` path specified in your package.json:

```json
{
  "msw": { "workerDirectory": "./public" }
}
```

If you don't, the worker script will not be updated or modified in any way. This knowledge alone is enough to predict the worker script updates and debug them when they happen.

What is the scenario when having the `msw` package version in the worker script would be useful?

**Comment by ibratoev** [comment]
The scenario where the version would be most beneficial is when reviewing a PR that updates the script. It is hard to understand by just looking at a PR change why this was updated and *if* it was update properly and on purpose.

**Comment by kettanaito** [comment]
I see, that does make sense when committing the worker script to the repository. 

@ibratoev have you considered ignoring the worker script in your VCS? It will be generated automatically when you install `msw`, so when you install dependencies in your project if you have the aforementioned property set in your package.json. Do you see some particular benefit in keeping the worker script in Git?

> Historically, MSW recommended committing the worker script because there was no means to ensure it gets generated during the project's bootstrapping. With the auto-generation feature merged, the worker script may be treated as a built artifact, which implies it may be ignored by VCS.

**Comment by ibratoev** [comment]
That's a good question.
I guess I would prefer to have the script explicitly visible in the public directory.
But I see the other way working fine for some situations as well.
Don't have a strong preference at the moment so, maybe, supporting both should be fine until a "best" practice is more clearly established, if ever.

**Comment by kettanaito** [comment]
Agree. At the moment we still recommend committing the worker script to VCS to give the developer the power over that script. It's just a JavaScript module like any other. This transparency is a vital part of the security view on MSW.
