### ISSUE TITLE
"Warning: Possible EventEmitter memory leak detected" when using with NextJS

### ISSUE THREAD

**Issue by GetafixIT** [mswjs/msw#785]
## Describe the bug
I've implemented client and server side mocks as per the docs. Using GraphQL queries and mutations in a NextJS application which I've bootstrapped from _app.tsx which is about as global as I can get without a custom server.

With each save the application is re-compiled and refreshed in the browser.

Beyond the performance details listed here, the isomorphic mocks are working nicely.

**Server side:**
Depending on how many routes are visited, or how many changes are made. MSW pretty quickly stops responding and warns of a memory leak with too many open handlers, message from server-side console as below:

"MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [IncomingMessage]. Use emitter.setMaxListeners() to increase limit"

This doesn't happen with mocks off.

**Client**
In the browser, after navigating to about 5 different routes, the browser stop responding. Chrome is timing out completely, doing nothing at all on route changes. The message in Chrome is:

"waiting for available socket".

When i use browser tools to end the service worker, normal performance resumes.

Problem doesn't happen with mocks off.

In NextJS Dev mode, there is hot module reloading going on every save... I think this is where the problem stems from as this uses sockets.

I think there's an issue with the service worker and the socket reloads.

Once I kill the service worker, the server-side resumes - just with the memory leak warning.

## Environment

- `msw: 0.29.0`
- `nodejs: 14.17.0`
- `npm: 6.14.13`
- `next: 10.2.3`

> Please also provide your browser version. 

Chrome: Version 91.0.4472.101 (Official Build) (x86_64)

## To Reproduce
1 - Load multiple, routes in a NextJS app
2 - after 5 different route loads there are already 1 end listeners
3 - App performance drops to unusable
4 - Use application panel to end the service worker in the browser & app responds as normal

## Expected behavior
No memory leaks

**Comment by kettanaito** [comment]
Hey, @GetafixIT. Thank you for reporting this. 

There is an issue with the NextJS integration, and it may be related to https://github.com/mswjs/msw/issues/765. Perpahs the new hot reloading mechanism doesn't play nicely with the service worker. 

This needs investigation and some in-depth analyzis. I'll try to prioritize this, but I don't see this happening any time soon unless we get help from the contributors. If you discover any more details, observations, or potential fixes, please post them here, as they will help us implement the right fix.

**Comment by kettanaito** [comment]
I also suspect multiple things at play, as this looks like a Node.js warning (there is no `IncomingMessage` in a browser):

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [IncomingMessage]
```

At the same time, you report the issue as partially remediated when disabling the worker, which only affects the in-browser interception. 

Since Node.js interception affects the entire process, there may be a chance it affects the underlying implementation of hot reloading in NextJS and causes issues. 

I'd start by running the Node.js interception in a debug mode:

```sh
$ DEBUG=http* yarn dev
```

This will log every request intercepted by MSW in Node.js. We can see any suspicious activity this way.

**Comment by webpro** [comment]
Looked into this as well. Here's a reproducible test case: https://github.com/webpro/msw-next

To reproduce the issue:

- `npm install && npm run dev`
- Click a few times to switch pages
- Try to refresh: page keeps loading indefinitely
- Stop service worker from Chrome dev tools, and things start working again

Seeing suspicious logs for requests such as:

> [MSW] Warning: captured a request without a matching request handler:

- GET /_next/static/development/_devPagesManifest.json
- GET /_next/static/webpack/4db3df89d55dadb9c978.hot-update.json
- GET /_next/webpack-hmr
- GET /_next/static/chunks/pages/index.js

In another application it also captures requests for images (they are served from the local `public` folder).

Tried a few versions of Next.js (v9.2 v10.2 v11.0) - all the same issue.

Even when using another hostname and port for the requests (added to `/etc/hosts`), it looks like it still starts capturing all requests from `localhost` (but also correctly captures the request for the other domain).

Then I tried to downgrade msw. It seems this leak is introduced in v0.25.0, as things start to work properly with v0.24.4 (and lower).

So to get a working version in the repo above, use `npm install msw@0.24.4`

**Edit**: also when downgrading msw to v0.24.4 in a pretty large project with a custom msw setup, the memory leak is no longer present.

**Comment by GetafixIT** [comment]
@webpro thanks for the input & test case...

I'm using GraphQL rather than rest and downgrading doesn't work in my scenario.

This could be a good starting point to debug the Graph implementation & see the changes to the worker between 0.24.0 and 0.29.0

**Comment by kettanaito** [comment]
@webpro I have a suspicion that the warnings you see are only a side-effect of the latest release, and aren't directly related to the issue. This can be easily tested by setting the `onUnhandledRequest` option to `"bypass"`:

```js
worker.start({ onUnhandledRequest: 'bypass' })
```

If this setting eliminates the issue, then the warnings are the root cause. Otherwise, there's something else in place.

Even with the warnings on unhandled requests, MSW still bypasses them (performs as-is). Conceptually, MSW intercepts _all_ requests that happen on the page. It always did and does so now. To distinguish whether a request should be mocked, it must be intercepted by the worker first. 

I suggest we debug this by attaching a Node inspector and observing that memory heap (what eats the memory?).

**Comment by fsubal** [comment]
Maybe I bumped into the same problem, while I'm seeing my `next dev` logs it showed

```
wait  - compiling...
event - build page: /items/[slug]
event - compiled successfully
(node:64287) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessage]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)      
```

```tsx
// /src/pages/_app.tsx
if (process.env.NODE_ENV === 'development' && !process.browser) {
  if (process.env['NEXT_PUBLIC_MOCK_SERVER']) {
    const { setupServer } = require('msw/node') as typeof import('msw/node')
    const { routes } = require('../api/mock.server')
    const server = setupServer(...routes)
    server.listen()
  }
}
```

It looked to me that something inside `@mswjs/interceptors` is related to this warning.
( because code like `.on('end', ...)` was not found in mswjs/msw, but found in mswjs/interceptors ! )

I first suspected `getIncomingMessageBody()` and added some `console.log` in my node_modules,
and reload around my app to see what's happening

https://github.com/mswjs/interceptors/blob/a4de91535c7b88ddefa3fa47395f8b673b199503/src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts

```diff
function getIncomingMessageBody(res) {
    var responseBody = '';

+    console.log(res._events)

    return new Promise(function (resolve, reject) {
        res.once('error', reject);
        res.on('data', function (chunk) { return (responseBody += chunk); });
        res.once('end', function () {
            resolve(responseBody);
        });
    });
}
```

And then it showed

```
$ node --trace-warnings ./node_modules/.bin/next dev

....

[Object: null prototype] {
  end: [
    [Function: responseOnEnd],
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] }
  ],
  error: [
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] },
    [Function: bound onceWrapper] { listener: [Function (anonymous)] }
  ],
  data: [
    [Function (anonymous)],
    [Function (anonymous)],
    [Function (anonymous)],
    [Function (anonymous)],
    [Function (anonymous)],
    [Function (anonymous)],
    [Function (anonymous)],
    [Function (anonymous)]
  ]
}
(node:65539) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessage]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at IncomingMessage.addListener (events.js:406:10)
    at IncomingMessage.Readable.on (internal/streams/readable.js:858:35)
    at IncomingMessage.once (events.js:437:8)
    at ClientRequestOverride.<anonymous> (/Users/f_subal/Development/my-app/node_modules/node-fetch/lib/index.js:1546:8)
    at ClientRequestOverride.emit (events.js:315:20)
    at ClientRequestOverride.EventEmitter.emit (domain.js:529:15)
    at ClientRequestOverride.<anonymous> (/Users/f_subal/Development/my-app/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:313:39)
    at ClientRequestOverride.emit (events.js:327:22)
    at ClientRequestOverride.EventEmitter.emit (domain.js:529:15)
    at ClientRequestOverride.<anonymous> (/Users/f_subal/Development/my-app/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:313:39)
    at ClientRequestOverride.emit (events.js:327:22)
    at ClientRequestOverride.EventEmitter.emit (domain.js:529:15)
    at ClientRequestOverride.<anonymous> (/Users/f_subal/Development/my-app/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:313:39)
    at ClientRequestOverride.emit (events.js:327:22)
    at ClientRequestOverride.EventEmitter.emit (domain.js:529:15)
```

`/createClientRequestOverride.js:313:39` was doing the following, which looks equivalent to https://github.com/mswjs/interceptors/blob/a4de91535c7b88ddefa3fa47395f8b673b199503/src/interceptors/ClientRequest/createClientRequestOverride.ts#L302-L305

```js
                            request.on('response', function (response) {
                                debug(response.statusCode, options.method, url.href);
                                _this.emit('response', response);
                            });
```

I still don't know what the root cause is, seemed a mistake of cleanup of listeners in `getIncomingMessageBody`, but not sure.

**Comment by fsubal** [comment]
If what I found is correct, should this be better reported as an issue of [mswjs/interceptors](https://github.com/mswjs/interceptors), instead of this repository ?

**Comment by GetafixIT** [comment]
My colleague noticed a workaround:

![image](https://user-images.githubusercontent.com/2236397/125978892-0a892941-3110-4b62-94be-752960ec6ebe.png)

Check the "Update on reload" checkbox.

This prevents the worker from stalling the application... but doesn't solve the underlying problem.

**Comment by GetafixIT** [comment]
@kettanaito I tried your suggestion & added { onUnhandledRequest: "bypass" } but the problem is still there.

**Comment by kettanaito** [comment]
Hey, @fsubal. Thank you for looking into it. Can you try a local build of interceptors with the event listeners removed in `getIncomingMessageBody`? I'll try to get to it this weekend and see if that helps. 

@GetafixIT, I see. Thanks for trying. I've experienced a strange issue when running Jest tests and Next.js simultaneously: it seems that some periodic code re-compilation in Next re-triggers the tests. This may be related to the issue, as Next may be doing something similar client-side, resulting in constant refreshes. Surely, there must be a way to tackle it.

**Comment by GetafixIT** [comment]
@kettanaito - next implements webpack with hot reload... so every change causes a reload. But that isn't the issue here as without any changes, simply navigating to different routes within the app causes the worker to lock the app.

Anyhow the [workaround](https://github.com/mswjs/msw/issues/785#issuecomment-881569447) above works for the time being.

**Comment by kettanaito** [comment]
@GetafixIT, sorry, I haven't made it clear: I've experienced constant test re-runs _without_ making any changes to the code. I run Next, I run Jest tests in `--watch` mode, the tests randomly re-run, and the Next re-compiles. Perhaps a similar thing may happen in the browser?

**Comment by kettanaito** [comment]
I'll prepare a pull request that cleans up the attached event listeners from the `IncomingMessage` as a part of the `getIncomingMessage` function. I've tested this change locally and confirm that `res._events` (`stream._events` in the latest interceptors) is empty once the function is done extracting the response body.

**Comment by kettanaito** [comment]
I've released the fix in `@mswjs/interceptors@0.12.3` ([Release notes](https://github.com/mswjs/interceptors/releases/tag/v0.12.3)). Could somebody please use that version and verify that the memory leak in Node.js is resolved by this fix?

**Comment by fsubal** [comment]
>  Can you try a local build of interceptors with the event listeners removed in getIncomingMessageBody

Sorry I didn't have the time to try this, but thank you so much for your effort to fix it!

**Comment by kettanaito** [comment]
@fsubal, no worries. I'd be thankful if you tried that latest version of `interceptors` and tell us if the issue is gone.

**Comment by andrelas1** [comment]
Hey @kettanaito I was facing that same issue but after trying the `@mswjs/interceptors@0.12.3`, it seemed to have solved the issue!

I will keep working with the new version and if it pops something not expected, I will let you know.

I guess we just need to wait for the release of the new msw version :)

Thanks for the fix!!

**Comment by kettanaito** [comment]
The fix has been released in 0.32.1 (see the [release notes](https://github.com/mswjs/msw/releases/tag/v0.32.1)). Could you please update and let us know if the issue is gone?

**Comment by larswww** [comment]
I was having the same issue, googled, found this thread, updated and issue gone :)

**Comment by andrelas1** [comment]
Hey @kettanaito I double checked and one of the issues is gone (hot reload) but I guess I didn't test enough the routing part when I said all was working in my previous comment. After doing more tests with route changes (client-side), the application stops responding (also using NextJS). I disabled the worker and things started working again.

However, after a bit more investigation I was able to solve my issue by stopping the worker (`worker.stop`) every time there is a client-side route change with NextJS. Then I need to start the worker (`worker.start`) again before the component mounts. It's a bit more work to setup MSW with NextJS but it works for now.

I guess this is more about NextJS and how it works than an issue with the msw library.

I will try to find more time to see if I can make a contribution to msw to avoid that extra setup with NextJS.

Thanks again for all the work!

**Comment by kettanaito** [comment]
> I will try to find more time to see if I can make a contribution to msw to avoid that extra setup with NextJS.

That would be amazing, @andrelas1. Let us know what you find, perhaps we can account for this on the MSW side, or at least in the official MSW NextJS usage example. Thank you.

**Comment by JReinhold** [comment]
> However, after a bit more investigation I was able to solve my issue by stopping the worker (`worker.stop`) every time there is a client-side route change with NextJS. Then I need to start the worker (`worker.start`) again before the component mounts. It's a bit more work to setup MSW with NextJS but it works for now.

@andrelas1 can you in the meantime share how you built your workaround in practice?

**Comment by andrelas1** [comment]
Hey @JReinhold, the workaround with NextJS is to stop the worker every time the MyApp Component (_app.tsx) is unmounted:

```
useEffect(() => {
    worker.start();
    return () => {
      worker.stop();
    };
  });
```

I am not that confident because I was concerned on a few race conditions for http requests, but I have tested many route changes + hot reload, and it all seems to work fine. The requests are also being mocked correctly in my case.

You could try the router.events, but I found them to be less reliable than useEffect.

**Comment by kettanaito** [comment]
The event listener leak has been fixed in #822 and the development server being not responsive has been addressed in #834. This issue should be resolved now.

Please update to `msw@0.33.1` and let me know if you can still reproduce this. I'll close the issue until further notice, as I can't reproduce any issues when working with NextJS now.

**Comment by Tosinkoa** [comment]
(node:2232) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 
increase limit
(Use `node --trace-warnings ...` to show where the warning was created)


Please how do I use mswjs with NextJS? 
This is my first time of hearing about it.

**Comment by baptisteArno** [comment]
Still get a ton of:
```
(node:76206) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [IncomingMessage]. Use emitter.setMaxListeners() to increase limit
```
 I'm on `0.36.8`. I'm calling this: `if (process.env.NEXT_PUBLIC_AUTH_MOCKING === 'enabled') enableMocks()` at the top of my `_app.ts` file. Is it preferable to run it inside a `useEffect`? But then what about server side 🤔
