### ISSUE TITLE
Ionic Framework support

### ISSUE THREAD

**Issue by Oyeniyi** [mswjs/msw#789]
Hello Guys,

I start using msw in some angular projects and it's work very fine. So now, i want to start using with ionic framework to build some hybrid mobile application and use mws for offline request.

And it's work very fine when i using `ionic serve` command line but after build andoird apk, i got error like this `Promise rejection: [MSW] Failed to register a Service Worker. Failed to register a ServiceWorker for scope ('http://localhost/') with script ('http://localhost/mockServiceWorker.js'): An unknown error occurred when fetching the script. ; Zone: <root> ; Task: Promise.then ; Value: Error: [MSW] Failed to register a Service Worker:`

It's possible to use msw in ionic mobile application ?

**Comment by kettanaito** [comment]
Hey, @Oyeniyi. Thank you for reaching out. 

It looks like the worker script is not being copied to your application's build. Could you please ensure that the `mockServiceWorker.js` script is included in your build's directory? It should be located at the same directory where you've initialized it when run `npx msw init`. 

The way MSW is written doesn't require any framework-specific code: it operates with plain requests and uses the standardized Service Worker API in the browser. Any difficulty to make it work with a framework is always a question of finding the correct configuration for that framework. 

Also, it's worth mentioning that you are unlikely to need MSW in a production application, as that means your app will communicate against the mocked data. There are rare cases when this is desired, but it's likely that you don't need MSW in production at all.

**Comment by kettanaito** [comment]
Hey, @Oyeniyi. Could you please try configuring Angular to include `mockServiceWorker.js` file in the build assets?

Here's an example of the [Angular configuration](https://github.com/mswjs/examples/blob/d6b6da65f4987b7049db0976fa6af50fafd514b1/examples/rest-angular/angular.json#L22-L26) on how to do that. Take a look at the [Angular usage example](https://github.com/mswjs/examples/tree/master/examples/rest-angular) in general to see how your setup may be different.

**Comment by kettanaito** [comment]
You need to explicitly configure Angular compiler in the `projects[name]. architect.build.options.assets` array like so:

```json
"assets": [
  "src/mockServiceWorker.js"
],
```

> `src/mockServiceWorker.js` is a relative path to the worker script in your project. The path you've used as an argument to `msw init`.

This is demonstrated in the Angular usage example in my previous comment. This should resolve your issue. Let me know if it doesn't.

**Comment by lukasreiner** [comment]
This is still not solved using latest Ionic Framework and Capacitor. The js file gets included correctly but we still get the same error.

**Comment by TechManTejas** [comment]
Hey just wondering if the issue was actually solved because I am facing the same issue in my application

**Comment by kettanaito** [comment]
If you're facing the same issue, follow the error message and make sure to _serve `mockServicveWorker.js` from the root of your application._ This isn't an MSW issue, you must configure your network to correctly serve that worker script. Once you do, the browser will register the worker correctly. I've never used Ionic in the past so I have no specific steps to share, but you have to consult the framework's docs on that instead.

**Comment by SaulMoro** [comment]
This solution works to enable service workers in android
https://github.com/ionic-team/capacitor/issues/1655#issuecomment-579229390
