### ISSUE TITLE
Release fixes for Jest 27

### ISSUE THREAD

**Issue by jonkoops** [mswjs/msw#792]
Hi, I am trying to upgrade my project to Jest 27 and for that I need the changes in https://github.com/mswjs/interceptors/issues/126. Can we get a new release of MSW to be able to do so?

**Comment by kettanaito** [comment]
Hey, @jonkoops.

The library should work properly with Jest v27 now with the latest release [0.30.0](https://github.com/mswjs/msw/releases/tag/v0.30.0). If you encounter any issues, please raise them in a separate ticket. Thank you.

**Comment by jonkoops** [comment]
Thanks a bunch @kettanaito!
