### ISSUE TITLE
body stream already read when handling NextJS's devPagesManifest request

### ISSUE THREAD

**Issue by gCardinal** [mswjs/msw#796]
## Describe the bug
When using the service worker to mock graphql queries, it seems like msw does something to queries that aren't supposed to be intercepted. I'm using NextJS and as you'll see in the screenshot below, calls to `http://crew.shadowshifts.local.majisti.com/_next/static/development/_devPagesManifest.json` will fail because when Next tries to parse the response, it fails with the error:

```
Failed to fetch devPagesManifest TypeError: Failed to execute 'json' on 'Response': body stream already read
    at eval (page-loader.ts?6f7a:67)
```

The code throwing this error is:

```
  getPageList() {
    if (process.env.NODE_ENV === 'production') {
      return getClientBuildManifest().then((manifest) => manifest.sortedPages)
    } else {
      if ((window as any).__DEV_PAGES_MANIFEST) {
        return (window as any).__DEV_PAGES_MANIFEST.pages
      } else {
        if (!this.promisedDevPagesManifest) {
          this.promisedDevPagesManifest = fetch(
            `${this.assetPrefix}/_next/static/development/_devPagesManifest.json`
          )
            .then((res) => res.json())
            .then((manifest) => {
              ;(window as any).__DEV_PAGES_MANIFEST = manifest
              return manifest.pages
            })
            .catch((err) => {
              console.log(`Failed to fetch devPagesManifest`, err)
            })
        }
        return this.promisedDevPagesManifest
      }
    }
  }
```

You'll notice a `.then((res) => res.json())` in the code above, which indicates that before Next even has a chance to process the response, it's already been parsed somehow.

Removing the service worker fixes the issue.

## Environment

- `msw: 0.30.0`
- `nodejs: 15.14.0`
- `npm: 7.7.6`

Brave, Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)

## To Reproduce
I'm not sure I can get an easy reproduction case, it's happening in a pretty big monorepo and I can't make the code public. Moreover, the [example project here](https://github.com/vercel/next.js/tree/canary/examples/with-msw) does not produce the issue.

## Expected behavior
msw should not interfere at all with Next's dev server requests.

## Screenshots
https://i.imgur.com/9eOcRr6.png

**Comment by kettanaito** [comment]
Hey, @gCardinal. Thank you for reporting this.

> msw should not interfere at all with Next's dev server requests.

MSW intercepts _all_ requests that happen on the page, which includes requests to dev servers, HMR, static assets, etc. What MSW should do is properly bypass those requests. In your case, there's some interference and the internal request gets somehow altered. 

MSW reads each response (bypassed and mocked) and signals it back to the client in the "response:"` [life-cycle events](https://mswjs.io/docs/extensions/life-cycle-events):

https://github.com/mswjs/msw/blob/1da34e4fef13e278043d65ad656875186ac84e90/src/mockServiceWorker.js#L115-L136

So you could react to those responses as you wish:

```js
worker.on('response:bypass', (response) => {
  console.log({ response })
})
```

Could you please try that snippet above and let me know if it outputs the console message? Does that message contain the response related to the `_devPagesManifest.json` file?  If so, could you please inspect that response's body within the "response:bypass" event listener? 

This may be related to #765.

**Comment by gCardinal** [comment]
I added the snippet you provided and get no log, though I admit it's very possible I did not implement it properly. [Here's a gist](https://gist.github.com/gCardinal/eb54adc9095df207a3d076d9c3819039) to show how my code is currently setup and [a screenshot of my console logs](https://i.imgur.com/5K9bmpN.png).

Looking at the service worker's code (I realised a bit too late after opening this issue that I _do_ have access to the service worker's source...), do all requests go through `handleRequest`? I don't see a conditional anywhere that would prevent a request from going through this method and as such, the response will have been read since `clonedResponse.text()` is called, making NextJS' call of `res.json()` (as displayed in my first comment) fail.

I'm sure I'm missing something obvious here, but I felt like I should at least mention it.

**Comment by kettanaito** [comment]
Here's the handler call in the "fetch" event listener:

https://github.com/mswjs/msw/blob/1da34e4fef13e278043d65ad656875186ac84e90/src/mockServiceWorker.js#L266-L275

This means that all requests go through the `handleRequest` function, **with the exception for**:

- Navigation requests.
- Cache requests.
- Any request that happens while the worker is not ready (has no active clients).

Yes, any response will have its body read to text in order to implement the "response:*" life-cycle events I've mentioned earlier. That shouldn't be an issue, as the worker clones a response before reading its body. I'd expect the original response's body stream to be left intact (this is also confirmed by reading the response body stream manually in your app: `fetch('mocked/url').then(res => res.json())`). Here's an excerpt from MDN on `Response.clone()`:

> In fact, the main reason `clone()` exists is to allow multiple uses of Body objects (when they are one-use only.)
> —[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response/clone)

It'd be useful to know when and who is locking the body stream, and also about the exact response the `page-loader` reports as locked. I think we can do that by attaching a proxy to the Response object and observing when it becomes locked. 

```js
function watchForLocked(res) {
  Object.defineProperty(res, 'bodyUsed', {
    set(value) {
      if (value) console.log(new Error().stack)
    },
  })
}
```

Could you try inspecting the responses in the worker script and in the `page-loader` with this utility? That should print a call stack when something is setting the `bodyUsed` of the response to true.

**Comment by gCardinal** [comment]
Sorry for the delay in response.

It took me a while to get the `watchForLocked` method working, but that did not help my issue, it wouldn't log anything so I assume this means you were right and nothing what toying with the response. However, I have figured out the problem.

While I have no clue why that is the case, switching from a dynamic `import` to a dynamic `require` solved the issue. In short, compared to the above gist, my code now looks like this:

```ts
// configure-worker.ts
export const configureWorker = () => {
  if (typeof window !== 'undefined') {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { graphql, setupWorker } = require('msw');

    const handlers = [ ... ];

    const worker = setupWorker(...handlers);
    worker.start();
  }
};

// _app.tsx

configureWorker();

function CustomApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>ShadowShifts - Crew Member</title>
      </Head>
      <Provider store={store}>
        // Other stuff, no more MockApiProvider
      </Provider>
    </>
  );
}

export default CustomApp;

```

Sorry for this non-issue issue. I'll close this issue, but maybe it would be interesting to know why `await`ing breaks `msw`. I don't understand why that would be the case.

**Comment by kettanaito** [comment]
That's correct: you must use dynamic `require` and not `import` to conditionally add MSW to your project. 

At least one difference I know of is that dynamic `import` cannot be conditional, even if you include it in an `if` statement. From my past experiments, the code you import this way ends up in the bundle due to the bundler's optimization of imports. `require` statements, even if dynamic, don't get evaluated at all, if they are included conditionally.

**Comment by misha-erm** [comment]
Hello, 

I have the same issue with the rest api.

All fetches for bypassed requests throw error `Failed to execute 'json' on 'Response': body stream already read`.

Tried to switch from import to require but it doesn't help.

@kettanaito do you have any ideas what could be the problem? Thanks in advance

browser.js
```
import {setupWorker} from "msw";
import {handlers} from "./handlers";

export const worker = setupWorker(...handlers);

```

index.js
```
if (isMswEnabled) {
    const {worker} = require("./mocks/browser");

    worker.start({onUnhandledRequest: "bypass"});
  }

```

handlers.js
```
import {rest} from "msw";
import {generateBlock} from "./block";

const block0 = generateBlock(0);
const block1 = generateBlock(1);

const blocksMap = new Map([
  [block0.id, block0],
  [block1.id, block1],
]);

export const handlers = [
  rest.get("/api/blocks", (req, res, ctx) => {
    return res(ctx.json([...blocksMap.values()]));
  }),

  rest.post("/api/blocks", (req, res, ctx) => {
    const block = generateBlock(blocksMap.size);
    blocksMap.set(block.id, block);

    return res(ctx.json(block));
  }),

  rest.delete("/api/blocks/:id", (req, res, ctx) => {
    blocksMap.delete(req.params.id);
    return res(ctx.status(200));
  }),
];
```

![image](https://user-images.githubusercontent.com/8783498/134349039-fc1dc726-8bae-479c-ba41-73f2f7aba3ec.png)
