### ISSUE TITLE
Paths with '+' in names does not match with mocks

### ISSUE THREAD

**Issue by tomaszwylezek** [mswjs/msw#811]
## Describe the bug
When I declared a mocked endpoint that has '+' in path then mocks for it does not work.
I have to change it to regex /user\+new/ and then it works, but because of it being an regex then it catches much more options than expected.
Did I do something wrong or it's a bug?
Provided repo with minimum setup to reproduce and also provided a screen on which we can see that there is info that we have a request without a matching request handles, but msw ask us if we meant same GET path instead.

## Environment
- `msw: 0.30.1`
- `Chrome:  91.0.4472.114`

## To Reproduce
https://github.com/tomaszwylezek/msw-bug

## Expected behavior
A paths with '+' works same as paths with '-' for example.

## Screenshots
![Screenshot 2021-07-09 at 15 57 07](https://user-images.githubusercontent.com/16152347/125089173-6f4af400-e0ce-11eb-9241-a3953ef385db.png)

**Comment by kettanaito** [comment]
Hey, @tomaszwylezek. 

I think this is the behavior `node-match-path` has in converting `+` into a RegExp repetition token.

Could you try escaping `+` in your request URL to see if that's the case?

```diff
-rest.get('/user+new', resolver)
+rest.get('/user\+new', resolver)
```

This should work based on the [REPL example](https://mswjs.io/repl?path=%2Fuser%5C%2Bnew&url=%2Fuser%2Bnew). 

I'd suggest escaping `+` for now until #691 is merged. Alternatively, you can help us making that migration to `path-to-regexp` happen, which would be a huge improvement in URL matching.
