### ISSUE TITLE
Captured request has empty body

### ISSUE THREAD

**Issue by florian-milky** [mswjs/msw#815]
## Describe the bug
In Jest with react-testing-library, I want to mock the response based on the body of the captured request (http POST or PUT). But the body of the captured request is empty.

## Environment

- `msw: 0.32.0`
- `nodejs: 14.13.1`
- `npm: 6.14.8`
- `jest@26.4.2`

## To Reproduce
Define a handler like this: 
```
export const sendEmailVerification = () =>
  rest.post(
    `${API_URL}authentication/v2/firebase/verify-email`,
    (req, res) => res(),
  );
```

send the request:
```
fetch(`${API_URL}authentication/v2/firebase/verify-email`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ accessToken: firebaseToken, url }),
  });
```
`req.body` is `{}`

## Expected behavior
`req.body` to return the actual body

Help to debug what is going wrong is appreciated

**Comment by florian-milky** [comment]
Close for now as it's working in 1 project but not the other

**Comment by kettanaito** [comment]
Your usage of MSW looks fine. I recommend taking the problematic scenario and isolating it, simplifying it along the way. This usually helps in discovering what went wrong.

**Comment by florian-milky** [comment]
I can confirm it was due to a bad implementation of xhr in the project.
Thanks!
