### ISSUE TITLE
Cannot intercept a request with a parentheses in the URL

### ISSUE THREAD

**Issue by renownrjm** [mswjs/msw#825]
## Issue 

The request URL having parenthesis eg: `https://made.up/api/usage('id')`,  `https://made.up/api/usage('id')/relObjects`   etc.. not intercepting in my jest react testing library tests using msw.

## Environment

| Name | Version |
| ---- | ------- |
| msw  |^0.30.1   |
| node | v14.16.1     |
| OS   | Windows 10   |

## Request handlers

```js
import { rest } from 'msw'

export const handlers = [
  /**
   * Example of a request handler—function that captures a request
   * and declares which mocked response to return upon match.
   * @see https://mswjs.io/docs/basics/request-handler
   */
  rest.get("https://made.up/api/usage\('id'\)", (req, res, ctx) => {
    return res(
      ctx.status(301),
      ctx.json({
        id: 1,
        firstName: 'John',
      }),
    )
  }),
]
```

## Actual request
```js
// App.js
const { loading, error, data } = useFetch("https://made.up/api/usage('id')");
```

https://codesandbox.io/s/msw-react-forked-nsqrs?file=/src/App.js

## Current behavior

The request is not intercepting 

## Expected behavior

msw mock should work and my test should pass

## Notes 

https://codesandbox.io/s/msw-react-puui0
in the above code sandbox for the URL "https://made.up/api/usage('id')" How should I match the URL in handlers ?
In a similar lines I am unable to intercept many URLs in my project, Tried different way of escaping characters as well
My project s on Jest React Testing library on a CRA

**Comment by kettanaito** [comment]
Hey, @renownrjm.

You need to escape the parenthesis in the request handler URL like so:

```js
rest.get("https://made.up/api/usage\('id'\)", fn)
```

> See the [path matching REPL](https://mswjs.io/repl?path=https%3A%2F%2Fmade.up%2Fapi%2Fusage%5C%28%27id%27%5C%29&url=https%3A%2F%2Fmade.up%2Fapi%2Fusage%28%27id%27%29) that matches this request handler.

However, even when escaped, the usage example you've posted doesn't capture that request. I'll investigate that and share my findings here.

**Comment by kettanaito** [comment]
The issue is in the `getAbsoluteUrl` function:

https://github.com/mswjs/msw/blob/82848744c67c69b00a27afc5d7e6057cf1521ed9/src/utils/url/getAbsoluteUrl.ts#L4-L15

Specifically, when constructing a `URL` instance using a path with escaped parentheses, it seems to ignore those escape backslashes:

```js
new URL(`/resource\\('id'\\)`, 'https://base.com').href
// "https://base.com/resource/('id'/)"
```

One way to ensure the escaped characters are present is to encode the given URL path:

```js
decodeURI(new URL(encodeURI(`/resource\\('id'\\)`), 'https://base.com').href)
// "https://base.com/resource\\('id'\\)"
```
