### ISSUE TITLE
Unhandled request throw error: [MSW] Failed to mock a "POST" request to

### ISSUE THREAD

**Issue by edouard-lopez** [mswjs/msw#841]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.33.1  |
| browser | Brave Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)     |
| OS      | Linux Mint 20.1     |

### handlers.ts
```js
import { rest } from 'msw';
import WebChatConfig from '~/Conversation/webchatConfig/__tests__/fixtures';

export const handlers = [
  rest.get(
    'https://dev-api-legacy.tolk.ai/v1/webchat/:webchatId',
    (req, res, ctx) => {
      console.info(`serving mock for ${req.params.webchatId}`, WebChatConfig);

      return res(ctx.status(200), ctx.json(WebChatConfig));
    }
  ),
];
```

### browser.ts

```
import { setupWorker } from 'msw';
import { handlers } from './handlers';

// This configures a Service Worker with the given request handlers.
export const worker = setupWorker(...handlers);
```

## Actual request

I reckon it's from CRA

## Current behavior

```
[MSW] Failed to mock a "POST" request to "https://dev-webchat-analytics.tolk.ai/webchat/analytics/7A3e3aE19b5DF96326DCe6Cf/252eEd2BB6dEEc2d14D39Efe/TKaDsIEm9UXC/uUkFTz7Xr94e0e8UK89nR-a/event/init": TypeError: Failed to fetch
POST https://dev-webchat-analytics.tolk.ai/webchat/analytics/7A3e3aE19b5DF96326DCe6Cf/252eEd2BB6dEEc2d14D39Efe/TKaDsIEm9UXC/uUkFTz7Xr94e0e8UK89nR-a/event/init net::ERR_FAILED
[WDS] Disconnected!
[MSW] Failed to mock a "GET" request to "http://192.168.1.8:3000/sockjs-node/info?t=1627636803942": TypeError: Failed to fetch
[MSW] Failed to mock a "GET" request to "http://192.168.1.8:3000/sockjs-node/info?t=1627636814981": TypeError: Failed to fetch
[MSW] Failed to mock a "GET" request to "http://192.168.1.8:3000/sockjs-node/info?t=1627636824069": TypeError: Failed to fetch
```

## Expected behavior

I don't want to write handlers for every requests, just the one I want to mock. How do I toggle off error for the unhandled requests ?

**Comment by kettanaito** [comment]
Hey, @edouard-lopez. 

You don't have to write handlers for every request, any unhandled request is performed as-is (bypassed). The errors you see most likely indicate an issue when performing those requests as-is. 

Could you please request those problematics resources directly? Is there any response? 

```
GET https://dev.to/kettanaito/spawn-an-http-server-from-your-mock-service-worker-request-handlers-2c19`
POST https://dev-webchat-analytics.tolk.ai/webchat/analytics/7A3e3aE19b5DF96326DCe6Cf/252eEd2BB6dEEc2d14D39Efe/TKaDsIEm9UXC/uUkFTz7Xr94e0e8UK89nR-a/event/init
```

I can also spot that those resources relate to some webchat, so there may be WebSockets in place. Note that MSW does not support WebSockets, but it shouldn't affect your mocking experience, as WebSocket events aren't even intercepted by the worker.

**Comment by kettanaito** [comment]
Would you have an opportunity to share a reproduction repository for this? That would be the fastest way to get help.

**Comment by edouard-lopez** [comment]
@kettanaito the original request is indeed failing, I was surprised to get a message from MSW at all

> [MSW] Failed to mock a "POST" request to …

I reckon it's due to the original failure, that means the error is logged twice, by the browser and MSW.

```
[MSW] Failed to mock a "POST" request to "https://dev-webchat-analytics.tolk.ai/webchat/analytics/7A3e3aE19b5DF96326DCe6Cf/252eEd2BB6dEEc2d14D39Efe/TKaDsIEm9UXC/uUkFTz7Xr94e0e8UK89nR-a/event/init": TypeError: Failed to fetch
POST https://dev-webchat-analytics.tolk.ai/webchat/analytics/7A3e3aE19b5DF96326DCe6Cf/252eEd2BB6dEEc2d14D39Efe/TKaDsIEm9UXC/uUkFTz7Xr94e0e8UK89nR-a/event/init net::ERR_FAILED
```

**Comment by kettanaito** [comment]
I think it's the error message that's confusing. We are handling any exceptions during the response phase in the worker like so:

https://github.com/mswjs/msw/blob/8f77f4c6123224c0dcf4a03d4318a1f2dd8f8d93/src/mockServiceWorker.js#L272-L281

While this wording makes sense in the context when there's an error during the mocked response, it's misleading when the error occurs during the original (bypassed) response. It leads the developers to believe that request is also being mocked when, in fact, it's not. 

I think adjusting that error message to something neutral would be a good DX improvement.

**Comment by edouard-lopez** [comment]
Is it possible for you to implement it like:
> As a developer, I would prefer MSW to show error message only when it's coming from handled resource. 

I mean that when it's a network error it's not MSW responsability, but the dev (wifi off, wrong URL, etc.) and adding MSW to the mix just add to the confusion.

**Comment by kettanaito** [comment]
Yes, that'd be the best behavior. It comes down to whether we can determine if the error originated from an unhandled resource in the worker. Note that the exception it catches may originate even during the request (i.e. given impossible request options), so it's not necessarily a network error. 

Would you be interested in looking into those exceptions in the worker script and finding the way to report only the exceptions related to the handled resources?

**Comment by edouard-lopez** [comment]
As an open source maintainer I appreciate your call to action, and I'm interested but unfortunately I won't have the time to investigate this

**Comment by kettanaito** [comment]
No worries! This issue doesn't obstruct you in any way, so it will be addressed whenever one of the maintainers has time.

**Comment by kettanaito** [comment]
The error messages have been redefined and the missing tests have been added. I'll release this change in the next minor version.
