### ISSUE TITLE
Messages aren't formatted in logs

### ISSUE THREAD

**Issue by OmgImAlexis** [mswjs/msw#844]
## Describe the bug
Messages aren't formatted with the new `devUtils` loggers.

## Environment

- `msw: 0.33.2`
- `nodejs: 16.x`
- `npm: 6.x`

## Expected behavior
Logs to have specifiers replaced with correct data.

## Reproduction
```js
devUtils.warn('Expected a mocking resolver function to return a mocked response Object, but got: %s. Original response is going to be used instead.', false);
````

### Expected
Expected a mocking resolver function to return a mocked response Object, but got: false. Original response is going to be used instead.

### Actual
Expected a mocking resolver function to return a mocked response Object, but got: %s. Original response is going to be used instead.

**Comment by OmgImAlexis** [comment]
The first argument "message" should be formatted using [`util.format`](https://nodejs.org/api/util.html#util_util_format_format_args) with the optional arguments passed in.

**Comment by kettanaito** [comment]
Thanks for reporting this, @OmgImAlexis.

I'll add the tests for this and change the internals of `outvariant` to rely on `util.format`. Since `outvariant` should run in both Node.js and a browser, I suppose we'd have to specify `util` as a dependency there.

**Comment by OmgImAlexis** [comment]
@kettanaito https://github.com/tmpfs/format-util

**Comment by kettanaito** [comment]
I was thinking about the [util](https://github.com/browserify/node-util) package, which seems to be more actively supported.

We can follow up on this discussion at https://github.com/open-draft/outvariant/pull/1.

**Comment by kettanaito** [comment]
I'll add the missing tests and update the `interceptors` version.
