### ISSUE TITLE
Outvariant dependancy doesn't link to source

### ISSUE THREAD

**Issue by OmgImAlexis** [mswjs/msw#845]
## Describe the bug
When looking up the newly added `outvariant` I can't find a link to it's source on npm. When I finally did find the repo it has it's issues disabled so I can't even open an issue there.

## Environment

- `msw: v0.33.2`
- `nodejs: 16.x`
- `npm: 6.x`

## Expected behavior
The package to have a `homepage` and/or `bugs` field.

**Comment by kettanaito** [comment]
Hey, @OmgImAlexis. Thank you for pointing that out.

I've added the repository reference to the `outvariant` package in [this commit](https://github.com/open-draft/outvariant/commit/ea73c04d6810d4e391eb2752ab40953b9e2369ce). The change has also been published to propagate to the package's page on NPM.
