### ISSUE TITLE
Cannot find name 'require'

### ISSUE THREAD

**Issue by andreidiaconescu** [mswjs/msw#849]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.33.2  |
| browser | Chrome     |
| OS      | Ubuntu 20     |

## Request handlers

Hello,
I have an angular application and I have tried to run the service worker using the documentation from
https://mswjs.io/docs/getting-started/integrate/browser:

i added the following code to src/main.ts
```js
  const { worker } = require('./mocks/browser')
  worker.start()
```
and i get the following error:
```
Error: src/main.ts:11:20 - error TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add `node` to the types field in your tsconfig.
```

What could i do to fix this problem ?
Thank you

**Comment by kettanaito** [comment]
Hey, @andreidiaconescu.

It looks like you don't have the type definitions for Node.js, or your TypeScript setup is incorrect. The error above originates from the `require()` call, not anything related to Mock Service Worker. You can confirm that by requiring any other module than `./mocks/browser`, I'm sure you'll see the same error. 

Please configure TypeScript so you have `require` support in your application. Here are some answers I've found online:

- https://stackoverflow.com/questions/31173738/typescript-getting-error-ts2304-cannot-find-name-require

**Comment by andreidiaconescu** [comment]
@kettanaito 
I have a standard angular project.
Where and how could i run the service worker  in a standard angular project ?

thank you .

**Comment by kettanaito** [comment]
See our [Angular usage example](https://github.com/mswjs/examples/tree/master/examples/rest-angular). You can find all the necessary steps to take under the "Key points" section in that example's README. You can also reference all the necessary configurations, such as the TypeScript configuration, and compare them with what you have in your project.

**Comment by andreidiaconescu** [comment]
thank you,

1. In the example readme: examples/rest-angular/README.md
it is written:
```
src/main.ts conditionally enables mocking in development environment.
```
But file seems to contain no reference to mocking, just default angular code.


2. In the example code:
examples/rest-angular/src/mocks/server.ts

it is written:
```
import { setupServer } from "msw/node";
import { handlers } from "./handlers";

// Setup requests interception using the given handlers.
export const server = setupServer(...handlers);
```
It is not clear for me:
 -  how to run this file: src/mocks/server.ts
 -  i want to run the mocking in the browser, does this run in the browser ?

**Comment by kettanaito** [comment]
> But file seems to contain no reference to mocking, just default angular code.

The `main.ts` file creates an environment, which [enables the worker in the browser](https://github.com/mswjs/examples/blob/a8bb071d997a24f3a7f7107cbb414659c22ccc5a/examples/rest-angular/src/environments/environment.ts#L5-L6).

> how to run this file: src/mocks/server.ts
You don't need to run it. It's used to [enable mocking in tests (Node.js)](https://github.com/mswjs/examples/blob/a8bb071d997a24f3a7f7107cbb414659c22ccc5a/examples/rest-angular/src/setup-jest.ts#L3) using the same request handlers.

> i want to run the mocking in the browser, does this run in the browser ?

Yes, the example above runs the mocks in the browser.
