### ISSUE TITLE
Vulnerability found with xml-dom

### ISSUE THREAD

**Issue by cmacdonnacha** [mswjs/msw#861]
Hey, a vulnerability has been found with `xml-dom` which is a dependency in MSW. Updating to version `0.7.0` should fix it.

See https://npmjs.com/advisories/1769  

Github dependabot info:

```
Remediation
Upgrade xmldom to version 0.7.0 or later. For example:

"dependencies": {
  "xmldom": ">=0.7.0"
}

GHSA-5fg8-2547-mr8q
moderate severity
Vulnerable versions: < 0.7.0
Patched version: 0.7.0
Impact
xmldom versions 0.6.0 and older do not correctly escape special characters when serializing elements removed from their ancestor. This may lead to unexpected syntactic changes during XML processing in some downstream applications.

Patches
Update to 0.7.0
(see issue #271 for the status of publishing the version to npm or join for Q&A/discussion #270 until it's resolved)

Workarounds
Downstream applications can validate the input and reject the maliciously crafted documents.

For more information
If you have any questions or comments about this advisory:

Open an issue in xmldom/xmldom
Email us: send an email to all addresses that are shown by npm owner ls xmldom
```

**Comment by kettanaito** [comment]
Hey, @cmacdonnacha. Thanks for reporting this.
 
`xmldom` is a transient dependency that ends up in MSW from the [interceptors](https://github.com/mswjs/interceptors ) package. This vulnerability has been raised in that repo to be closed to the source (https://github.com/mswjs/interceptors/issues/145). The vulnerability itself has been addressed by the `xmldom` maintainers but it looks like they're having an issue with publishing it to NPM (see https://github.com/xmldom/xmldom/issues/271). 

We will update that dependency once that said issue is resolved.

**Comment by cmacdonnacha** [comment]
Great update thanks @kettanaito

**Comment by fernandopasik** [comment]
The new version of `xmldom` is now published in a different package https://www.npmjs.com/package/@xmldom/xmldom

**Comment by kettanaito** [comment]
@fernandopasik, thanks for letting us know. @kevinpost has already tackled the update and the new version of `interceptors` has been published. MSW update is on the way (#876).
