### ISSUE TITLE
React Native: handlers with parameters break completely

### ISSUE THREAD

**Issue by wwdrew** [mswjs/msw#869]
## Describe the bug

WIth React Native, using a REST handler that includes a parameter causes all network requests to fail.

## Environment

- `msw: 0.34.0`
- `nodejs: 16.3.0`
- `npm: 7.16.0`
- `react-native: 0.64.2`

## Expected behavior

Mocked network requests to be handled.

## Explanation

I've created several REST handlers that have been working really well. I've subsequently added a new one that has a parameter value in the URL, but this causes all handlers to fail. I've tracked the problem down to the getResponse function, in particular it fails trying to find a relevant handler with the error:

`SyntaxError: Invalid RegExp: Quantifier has nothing to repeat`

To verify it's only broken in React Native, I've created a node test and have verified it is working correctly.

I've spent a little while trying to track it down but it has me stumped. If anyone has any any pointers or suggestions on what might be going wrong I'm happy to create a pull request, but at this point I'm lost!

It's probably worth mentioning that paths with wildcards _do_ work, so in this case:

`http://localhost/path/:id` will fail

`http://localhost/path/*` will work

**Comment by kettanaito** [comment]
Hey, @wwdrew. Could you please submit a reproduction repository for this? I'd be happy to look into it then. Thanks.

**Comment by wwdrew** [comment]
Yep no worries, I'll try to get it sorted for you this evening.

**Comment by wwdrew** [comment]
Hmm, okay that's weird. I've created a bare-bones repo to demonstrate the bug - and it's working there just fine. I'm going to have to dig in a little harder to figure out what's causing it to break in my actual app.

**Comment by kettanaito** [comment]
I'm going to close this due to the lack of a reproduction scenario. Please, if you get to catch this issue, share your repository here so the library maintainers could look into it. Thanks.

**Comment by easybird** [comment]
I have the same issue, everything works fine until I add `/:id`, in react-native.
It is a monorepo (nx) setup and with a nextjs webapp as well that uses the same handlers: and that one works fine with `/:id`)
Hard to share as it is a private company repo.. I can share some screenshots if you like

msw: 0.35.0
nodejs: 14.7.6
npm: 8.1.0
react-native: 0.66.1

The weird thing is that it fails silently. Every external request has: Network request failed ; and msw is not starting up (eg.: not even showing any onUnhandledRequest errors/warnings for example)

**Comment by easybird** [comment]
The issue is related to Hermes, and the way they handle regexes:

- https://github.com/facebook/hermes/issues/46
- https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/3371

Solution: 
- Issue only occurs in debug mode.
- In debug mode, disabling Hermes in your Podfile and rebuilding the app solves the issue
