### ISSUE TITLE
Add WebSocket mocking

### ISSUE THREAD

**Issue by washingtonsoares** [mswjs/msw#889]
Hi there!

Do you think it would be interesting to add support for WebSocket (and maybe socket.io as well)?

If the answer is yes, I would like to start a discussion, and maybe develop a draft of the idea and create a PR soon.

Related projects: https://github.com/thoov/mock-socket

**Comment by kettanaito** [comment]
Hey, @washingtonsoares. Thank you for raising this.

WebSocket support has been previously discussed (see #156) and is currently under development (#396). The in-browser support is largely done, but the Node.js support puts the entire feature under question. I simply don't have enough resources to properly research it.

We would be thankful for your help with that, though. We can discuss the intricacies of mocking WebSockets in Node.js in #156, if you're interested. Feel free to post your findings and ideas, and check out the linked pull request, you can built it locally (or install the PR directly via npm) and give the feature a try.

**Comment by ljmerza** [comment]
Where was this completed? I still don't see support for web sockets.

**Comment by RayOei** [comment]
> Where was this completed? I still don't see support for web sockets.

It is not there, yet, as I understand it but there is progress. See #2010 and hot from the press apparently (3hrs ago) https://github.com/mswjs/interceptors/pull/236
