### ISSUE TITLE
GraphQL handler not working.

### ISSUE THREAD

**Issue by ricn** [mswjs/msw#892]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.35.0   |
| node | v14.17.0     |
| OS   | macOS 10.15.2     |

## Request handlers
server.ts:
```
import { rest, graphql } from 'msw';
import { setupServer } from 'msw/node';

// Only global handlers init here
const server = setupServer(
    // This one works and gets intercepted
    rest.get('/api/v1/applications/types', (req, res, ctx) => {
        return res(
            ctx.json({
                types: types,
            }),
        );
    }),
    // This one does not work
    graphql.query<ApplicationQuery, ApplicationQueryVariables>('Application', (req, res, ctx) => {
        const { id } = req.variables;
        if (id) {
            const application: ApplicationQuery = {
                application: {
                    id: id,
                    applicationNumber: 1234,
                },
            };

            return res(ctx.data(application));
        }
    }),
);

export { server, rest, graphql };
```
setupTests.ts:
```
import '@testing-library/jest-dom/extend-expect';
import { server } from 'mocks/server';

beforeAll(() => {
    server.listen({
        onUnhandledRequest(req) {
            console.error('Found an unhandled %s request to %s body %s', req.method, req.url.href, req.body);
        },
    });
});
afterEach(() => server.resetHandlers());
afterAll(() => server.close());
```

## Actual request

the onUnhandledRequest prints out that this is the actual request that are being made when running a jest test:

```
Found an unhandled POST request to http://localhost/api/v2/graphql body {"query":"\n    query Application($id: ID) {\n  application(id: $id) {\n    id\n    applicationNumber\n  }\n}\n    ","variables":{"id":"3fa85f64-5717-4562-b3fc-2c963f66afa6"}}
```
## Current behavior

It seems like the graphql handler is not registered correctly or something.

## Expected behavior

The graphql handler should be used and return the mocked response.

**Comment by kettanaito** [comment]
Hey, @ricn. Thanks for reporting this.

Please, could you put this use case into a reproduction repository and share a link with us here?

**Comment by ricn** [comment]
Thanks I'll try to do that. However I found something that differs between the rest handlers and the GraphQL handlers. The rest handlers intercepts requests that is using Axios but the GraphQL code is generated and uses fetch behind the scenes. So I setup a minimal test where I'm doing a GraphQL request with Axios instead and that works great but not when I switch to using fetch.

**Comment by kettanaito** [comment]
Ensure you’re making a valid GraphQL request, method-, body-, and query-wise.

**Comment by ricn** [comment]
I did not find a solution by using fetch but I changed the code to use Axios instead and now it works.
