### ISSUE TITLE
MSW leaks Node.js types

### ISSUE THREAD

**Issue by bug-brain** [mswjs/msw#897]
## Describe the bug
Importing MSW leaks the Typescript declarations of Node.js.

## Environment

- `msw: 0.35.0`
- `nodejs: 16.6.2`
- `typescript: 4.3.4`

## To Reproduce

1. Create a Typescript file that is meant for the browser:
```
// repro.ts
import 'msw'
console.dir(global)
```
2. Run `tsc  --types --noEmit repro.ts` to see that there is no error although `global` is expected to be unknown.

## Expected behavior
Importing MSW does not introduce global variables or types from Node.js.

**Comment by kettanaito** [comment]
Hey, @bug-brain.

`global` is a legitimate object in Node.js that is present there even without `msw` being imported:

```ts
console.log(global)
```
```
Object [global] {
  global: [Circular],
  clearInterval: [Function: clearInterval],
  clearTimeout: [Function: clearTimeout],
  setInterval: [Function: setInterval],
  setTimeout: [Function: setTimeout] {
    [Symbol(nodejs.util.promisify.custom)]: [Function]
  },
  queueMicrotask: [Function: queueMicrotask],
  clearImmediate: [Function: clearImmediate],
  setImmediate: [Function: setImmediate] {
    [Symbol(nodejs.util.promisify.custom)]: [Function]
  }
}
```

The fact that you see the `error TS2304: Cannot find name 'global'` error when compiling the example module means you don't have type definitions for Node.js installed. When you import MSW, I believe TypeScript detects `@types/node` from one of its fourth-party dependencies:

```
└─┬ msw@0.35.0
  ├─┬ @mswjs/cookies@0.1.6
  │ └─┬ @types/set-cookie-parser@2.4.1
  │   └── @types/node@16.7.10
```

## Resolution

Install `@types/node` if you wish to compile Node.js code:

```sh
$ npm install @types/node
```

This is not an issue with MSW.

**Comment by bug-brain** [comment]
HI @kettanaito,

I do not see the error you described but I expect to see it because `global` should only be available in Node.js. Importing MSW also importing the Node.js types introduces name clashes in our browser code.

Thank you for supplying the dependency chain. The root cause is in fact not MSW itself.

**Comment by kettanaito** [comment]
I understand the concerns, but MSW doesn't introduce any global types, at least directly. There's a related issue #408 that we haven't solved yet. Please feel free to post any suggestions there.
