### ISSUE TITLE
Cannot access response body after request is intercepted by MSW

### ISSUE THREAD

**Issue by romaolucas** [mswjs/msw#905]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.35.0   |
| chrome | Version 91.0.4472.114     |
| Ubuntu     | 20.04.2 LTS     |

## Request handlers

I have the following setup for msw in my project. The request that I'm having an error should be bypassed.
```js
const setup = () => {
  if (typeof window === 'undefined') {
    const { server } = require('./server');
    server.listen();
  } else {
    const { worker } = require('./browser');
    worker.start({ onUnhandledRequest: 'bypass' });
  }
};
```

## Actual request

```js
const parseJSON = (text) => JSON.parse(text);

fetch('/url').then((res) => parseJSON(res.text()))
```

## Current behavior

I get the following error in my application

```
Uncaught (in promise) TypeError: Failed to execute 'text' on 'Response': body stream already read
    at parseJSON
```

## Expected behavior

I should be able to access the `response.text` in the promise resolve as the request was bypassed.

**Comment by kettanaito** [comment]
Hey, @romaolucas. 

We've fixed this issue in the browser [about half a year ago](https://github.com/mswjs/msw/blame/172bc104a3f42dd779128fead34fe7ebb612dd87/src/mockServiceWorker.js#L120). What you're experiencing is likely to be a Node.js issue that was raised in the related library and fixed (https://github.com/mswjs/interceptors/releases/tag/v0.12.7). Please wait for the next MSW release for the fix to land in your project. Thank you!

**Comment by patrickmcdougle-okta** [comment]
I'm also experiencing this issue. I think it's scope:browser. Since the response `body` property's value comes from awaiting text() it's already been run once and can't be run again.

**Comment by kettanaito** [comment]
In the setupBrowse API the response is being cloned before its body is read.

Please, if you feel it’s a browser issue, post a reproduction repository here. Thanks.

**Comment by patrickmcdougle-okta** [comment]
I believe this was fixed 3 days ago here: https://github.com/mswjs/interceptors/pull/152

**Comment by kettanaito** [comment]
@patrickmcdougle-okta, true, but that fix is related only to Node.js or in-browser execution in the _fallback mode_ (which enables only when MSW cannot otherwise use Service Worker API). Hmm, perhaps the latter was your case?

**Comment by patrickmcdougle-okta** [comment]
No. Cloning the repo and manually bumping mswjs/interceptors to the current version worked for me. I need to get a little organized, but I can have a PR ready this week.

**Comment by romaolucas** [comment]
For me bumping the interceptors to the current version didn't work. @patrickmcdougle-okta have you specified in your package.json that is a peerDependence to mswjs or have you simply ran `npm install --save @mswjs/interceptors`?
