### ISSUE TITLE
You're welcome :). If you need further help we are happy to help :)

### ISSUE THREAD

**Issue by Abdulqadir579** [mswjs/msw#906]
You're welcome :). If you need further help we are happy to help :)

_Originally posted by @marcosvega91 in https://github.com/mswjs/msw/issues/494#issuecomment-763148853_

Sir I got stuck with my application, And I am facing ECONNREFUSED Error.

**Comment by kettanaito** [comment]
Hey. Please provide a reproduction repository where your issue can be reproduced. Thanks.
