### ISSUE TITLE
Support handling XHRs?

### ISSUE THREAD

**Issue by kentcdodds** [mswjs/msw#93]
I don't know whether this is possible, but due to the cancelation issues with promises/fetch, XHRs are actually preferable. Can msw support requests made via XHR?

**Comment by kettanaito** [comment]
Hi, @kentcdodds. I believe you mean so that MSW could intercept the requests made via XHR in your client code?

In that case it comes down to the possibilities of Service Workers, yet I don't see a reason why XHR wouldn't be causing the `fetch` event in a Service Worker.

Could you please give me an example of expected usage?

**Comment by kentcdodds** [comment]
I basically would like to swap [this](https://github.com/kentcdodds/bookshelf/blob/bdcc1942ff3c70e8dd1e5717bb99886e28846107/src/utils/api-client.js#L22-L37) for an XHR request and have that still be handled by the service worker without needing to change anything in my handlers.

**Comment by kettanaito** [comment]
Hi, @kentcdodds. I see. I've added a basic XHR test scenario, could you please see if this is how you intend to use MSW?

https://github.com/open-draft/msw/pull/95/files#diff-ac6cb7531f89526b2d98c2180c99ecdbR18-R20

**Comment by kentcdodds** [comment]
Yup, that's exactly it 👍

**Comment by kentcdodds** [comment]
I take it that since the build passed that this "just works™️"? Super!

**Comment by kettanaito** [comment]
Yes, you should be able to mock a XHR requests as-is. I'll add the integration test to the master to test regressions, if any. Feel free to reopen this if you encounter any unexpected behavior on the library's side when dealing with XHR. Thanks for bringing this topic.

**Comment by kentcdodds** [comment]
Thank *you*!
